### ISSUE TITLE
[Low priority]: Backport backup / recovery feature to 0.4.x

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1006]
This change was requested to backport to 0.4.x by one of the teams. 

Describe the solution you'd like:
Backport backup / recovery solution introduced with version 0.7 to use it with version 0.4

Additional context:
There were changes in PostgreSQL role between version 0.5 and 0.6 ([new data model for configuration](https://github.com/epiphany-platform/epiphany/issues/973)) we need to look after this.

@toszo can you confirm that this feature is stil needed?

**Comment by mkyc** [comment]
@toszo can you decide what to do with it?

**Comment by mkyc** [comment]
@toszo as we are releasing 0.8.0 in couple next days, it looks like we no longer support 0.4.x versions. Shall we close this issue then without resolution as outdated?

**Comment by toszo** [comment]
Yes, close it.

**Comment by mkyc** [comment]
Closing as outdated.
