### ISSUE TITLE
[FEATURE REQUEST] Add possibility to specify SSH port in Epiphany configuration

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1036]
**Is your feature request related to a problem? Please describe.**
In some cases we want to use different than standard 22 port for SSH. E.g. in some environments SSH is exposed via NAT on non-standard port.

**Describe the solution you'd like**
We want to have ability to specify port in machine configuration and expose SSH on non-standard port.

**Describe alternatives you've considered**
We have workaround for this. We can specify ip in specification section of kind: infrastructure/machine like:
`ip: 10.1.1.1 ansible_port=47901`

**Additional context**
None.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by sk4zuzu** [comment]
@erzetpe @rafzei can you describe the reason we want this? :)

**Comment by erzetpe** [comment]
Because we had users that were requiring non-standard configuration because of using NAT connection to their environment with SSH ports exposed on different ports.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
