### ISSUE TITLE
Offline installation (RedHat AWS specific): could not contact any CDS load balancers

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1041]
When running an offline installation on AWS RedHat (outbound rules set only to cluster ips) epicli fails on TASK [repository : Add and enable epirepo]  with error:

> 2020-03-20T08:59:55.6870827Z 08:59:55 INFO cli.engine.ansible.AnsibleCommand - fatal: [ec2-35-180-85-18.eu-west-3.compute.amazonaws.com]: FAILED! => {"changed": true, "cmd": "set -o pipefail && /tmp/epi-repository-setup-scripts/add-epirepo-client.sh http://10.1.2.243/epirepo |& tee /tmp/epi-repository-setup-scripts/add-epirepo-client.log", "delta": "0:01:00.253262", "end": "2020-03-20 08:59:54.646764", "msg": "non-zero return code", "rc": 1, "start": "2020-03-20 08:58:54.393502", "stderr": "", "stderr_lines": [], "stdout": "HTTP/1.1 200 OK\r\nLoaded plugins: amazon-id, rhui-lb, search-disabled-repos\n\n\nCould not contact any CDS load balancers: rhui2-cds01.eu-west-3.aws.ce.redhat.com, rhui2-cds02.eu-west-3.aws.ce.redhat.com.\nCould not contact CDS load balancer rhui2-cds01.eu-west-3.aws.ce.redhat.com, trying others.", "stdout_lines": ["HTTP/1.1 200 OK", "Loaded plugins: amazon-id, rhui-lb, search-disabled-repos", "", "", "Could not contact any CDS load balancers: rhui2-cds01.eu-west-3.aws.ce.redhat.com, rhui2-cds02.eu-west-3.aws.ce.redhat.com.", "Could not contact CDS load balancer rhui2-cds01.eu-west-3.aws.ce.redhat.com, trying others."]}

It looks like the system repositories were not disabled and yum is trying to connect to the Internet when running yum makecache fast.

This is due to the fact that the script `create-enabled-system-repos-list.sh` does not result in creating valid list of repositories (the /var/tmp/enabled-system-repos.txt file is empty), but anyway it exits with status code 0, probably because of pipeing commands. Needs some refactoring.
Running `yum --cacheonly repolist enabled` without access to Internet seems to be causing the problem.

> Could not contact any CDS load balancers: rhui2-cds01.eu-west-3.aws.ce.redhat.com, rhui2-cds02.eu-west-3.aws.ce.redhat.com.
> Could not contact CDS load balancer rhui2-cds01.eu-west-3.aws.ce.redhat.com, trying others.
> 

For testing purposes I am disabling all repositories before running epirepo scripts.

**Comment by seriva** [comment]
No longer valid as per @przemyslavic input.
