### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: scaling up and down the main components

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1051]
**Is your feature request related to a problem? Please describe.**
We don't test scaling up/down components in our pipelines.

**Describe the solution you'd like**
Create new pipelines with  scaling up/down Epiphany components in Azure

**Comment by erzetpe** [comment]
This should be slitted into more specific tasks with proper configuration for each.

**Comment by mkyc** [comment]
@rafzei I don't think label grooming-needed should be removed. I agree with comment from @erzetpe that we need to divide this task into list of smaller one for each component.

**Comment by atsikham** [comment]
@mkyc so in the scope of this task grooming we need to create new ones and close this one?

**Comment by mkyc** [comment]
Yeah, or reshape this one to one of subtasks you'd create.

**Comment by atsikham** [comment]
New tasks are created under 'Components Scalability' epic. Opendistro and logging components are combined into one task as it's almost the same.
#1596 #1597 #1598 #1599 #1600 #1601 #1602 #1603 #1604
