### ISSUE TITLE
[FEATURE REQUEST] Add process-exporter to Epiphany

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#107]
**Is your feature request related to a problem? Please describe.**
We like to get a better insight in the performance metrics of the various services we run inside Epiphany.

**Describe the solution you'd like**
Add [process-exporter](https://github.com/ncabatoff/process-exporter) component (Prometheus exporter that mines /proc to report on selected processes).

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/ncabatoff/process-exporter

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
@toszo do you know what is this about?

**Comment by seriva** [comment]
I would think something about monitoring.

**Comment by toszo** [comment]
This task is to introduce Prometheus Exporter that will monitor linux process (like ElasticSearch, PostgreSQL, etc.). The more generic the better.

**Comment by seriva** [comment]
Not going to do this anymore for Epiphany so closing.
