### ISSUE TITLE
Add sorting entries in the inventory file

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1076]
**Describe the bug**
Now for different clusters we have virtual machines in a disordered way.

**Expected behavior**
There should be always the same order of the hostnames based on for example timestamp of creation data.

**Config files**
```
[kubernetes_master]
ci-haazurrhelcanal-kubernetes-master-vm-2 ansible_host=
ci-haazurrhelcanal-kubernetes-master-vm-0 ansible_host=
ci-haazurrhelcanal-kubernetes-master-vm-1 ansible_host=

[kubernetes_master]
ci-haazurubucanal-kubernetes-master-vm-0 ansible_host=
ci-haazurubucanal-kubernetes-master-vm-1 ansible_host=
ci-haazurubucanal-kubernetes-master-vm-2 ansible_host=

[kubernetes_master]
ci-haazurubuflannel-kubernetes-master-vm-2 ansible_host=
ci-haazurubuflannel-kubernetes-master-vm-1 ansible_host=
ci-haazurubuflannel-kubernetes-master-vm-0 ansible_host=

```
**Provider:** 

Azure, AWS

**Comment by mkyc** [comment]
Check if that is related to #1706

**Comment by rpudlowski93** [comment]
Yes, it looks that the PR is releated to the task. Moreover as seriva metioned here : https://github.com/epiphany-platform/epiphany/issues/1702, we should removed ASG for AWS. So in my opinion the task can be connected to #1706, and a new task should be created for removing the ASG for AWS.

**Comment by przemyslavic** [comment]
:heavy_check_mark: `apply` + `reapply` for `azure` and `any` providers
:heavy_check_mark:  `upgrade` from v1.0 to v1.3.0dev + `apply` v1.3.0dev
After executing the `apply` command, the hosts are sorted in inventory by hostname.
Tested all available components with clustering enabled (where possible).

IMO #1706 should be closed now.
