### ISSUE TITLE
Updgrade repmgr

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1081]
We use v4.0.6 from June 2018, there were some important changes since that time.

See: https://repmgr.org/docs/repmgr.html#APPENDIX-RELEASE-NOTES

**Comment by mum0l** [comment]
We should consider upgrading this tool to the latest 5.10 version. This version is fully supported with our postgresql 10. 

What needs to be checked during the task implementation:
1. Which repositories are used to deploy repmanager? They should contain the 5.1.0 version of repmanager.
2. Are there any deprecated objects? See https://repmgr.org/docs/repmgr.html#APPENDIX-RELEASE-NOTES

**Comment by rpudlowski93** [comment]
I'm closing the task in favour of #2074
