### ISSUE TITLE
K8s HA installation - Error from server: etcdserver: leader changed

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1086]
**Describe the bug**
Ansible automation fails during HA cluster deployment.

**To Reproduce**
1. Deploy HA cluster in Azure.
2. Look for similar errors in logs:
> 2020-03-28T22:24:44.9969616Z 22:24:44 INFO cli.engine.ansible.AnsibleCommand - TASK [kubernetes_master : Check if old flannel daemonset exists] ***************
> 2020-03-28T22:24:50.2462992Z 22:24:50 INFO cli.engine.ansible.AnsibleCommand - fatal: [ci-haazurrhelcanal-kubernetes-master-vm-0]: FAILED! => {"changed": false, "cmd": "kubectl get ds kube-flannel-ds  --namespace kube-system\n", "delta": "0:00:03.798104", "end": "2020-03-28 22:24:49.981120", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2020-03-28 22:24:46.183016", "stderr": "Error from server: etcdserver: leader changed", "stderr_lines": ["Error from server: etcdserver: leader changed"], "stdout": "", "stdout_lines": []}
>

**Expected behavior**
Multi-master Kubernetes cluster should deploy without issues.

**Config files**
Any standard HA config should have a chance to reproduce the issue.

**OS (please complete the following information):**
Ubuntu, RHEL, CentOS(?)

**Cloud Environment (please complete the following information):**
 Azure

**Additional context**
Happens randomly, it's difficult to reproduce.

**Comment by mkyc** [comment]
@przemyslavic can you please review if that bug is still valid? If yes then can you please provide steps to reproduce?

**Comment by przemyslavic** [comment]
I am not able to reproduce with the latest `epicli` version. If the error occurs again, a new issue  will be created.
