### ISSUE TITLE
Upgrade node_exporter to v1.0

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1115]
Currently we use v0.16.0 but the latest is v1.0.1.

Changelog:
https://github.com/prometheus/node_exporter/releases

Note: Version v1.0.0 has [breaking changes](https://github.com/prometheus/node_exporter/releases/tag/v1.0.0).

**Comment by atsikham** [comment]
Systemd service template should be processed and based on both configurations - manifest and role's defaults. It will be possible to do after #1619 is merged, so this task is moved to blocked.

**Comment by atsikham** [comment]
Implemented with updated doc.

**Comment by przemyslavic** [comment]
There is a bug to be fixed: [[BUG] Node exporter does not work after the upgrade - unknown long flag '--collector.netdev.ignored-devices'](https://github.com/epiphany-platform/epiphany/issues/1681).

**Comment by przemyslavic** [comment]
After applying the fix, the node exporter works fine.
Cluster upgrade from version 0.5 and 0.7 to develop was tested as well as the deployment of a new cluster from the develop branch.
