### ISSUE TITLE
[k8s HA] Error from server: etcdserver: leader changed when running 'kubectl get pods'

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1124]
Successfully promoted non-HA cluster to HA and scaled it up to 3 masters.
In one test, the `kubectl get pods --all-namespaces --field-selector=status.phase!=Running` command returned an error `Error from server: etcdserver: leader changed`.

**Comment by rafzei** [comment]
Cannot reproduce, @przemyslavic if you face it one more time, please reopen and provide more details.
