### ISSUE TITLE
[INVESTIGATION] Investigate if possible cluster networking issues initially noticed on AWS affect Azure

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1130]
**Describe what to investigate**
There where several networking bugs reported on AWS:

https://github.com/epiphany-platform/epiphany/issues/1129
https://github.com/epiphany-platform/epiphany/issues/1072

This requires investigation on Azure to make sure its not effecting Azure. Check the links above to the AWS issues for more information and how to reproduce.

**Expected outcome**
The expected outcome of this investigation should awnser if the bugs on AWS also effect Azure. If one or both issues occur additional additional bugs will be reported to fix them for Azure.

**Additional context**
none

**Comment by mkyc** [comment]
@przemyslavic why did you removed `bug` label? Can you also explain title a bit? It has `[Azure]` but says about `AWS`?

**Comment by pprach** [comment]
I cannot reproduce this.
Trying on Azure-RHEL7/Ubuntu-canal/flannel and it was always working.
