### ISSUE TITLE
Upgrade ZooKeeper

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1136]
In use version: 3.14.12
Latest available version (stable): 3.6.1

- Check Kafka vs. Zookeeper version compatibility

Useful links:
Download: https://zookeeper.apache.org/releases.html
Upgrade FAQ: https://cwiki.apache.org/confluence/display/ZOOKEEPER/Upgrade+FAQ
Check Kafka notes (compatibility): https://kafka.apache.org/23/documentation.html#upgrade

**Comment by erzetpe** [comment]
Upgrade at least to version 3.4.14 as this solves some security issues.

**Comment by usshmah** [comment]
Why not move to 3.6.0?

**Comment by erzetpe** [comment]
We are not saying, not to move to 3.6.0, but to upgrade at least to version 3.4.14, which solves some security issues. Right now in Kafka 2.4.1 Zookeeper 3.5.7 is used and we need to think about upgrading also Kafka to support newer Zookeeper.

**Comment by rafzei** [comment]
Looks like it's duplicated with already merged https://github.com/epiphany-platform/epiphany/issues/1853. @toszo can we close this issue?

**Comment by mkyc** [comment]
@toszo can you respond to @rafzei ?

**Comment by toszo** [comment]
Yes, lets close it.
