### ISSUE TITLE
Upgrade Kafka (to 2.6.0)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1137]
**Is your feature request related to a problem? Please describe.**
Need to perform Kafka upgrade to the latest possible version with all fixes included.

**Describe the solution you'd like**
Upgrade Kafka the same way as other components, using Ansible's 'upgrade' role.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by gj25** [comment]
@toszo Is the Kafka upgrade, preferably to to the latest version (2.6.0), scheduled for 0.8?

**Comment by usshmah** [comment]
Comment from Steve Kieu in #prod-de-devops channel

Our Kafka version used by epiphany 0.6.0 is 2.3.1 with zookeeper 3.4.12

There are these issues have been logged and resolved with latest version 2.6.0

https://issues.apache.org/jira/browse/KAFKA-7925 - CPU consumption

https://issues.apache.org/jira/browse/KAFKA-10254 - CPU consumption when broker lost connection

https://issues.apache.org/jira/browse/KAFKA-9603 - Leak file handles

To review file descriptor limit currently set for a running Kafka broker, run `cat /proc/KAFKA_BROKER_PID/limits` and look for Max open files.

To see open file descriptors, run: `lsof -p KAFKA_BROKER_PID`

**Comment by mkyc** [comment]
@gj25 It's not.

**Comment by sunshine69** [comment]
I made a PR https://github.com/epiphany-platform/epiphany/pull/1790 to address the issues.

To add one more BUG of the current version and we are spending huge time to fix/work around - please see 
https://issues.apache.org/jira/browse/KAFKA-9133

**Comment by mkyc** [comment]
While releasing please make sure that it was tested together with #1853

**Comment by rpudlowski93** [comment]
Tested, upgrade from 0.7.2 to develop finished with success. Kafka works properly after the changes. 
Tested with #1853 (upgrade zookeeper to 3.5.8)
