### ISSUE TITLE
Upgrade Apache Ignite

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1139]
**Is your feature request related to a problem? Please describe.**
Version installed by Epiphany should be upgraded to newer version.

**Describe the solution you'd like**
We want to upgrade Apache Ignite to version 2.8.1.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by erzetpe** [comment]
Waiting for more information from interested sides.

**Comment by sk4zuzu** [comment]
Closing because of #1862
