### ISSUE TITLE
Backup: HAProxy

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1188]

**Comment by rafzei** [comment]
I've tested backup/restore of HAProxy configuration - it works as expected.

**Comment by rafzei** [comment]
Performing additional tests. For now, I found an issue on RHEL. 
The backup script doesn't care about the file type in source location. In the following case the haproxy.cfg file is a slink so only slink is backed up. 


**OS**:
- Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Installed packages**:
- rh-haproxy18.x86_64                 3.1-2.el7                      epirepo     
- rh-haproxy18-haproxy.x86_64         1.8.24-2.el7                   epirepo     
- rh-haproxy18-haproxy-syspaths.x86_64
- rh-haproxy18-runtime.x86_64         3.1-2.el7                      epirepo   

**rpm -ql rh-haproxy18-haproxy**:
- {..}
- /etc/opt/rh/rh-haproxy18/haproxy
- /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg
- {..}

**ls -l /etc/haproxy/haproxy.cfg**:
lrwxrwxrwx. 1 root root 44 Jun 26 07:11 /etc/haproxy/haproxy.cfg -> /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg

**Comment by sk4zuzu** [comment]
@rafzei please take a look at this PR https://github.com/epiphany-platform/epiphany/pull/1390 it should resolve the issue :+1:
