### ISSUE TITLE
Restore: PostgreSQL

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1195]
Restore for one node configuration is already implemented.
Workin on configuration with two-nodes and repmgr.

**Comment by pyrkamarcin** [comment]
@plirglo tested restore scenario: single node PostgreSQL, 2 nodes PostgreSQL done, works for me

**Comment by pyrkamarcin** [comment]
Tested restore scenario: single node PostgreSQL, clustered nodes PostgreSQL; on Ubuntu and RedHat.
