### ISSUE TITLE
[FEATURE REQUEST] Verify components backup/recovery data

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1201]
**Is your feature request related to a problem? Please describe.**
We have pipelines for running the backup and recovery of components, however we don't verify the data after running this.

**Describe the solution you'd like**
Add tests to verify the data after running the backup and recovery of components.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo this anymore for Epiphany.
