### ISSUE TITLE
Moving terraform's state and epiphany-cluster-config to a shared place in the cloud.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1203]

**Comment by mkyc** [comment]
This does not look like part of autoscaling feature @sk4zuzu. It looks rather like added here "by the way". Am I right?

**Comment by sk4zuzu** [comment]
@mkyc in the previous solution this would be a very important part so we would be able to share state between epicli invocations. This is IMO some technical debt we have anyways, but for autoscaling in AKS/EKS it's pointless now.

**Comment by mum0l** [comment]
Looks like there is official documentation how to setup remote state in vault: https://learn.hashicorp.com/tutorials/terraform/aws-remote

The only issue which we might face is that this require Terraform Cloud, but free version limits number of users to 5... https://www.hashicorp.com/products/terraform/pricing - is that something we want to go with or not?

**Comment by mkyc** [comment]
I believe not. We are going to try to be as far from being locked in terraform state as possible. If we want to store state somewhere, it should be our own implementation to allow storage of all kinds of files, not only terraform state. BTW: terraform state is going to be less and less issue in modularised approach.

**Comment by mum0l** [comment]
Make sense. than we need to prepare our own implementation than.

**Comment by toszo** [comment]
@mum0l please take work that was groomed and planned for the current sprint and not take additional things while work in the sprint has not finished.

**Comment by mum0l** [comment]
Already do that, thanks!

**Comment by seriva** [comment]
Closing as this is not going to happen in the current scope of Epiphany.
