### ISSUE TITLE
Building packer images to quickly add new Kubernetes nodes.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1204]

**Comment by mkyc** [comment]
@sk4zuzu if we are talking about managed clusters, we do not need this task I believe. What do you think?

**Comment by sk4zuzu** [comment]
@mkyc correct. We can stiil use packer here to speed up deployment though IMO. :+1:

**Comment by mkyc** [comment]
Hmmmm ... I think you might be right. I believe that there was possibility to choose OS image to be used in managed clusters, on some cloud providers. I'll leave this issue for now, but I'll mark it low priority. We should spend some time here anyways.

**Comment by seriva** [comment]
Closing as this feature currently has no usecase anymore
