### ISSUE TITLE
Realistic provisioning minimalization and speedup.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1205]

**Comment by mkyc** [comment]
@sk4zuzu if we are talking about managed clusters, we do not need this task I believe. What do you think?

**Comment by sk4zuzu** [comment]
@mkyc correct :+1:, I don't think running full `epicli apply` is needed here if we are going to use AKS/EKS, so we probably don't need such optimizations that much.

**Comment by mkyc** [comment]
Ok, so closing it as not relevant in current plan.
