### ISSUE TITLE
Adding ability to authenticate and run epicli from a pod.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1206]

**Comment by mkyc** [comment]
@sk4zuzu what would be a use case for that issue?

**Comment by sk4zuzu** [comment]
@mkyc so the previous idea for autoscaling was to reuse existing k8s automation we have already, but without any kind of cloud provider software deployed. Also we were supposed to reuse existing epicli/ansible code. We would introduce a long running process inside k8s that would control the size of the cluster by running epicli commands. I don't think that this is needed anymore.

**Comment by mkyc** [comment]
Yeah, I agree. Closing it for now.
