### ISSUE TITLE
Introducing python application that will scale the pool of worker nodes.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1207]

**Comment by mkyc** [comment]
@sk4zuzu if we are talking about managed clusters, we do not need this task I believe. What do you think?

**Comment by sk4zuzu** [comment]
@mkyc correct. If we are gonna use AKS/EKS there is no need for this task for autoscaling. The one use case I can see if for on-prem clusters, where an user would like to manually scale-down some multi-master k8s cluster - so in the end we would scale-down control plane instead of nodes.

**Comment by mkyc** [comment]
Yes. As we do not plan to have such feature, I close it for now. If we ever need to get back to this we will reopen and move to some better place.
