### ISSUE TITLE
[upgrading 0.5 to 0.6] ERROR CoreDNSMigration

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1214]
Failing configurations:
- AWS Ubuntu calico
- AWS Ubuntu canal
- AWS RedHat canal

`2020-04-27T12:32:16.8618648Z 12:32:16 INFO cli.engine.ansible.AnsibleCommand - fatal: [ec2-3-248-182-183.eu-west-1.compute.amazonaws.com]: FAILED! => {"attempts": 20, "changed": true, "cmd": "kubeadm upgrade apply -y v1.16.7 --config /etc/kubeadm/kubeadm-config.yml --ignore-preflight-errors=CoreDNSUnsupportedPlugins", "delta": "0:00:00.053159", "end": "2020-04-27 12:32:16.771872", "msg": "non-zero return code", "rc": 2, "start": "2020-04-27 12:32:16.718713", "stderr": "\t[WARNING CoreDNSUnsupportedPlugins]: Get https://10.1.1.220:6443/api/v1/namespaces/kube-system/configmaps/coredns: dial tcp 10.1.1.220:6443: connect: connection refused\n[preflight] Some fatal errors occurred:\n\t[ERROR CoreDNSMigration]: Get https://10.1.1.220:6443/api/v1/namespaces/kube-system/configmaps/coredns: dial tcp 10.1.1.220:6443: connect: connection refused\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["\t[WARNING CoreDNSUnsupportedPlugins]: Get https://10.1.1.220:6443/api/v1/namespaces/kube-system/configmaps/coredns: dial tcp 10.1.1.220:6443: connect: connection refused", "[preflight] Some fatal errors occurred:", "\t[ERROR CoreDNSMigration]: Get https://10.1.1.220:6443/api/v1/namespaces/kube-system/configmaps/coredns: dial tcp 10.1.1.220:6443: connect: connection refused", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[upgrade/config] Making sure the configuration is correct:\n[preflight] Running pre-flight checks.", "stdout_lines": ["[upgrade/config] Making sure the configuration is correct:", "[preflight] Running pre-flight checks."]}`

**Comment by rafzei** [comment]
Cause:
Not enough disk space on master node so pods cannot start.

Disk space usage after upgrade from 0.5.4 to 0.6.0:
```
/ -> 31GB
/tmp -> 8.2GB
/var/www/html -> 11GB
```
