### ISSUE TITLE
Create guide for applying OS patches to machines running Epiphany on Red Hat

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1225]
**Is your feature request related to a problem? Please describe.**
We need to provide a guide how to apply OS patches on machines where Epiphany is installed on Red Hat and running.

**Describe the solution you'd like**
We need to provide the guide how to install updates with package manager to Red Hat OS and not break working components from Epiphany platform.

**Describe alternatives you've considered**
Solution that installs patches to OS automatically. 

**Additional context**
None.

**Comment by mkyc** [comment]
Split it to reel and ubuntu related ones.
