### ISSUE TITLE
QA - Automatic Hashicorp Vault installation and configuration

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1238]
**Is your feature request related to a problem? Please describe.**
We don't have any tests of Hashicorp Vault after installation.

**Describe the solution you'd like**
We want to check if ports, TLS, namespace, vault is unsealed are setup correctly,  

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by mum0l** [comment]
We need to go thru the deployment process, and check all points one-by-one, if they're deployed properly. For sure as author mention we need to check if ports are listening, TLS certificate works properly, namespace is set, vault seal/unseal process works correctly. I'm not sure what else is there, but those should be the basics, but in-deep verification should be performed as I mention point-by-point.

**Comment by erzetpe** [comment]
Closing because of deprecation of Hashicorp Vault component.
