### ISSUE TITLE
QA - Automatic Hashicorp Vault Agent installation, configuration and Kubernetes - Hashicorp Vault integration

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1239]
**Is your feature request related to a problem? Please describe.**
We don't have integration tests between Hashicorp Vault and Kubernetes.

**Describe the solution you'd like**
We want have integration tests between Hashicorp Vault and Kubernetes.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by przemyslavic** [comment]
Vault integration with Kubernetes was tested manually according to the [scenario](https://github.com/epiphany-platform/epiphany/issues/1338#issuecomment-651687655).
We can consider adding automated tests here (deploying a test application and checking the possibility of secret injection).

**Comment by erzetpe** [comment]
Closing because of deprecation of Hashicorp Vault component.
