### ISSUE TITLE
Druid: Create Ansible playbook for single install

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1245]
**Is your feature request related to a problem? Please describe.**
We have only option to deploy Druid for clustered install.

**Describe the solution you'd like**
We want to have option to deploy Druid for single instance installation running on Kubernetes using helm chart.

**Describe alternatives you've considered**
None.

**Additional context**
This solution may be similar to the one from the link below:
https://github.com/helm/charts/tree/master/incubator/druid

**Comment by seriva** [comment]
Will not be part of Epiphany in this form anymore.
