### ISSUE TITLE
Default configuration of Grafana (dashboards)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#127]

**Comment by ar3ndt** [comment]
In grafana default configuration the dashboard part is commented:

```
  # Dashboards from https://grafana.com/dashboards
  grafana_dashboards: []
  #  - dashboard_id: '4271'
  #    revision_id: '3'
  #    datasource: 'Prometheus'
  #  - dashboard_id: '1860'
  #    revision_id: '4'
  #    datasource: 'Prometheus'
  #  - dashboard_id: '358'
  #    revision_id: '1'
  #    datasource: 'Prometheus'
```

We either remove this part as no needed anymore or comment it out and set with some defaults

**Comment by przemyslavic** [comment]
It looks like the ability to deploy Grafana dashboards has already been implemented: [link](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/grafana/tasks/dashboards.yml).

The sample dashboards are commented out in the default configuration: [link](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/defaults/configuration/grafana.yml#L54). We have to consider whether we choose some default dashboards ourselves or let the users do it.

We have to check if the functionality works in the `develop` version and why it does not work in version `0.7`: [link](https://github.com/epiphany-platform/epiphany/issues/1777). Also be aware of `offline mode` and what about downloading dashboard files then?

**Comment by przemyslavic** [comment]
Tested monitoring component with Grafana enabled. 
:heavy_check_mark: `epicli apply`
:heavy_check_mark: `epicli re-apply`
:heavy_check_mark: `epicli apply` in offline mode

Importing dashboards from the official Grafana website (online mode only) as well as enabling predefined Grafana dashboards have been checked.
