### ISSUE TITLE
[FEATURE REQUEST] Backup RabbitMQ Data

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1283]
**Is your feature request related to a problem? Please describe.**
Currently we only backup RabbitMQ configuration.

**Describe the solution you'd like**
We would like to be able to backup the RabbitMQ data as well.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by sk4zuzu** [comment]
This is something that we could use https://github.com/meltwater/rabbitio - needs research.

**Comment by sk4zuzu** [comment]
Waiting for results from research and implementation from #1309 :+1:.

**Comment by ar3ndt** [comment]
backup seems to work fine for configuration files. Files are archived and moved to desired `mounted` location.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
