### ISSUE TITLE
[FEATURE REQUEST] Restore RabbitMQ Data

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1284]
**Is your feature request related to a problem? Please describe.**
Currently we can only restore the RabbitMQ configuration.

**Describe the solution you'd like**
We would like to be able to restore the RabbitMQ data as well.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by sk4zuzu** [comment]
Waiting for results of research and implementation from #1309 :+1:.

**Comment by ar3ndt** [comment]
recovery works fine for configuration files. Once changed the config file in location /etc/rabbitmq and performed recovery for chosen timestamp the version was recovered properly.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
