### ISSUE TITLE
[FEATURE REQUEST] Create serverspec for Helm

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1286]
**Is your feature request related to a problem? Please describe.**
We don't have automatic tests to test Helm.

**Describe the solution you'd like**
We need to tests automatic tests for Helm. Create pipeline with some test scenarios for Helm. 
- create Helm chart in system directory (helm_charts role/files)
- check if chart is added to apache repository
- check if chart is available as Helm chart repo (helm repo != apache repo)
- trigger installation of a chart from other sample role (install-chart task)

**Describe alternatives you've considered**
None

**Additional context**
All information regarding Serverspec tool/framework can be found at https://serverspec.org/.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mum0l** [comment]
All good, the only thing which we could add here, is to put list of all places where we use helm, just to be sure, that everything was included in those checks.
