### ISSUE TITLE
Epicli does not interpret alternative yaml boolean values as true booleans.

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1296]
Epipany switched to the `ruamel.yaml` library. I believe this caused following regression problem:
```python
import yaml
import ruamel.yaml

DOC = """
a: true
b: yes
c: false
d: no
"""

print(yaml.load(DOC))
print(ruamel.yaml.YAML().load(DOC))
```
```
{'a': True, 'b': True, 'c': False, 'd': False}
ordereddict([('a', True), ('b', 'yes'), ('c', False), ('d', 'no')])
```
This means that "yes/no" (and others) are no longer converted to boolean values. Non-empty strings in python always evaluate to True, it means that user can by mistake put "no" inside yaml and expect something will not run, but the opposite will happen.

> To clarify, this has been changed with YAML 1.2:
> The primary objective of this revision is to bring YAML into compliance with JSON as an official subset. YAML 1.2 is compatible with 1.1 for most practical applications - this is a minor revision. An expected source of incompatibility with prior versions of YAML, especially the syck implementation, is the change in implicit typing rules. We have removed unique implicit typing rules and have updated these rules to align them with JSON's productions. In this version of YAML, boolean values may be serialized as “true” or “false”; the empty scalar as “null”.

Please check here https://yaml.org/spec/1.2/spec.html#tag/repository/bool

**Comment by mkyc** [comment]
There is no unit tests for https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/cli/helpers/yaml_helpers.py This task should introduce some tests for regression of this  kind.

**Comment by przemyslavic** [comment]
Tested different values for `yes` / `no` option:
```
YES_VALUES = ['y', 'Y', 'yes', 'Yes', 'YES']
NO_VALUES = ['n', 'N', 'no', 'No', 'NO']
```
:heavy_check_mark: All values were correctly converted to booleans: `true` / `false`. Additionally 2 unit tests have been added.
