### ISSUE TITLE
post-terraform/pre-ansible: operating system update (base packages) step

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1303]
Currently Epiphany does not support automatic apt / yum security and base package updates. Older system source images are being used, which forces users to update clusters on their own. This looks like a serious security issue!

Using automatic upgrades, like for example Ubuntu provides ([AutomaticSecurityUpdates](https://help.ubuntu.com/community/AutomaticSecurityUpdates)) seem, on the other hand, to be too problematic. We don't want this kind of situation, where Epiphany cluster suddenly crashes, caused by unexpected and untested upgrade.

The idea here is to introduce ansible managed semi-automatic upgrades of security and possibly base system packages, executed knowingly by users at a convenient time 👍.

Epiphany supports both `online` and `offline` ([how-to-create-an-epiphany-cluster-on-existing-airgapped-infrastructure](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-existing-airgapped-infrastructure)) installations. Taking that into account, we could say that:
1. In the `online` case, it should be fairly easy to implement ansible logic, that would apply security and base package updates (without upgrading linux distros to major releases). This needs to be confirmed though if there won't be any package version conflicts, since the repository code specifies quite a lot of packages already ([redhat-7/requirements.txt](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/requirements.txt)).
2. In the `offline` case, we would have to deal with constant modifications of Epiphany's repository role package requirement list (for each supported linux distro). Which seems to be impractical and laborious, as this would require non-stop maintenance (on daily basis) and rapidly increasing volume of the offline package. It would be best for the offline case, to be excluded and left in the hands of cluster owners.

Another topic is what happens next, when semi-automatic pre-tested upgrade fails anyway? It's not always easy to rollback such changes. Introducing automatic VM snapshots (cloud) could be an idea here.

**Comment by seriva** [comment]
Not going to do this anymore for the current Epiphany.
