### ISSUE TITLE
--no-infra epicli option should not change sshd_config/sudoers

### ISSUE THREAD

**Issue by ar3ndt** [epiphany-platform/epiphany#1305]
modify `--no-infra` epicli option to NOT change `sshd_config` or `sudoers` with assumption it is configured as desired and the epiphany provided ssh account will have all needed access.

**Comment by mkyc** [comment]
I think it's similar thing with `/etc/hosts`. If there is assumption that infrastructure is already ok to handle connections I would assume `/etc/hosts` contains correct entries already. Currently epiphany deletes all existing entries and adds it's own. I think that, if we want to do anything with that file at all, we should add new entries and do not change existing ones when `--no-infra` parameter is present.

**Comment by seriva** [comment]
Not gonna do this anymore for this Epiphany.
