### ISSUE TITLE
Secure access, management and monitoring of the cluster with access roles

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1307]
There is suggestion from user: 

> Support and document Epiphany setup for secure access, management and monitoring of the cluster with commonly known varying access roles, e.g.:
> - Super-admin role - able to manage all Epiphany installation aspects (including Azure resources, OS, services, deployed applications, etc.) allowing to scale the cluster, update it, monitor it, manage deployed applications, etc.
> - Application-admin role - able to manage applications deployed on the cluster, allowing to deploy, update, configure those applications and also monitor them and monitor the related resources and services (which includes monitoring whole cluster load, monitoring messaging bus, load balancer, etc. and allows access to application logs and logs of related services).
> - Application-support role - able to manage basic application configuration (e.g. scale K8s deployments, change selected application settings) and monitor it (access to logs and monitoring data of the application and related services).
> - Monitoring role - able to monitor the cluster and application performance, with no access to configuration and logs.
> 
> Including guide (with examples) on user setup and management.

After additional conversation it was elaborated more: 

> This is both about managing the Epiphany (it’s components, underlying infrastructure, etc.) and managing what it’s used for, so the applications deployed on it.
> Epiphany delivered as is, so without actual guidelines on the security and management model, without tools to work with it on daily basis, does not fulfill its goals.
> The goals of Epiphany, as I understand those, is to standardize (on technical solutions, but also on processes and patterns) and to abstract (isolate from having to know and understand the underlying platforms and infrastructures).
> As there are no guidelines nor tools for common tasks, each project must produce own solutions/approaches to the processes, which invalidates the standardization part.
> Without those tools, each project must be able to fully understand and support all underlying components of the platform and infrastructure, which defeats the purpose of the abstraction.
> The only time theoretically saved is on learning how to deploy all the components on your own. The problem is, that you still must learn how to deploy Epiphany and you need to understand what it does underneath, to be able to support the deployment results. This requires as much time spent, as there is saved.
> As you obviously can’t support all possible use-case scenarios, I’ve started with an expectation on Epiphany delivering full solution for managing access within the platform. I.e. when I’m to deploy an Epiphany cluster for a project, I expect to have tools and guidelines on how to set up credentials for all (or at least most) the people, who will be working with the cluster, how to ensure they have access to the infrastructure and can safely maintain their credentials, while keeping the platform secure, etc. The roles I’ve listed, are an example of how it could be set up: Epiphany would define some logical roles and provide full process and toolset support to manage users and assign those roles to them. The list of roles may not be complete (as I don’t know all the other projects), nor defined best – it’s just an example. The core idea is that it must be complete and consistent, so having a separate set of guidelines/tools on how to manage Kubernetes and separate one on Kibana and separate one on Kafka and separate one on Grafana, etc. does not cut it – this is something already provided by the documentation and tools from the individual components and is not enough for a platform. It has to have some extension points, to cover for individual aspects of complex projects and cover various deployment scenarios (so it does not require completely different approaches for e.g. Azure, than for AWS).

This should be discussed further.

**Comment by atsikham** [comment]
Seems to be not a task, but an epic with undefined design, implementation, documentation parts. So my proposal to discuss it together as a team and not make a grooming by only one person.

**Comment by seriva** [comment]
For now we are not going to pursue this in the current Epiphany. Closing and moving to new internal Epiphany work.
