### ISSUE TITLE
Master node requires more disk space in further releases

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1313]
Epihpany stores all requirements on Master local volume (/var/www/html) to provide a local repository. 
New releases deployment will require more disk space, below you can find a comparison of version to used disk space. Also, upgrades to newer versions require some free space on a disk. 

Problem: 
Not enough space on master node after fetching all requirements so it causes a bunch of errors during deployment/upgrade (eg. issue #1214)
Deployment uses /tmp directory which is not cleaned up at the end

Solution:
As decided to keep /var/www/html in case of offline deployments here are potential solutions:
1. Provide a bigger volume for fresh deployment and manually resize disk for existing-upgrading environments  (not a long-term solution) 
2. Gzip/xz/bz2 files after deployment and keep it in case of offline installation (compress results below)
3. Implement local repository as Epiphany cluster component (separated VM)

The pros and cons of a particular solution should be discussed.

It also should solve #992

Disk usage after deployments:
Version 0.5.4:
```
/ -> 18GB
/var/www/html -> 5.9GB
/tmp -> 4.1GB
```
Version 0.6.0:
```
/ -> 23GB
/tmp -> 4.5GB
/var/www/html -> 10GB
```
Version 0.5.4 upgraded to 0.6.0:
```
/ -> 31GB
/tmp -> 8.2GB
/var/www/html -> 11GB
/var/www/html/ compressed with:
  -> xz: 4.1GB (compress time: 1h22min)
  -> gz: 4.9GB (compress time: 10mins )
  -> bz2: 4.6GB (compress time: 20min)
```

**Comment by mkyc** [comment]
how is it related to #139?

**Comment by rpudlowski93** [comment]
In my opinion this task can be closed since we already don't have repository on master node but on separated repository machine and there is already task for additional disks with defined sizes to VMs.

@rafzei  Can You agree?

**Comment by sk4zuzu** [comment]
> In my opinion this task can be closed since we already don't have repository on master node but on separated repository machine and there is already task for additional disks with defined sizes to VMs or #992
> 
> @rafzei Can You agree?

@rpudlowski93 this is really much more complex :) because we support [this](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-enabledisable-epiphany-repository-vm). In theory we should have some kind of mechanism that would calculate partition sizes basing on defaults for each role or user input. :thinking:

**Comment by sk4zuzu** [comment]
> how is it related to #139?

IMO #139 should be implemented first and then reused to provide persistence for the repository/image_registry role. :)

**Comment by erzetpe** [comment]
We will create a new issue if needed after [#992](https://app.zenhub.com/workspace/o/epiphany-platform/epiphany/issues/992).
