### ISSUE TITLE
The VSCode devcontainer does not support custom CA certificate bundles

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1314]
Currently we can only include one custom CA when building the devcontainer. We need the ability to:

- Add multiple crt certs to /usr/local/share/ca-certificates/
- Add the ability to configure the full CA bundles for PIP and Boto3
- Original configuration for a single CA cert should be maintained

**Comment by mkyc** [comment]
@seriva what about this task? Shouldn't it be closed?

**Comment by seriva** [comment]
This was fixed already of part 0.7.0
