### ISSUE TITLE
Upgrade HAProxy to v2.2

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1316]
**Is your feature request related to a problem?** 
Currently HAProxy is in version 1.8 which is quite old (released 26.11.2017) with some bugs.
**Describe the solution you'd like**
HAProxy in the latest stable version at least : 2.2
Source: http://www.haproxy.org/
No major issues reported regarding this version: http://www.haproxy.org/bugs/bugs-2.2.2.html

**Describe alternatives you've considered** 

**Additional context** 
It [haproxy] is provided as a single executable file which doesn't
require any installation process. Multiple versions can easily coexist, meaning
that it's possible (and recommended) to upgrade instances progressively by
order of importance instead of migrating all of them at once. Configuration
files are easily versioned. Configuration checking is done off-line so it
doesn't require to restart a service that will possibly fail. During
configuration checks, a number of advanced mistakes may be detected (e.g. a rule
hiding another one, or stickiness that will not work) and detailed warnings and
configuration hints are proposed to fix them. Backwards configuration file
compatibility goes very far away in time, with version 1.5 still fully
supporting configurations for versions 1.1 written 13 years before, and 1.6
only dropping support for almost unused, obsolete keywords that can be done
differently. The configuration and software upgrade mechanism is smooth and non
disruptive in that it allows old and new processes to coexist on the system,
each handling its own connections. System status, build options, and library
compatibility are reported on startup.

**Comment by to-bar** [comment]
Created related issue #1691.

**Comment by ar3ndt** [comment]
LGTM
