### ISSUE TITLE
 Add proper documentation how to define additional security rules for AWS/Azure

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1322]
Currently there is no documentation how to manage security rules for both AWS and Azure. In most cases teams are adding them manually through the clouds web interfaces or APIs resulting in Terraform wiping them out after re-running Epiphany.

Documentation (with example) should be written for both AWS and Azure showing:

- Change existing default rules
- How to add/extend rules

And should show how to do it so it does not break Epiphany features and support (e.g. still allows use of Epiphany tools to scale out the cluster, update it. etc.

**Comment by mkyc** [comment]
looks like related to #896

**Comment by TolikT** [comment]
Defaults:

- https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/aws/defaults/infrastructure/virtual-machine.yml
- https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/azure/defaults/infrastructure/virtual-machine.yml

Documentation should display with examples how to override/change these settings.

**Comment by mkyc** [comment]
We should add task (or check if there is one already) to adjust current defaults.

**Comment by mum0l** [comment]
Please note, that I stuck with this topic. 

Cannot set the additional security rules in AWS, as none of configs provided by colleagues is working. If I need to document the procedure, first I need to have working solution (working yaml deployment file). Without that, it might be really hard to document, something what is not working

**Comment by seriva** [comment]
Reviewed provided configuration: Azure was fine, AWS had port assigned to wrong field. Outstanding pull request to simplify the defaults and make them less confusing: #1714

**Comment by mkyc** [comment]
Is there any PR to be connected to this issue?

**Comment by mum0l** [comment]
@mkyc yes it is: https://github.com/epiphany-platform/epiphany/pull/1717

**Comment by seriva** [comment]
Tested with the configurations provided and everything works as expected.
