### ISSUE TITLE
Instruction how to handle huge amount logs, rotation, disk space in elk opendistro

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1323]
ELK documentation needs to be reviewed.

Create instruction:
- how to handle huge amount logs, rotation, disk space etc. in opendistro. 
Instruction how to setup log rotation:
https://pgga-es.atlassian.net/wiki/spaces/~600744605/pages/1144063316/Setup+Elasticsearch+log+rotation+using+Kibana

- curator is no longer supported, but we still have this in our code and on components' list

**Comment by to-bar** [comment]
It seems Curator can be replaced by Open Distro for Elasticsearch Index Management:
https://github.com/opendistro-for-elasticsearch/index-management

There is Index State Management (ISM) Kibana plugin for periodic, administrative operations that triggers them based on changes in the index age, index size, or number of documents. Using ISM you can define policies that automatically handle index rollovers or deletions.

More information:
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/

According to Filebeat docs, starting with version 7.0, Filebeat uses index lifecycle management by default when it connects to a cluster that supports lifecycle management. Filebeat loads the default policy automatically and applies it to any indices created by Filebeat. **However, there is X-Pack mark on that site, so we need to check (spike) whether this feature works with OSS Filebeat and Open Distro for Elasticsearch Index Management.**

More information:
https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html

**Comment by rafzei** [comment]
This instruction should be placed in how-to doc: [Logging](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/LOGGING.md).
If you take this task, please create a spike according to the above comment.

**Comment by plirglo** [comment]
At this moment Opendistro for Elasticsearch [does not support](https://github.com/opendistro-for-elasticsearch/sample-code/issues/77) [ILM](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html), log rotation is possible only by configuration created in ISM

**Comment by plirglo** [comment]
Created [issue #2149 ](https://github.com/epiphany-platform/epiphany/issues/2149) to check possibilities of using curator

**Comment by przemyslavic** [comment]
Documentation only. Nothing to test here.
Detailed instructions on defining index policies can be found in the official OpenDistro documentation.
