### ISSUE TITLE
Export logs to any file format

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1324]
Export logs to any file format. Currently default indexes created by epiphany prevents any tries of supported export to CSV. What we can do about this

**Comment by plirglo** [comment]
- logstash import and expert to csv:
https://medium.com/@shaonshaonty/export-data-from-elasticsearch-to-csv-caaef3a19b69

- some other tools:
https://www.skedler.com/blog/the-best-tools-for-exporting-elasticsearch-data-to-csv/

**Comment by mkyc** [comment]
@plirglo can you provide any more context for this? Is that someone external request? Why would we need export? Where we want file to be stored?

**Comment by mkyc** [comment]
I spoke with author of this feedback and: 
 - this is to get pod logs from remote locations where we do not have access but someone would like to send us logs
 - this is not for some scheduled operation but when someones decide that he/she wants result of that query to be exported

Exported logs can be in CSV or JSON format. In fact whatever format suits. Location of output file is not defined.

**Comment by toszo** [comment]
Consider upgrading OpenDistro first: #1140, in newer version Kibana has a reporting module that can be useful.

**Comment by mum0l** [comment]
**Goal:**
This ticket is to add functionality of exporting logs from Kibana into any format (can be json, csv, xml etc).

**Reason:**
Sometimes our customers needs to export logs from their private clusters (which are not connected to internet / or simply we don't have access to), so whenever they need to give us some logs for investigation from their platform, they are sending us... screenshots, as exporting option doesn't exist in Kibana. 

**Notes:**
This option is available in commercial version of Kibana, but in OpenSource which we have, not.

**Past solution:**
Some time ago ppl test possibility of adding this option on new OpenDistro deployment. Sadly it doesn't work.

**Current solution:**
We need to investigate, how to upgrade our Kibana deployment, to allow Log Export functionality. If that won't be possible, we need to setup a query which will be exporting those logs - ref: https://github.com/opendistro-for-elasticsearch/sql/issues/40

**Comment by rafzei** [comment]
> Consider upgrading OpenDistro first: #1140, in newer version Kibana has a reporting module that can be useful.

Currently, Kibana-reporting plugin for ODFE is [scheduled as `Next, Next Release`](https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/2) so it should be released in version after 1.10.0. I cannot see any time estimates for this release.

**Comment by rafzei** [comment]
> Logstash approach seams promising. It requires some more definition what is purpose of export and if there is some scheduling of this export required.

Logstash approach works only with provided ssl cert, logstash-input-elasticsearch

**Comment by przemyslavic** [comment]
There is a bug to be fixed [[BUG] Logstash installation fails on Azure RedHat environments #1632](https://github.com/epiphany-platform/epiphany/issues/1632)

**Comment by przemyslavic** [comment]
Fixed in [#1648](https://github.com/epiphany-platform/epiphany/pull/1648)
