### ISSUE TITLE
Increasing disk space on already deployed Ubuntu VMs

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1325]
Azure: 
1.https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks

AWS: 
1. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/requesting-ebs-volume-modifications.html
2. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html

I resized volumes only on Azure platform and used manual provided above (azure cli)

Manual instruction delivered by client:
1. Gracefully stop any running services to make sure that they have a chance to write work to disk, or migrate responsibilities to other nodes in the cluster. 
2. Shut down the VM from the Azure portal by “stopping” it from the VM page.  
3. Once it is completed shutting down, go to the “disks” option on the left of the VM page.
4. Select the main OS disk in the display to go to the disk page.
5. From the disk page, click on the “configure” option on the left of the disk page.
6. Here you should see an editable value for size of the disk.  Change that size.
    If it’s not editable it’s likely the VM is still up or in the process of shutting down. Just wait.
7. Once changed, hit “save” button at top of page.  It should take just a second.
8. Go back to the VM page and hit the “start” button at the top.
9. Once the VM is up, confirm services are now running.

**Comment by seriva** [comment]
Preferably we want todo this through Terraform with the standard Epicli configuration. Needs some more research how our current Terraform is behaving and if newer versions might fix any issues.

**Comment by mkyc** [comment]
@seriva I added spike task with your suggestion.

**Comment by seriva** [comment]
Closing as we currently don't have a valid business case anymore.
