### ISSUE TITLE
Tuning application logging parameters for ElasticSearch

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1328]
1. Update Docker Filebeat for Multiline Log Support
2. Update version of ElasticSearch Curator (?)
3. Enabling clean up curation of ElasticSearch application logs
4. Setting up ElasticSearch disk space limitation to avoid corrupting ElasticSearch indexes when running out of disk space. 
5. Reducing App Logging noise

**Comment by seriva** [comment]
Not gonna pursue this anymore as we are moving to OpenSearch.
