### ISSUE TITLE
Provide possibility to change additional parameters in default kafka configuration

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1329]
**Describe the bug:**
Additional Kafka parameters such as:  

- max.incremental.fetch.session.cache.slots
- controlled.shutdown.enable
- default.replication.factor
- offsets.topic.replication.factor 

are not configurable in Epiphany configuration. It is not possible to override the default values.

**Expected behavior**
Possibility to change additional Kafka parameters and successfully deployed cluster with the changed parameters.

**OS (please complete the following information):**

- OS: [all]

**Cloud Environment (please complete the following information):**

- Cloud Provider [e.g. AWS/Azure]

**Comment by KWReidABB** [comment]
Things like replication factors should be set automatically by Epiph. If I'm setting up an environment that has 3 Kafka nodes, Epiph should set up these options in the Kafka server.properties file to use those 3 nodes to replicate partitions across the nodes.

Some of the other options should just have their defaults changed to more appropriate values for defaults, and allow override in config file if needed.

**Comment by seriva** [comment]
I would suggest the (Default) replication factors should only be set by epiphany to the nr of brokers if the config is not defined in the YAML. It might not always be preferred to set the default to the nr of brokers.

As for the rest of the options, we should check server.properties and see what else might be worth exposing as now some projects are making changes straight to the config after Epiphany installation to meet there needs.

**Comment by erzetpe** [comment]
I would stick to defaults that we have right now and make those options configurable. You are setting them after some performance tests and configuration for each user can be different and those settings could have impact on their deployments.

**Comment by rpudlowski93** [comment]
After the small conversation with @KWReidABB, I can confirm that sticking the defaults values and make those option configurable is enough.
