### ISSUE TITLE
Update cloud based OS images

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1330]
| Cloud | RHEL 7 - Used | RHEL 7 - Latest | Ubuntu 18.04 - Used | Ubuntu 18.04 - Latest |
| --- | --- | --- | --- | --- |
| AWS | RHEL-7.6_HVM_GA-20181017-x86_64-0-Hourly2-GP2 | RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2 | ubuntu-bionic-18.04-amd64-server-20190212.1 | ubuntu-bionic-18.04-amd64-server-20200430 |
| Azure | 7.6.2018103108 | 7.8.2020042719 (RedHat:RHEL:7-LVM:latest) | 18.04.201810030 | 18.04.202005220 |

To be updated:
1) Epiphany defaults
2) Variables in build pipelines

**Comment by przemyslavic** [comment]
[#1355 Updating cloud based OS images - configuration required for Azure RHEL LVM image](https://github.com/epiphany-platform/epiphany/issues/1355)
