### ISSUE TITLE
Support for Ubuntu Server 20.04 LTS

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1331]
**Is your feature request related to a problem? Please describe.**
Ubuntu Server 20.04 LTS was officially released on April, 23rd, 2020. The 'main' archive of Ubuntu 18.04 LTS will be supported until April 2023.

**Describe the solution you'd like**
We want to provide support for Ubuntu 20.04 LTS and drop soon unsupported Ubuntu 18.04 LTS in the new versions of Epiphany.

**Describe alternatives you've considered**
None.

**Additional context**
Results and conversation from the spike #2529.

More information from documentation can be found:
https://ubuntu.com/blog/ubuntu-server-20-04
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes

Upgrading:
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Upgrading_from_Ubuntu_18.04_LTS_or_19.10

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by plirglo** [comment]
Ubuntu 18.04 LTS Support will end in 04.2023 -  we have some time, but we should start thinking about upgrade to 20.04 since it was released in Q2 2020.

- all packages compatibility needs to be check and tested
- we have to create upgrade role (including offline)
- tests will be very time consuming

**Comment by mkyc** [comment]
We should discuss here again if we should support automatic upgrade from 18.04 to 20.04.

**Comment by erzetpe** [comment]
Results from Spike #2529 are having instruction and describe the problems with installing Epiphany on clean Ubuntu 20.04. Upgrade to version 20.04 from 18.04 doesn't cause any problems.

**Comment by rafzei** [comment]
There is no clear information if we should support 18.04 along with 20.04 in v1.3. 
If we won't, we have to force users to upgrade OS before upgrade epicli.
1- add a preflight check,
2- add how-to upgrade os's on existing env

@to-bar, @erzetpe, @mkyc, @plirglo, @seriva tell what do you think

**Comment by erzetpe** [comment]
From LTS version 2.0 we shouldn't let the users to install Epiphany on Ubuntu different than 20.04 LTS. Can be done with preflight check. In version 1.3 we should add information about deprecation of Ubuntu 18.04 LTS in docs and also in preflight.

**Comment by mkyc** [comment]
My opinion is that we want to support one version in release.

**Comment by plirglo** [comment]
In my opinion since 1.3 we should support only 20.04 version.
1. Upgrade from 1.0: System should be upgraded to v20.04 manually by user and than upgrade do epicli v1.3 is available.
2. New installations of epi 1.3 use system version 20.04 and preflight fail when other version is in use.

**Comment by mkyc** [comment]
Decisions were made to:
 - support only 20.04 starting version 1.3.0. 
 - users will need to upgrade OS on them own
 - there will be preflight check to ensure we do not upgrade to 1.3.0 if OS is not 20.04
