### ISSUE TITLE
[FEATURE REQUEST] Deploy Epiphany on newly created VMs with RHEL 8

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1332]
This task is about creating new Epiphany cluster based on Red Hat Enterprise Linux 8.

TODO items:
- Remove support for RHEL 7 and CentOS 7 (update preflight checks)
- Update cloud images
- Migrate from yum to dnf (download_requirements.sh and Ansible module - if needed)
- Adjust requirements (some packages need to be replaced or removed)
- Check and adjust Ansible roles to work with RHEL 8
- Ensure automated tests pass

Latest release: 8.5 / November 9, 2021

**Dates for RHEL 7**
End of Maintenance Support 1: August 6, 2020
End of life: June 30, 2024
Source: https://endoflife.software/operating-systems/linux/red-hat-enterprise-linux-rhel

RHEL 8 documentation:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/

Key differences between Red Hat Enterprise Linux 7 and Red Hat Enterprise Linux 8:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/index

Upgrading:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [x] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [x] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by mkyc** [comment]
We should handle it in basic infrastructure modules.

**Comment by plirglo** [comment]
1. Upgrade process:
Upgrade should include two steps process:
- Update to latest available RHEL 7 version (as mentioned in upgrade requirements)
- Major upgrade to RHEL 8

We need to confirm this since in Azure the latest with RAW partitioning is 7.7: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#note-for-rhel--centos-azure-images

2. Starting RHEL version 8 for new instances we should start support LVM partitioning, since cloud providers are not deliver RAW partitioning images anymore. This means that we should also look at additional disk work item #1776

**Comment by atsikham** [comment]
> We should handle it in basic infrastructure modules.

Are there tasks for that?

**Comment by erzetpe** [comment]
Do we really want to perform automatic upgrade from RHEL 7.x to 8.x? Maybe it will be better to support 8.x but leave whole procedure of upgrade to user and just give instruction/links how to perform this manually?

**Comment by rafzei** [comment]
This task has to be done right after Spike #2529 in a way(s) described in the outcome of the Spike.

**Comment by mkyc** [comment]
This task looks like it should be done in next quarter, not now.

**Comment by plirglo** [comment]
Please check spike results place in Conluence page before start
