### ISSUE TITLE
Noisy performance-analyzer-agent-cli messages every 5s

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1333]
Details:
https://discuss.opendistrocommunity.dev/t/performance-analyzer-agent-cli-spamming-syslog-in-od-1-3-0/2040

**Comment by przemyslavic** [comment]
First need to confirm if it still occurs in the ODFE version we are currently using.

**Comment by seriva** [comment]
Closing as we are moving to ODFE and for now I don't think we want todo anything with this for older releases.
