### ISSUE TITLE
Deployment of version 0.7.0 failed on-prem (spec.hostname)

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1336]
Error:
`{"asctime": "15:08:36", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "fatal: [master]: FAILED! => {\"attempts\": 30, \"changed\": false, \"cmd\": \"kubectl wait --for=condition=Ready pods -l app=flannel --field-selector=spec.nodeName=$(hostname --long) -n kube-system --timeout=10s\", \"delta\": \"0:00:00.096575\", \"end\": \"2020-06-03 11:08:36.416725\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2020-06-03 11:08:36.320150\", \"stderr\": \"error: no matching resources found\", \"stderr_lines\": [\"error: no matching resources found\"], \"stdout\": \"\", \"stdout_lines\": []}"}
{"asctime": "15:08:36", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}`

Environment:
This issue appeared only on-prem. Tested on CentOS7.8 so far. 

Problem:
If spec.hostname in manifest is different than on target VM, deployment will fail.  Epicli set only transient hostname.
```
---
kind: infrastructure/machine
provider: any
name: default-k8s-master
specification:
  hostname: master
  ip: 192.168.100.101
```
```
[centos@master ~]$ hostnamectl status                                                                                                                  
   Static hostname: localhost.localdomain
Transient hostname: master
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 25d20838a8a8f747b140a5174222adf7
           Boot ID: e164b8e2196d4f3bbc3f4fc4629bdeeb
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.el7.x86_64
      Architecture: x86-64
```

Deployment uses:
` kubectl wait --for=condition=Ready pods -l {{ selectors[network_plugin] }}
    --field-selector=spec.nodeName=$(hostname --long) -n kube-system --timeout=10s`
`hostname --long` return transtient hostname but k8s components uses static one:
```
[centos@master ~]$ kubectl get node                        
NAME                    STATUS   ROLES    AGE     VERSION
localhost.localdomain   Ready    master   6h27m   v1.17.4
[centos@master ~]$ kubectl get pods -n kube-system -o yaml | grep -n nodeName
85:    nodeName: localhost.localdomain
240:    nodeName: localhost.localdomain
382:    nodeName: localhost.localdomain
527:    nodeName: localhost.localdomain
670:    nodeName: localhost.localdomain
836:    nodeName: localhost.localdomain
978:            fieldPath: spec.nodeName
1001:    nodeName: localhost.localdomain
1150:    nodeName: localhost.localdomain
```

**Comment by przemyslavic** [comment]
After the fix, the hostname is set correctly as configured in the yaml file.
