### ISSUE TITLE
[SPIKE] Research different storages options for Azure (Kafka, Elasticsearch, Prometheus, PostrgreSQL)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#134]
**Is your feature request related to a problem? Please describe.**
Currently Epiphany only provides basic OS disk and attached disk storage.

**Is your spike related to a problem or idea? Please describe.**
Currently Epiphany only provides basic disk storage to the VMs.

**Describe the outcome you'd like**
A clear an concise overview of storages we could add for the different components in Epiphany on Azure. What the effort would be to implement it and a possible plan.

**What is the reason or source for the spike**
Currently Epiphany only provides basic OS disk and attached disk storage.

**Additional context**
None

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by mkyc** [comment]
@toszo can you check if that issue should be part of CNS epic? In my opinion this issue is defined too tightly in relation to cloud provider, thus is incorrect with our current approach.

**Comment by toszo** [comment]
No - it should not. It is for "traditional" cloud storage (Block Device, EFS/Blob, etc.).

**Comment by seriva** [comment]
Not going to do this anymore for Epiphany so closing. Teams can work around this with custom Terraform added to LTS versions of Epiphany.
