### ISSUE TITLE
[BUG] Kibana config always points its elasticsearch.hosts to a "logging" VM 

### ISSUE THREAD

**Issue by apopaa** [epiphany-platform/epiphany#1347]
**Describe the bug**
Kibana config always points its elasticsearch.hosts to a "logging" VM , even when Kibana is installed for/on an "opendistro_for_elasticsearch" VM.

**Expected behavior**
Kibana should also check for [opendistro_for_elasticsearch] hostnames and generate URLs for all queries.

**Config files**
Imo, the culprit is this code in [kibana.yml.j2]
(https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/kibana/templates/kibana.yml.j2):
```
elasticsearch.hosts: 
{% for host in groups['logging'] %}
  - "https://{{hostvars[host]['ansible_hostname']}}:9200"
{% endfor %}
```

**OS (please complete the following information):**
 - OS: all

**Cloud Environment (please complete the following information):**
 - Cloud Provider: all

**Additional context**
Kibana is not installed only for "logging", but also for "opendistro_for_elasticsearch", so that groups[] is incorrect in the latter case.

**Comment by rafzei** [comment]
Hi @apopaa,
thanks for creating the issue.
I've updated the description to use a template. Please check and adjust it if I missed something.

**Comment by sk4zuzu** [comment]
I tested the changes during code review and after code review, I can confirm it was working fine for me. :+1:

**Comment by rafzei** [comment]
Here is link to doc with how to start a Kibana for opendistro: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-start-working-with-opendistro-for-elasticsearch
