### ISSUE TITLE
Refactor Keycloak to work with Postgresql HA configuration

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1351]
Currently keycloak is configured to work with only one database node (vm-0). We need to add setup to connect to database using ha tools (pgbouncer, pgpool) when HA is enabled.

**Comment by mkyc** [comment]
Shouldn't we also have Keycloak itself in HA mode? Or is that in separate issue?

**Comment by plirglo** [comment]
Keycloak is deployed in Kubernetes cluster, and yes it's replicable, but uses postgres database, and now kc configuration delivered by epiphany doesn't support HA postgres configuration. We might have problems because of this.

**Comment by mkyc** [comment]
All clear now. I just noticed that kc uses ha configuration.

**Comment by przemyslavic** [comment]
:heavy_check_mark: `Keycloak` deployment with 1 PostgreSQL node + `reapply`
:heavy_check_mark: `Keycloak` deployment with 2 clustered PostgreSQL nodes  + `reapply`
:heavy_check_mark: `Keycloak` deployment with 3 clustered PostgreSQL nodes  + `reapply`
:heavy_check_mark: `Keycloak` deployment with custom database config provided  + `reapply`

Tested both `develop` and `v1.2`.
