### ISSUE TITLE
[FEATURE REQUEST] Change login method to Azure in Epiphany that it doesn't require owner rights on subscription

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#138]
**Is your feature request related to a problem? Please describe.**
Currently Epiphany requires a users to have owner rights on a subscription to create a cluster.

**Describe the solution you'd like**
Change login method to Azure in Epiphany that it doesn't require owner rights on subscription.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Lots of things have changed in that area since then so this should checked if still valid.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
