### ISSUE TITLE
[BUG] Epiphany does not support upgrades for Kubernetes in HA mode

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1408]
**Describe the bug**
Epiphany does not support upgrades for Kubernetes in HA mode (which was introduced in 0.6.0).

**To Reproduce**
Create a multi-master cluster from the v0.6 branch (it will install Kubernetes 1.17.4), then try upgrading it. 

**Expected behavior**
Multi-master Kubernetes cluster is upgraded to 1.17.7 (our current latest) without any issues on each and every node.

**Config files**
N/A

**OS (please complete the following information):**
All OS distributions Epiphany supports.

**Cloud Environment (please complete the following information):**
All cloud environments Epiphany supports.

**Additional context**
N/A

**Comment by mkyc** [comment]
@sk4zuzu can you please explain solution for that issue you plan to use?

**Comment by rafzei** [comment]
This should also refactor a part of code added to fix issue #1401. Currently, we are providing kubeconfig on nodes to go through upgrade procedure. It's required by a couple of tasks that shouldn't be run on nodes.

**Comment by przemyslavic** [comment]
The upgrade from version 0.6 to develop for K8s HA configuration (3 masters, 3 nodes) has been tested and it works fine.
There is a random issue with deploying HA clusters on Azure environments that was reported in [#1075](https://github.com/epiphany-platform/epiphany/issues/1075)
