### ISSUE TITLE
[FEATURE REQUEST] Backup OpenSearch in HA mode

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1416]
**Is your feature request related to a problem? Please describe.**
Backup feature does not work with clustered multi-node OpenSearch. Please check #884.

**Describe the solution you'd like**
Backup code should work with clustered multi-node OpenSearch .

**Describe alternatives you've considered**
N/A

**Additional context**
Clustered multi-node OpenSearch requires shared folder (for example NFS) to create / restore snapshots. Epiphany does not support such a shared storage currently. 

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
@sk4zuzu and @to-bar can you provide some more comment what dis task is dependent to? Can we do it now?

**Comment by to-bar** [comment]
Tasks to be done before (in order):

1. Add time synchronization service (NTP) to Epiphany #1298
2. NFS storage for Epiphany #1233 (with Stunnel TLS encryption)

**Comment by seriva** [comment]
Changing this in the context of OpenSearch. We might need to verify again how todo this there.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
