### ISSUE TITLE
[FEATURE REQUEST] Restore OpenSearch in HA mode

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1417]
**Is your feature request related to a problem? Please describe.**
Recovery feature does not work with clustered multi-node OpenSearch . Please check #1197.

**Describe the solution you'd like**
Recovery code should work with clustered multi-node OpenSearch .

**Describe alternatives you've considered**
N/A

**Additional context**
Clustered multi-node OpenSearch requires shared folder (for example NFS) to create / restore snaphosts. Epiphany does not support such a shared storage currently. 

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by to-bar** [comment]
We need to check if having ES always in K8s is acceptable (performance tests) in order to use Ceph for shared storage (will be available in K8s cluster) or implement NFS, which seems to be ok just for backup purposes.

**Comment by seriva** [comment]
Changing this in the context of OpenSearch. We might need to verify again how todo this there.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
