### ISSUE TITLE
[FEATURE REQUEST] Add availability zones for cluster components on Azure

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#142]
**Is your feature request related to a problem? Please describe.**
Currently we cannot specify availably zones on Azure for cluster components.  Without availability sets, Azure will not guarantee no service disruption.

**Describe the solution you'd like**
Add availably zones support to the Epiphany Azure provider.

**Describe alternatives you've considered**
None

**Additional context**
https://docs.microsoft.com/en-us/azure/availability-zones/az-overview
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/availability_set
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#zones

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by gj25** [comment]
Hi, is this issue fixed for Azure deployments on 0.5.1? We have tried the install and no availability sets have been created. Thanks.

**Comment by seriva** [comment]
@gj25 No that is not fixed jet.

**Comment by gj25** [comment]
@toszo is this fixed for 0.6.0.
Without availability sets, Azure will not guarantee no service disruption so we would need this for the new production clusters for DE .

**Comment by seriva** [comment]
Not going to do this anymore for Epiphany so closing.
