### ISSUE TITLE
[spike] identify if we should backup RabbitMQ data

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1430]
**Description**
To be able to proceed with RabbitMQ backup/restore processes it's necessary to identify which data is sensitive and needs to be managed additionally.

**Expected results**
 - RabbitMQ docs are analysed
 - It's identified and documented which data is sensitive
 - Description of following (blocked) tasks is updated

**Cloud Environment (please complete the following information):**
 - Azure
 - AWS
 - On-prem

**Additional context**
No

**Comment by seriva** [comment]
Closing as we currently don't have a valid business case anymore.
