### ISSUE TITLE
[FEATURE REQUEST] Separate preflight checks for 'epicli apply' and 'epicli upgrade'

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1433]
**Is your feature request related to a problem? Please describe.**
We need to add preflight check only for 'epicli upgrade' mode to verify whether existing version of Kubernetes is supported by Epiphany. Since v0.7.0 we do not support K8s versions older than 1.14.6 (Epiphany v0.4.4) and we do not inform users about this using a friendly message.

Without such check user who tries upgrade old (not supported) cluster will wait for repository setup (for example 15 min) and then get unexpected error (possibly not easy to interpret).

**Describe the solution you'd like**
We should check the prerequisite before running `repository_setup` role and inform the user that they need to use older Epiphany version first to upgrade Kubernetes to the supported version or create a new cluster using `epicli apply` instead.

**Describe alternatives you've considered**
The preflight check could be in the `upgrade` role but the drawback is that the assertion will fail after wasting some time for repository setup. 

**Additional context**
This feature would also bring additional benefits, e.g. we could differentiate supported OS versions for new and existing clusters, for example for a new cluster RHEL 7.8 could be required but for upgrade 7.6 could be allowed as well.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
@to-bar pls verify if this is still something valid.

**Comment by to-bar** [comment]
We already have this feature since version 1.1.
