### ISSUE TITLE
[Epic] Kubernetes Autoscaling

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1439]
Kubernetes Autoscaling functionality with following assumptions: 
* AKS and EKS managed clusters components will be introduced. 
* managed clusters would be tested how they scale with increased and decreased load
* managed clusters would be packaged to new epiphany configurations. 
* validation would ensure that there is just one Kubernetes cluster component in environment. 
* new managed Kubernetes clusters would be integrated with existing components.
* there would be additional testing pipelines

**Comment by seriva** [comment]
Closing as this is not longer valid for the current Epiphany strategy. We can revisit if this ever becomes relevant again.
