### ISSUE TITLE
AKS cluster setup

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1440]
Prepare terraform scripts to setup AKS cluster. Not integrate with epiphany code yet, might be some new directory. 

**Is your feature request related to a problem? Please describe.**
We need to introduce AKS managed cluster as component to our environment. 

**Describe the solution you'd like**
As this task is first in line of multiple tasks related to AKS introduction, I'd like to have separate directory with terraform scripts not integrated with epiphany at all.

**Describe alternatives you've considered**
Unknown. 

**Additional context**
Here are some initial useful links:

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html
https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks

This scripts should also consider creation of AKS with 
* different operating systems, 
* different network drivers, 
* different resource groups
* existing networks

etc. If any of this topics is complicated it should be separated to another task.

**Comment by mkyc** [comment]
There is [comment](https://github.com/epiphany-platform/epiphany/issues/1447#issuecomment-658991121) from @rafzei giving helpful links regarding networking: 

> Regarding network plugins I see two available options in AKS:
> ```
> 1. Basic - Kubenet (aka kubenet)
> 2. Advanced - Azure CNI (aka azure)
> ```
> both have Calico support in case of network policies. 
> Network concepts quite well described here:
> https://docs.microsoft.com/en-us/azure/aks/concepts-network
> 
> Comparison of Azure Network Policy & Calico:
> https://docs.microsoft.com/en-us/azure/aks/use-network-policies

**Comment by rpudlowski93** [comment]
Configuration almost done using Terraform scripts. 
Features done: 
- different operating systems
- different virtual machines specification (disk size, 
- different cluster specification (size, location, name, public ip, k8s version, name)
- different network drivers (basic/advance)
- different resource groups
- possibility to create new network or use existing network


The topic is very interesting but also complicated, many topics require discussions. AKS has a specific architecture. After needed discussions I will share the code and implement needed changes.

**Comment by rpudlowski93** [comment]
AKS cluster setup using terraform scripts done in PR #1517. Design Doc done. Need to be tested by someone else and will be ready to DoD.

**Comment by mkyc** [comment]
@mum0l can you test this?

**Comment by mum0l** [comment]
Tested. All components works as expected. All good.
