### ISSUE TITLE
EKS cluster setup

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1442]
Prepare terraform scripts to setup EKS cluster. Not integrate with epiphany code yet, might be some new directory. 
**Is your feature request related to a problem? Please describe.**
We need to introduce EKS managed cluster as component to our environment. 

**Describe the solution you'd like**
As this task is first in line of multiple tasks related to EKS introduction, I'd like to have separate directory with terraform scripts not integrated with epiphany at all.

**Describe alternatives you've considered**
Unknown. 

**Additional context**
Here are some initial useful links:

https://learn.hashicorp.com/terraform/kubernetes/provision-eks-cluster

This scripts should also consider creation of EKS with 
* different operating systems, 
* different network drivers, 
* existing VPCs

etc. If any of this topics is complicated it should be separated to another task.

**Comment by mum0l** [comment]
Ticket owner:
- Please, put into description, which components are mandatory (from our side) to deploy complete EKS cluster. For example: IAM, VPC, storage etc.
- Which parameters are expected in configuration, to smoothly integrate it with our platform.

Summary:
From my side, I can own this ticket as its super interesting! As a starting point, I suggest to go thru official TF docs and AWS TF modules:
- https://learn.hashicorp.com/terraform/kubernetes/provision-eks-cluster
- https://github.com/terraform-aws-modules/terraform-aws-eks
- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

**Comment by mkyc** [comment]
@mum0l I don't think we need IAM in that phase. VPC, Security Groups, AutoScaling Groups, EKS Cluster, Storage, etc, would be ok. As of parameters that would be considered in #1445 and #1448.

**Comment by mkyc** [comment]
This task is similar to #1440 in it's aim. It should be discussed between persons preparing those scripts.

**Comment by mkyc** [comment]
There is [comment](https://github.com/epiphany-platform/epiphany/issues/1448#issuecomment-658649421) from @rpudlowski93 regarding networking drivers.

**Comment by mkyc** [comment]
@rpudlowski93 can you test this?

**Comment by rpudlowski93** [comment]
Tests done: 
- 12.2.0 version of aks module require at least 0.12.9 version of terraform, in our case terraform in version 0.12.6 works fine with 7.0.0 module of aks - tested. 
- cluster creation works fine on Linux OS but there is a issue when You want to run the cluster creation process on Windows OS - it looks like a bug reported here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/607
