### ISSUE TITLE
EKS cluster autoscaling tests

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1443]
Prepare manual load tests to ensure that cluster scales up and down as expected. Load tests will be included later into epiphany code but not at that moment.

**Is your feature request related to a problem? Please describe.**
EKS clusters we will provide in epiphany need to have horizontal autoscaling enabled and tested. 

**Describe the solution you'd like**
There should be some Kubernetes Deployment defined with images applying some high load on cluster. With this deployment we should be able to scale number of replicas up and down, and check if vertical autoscaler is responding accordingly and scales nodes up and down. 

Deployment and description of commands should be committed to sub-directory with terraform scripts of EKS cluster. There is no need to integrate it with any test pipeline at this point. 

**Describe alternatives you've considered**
Unknown. 

**Additional context**
No.

**Comment by mkyc** [comment]
This task is extremely similar to #1441 and code might be shared by both tasks.

**Comment by przemyslavic** [comment]
I'm having problems deploying a cluster.
Looks like an issue installing chart.
```
Error: failed to download "stable/cluster-autoscaler" (hint: running `helm repo update` may help)

  on cluster-autoscaler.tf line 1, in resource "helm_release" "cluster-autoscaler":
   1: resource "helm_release" "cluster-autoscaler" {
```

**Comment by mum0l** [comment]
@przemyslavic  - I am working on that.. Looks like there is an issue when deploying 2 clusters.
Simplest solution which is working properly is to re-use the "cluster-autoscaler" role for other deployments, but @pyrkamarcin  mention that this solution might be not secure, so I am looking for other possibilities to run multiply roles  - one per cluster. Sadly its quite tought

**Comment by mum0l** [comment]
Just make a new PR: https://github.com/epiphany-platform/epiphany/pull/1623 - please review

**Comment by mum0l** [comment]
I already test the autoscaling feature, but it will be good if someone else will check it.
Some docs, which I did recently:
https://github.com/mum0l/epiphany/blob/feature/eks_autoscaler_fix/docs/design-docs/eks/README.md#testing-the-autoscaling-feature

**Comment by mum0l** [comment]
@przemyslavic could you test it again?

**Comment by przemyslavic** [comment]
Autoscaling has been tested in the same way as for the AKS cluster (according to the scenario described [here](https://github.com/epiphany-platform/epiphany/blob/feature/eks-cluster-creation/docs/design-docs/eks/README.md#testing-the-autoscaling-feature)). The number of pods and nodes varied depending on the load. Seems to be working properly.
