### ISSUE TITLE
AKS cluster epiphany configuration 

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1444]
Create AKS cluster configuration to be able to create it using epiphany. 

**Is your feature request related to a problem? Please describe.**
We need to have possibility to create AKS cluster with epiphany. 

**Describe the solution you'd like**
In previous tasks in order (#1440, #1441) terraform scripts should already be prepared. That means that here we want to develop yaml configs similar to what we have in epicli, inserting those previously prepared terraform scripts, embed it in epiphany environment to be able to create cluster with epiphany. This task is basically "do the thing" task. Previous ones are preparations.

**Describe alternatives you've considered**
This task has to consider what would be output from task #1462 as it will discuss modularisation in epiphany. 

**Additional context**
No.

**Comment by sk4zuzu** [comment]
@mkyc are we talking here about yaml configs that we have in epicli? Or is it something else like terraform configs etc?

**Comment by mkyc** [comment]
In previous tasks in order (#1440, #1441) terraform scripts should already be prepared. That means that here we want to develop yaml configs we have in epicli, inserting those previously prepared terraform scripts, embed it in epicli to be able to create cluster with epiphany. This task is basically "do the thing" task. Previous ones are preparations. 

One more comment here is that thing in brackets. This task depends slightly on component versioning epic (which is not in GH so far) and before start of this task, it should be reviewed again with output of researches in that other epic in mind.

**Comment by sk4zuzu** [comment]
@mkyc thank you, that makes it clearer. :+1:

>One more comment here is that thing in brackets. This task depends slightly on component versioning epic (which is not in GH so far) and before start of this task, it should be reviewed again with output of researches in that other epic in mind.

I'm keeping the `status/grooming-needed` label then.

**Comment by mkyc** [comment]
What we discuss so far is:
 * if we go with classic epiphany model we need to think of: 
   * specification part inside epiphany configuration
   * also offline-related sections should be optimised 
   * verify if AKS-related terraform code can be downgraded to Epiphany terraform version
 * if we go with modularised way we need to think of: 
   * `--external-kubernetes=/shared/kubeconf` switch
   * preparation of separate aks module
   * preparation of separate infrastructure module
 * for both approaches we need to think of: 
   * coreDNS hosts plugin
   * prometheus endpoints from AKS
   * possibility to install filebeat as DaemonSet
   * all Kubectl usage in Ansible has to be changed to remote use
   * the same with helm

**Comment by mkyc** [comment]
This diagram shows what would be order of modules execution in modularisation approach: 

![AKS-modules-order.png](https://images.zenhubusercontent.com/5ef4ad9f4408ae79e992e8d6/973357d3-0f4e-4971-b62d-cf407f44ed25)

**Comment by mkyc** [comment]
As is was decided we are not going to include any managed kubernetes clusters configuration inside epiphany, but we will release AKS as separate module already [done here](https://github.com/epiphany-platform/m-azure-basic-infrastructure).
