### ISSUE TITLE
epiphany validation ensuring only one Kubernetes type configuration present

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1446]
**Is your feature request related to a problem? Please describe.**
Right now more than one configuration of Kubernetes cluster can exist in Epiphany configuration file.

**Describe the solution you'd like**
Validation should check if there exist more than one Kubernetes cluster configuration and fail validation if will find
multiple configurations.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by mkyc** [comment]
@sk4zuzu can you help me with that issue? In theory it is no longer required and eventually it will be modules dependency mechanism what would be responsible for that. But AFAIK there is still possibility to install Epiphany on AzBI and AzKS and deploy Kubernetes-master and Kubernetes-nodes on AzBI provided machines ... and in result have two kubernetes clusters in environment.

**Comment by DaOsie** [comment]
In my opinion, having strict rule for supporting only one configuration of kubernetes would be a good idea - less edge cases, clarity in config file and users input validation. Although, more expirienced person than me should look at this task.

**Comment by mkyc** [comment]
Yes, I believe that in usage with epiphany single-kubernetes approach is correct.

**Comment by seriva** [comment]
Closing as the work on modules is halted.
