### ISSUE TITLE
AKS cluster epiphany integration 

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1447]
**When** I setup epiphany environment with AKS cluster **I want** to have communication to/from other epiphany components in place, **so I can** order my application running on AKS to use those components. 

**Is your feature request related to a problem? Please describe.**
After epiphany environment criterion with AKS cluster deployment we should be able to connect to any other available Epiphany component (Kafka, RabbitMQ, Logging, Monitoring, etc..). These components have to talk with each other.  

**Describe the solution you'd like**
Ensure that epicli configuration is correct when there is AKS cluster used instead of our unmanaged one. 

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
This task will be very similar in its goals with #1448 so might be developed in cooperation.

**Comment by rafzei** [comment]
After AKS cluster deployment we should be able to start a new instance (or connect to existing one) of every available Epiphany component (Kafka, RabbitMQ, Logging, Monitoring, etc..). These components have to talk with each other within AKS cluster.

Regarding network plugins I see two available options in AKS:
```
1. Basic - Kubenet (aka kubenet)
2. Advanced - Azure CNI (aka azure)
```
both have Calico support in case of network policies. 
Network concepts quite well described here:
https://docs.microsoft.com/en-us/azure/aks/concepts-network

Comparison of Azure Network Policy & Calico:
https://docs.microsoft.com/en-us/azure/aks/use-network-policies

**Comment by mkyc** [comment]
This task is similar to #1448 so should be developed with close cooperation with that another one.

**Comment by mkyc** [comment]
As this is solved with modules mechanism and local kubernetes was introduced in #1654 it should be closed.
