### ISSUE TITLE
EKS cluster epiphany integration 

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1448]
**When** I setup epiphany environment with EKS cluster **I want** to have communication to/from other epiphany components in place, **so I can** order my application running on EKS to use those components. 

**Is your feature request related to a problem? Please describe.**
Amazon EKS exposes a Kubernetes API endpoint and Epiphany components (Kafka, RabbitMQ, Logging, Monitoring, etc..) could connect directly to EKS managed control plane. These components have to talk with each other.  

**Describe the solution you'd like**
Keep total functionality of Epiphany platform after setup EKS cluster with using **all epiphany's components** such as Kafka, Grafana, Prometheus, Elasticsearch etc... Ensure that epicli configuration is correct when there is AKS cluster used instead of our unmanaged one. 

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
This task will be very similar in its goals with #1447 so might be developed in cooperation.

**Comment by rpudlowski93** [comment]
@mkyc Should we take into consideration integration EKS cluster with CNI plugins such as Canal, Flannel, Calico? As I understand, EKS use native Amazon VPC CNI plugin.

**Comment by mkyc** [comment]
@rpudlowski93 is that even possible to change network driver on EKS?

**Comment by rpudlowski93** [comment]
@mkyc. Yes, I did small research and it looks like there are still some alternate compatible CNI plugins for EKS such as Calico or Flannel.

https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html

**Comment by mkyc** [comment]
@toszo can you decide about it? I'm not sure what are the reasons that we have multiple network drivers anyway.

**Comment by toszo** [comment]
Supporting multiple network drivers was introduced because flannel has best performance where calico/canal has better security - should be used depending on the use case. 

I prefer to keep ability to select the network driver.

**Comment by erzetpe** [comment]
In official documentation of EKS they state - Amazon EKS only officially supports the Amazon VPC CNI plugin. 

I would stick only to officially supported plugin, to avoid troubleshooting in unknown environment other plugins.

https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html

**Comment by mkyc** [comment]
As this is solved with modules mechanism and local kubernetes was introduced in #1654 it should be closed.
