### ISSUE TITLE
[FEATURE REQUEST] Create Kubernetes Native Storage Epiphany configuration for Azure provider

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1452]
**Is your feature request related to a problem? Please describe.**
We don't have any configuration for Kubernetes Native Storage in Epiphany on Azure.

**Describe the solution you'd like**
We want to create configuration that will be used in Epiphany deployments with proper defaults, 
that can be overridden by the user. 

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Spike with offline packages: [#1457](https://github.com/epiphany-platform/epiphany/issues/1457)

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by seriva** [comment]
This issues should be changed to make sure it includes the best support for the cloud native storage, also as we AWS changes we might want to split this up in AWS and Azure seperately.
