### ISSUE TITLE
Create PostgreSQL performance test comparison

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1453]
**Is your feature request related to a problem? Please describe.**
We don't have any data on performance of Rook Operator and any comparison data.

**Describe the solution you'd like**
We want to have comparision of performance between Rook Operator storage with normal storage with using
for comparison purpose PostgreSQL backend.

Test plan can be similar to the one below:
1. Have epiphany cluster with PostgreSQL database created in standard epiphany way
2. Create performance test running in Kubernetes pod using PostgreSQL in current setup (pgbench can be used)
3. Deploy Rook Operator and create Ceph cluster
4. Create PostgreSQL database running in Kubernetes pod using Ceph PVC (use some of those https://operatorhub.io/?keyword=postgresql)
5. Run performance test using Kubernetes PostgreSQL instance
6. Compare results

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by ar3ndt** [comment]
Test results look like the following:

WRITE NO PVC CURRENT SETUP:
`transaction type: <builtin: simple update>
scaling factor: 1
query mode: simple
number of clients: 100
number of threads: 1
duration: 300 s
number of transactions actually processed: 1198256
latency average = 25.052 ms
tps = 3991.660980 (including connections establishing)
tps = 3991.698811 (excluding connections establishing)`

WRITE  PVC WITH CEPH (block storage):
`transaction type: <builtin: simple update>
scaling factor: 1
query mode: simple
number of clients: 90
number of threads: 1
duration: 300 s
number of transactions actually processed: 915886
latency average = 29.486 ms
tps = 3052.266371 (including connections establishing)
tps = 3052.285772 (excluding connections establishing)
`

WRITE  PVC WITH CEPH (block storage) INSTALLED WITH CRUNCHY PGO:
`transaction type: <builtin: simple update>
scaling factor: 1
query mode: simple
number of clients: 90
number of threads: 1
duration: 300 s
number of transactions actually processed: 741266
latency average = 36.440 ms
tps = 2469.828167 (including connections establishing)
tps = 2469.852819 (excluding connections establishing)
`
------------------------------------------------------

Test results look like the following:

READ NO PVC CURRENT SETUP:
`transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 100
number of threads: 1
duration: 300 s
number of transactions actually processed: 5159306
latency average = 5.818 ms
tps = 17188.423726 (including connections establishing)
tps = 17188.528112 (excluding connections establishing)
`

READ  PVC WITH CEPH (block storage):
`transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 90
number of threads: 1
duration: 300 s
number of transactions actually processed: 4749131
latency average = 5.686 ms
tps = 15827.274870 (including connections establishing)
tps = 15827.371305 (excluding connections establishing)
`

READ  PVC WITH CEPH (block storage) INSTALLED WITH CRUNCHY PGO:
`transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 90
number of threads: 1
duration: 300 s
number of transactions actually processed: 3993386
latency average = 6.761 ms
tps = 13311.008753 (including connections establishing)
tps = 13311.180973 (excluding connections establishing)`

**Comment by toszo** [comment]
@ar3ndt  can you create table with comparison "Rook (Ceph) | VM"?

**Comment by ar3ndt** [comment]
|   | write tps  | read tps  | replicas  | vm/k8s  |
|---|---|---|---|---|
| NO PVC  | 4200  | 18402 | 2  | vm  |  
| NO PVC | 3991 | 17188 | 1 | k8s  |  
| PVC WITH CEPH  |  3052  | 15827 | 1  | k8s  |  
| PVC WITH CEPH & PGO   | 2469  | 13311  | 1  | k8s  |  
| PVC WITH CEPH & PGO   | 2382  | 12720  | 3 | k8s  |

**Comment by mkyc** [comment]
LGTM. Results in table are clear. Moving to DoD Check.

**Comment by to-bar** [comment]
Notes for the future:

With `pgbench` you may test at the 3 levels of performance related to disk: in buffer, mostly in cache, and all on disk. You manipulate this by changing the scale factor, see [Memory_vs._Disk_Performance](https://wiki.postgresql.org/wiki/Pgbenchtesting#Memory_vs._Disk_Performance).

While running read-only test cases (with the `-S` option), it's good practice to measure the database cache hit ratio (query from `pg_stat_database`). At table level we can use: `EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM <table_name>;`

It seems PostgreSQL do not have any predefined functionality to clear the cache from the memory. To clear the database level cache, we need to shut down the whole instance then clear the operating system cache. 

Steps:
1) Shut down PostgreSQL cluster
2) Clear OS cache as follows:
```
sync
echo 3 >/proc/sys/vm/drop_caches
```
3) Start PostgreSQL instance

It is also possible to collect timing statistics for database I/O activity, see [track_io_timing](https://postgresqlco.nf/en/doc/param/track_io_timing/).
