### ISSUE TITLE
[doc] Prepare example application using PVC

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1454]
**Is your feature request related to a problem? Please describe.**
We don't have any application to present PVC usage.

**Describe the solution you'd like**
We need to create simple app to show PVC usage and also documentation how PVC is used.

**Describe alternatives you've considered**
No  alternatives.

**Additional context**
No additional context.

**Comment by toszo** [comment]
There is a dotnet application that can be extended to use PVC -> https://github.com/epiphany-platform/epiphany/tree/develop/examples/dotnet/Epiphany.Examples.Web
It exposes UI and REST endpoints so PVC usage would be presented to the user or automation.

**Comment by erzetpe** [comment]
Closing as there are already applications to perform tests.
