### ISSUE TITLE
Increase visibility of test results

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1467]
**Is your feature request related to a problem? Please describe.**
Our test matrix and test display should be improved.

**Describe the solution you'd like**
We want to increase visibility of tests:
1.	Provide test matrix and make it visible to team. 
2.	Include test matrix review as part of DoD.  

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by seriva** [comment]
IMO improved with output of tests on every pull.
