### ISSUE TITLE
[FEATURE REQUEST] Add assertion to check whether K8s version is supported before running upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1474]
**Is your feature request related to a problem? Please describe.**
We need to add assertion to verify whether existing version of Kubernetes is supported by Epiphany. Since v0.7.0 we do not support K8s versions older than 1.14.6 (Epiphany v0.4.4) and we do not inform users about this using a friendly message.

Without such check user who tries upgrade old (not supported) cluster will get unexpected error (possibly not easy to interpret).

**Describe the solution you'd like**
Add assertion to the `upgrade` role, the drawback is that the assertion will fail after waiting some time for repository setup. The preferred solution is described in #1433 but it requires more work than this issue.

**Comment by przemyslavic** [comment]
The upgrade from 0.4.4, 0.5.4 and 0.6.0 to develop has been tested. The assertions were satisfied.
Can't check assertion for version 0.3.1 due to the issue [#1491](https://github.com/epiphany-platform/epiphany/issues/1491).
