### ISSUE TITLE
docker layering structure

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1478]
**When** I need to use new component of epiphany, **I want to** download as small portion of docker images as possible, **so I don't** spend too much time every time I try something new. 

In this task we should check what we already have in docker images, do we layer them correctly, do we have some smart "images tree policy", etc.

**Comment by rafzei** [comment]
Is this more about epicli docker image layers or image_registry to check&fetch only these images required to enable specific components (version)?

**Comment by seriva** [comment]
None of these, this would be how we want to layer the docker images for components if we go that route.

**Comment by seriva** [comment]
Not needed anymore as we are probably not moving forward with modules.
