### ISSUE TITLE
offline installation in modularised world

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1481]
we should define how process of offline installation will look like in versioned and modularised model

**Comment by ar3ndt** [comment]
**Is your feature request related to a problem? Please describe.**

Once epi code is divided to separate modules the offline installation process will be broken.

**Describe the solution you'd like**

Add offline installation option of each component after modularisation.


**Describe alternatives you've considered**
None

**Additional context**
No.

**Comment by mkyc** [comment]
# Offline installation with modules
## Preface
Due to ongoing modularization process and slow introduction of middleware modules we need to decide how modules would obtain required binaries for “offline” mode. 

## Assumptions
Each module has access to the “/shared” directory. Most wanted way to use modules is via “e” CLI app. 

## Options
### Option 1
Each module docker image has all required binaries embedded in itself during build process. 

Pros
 * There is no “download requirements” step.
 * Each module has all requirements ensured on build stage.

Cons
 * Module image is heavy.
 * Possible licensing issues. 

### Option 2
There is separate docker image with all required binaries for all modules embedded in itself during build process. There is no “download requirements” step.

Pros
 * There is no “download requirements” step.
 * All requirements are stored in one image.

Cons
 * Image would be extremely large.
 * Possible licensing issues.

### Option 3
There is separate “dependencies” image for each module containing just dependencies. There is no “download requirements” step. 

Pros
 * There is no “download requirements” step.
 * Module image itself is still relatively small.
 * Requirements are ensured on build stage. 

Cons
 * “Dependencies” image is heavy.
 * Possible licensing issues.

### Option 4
Each module has “download requirements” step and downloads requirements to the “/shared” directory directly. 

Pros
 * Module is responsible for downloading its requirements on its own. 
 * Currently existing “export/import” CLI feature would be enough. 

Cons
 * Offline upgrade process might be hard. 
 * Each module would perform download bit differently. 

### Option 5
Each module has “download requirements” step and downloads requirements to docker named volume. 

Pros
 * Module is responsible for downloading its requirements on its own.
 * Generic docker volume practices could be used

Cons
 * Offline upgrade process might be hard. 
 * Each module would perform download bit differently.

### Option 6
Each module contains “requirements” section in its configuration, but there is one single module downloading requirements for all 

Pros
 * Module is responsible for creation of BOM and single “downloader” container satisfies needs of all the modules. 
 * Centralised downloading process. 
 * Manageable offline installation process. 

Cons
 * Another “module”

## Discussion
 * Options 1, 2 and 3 are probably unelectable due to licenses of components and possibly big or even huge size of produced images.  
 * Options 4 and 5 will introduce possibly bit of a mess related to each module managing downloads on its own. Also upgrade process in offline mode might be problematic due to burden related to provide new versions for each module separately. 
 * Option 6 sounds like most flexible one. 

## Installation modes
Currently identified modes are: 
 * Online – all machines have access to internet. 
 * Jump Host – cluster machines do not have access to internet. There is single jump host machine which has both access to internet and to cluster machines. Cluster machines can access jump host machine services. 
 * Bastion – cluster machines do not have access to internet. There is bastion machine which has access to machines but also does not have access to internet. Cluster machines can access bastion machine services. 

In online mode there is no need to have “repository”, but in both “air gapped” scenarios there is a need for “repository” and the best place to put it is jump host / bastion machine. It looks like “downloader” module described in Option 6 point should be closely connected with “repository” module.

**Comment by seriva** [comment]
Few comments:

1. I would not dismis 1..3 before doing some spiking and talking to the BDS people as there can be a few benefits to this approach:
   - We control the download locations as in, if we want we could even host all of this stuff on our own docker repo on Azure/AWS and make E configurable.
   - People will only download what they require.
   
   However 2 and 3 I think we could dismis as: 
   - One big download image is not very practicle as people need to download everything, even if they only need to install a few components
   - Seperate dependencies image per component would mean just downloading 2 images instead of 1 if we would embed the resources.
   
   Only main issue is that 1..3 would only work for containers and binairies but not OS packages as these are dependent on the targeted OS version and installation. This is something we cannot forsee or bundle for.
2. Totally agreed with the comments on 4 and 5 as it will only replicate the mess we are dealing with now.
3. Agreed that option 6 would be the most flexible one.
