### ISSUE TITLE
[BUG] Documentation adjustment - Clustering k8s

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1496]
**Describe the bug**
This issue was created to fix documentation regarding the **clustering** Epiphany environment.
During some minor changes in readme.md it turned out that we are not describing things properly. 

**Expected behavior**
[CLUSTER.MD](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) has to provide real information about what user can achieve increasing/decreasing a `count` in manifest.yml.
The most important cases are:
-  describe how specific component will behave when increasing/decreasing amount of vm (if its already described in the component description - put down a link)
- describe how master/node will behave when increasing/decreasing its `count` value (and what does it mean)
- describe steps to manually delete node/master from Kubernetes cluster

**OS (please complete the following information):**
 - OS: All

**Cloud Environment (please complete the following information):**
 - Cloud Provider: All

**Additional context**
If you approach any inaccuracies in another (related) document, please create another issue with a specific case.

**Comment by TolikT** [comment]
Should be updated with an information from #1497
