### ISSUE TITLE
Upgrade Kubernetes Dashboard to v2.0.3

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1510]
**Is your feature request related to a problem? Please describe.**
We have K8s Dashboard in version 2.0.0-beta8 (from Dec 6, 2019) which according to documentation may be incompatible with K8s v1.18.6. See [Compatibility table](https://github.com/kubernetes/dashboard/releases/tag/v2.0.0-beta8).

We have also a non-deterministic issue related to K8s Dashboard, see [#1394](https://github.com/epiphany-platform/epiphany/issues/1394).

**Describe the solution you'd like**
Upgrade to the version with confirmed compatibility with K8s v1.18, which currently is [2.0.3](https://github.com/kubernetes/dashboard/releases/tag/v2.0.3).

**Comment by przemyslavic** [comment]
The latest version of the Kubernetes dashboard `v2.0.3` has been tested (both deploying a new cluster and upgrading the existing one from `0.4.4`, `0.5.4` and `0.6.0`). It seems to be working fine.

**Comment by toszo** [comment]
@rafzei please add Dashboard row in COMPONENTS.md file.
