### ISSUE TITLE
[spike] EKS - diffrent network drivers setup

### ISSUE THREAD

**Issue by mum0l** [epiphany-platform/epiphany#1511]
**Is your feature request related to a problem? Please describe.**
So far, the EKS cluster scripts have been created (PR 1489). Different network drivers require more time spend on it, so we decide to spit it into separate task. Current investigations with different drivers:

1. **Calico** - It's possible to implement, but cluster needs to be created with ekscli, and there is no support for terraform, so w stuck a bit. Lets do some research on that. Links:
- https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks 

2. **Flannel** - I was unable to get it working. - get some issues after deploying simple app. Links:
- Legacy: https://coreos.com/flannel/docs/latest/kubernetes.html
- Current: https://github.com/coreos/flannel
- Other: https://medium.com/@jeremy.i.cowan/running-flannel-on-eks-9a2f7a285a23

**Describe the solution you'd like**
More depth research

**Describe alternatives you've considered**
Use awscli to setup the cluster, or find a better solution

**Additional context**
Amazon EKS clusters come with default Amazon CNI driver, and the cons for it, is that driver is supporting newer kubernetes versions (in example 1.17). The only limitations which comes with that solutions is that with this driver, we have some limitations on number of pods per node (different network drivers might do the job).
https://www.contino.io/insights/kubernetes-is-hard-why-eks-makes-it-easier-for-network-and-security-architects

**Comment by erzetpe** [comment]
Because of the statement in the official AWS documentation: 

> Amazon EKS only officially supports the Amazon VPC CNI plugin. Amazon EKS runs upstream Kubernetes and is certified Kubernetes conformant however, so alternate CNI plugins will work with Amazon EKS clusters. If you plan to use an alternate CNI plugin in production, then we strongly recommend that you either obtain commercial support, or have the in-house expertise to troubleshoot and contribute fixes to the open source CNI plugin project.

I am closing this issue as we cannot provide a setup without support of AWS or Azure. More information accessible at:
https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html
