### ISSUE TITLE
[spike] EKS joining diffrent VPC 

### ISSUE THREAD

**Issue by mum0l** [epiphany-platform/epiphany#1513]
**Is your feature request related to a problem? Please describe.**
Currently, terraform scripts prepared via #1442 creates new VPC each time the new cluster is set. We need to adjust this configuration, so we can easily join cluster to existing VPCs in AWS.

**Describe the solution you'd like**
Optionally create a VPC 

- https://medium.com/datamindedbe/how-to-conditionally-disable-modules-in-terraform-f38fdbe34f1b
- use `count` inside a module starting from Terraform v0.13: https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/README.md

**Describe alternatives you've considered**
N/A

**Additional context**
Are VPC's resources/subnets should be retrieved, collected and used automatically or they will be still present as variables?

**Comment by TolikT** [comment]
@mkyc please look at [Additional context] part. When it's clarified, we can move this task further. Described solutions seems to be applicable, but it needs to be verified.

**Comment by mkyc** [comment]
All clear :)

**Comment by rpudlowski93** [comment]
Done :) PR created #1671

**Comment by mum0l** [comment]
After creating VPC basing on those docs: https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html I was able to successfully deploy the EKS cluster using previously created VPC. After cluster deletion my VPC has been not deleted, so everything works properly.
