### ISSUE TITLE
[SPIKE] Research additional Kafka monitoring/metric solutions.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1526]
**Is your feature request related to a problem? Please describe.**
Currently the solution we have for monitoring and getting metrics from Kafka are based one:

- [Kafka Exporter](https://github.com/danielqsj/kafka_exporter)
- [JMX Exporter](https://github.com/prometheus/jmx_exporter)
- [Prometheus](https://prometheus.io/)
- [Grafana](https://grafana.com/)

While these tools work OK in most situations in some cases they might not be sufficient and cause problems like high CPU utilization and a large number of outstanding issues with for example the Kafka exporter plugin.

**Describe the solution you'd like**
We would like to investigate any alternative solutions which might be useful to add to Epiphany to monitor and get metrics on Kafka besides the above solution. A good starting point might be this article:

https://medium.com/@giorgosmyrianthous/overview-of-ui-monitoring-tools-for-apache-kafka-clusters-9ca516c165bd

**Additional context**
*

**Comment by ar3ndt** [comment]
Additional tools worth consideration:
https://sematext.com/blog/kafka-open-source-monitoring-tools/#toc-cruise-control-3 (Cruise Control)

**Comment by rpudlowski93** [comment]
SPIKE done in the PR: https://github.com/epiphany-platform/epiphany/pull/2063
