### ISSUE TITLE
Checkout possibility of tfvars file usage when deploying EKS

### ISSUE THREAD

**Issue by mum0l** [epiphany-platform/epiphany#1527]
This task is to checkout possibility of using tfvars file instead of regular ones.

**Comment by mum0l** [comment]
This was already implemented during the auto-scaling ticket #1568.

https://github.com/epiphany-platform/epiphany/pull/1568/files#diff-8d041ca9b2317841030bdc9984748b37

**Comment by mkyc** [comment]
If that was already done, I'm closing it.
