### ISSUE TITLE
[Spike] AKS - Research on Azure Kubernetes Network Policies 

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1538]
**Is your feature request related to a problem? Please describe.**
We don't have any information about Azure AKS network policies but we want to have knowledge about this prior to implementation of Azure Kubernetes Network Policies feature. 

**Describe the solution you'd like**
We want to have some design doc that shows how to use Network Policies in AKS and configure them as close as it possible to the solution that is available on EKS on AWS and on prem deployments.

**Describe alternatives you've considered**
None.

**Additional context**
We want only to consider Network Plugins and Policies that are supported by the cloud providers.

**Comment by seriva** [comment]
No longer valid
