### ISSUE TITLE
[Spike] EKS - Research on Kubernetes Network Policies 

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1539]
**Is your feature request related to a problem? Please describe.**
We don't have any information about EKS network policies but we want to have knowledge about this prior to implementation of EKS Network Policies feature.

**Describe the solution you'd like**
We want to have some design doc that shows how to use Network Policies in EKS and configure them as close as it possible to the solution that is available on AKS on Azure and on prem deployments.

**Describe alternatives you've considered**
None.

**Additional context**
We want only to consider Network Plugins and Policies that are supported by the cloud providers.

**Comment by rafzei** [comment]
I've put estimates to '2', if you disagree, please change it.

**Comment by seriva** [comment]
No longer valid
