### ISSUE TITLE
[BUG] make download requirements more stable

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1541]
**Describe the bug**

I have hit a situation (many times when re-run from the current system) that this role failed because the script
core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/download-requirements.sh

this part

```
repos_backup_file="/tmp/epi-repository-setup-scripts/enable-system-repos.sh"
if [[ ! -f /etc/apt/sources.list ]]; then
    if [[ -f /var/tmp/enabled-system-repos.tar ]] && [[ -f ${repos_backup_file} ]]; then
        echol "OS repositories seems missing, restoring..."
        ${repos_backup_file}
    else
        echol "/etc/apt/sources.list seems missing, you either know what you're doing or you need to fix your repositories"
    fi
fi

```

It comes to the the part `/etc/apt/sources.list seems missing, you either know what you're doing or you need to fix your repositories`

As you can see this relies on the /tmp/epi-repository-setup-scripts/enable-system-repos.sh.

- Set DEBIAN_FRONTEND=noninteractive for download-requirements.sh

**To Reproduce**
1. execute `epicli init ... (with params)`
2. edit config file 
3. execute `epicli apply ...`

**Expected behavior**

**Config files**
If applicable, add config files to help explain your problem.

**OS (please complete the following information):**
 - OS: [e.g. RHEL7]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [e.g. MS Azure]

**Additional context**

This task is to manage already existing PR #1521

**Comment by sk4zuzu** [comment]
I looked at the code and PR and I think the solution presented there is not correct. 🤔 Please take a look at my review comment https://github.com/epiphany-platform/epiphany/pull/1521#discussion_r472028545.

**Comment by przemyslavic** [comment]
The fix has been tested. If there is an issue downloading the image, a second attempt is made.
