### ISSUE TITLE
[FEATURE REQUEST] Implement ansible role postgres-exporter

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1542]
**Is your feature request related to a problem? Please describe.**
Missing PostgreSQL metrics for Prometheus

**Describe the solution you'd like**
Ansible role to provide PostgreSQL metrics service

**Additional context**
This task is to manage already existing PR #1518

**Comment by plirglo** [comment]
PR: https://github.com/epiphany-platform/epiphany/pull/1684
