### ISSUE TITLE
[BUG] Azure unmanaged disks not suppored by Epiphany but there is misleading setting in the default configuration

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1569]
**Describe the bug**
The default specification for Azure VM contains the following setting:
```
storage_os_disk:
  managed: false
```
This setting suggests that by default Epiphany will create unmanaged disk but managed disk is created.

**To Reproduce**
1. Create Azure cluster using the default configuration.
2. Check terraform.tfstate file, it will contain a value for `managed_disk_id`.

**Expected behavior**
Unmanaged disk created or no setting for not supported feature in the default configuration.

**Cloud Environment**
Cloud Provider: Azure

**Additional context**
Found in version 0.7.1.

**Comment by cicharka** [comment]
[This PR](https://github.com/epiphany-platform/epiphany/pull/2852) is changing default setting to true:
```bash
  storage_os_disk:
    managed: true
```
