### ISSUE TITLE
[BUG] Disks are not removed after downscale of any Epiphany component (Azure)

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1574]
**Describe the bug**
This bug is the result of #1497 spike and repeats for all Epiphany components in Azure. In addition the same should be checked for other providers.

**To Reproduce**
1. create a few instances of any component in Azure, for example `monitoring`  
2. edit config file to have lesser number of instances than before, for example `count: 0`
3. apply changes and check `Disk` resources 

**Expected behavior**
- All resources of removed instances should disappear, including disks.
- **[Documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) about scaling process should be updated.**

**Config files**
No 

**Cloud Environment (please complete the following information):**
 Azure, but should be also checked for other cloud providers.

**Additional context**
Found in version 0.7.1.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by rafzei** [comment]
The issue is still valid - checked on 1.3.0dev

**Comment by seriva** [comment]
This issue is probably caused by delete_os_disk_on_termination  flag we could set for VMs which was false by default. It was removed for 2.0.0 so we might want to re-introduce this at one point:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#delete_os_disk_on_termination
