### ISSUE TITLE
[BUG][Kafka] Incorrect number of brokers/queues available after scaling up/down

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1576]
**Describe the bug**
This bug is the result of #1497 spike.
After scaling up/down, numbers of Kafka brokers and queues are incorrect.

**To Reproduce**
Steps to reproduce the behavior (see `More information` part for some useful commands):
1. deploy 1 kafka instance
2. scale up to 3 instances
3. check the number of brokers - there is only 2 available
4. create 10 queues
5. scale kafka down to 2 instances, not all queues are listed on different nodes (in my case only 2 queues were created)
```
root@atsikham-scale-test-kafka-vm-1:~# /opt/kafka_2.12-2.3.1/bin/kafka-topics.sh --zookeeper localhost:2181 --list
topic2

root@atsikham-scale-test-kafka-vm-0:~# /opt/kafka_2.12-2.3.1/bin/kafka-topics.sh --zookeeper localhost:2181 --list
topic1
topic2
```

**Expected behavior**
- After scaling up/down, number of brokers and queues should be correct.
- **[Documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) about scaling process should be updated.**

**Config files**
No

**Cloud Environment (please complete the following information):**
Azure, but should also be tested with other providers.

**Additional context**
Found in version 0.7.1.

**More information**
Verification commands
```shell
systemctl status kafka
systemctl status zookeeper
# list brokers
echo dump | nc localhost 2181 - check available brokers
/opt/zookeeper-3.4.12/bin/zkCli.sh -server localhost:2181 ls /brokers/ids
# list topics
/opt/kafka_2.12-2.3.1/bin/kafka-topics.sh --zookeeper localhost:2181 --list
# create a topic
/opt/kafka_2.12-2.3.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic topic1
```
Configuration files
- /opt/kafka/config/server.properties
- /opt/zookeeper/conf/zoo.cfg

**Comment by przemyslavic** [comment]
Tested scenarios:
:heavy_check_mark: `epicli apply:` 3 kafka nodes -> 3 kafka nodes (re-apply)
:heavy_check_mark: `epicli apply:` 1 kafka node -> 3 kafka nodes -> 5 kafka nodes
:heavy_check_mark: `epicli apply:` 3 kafka nodes -> 1 kafka node
:heavy_check_mark: `epicli apply:` 3 kafka nodes -> created some topics -> 2 kafka nodes (manually deleted remaining os disk on Azure) -> 4 kafka nodes

All previously created topics were available after following the steps above.
When scaling down, disks are not deleted on Azure but this generally applies to scaling down for all components.
