### ISSUE TITLE
[BUG] Incorrect number of cluster instances when scaling up/down 

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1577]
**Describe the bug**
This bug is the result of #1497 spike. There is an incorrect number of postgresql cluster instances when scaling up/down.

**To Reproduce**
1. deploy 1 node of PostgreSQL
2. edit config file (see `Config files` part) to enable replication
3. scale up to 3 nodes (`count: 3`)
1 node is not joined to the cluster:

  ```text
  [postgres@atsikham-scale-test-postgresql-vm-0 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster show
  ID | Name                                | Role    | Status    | Upstream                            | Location | Connection string
  ----+-------------------------------------+---------+-----------+-------------------------------------+----------+-------------------------------------------------------------------
  1  | atsikham-scale-test-postgresql-vm-0 | primary | * running |                                     | default  | host=10.1.6.4 user=epi_repmgr dbname=epi_repmgr connect_timeout=2
  2  | atsikham-scale-test-postgresql-vm-1 | standby |   running | atsikham-scale-test-postgresql-vm-0 | default  | host=10.1.6.6 user=epi_repmgr dbname=epi_repmgr connect_timeout=2

  [postgres@atsikham-scale-test-postgresql-vm-0 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster crosscheck
                                 Name | Id |  1 |  2
  ------------------------------------+----+----+----
  atsikham-scale-test-postgresql-vm-0 |  1 |  ? |  ?
  atsikham-scale-test-postgresql-vm-1 |  2 |  ? |  ?


  [postgres@atsikham-scale-test-postgresql-vm-2 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster show
  ERROR: unable to retrieve node records
  DETAIL: ERROR:  relation "repmgr.nodes" does not exist
  LINE 1: ...le, un.node_name AS upstream_node_name       FROM repmgr.nod...
                                                             ^

  [postgres@atsikham-scale-test-postgresql-vm-2 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster crosscheck
  ERROR: unable to retrieve any node records
  ```
4. Scale down to 2 nodes, check cluster status
5. Remove the 3rd node's disk (bug #1574)
6. Scale up to 3 nodes, there are still 2 nodes in the cluster, but standby node is replaced:

  ```text
  [postgres@atsikham-scale-test-postgresql-vm-0 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster crosscheck
                               Name | Id |  1 |  2
  ------------------------------------+----+----+----
  atsikham-scale-test-postgresql-vm-0 |  1 |  ? |  ?
  atsikham-scale-test-postgresql-vm-2 |  2 |  ? |  ?
  [postgres@atsikham-scale-test-postgresql-vm-0 ~]$ /usr/lib/postgresql/10/bin/repmgr cluster show
   ID | Name                                | Role    | Status    | Upstream                            | Location | Connection string
  ----+-------------------------------------+---------+-----------+-------------------------------------+----------+-------------------------------------------------------------------
   1  | atsikham-scale-test-postgresql-vm-0 | primary | * running |                                     | default  | host=10.1.6.4 user=epi_repmgr dbname=epi_repmgr connect_timeout=2
   2  | atsikham-scale-test-postgresql-vm-2 | standby |   running | atsikham-scale-test-postgresql-vm-0 | default  | host=10.1.6.5 user=epi_repmgr dbname=epi_repmgr connect_timeout=2
```

**Expected behavior**
- There should be a correct number of (standby) nodes after upscale/downscale.
- Nothing should be changed in the cluster when applying the same configuration.
- Only specified changes should be added to the cluster when applying new configuration.
- **[Documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) about scaling process should be updated.**

**Config files**
```yaml
---
kind: configuration/postgresql
title: PostgreSQL
name: default
provider: azure
specification:
  extensions:
    replication:
      enabled: true
```

**Cloud Environment (please complete the following information):**
Azure, but should also be tested with other providers.

**Additional context**
Found in version 0.7.1.

**More Information**
Verification commands
```shell
ln -s /etc/postgresql/10/main/repmgr.conf /etc/repmgr.conf
sudo -i -u postgres
/usr/lib/postgresql/10/bin/repmgr cluster show
/usr/lib/postgresql/10/bin/repmgr cluster crosscheck
```

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by atsikham** [comment]
Primary/standby switching should be resolved in the scope of #1702. If it's not supposed to have more than 2 instances, it should be added to documentation (CLUSTER.md).

**Comment by plirglo** [comment]
Currently we support installation with one node machine, and several nodes (clustered), but not scalable. It's documented [here](https://github.com/epiphany-platform/epiphany/blob/v1.2/docs/home/howto/DATABASES.md#how-to-set-up-postgresql-ha-replication-with-repmgr-cluster)

Additionally created feature request to add such option (scaling up) do Epiphany: #2626

**Comment by seriva** [comment]
Going to close this one because:
- Concerns PG10
- Limitations documented
- New issues created to deal with this issue as was mentioned
