### ISSUE TITLE
[FEATURE REQUEST] Implement worker nodes downscale

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1580]
**Is your feature request related to a problem? Please describe.**
This request is the result of #1497 spike. At the moment Epiphany has no ability to scale down worker nodes correctly, this ability should be added. Such task existed previously - #1202, that work should be continued.

**Describe the solution you'd like**
When `count` of k8s worker nodes is decreased in config file and new configuration applied, all necessary work, such as cordon/drain nodes should be done before node removal by Terraform. 

**Describe alternatives you've considered**
No

**Additional context**
- **[Documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) about scaling process should be updated.**
- Should work for all cloud providers.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
