### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: scaling up and down Kafka

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1596]
**Is your feature request related to a problem? Please describe.**
Original task is #1051. We don't test scaling up/down components in our pipelines.
Scalability status is described in [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-scale-or-cluster-components).

**Describe the solution you'd like**
Create new pipelines with scaling up/down Epiphany components in Azure.

**Comment by mum0l** [comment]
Please put a comment how exactly this cluster is deployed (config?).
Is the issue simply related to the kafka pods number change, or sth else is changed as too?

**Comment by atsikham** [comment]
@mum0l this is a feature request, not a bug, so the way how to test Kafka scalability should be identified in the scope of this task. There is a link to documentation in description where the process is described.

**Comment by rafzei** [comment]
The bug regarding scaling up/down Kafka: https://github.com/epiphany-platform/epiphany/issues/1576
This FR is about creating a new pipeline like: 1- deploy Kafka , 2- scaling up, 3- do some checks, 4-scale down, 3- do some checks, 4- remove Kafka.

**Comment by przemyslavic** [comment]
A pipeline was created to test the scalability of the main components.
https://dev.azure.com/abb-epiphany/epiphany/_release?_a=releases&view=mine&definitionId=215
