### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: scaling up and down opendistro/logging

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1598]
**Is your feature request related to a problem? Please describe.**
The original task is #1051. We don't test scaling up/down components in our pipelines.
Scalability status is described in [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-scale-or-cluster-components).

**Describe the solution you'd like**
Create new pipelines with scaling up/down Epiphany components (opendistro & logging) in Azure DevOps.

**Comment by przemyslavic** [comment]
A pipeline was created to test the scalability of the main components.
https://dev.azure.com/abb-epiphany/epiphany/_release?_a=releases&view=mine&definitionId=215
