### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: scaling up and down load balancer

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1599]
**Is your feature request related to a problem? Please describe.**
We don't test scaling up/down components in our pipelines.

**Describe the solution you'd like**
Create new pipelines with scaling up/down Epiphany components in Azure.

**Describe alternatives you've considered**
None.

**Additional context**
Original task is #1051. Scalability status is described in [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-scale-or-cluster-components).

**Comment by przemyslavic** [comment]
A pipeline was created to test the scalability of the main components.
https://dev.azure.com/abb-epiphany/epiphany/_release?_a=releases&view=mine&definitionId=215
