### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: scaling up and down k8s control plane nodes

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1601]
**Is your feature request related to a problem? Please describe.**
Original task is #1051. We don't test scaling up/down components in our pipelines. This task consider scaling control plane nodes - master nodes.
We should create here pipelines for scaling up master nodes since scaling down feature is not impletented yet - [PR](https://github.com/epiphany-platform/epiphany/issues/1579). Scalability status is described in [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-scale-or-cluster-components).

**Describe the solution you'd like**
Create new pipelines with scaling up/down Epiphany components in Azure.

**Comment by rpudlowski93** [comment]
We don't have the feature with scaling down the control plane nodes so I think the task should consider only scaling up. 

> 
When increased this will setup additional control plane nodes, but in the case of non-ha k8s cluster, existing control plane node must be promoted first. At the moment there is no ability to downscal

**Comment by atsikham** [comment]
@rpudlowski93 this is why feature request was created. We need to have the ability for upscale/downscale.

**Comment by przemyslavic** [comment]
A pipeline was created to test the scalability of the main components.
https://dev.azure.com/abb-epiphany/epiphany/_release?_a=releases&view=mine&definitionId=215
