### ISSUE TITLE
[spike] exporting logs from Autoscaled AKS

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1608]
**Is your feature request related to a problem?:**
We need to know how to export logs from AKS nodes to our ElasticSearch. We need some solution which will be working with autoscaling cluster. All the services should be deployed as for example DaemonSets, since we don't want to install each service manually after scale up.

**Describe the solution you'd like:**
We would like to use our currect Filebeat configuration but install it as DaemonSet with access to host filesystem logs. Moreover We would like to have some "human readable" hostnames of nodes which will scale up/down.

**Describe alternatives you've considered:**

**Additional context:**
Bottom section of following diagram can be helpful: 
![AKS-observability.png](https://images.zenhubusercontent.com/5ef4ad9f4408ae79e992e8d6/98505b90-7935-45af-94b0-7573df5b664b)

Related to #1444

**Comment by rpudlowski93** [comment]
- We can't totally change hostname of AKS nodes. We can setup our custom "prefix" in the full hostname, for example in hostname aks-linux-24481073-vmss we can only change the "linux" part.

**Comment by rpudlowski93** [comment]
- The same as with prometheus, It is recommened to install filebeat as DaemonSets using Helm - [link] (https://hub.helm.sh/charts/elastic/filebeat) to ensure there’s a running instance on each node of the cluster. It is also possible to install filebeat using manilfest files, but I can't recommend it - [link](https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/filebeat-kubernetes.yaml)

**Comment by mkyc** [comment]
All as expected. Moving to DoD Check now.
