### ISSUE TITLE
[FEATURE REQUEST] Build epicli image using Dockerfile only (without shell script)

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1609]
**Is your feature request related to a problem? Please describe.**
To build `epicli` Docker image we use the `build-docker.sh` shell script. It builds `epicli` wheel  file (distribution package) which is used (copied) in the Dockerfile. The build script has no support for any `docker build` parameters (like tags or labels) and always creates the `epicli` image tagged as `latest`. This requires another task in the build pipeline to tag the image using the target tag. In case of parallel builds there is a risk that the tagging task will label not the right image. 

**Describe the solution you'd like**
Build `epicli` wheel file as a part of Dockerfile (using multistage builds feature) instead of wrapper script.

**Comment by mkyc** [comment]
Please remember also about: 
 * documentation update
 * after finish implementation create back port tasks

**Comment by to-bar** [comment]
> 
> 
> Please remember also about:
> 
>     * after finish implementation create back port tasks

Decided with @przemyslavic to not backport this feature to support branches.

**Comment by przemyslavic** [comment]
Changes have been tested. The docker image is built correctly both locally and in the CI pipeline. The devcontainer was also rebuilt and no problems were encountered. It was decided not to backport this as it is more of an improvement/feature than a critical fix.
