### ISSUE TITLE
[BUG] RabbitMQ Management Plugin is not enabled on vms by default

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#161]
**Describe the bug**
Have defined the rabbitmq_management plugin in the data.yaml file but for some reason it is not enabled on the vm.

`rabbitmq-plugins list rabbitmq_management`

> Listing plugins with pattern "rabbitmq_management" ...
 Configured: E = explicitly enabled; e = implicitly enabled
[  ] rabbitmq_management       3.7.10
[E ] rabbitmq_management_agent 3.7.10`

**Expected behavior**
That rabbitmq_management plugin will be installed.

**Config files**
None

**Environment**
RHEL 7.6

**epicli version**: [`epicli --version`]
TBD

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by seriva** [comment]
Needs to be verified if still an issue.
