### ISSUE TITLE
[FEATURE REQUEST] Add kubectl and Helm to epicli and devcontainer images

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1618]
**Is your feature request related to a problem? Please describe.**
There is no kubectl and helm binaries present in devcontainer and epicli containers.

**Describe the solution you'd like**
We need those two binaries in order to start interact with Kubernetes API from machine with epicli.

**Describe alternatives you've considered**
no alternatives. 

**Additional context**
This is required to start work with managed Kubernetes services (such as AKS).

**Comment by rpudlowski93** [comment]
I already tested kubectl locally from devcontainer and it works fine.
