### ISSUE TITLE
Prepare AzureBasicInfrastructure module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1622]
We need new module to enclose existing Epiphany infrastructure terraform code. As far as I understand that means: 
 * create new git repo for the module
 * implement required methods (as described [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/modular-cli/component-provider-template.md#required-methods)) For starters: Init, Plan, Apply, Audit.
 * develop test scenarios
 * implement tests

**Comment by sk4zuzu** [comment]
Existing set of makefiles from https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/modular-cli/cpt-tests can be used as a template.
Here is an example of a working modle https://github.com/seriva/component-cli
:+1:

**Comment by atsikham** [comment]
Verified that infrastructure created without any issues. But I would like to see how to destroy created resources in readme:

```bash
make destroy-plan
make destroy
```

**Comment by mkyc** [comment]
Sure, I added separate task for this, not to stop that issue in pipeline.
