### ISSUE TITLE
Prepare AzureAKS module

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1624]
After the https://github.com/epiphany-platform/epiphany/issues/1622 AzureBasicInfra module is ready we can start working on deploying AKS on top of it. It should have similar structure to the AzureBasicInfra module.

We need to do:
* create new git repo for the module
* implement required methods, for starters: Init, Plan, Apply, Audit.
* develop test scenarios
* implement tests

Existing set of makefiles from https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/modular-cli/cpt-tests can be used as a template.
Here is an example of a working module https://github.com/seriva/component-cli

**Comment by atsikham** [comment]
Can be tested together wit this task - https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/m-azure-kubernetes-service/3

**Comment by atsikham** [comment]
Verified in different regions, but for some regions there is an error related to resource unavailability in the region. Probably we need some mention in documentation about supported regions.

```text
Error: Error creating Resource Group "mop-module-tests-rg": resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" Message="The provided location 'switzerlandwest' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast'."
```
