### ISSUE TITLE
[FEATURE REQUEST] Use local kubectl in 'prometheus' role

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1639]
**Is your feature request related to a problem? Please describe.**
This is a second part of work started in #1638
To be able to manage a k8s cluster connection via kubectl in one place, it's suggested to use a separate ansible role and include this role in all necessary places with a fact that defines, should it be executed on k8s master as before or locally.
If there is some place, when connection from a container cannot be used (localhost delegation), it should be explained and left as is, but with the usage of created role.

**Describe the solution you'd like**
Try to review and include ansible role from #1638 in all places of kubectl usage, describe if everything works well or there is some pitfalls. The alternative can be considered.

**Describe alternatives you've considered**
Use a kubectl command without a new role, review all kubectl usages and change to use a connection from a container.

**Additional context**
```text
$ ./count_matches.sh
===============================
pattern: 'kubectl '
         role: applications      counter: 11
         role: backup    counter: 1
         role: kubernetes_common         counter: 3
         role: kubernetes_master         counter: 21
         role: kubernetes_promote        counter: 5
         role: preflight_facts   counter: 3
         role: prometheus        counter: 4
         role: repository        counter: 6
         role: upgrade   counter: 36
         role: vault     counter: 3
===============================
pattern: 'helm '
         role: helm      counter: 10
         role: repository        counter: 1
         role: vault     counter: 4
===============================
pattern: 'kubernetes_master'
         playbook: applications.yml      counter: 3
         playbook: backup_kubernetes.yml         counter: 1
         playbook: kubernetes_master.yml         counter: 6
         playbook: kubernetes_node.yml   counter: 2
         playbook: upgrade.yml   counter: 7
         role: applications      counter: 4
         role: filebeat          counter: 2
         role: firewall          counter: 4
         role: helm      counter: 1
         role: image_registry    counter: 1
         role: kubernetes_common         counter: 6
         role: kubernetes_master         counter: 7
         role: kubernetes_node   counter: 1
         role: preflight_facts   counter: 1
         role: prometheus        counter: 4
         role: repository        counter: 1
         role: upgrade   counter: 29
===============================
pattern: 'kubernetes_node'
         playbook: kubernetes_node.yml   counter: 4
         playbook: upgrade.yml   counter: 5
         role: filebeat          counter: 2
         role: firewall          counter: 4
         role: kubernetes_master         counter: 1
         role: prometheus        counter: 2
         role: upgrade   counter: 12
```

**Comment by mkyc** [comment]
After someone starts this task it should be assessed fast if we need to split it into smaller.

**Comment by atsikham** [comment]
Results:
PR - https://github.com/epiphany-platform/epiphany/pull/1655
Extracted 3 additional tasks: #1654, #1656, #1672
Found 2 bugs: #1659, #1664

**Comment by przemyslavic** [comment]
What has been tested here: 
- single master + monitoring
- multi master (HA) + monitoring
- monitoring (no k8s)

No issues found after refactoring.
