### ISSUE TITLE
[FEATURE REQUEST] Separate repository machine

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1640]
We need it because we no longer have guaranteed that there will be kubernetes master machine. 

**Is your feature request related to a problem? Please describe.**
- AKS/EKS offline deployment

**Describe the solution you'd like**
- Create repository machine
- Configure repository machine 
- Validate networking/connections/apps if we need anything more.
- Adjust epiphany scripts, so they can be used for our deployments.
- Test and validate various deployment scenarios

**Describe alternatives you've considered**
- We can go to cloud ECR/OCI but it will require internet connection, and complicate things

**Additional context**

**Comment by mkyc** [comment]
@toszo we need your confirmation here.

**Comment by toszo** [comment]
I'm fine with detaching repository role from K8s Master machine.

**Comment by sk4zuzu** [comment]
Please take a look at configuration example that can be used https://github.com/epiphany-platform/epiphany/issues/1349#issuecomment-649405873 :+1:

**Comment by mkyc** [comment]
Put it in SG of kubernetes master node.

**Comment by ar3ndt** [comment]
looks good, no additional configuration was required

**Comment by ar3ndt** [comment]
Helm needs to be included in local container with tunnelling

**Comment by ar3ndt** [comment]
Tunnell tested manually and it works. Switch to review.

**Comment by przemyslavic** [comment]
Tested:
- single machine
- multi master

on:
- `Ubuntu`/`RHEL` x `AWS`/`Azure`

**Requires additional testing with Vault enabled after bugfix for [#1729](https://github.com/epiphany-platform/epiphany/issues/1729/) which @ar3ndt  is working on (due to planned changes in the repository/helm roles).**

**Comment by rpudlowski93** [comment]
Bugfix #1729 fixed.  

I installed the vault on kubernetes master when the flag k8s_as_cloud_service was false without any errors.
Vault works fine with the seperated repository and I tested the vault using the following scenario: [link](https://github.com/epiphany-platform/epiphany/issues/1338#issuecomment-651687655)

All necessary binaries/files were downloaded properly from separated repository to the master machine. 

Moreover I also tested the repository from local container in order to install filebeat (#1670) and node exporter (#1673) as daemonset and it works fine.

**Comment by ar3ndt** [comment]
Default disk size for repository machine is increased. 64gb by default for both aws and azure.

**Comment by przemyslavic** [comment]
Blocked by: [[BUG] Only 32 GB mounted on the root directory when the disk size of the repository machine is 64 GB](https://github.com/epiphany-platform/epiphany/issues/1776).

**Comment by przemyslavic** [comment]
- `Azure/RedHat`: available 32 GB - investigated in #1776
- `Azure/Ubuntu`: available 62 GB
- `AWS/RedHat`: available 64 GB
- `AWS/Ubuntu`: available 62 GB
