### ISSUE TITLE
[FEATURE REQUEST] Create pipelines for releasing Epiphany modules

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1641]
**Is your feature request related to a problem? Please describe.**
We need pipelines to run unit tests, build Docker image and push it to Azure Container Registry (development) and Docker Hub (releases).

**Describe the solution you'd like**
Similar solution like we have for epiphany repo.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No context.

**Comment by mkyc** [comment]
We should test it also on new testing nodes pool.

**Comment by plirglo** [comment]
Build module pipelines are ready and located under url: https://abb-epiphany.visualstudio.com/epiphany/_build?definitionScope=%5CModules

Modules release pipelines are located under url: https://abb-epiphany.visualstudio.com/epiphany/_release?_a=releases&view=all&path=%5CModules

We faced issue with running tests on existing agents infrastructure. We need to reconfigure a bit agents configuration and tests scripts to create properly working tests pipelines. This part of task is in progress.

**Comment by mkyc** [comment]
[AzBI 0.0.1 release](https://github.com/epiphany-platform/m-azure-basic-infrastructure/releases/tag/v0.0.1)

Pull:
```shell
docker pull epiphanyplatform/azbi:latest
latest: Pulling from epiphanyplatform/azbi
df20fa9351a1: Already exists 
bd6d618ddfba: Already exists 
27ee0da89174: Already exists 
d6e31748cf29: Pull complete 
d4573f8fa902: Pull complete 
0bc2d73d3a77: Pull complete 
0b1735669f28: Pull complete 
04e8ba7098d5: Pull complete 
Digest: sha256:55c3c7c57305568ab6e72174100b706447dbeedb9f900ee981273ea25ed953b4
Status: Downloaded newer image for epiphanyplatform/azbi:latest
docker.io/epiphanyplatform/azbi:latest
```

Run:
```shell
docker run --rm -t epiphanyplatform/azbi metadata
#AzBI | metadata | should print component metadata
labels:
  version: 0.0.1.3678
  name: Azure Basic Infrastructure
  short: azbi
  kind: infrastructure
  provider: azure
  provides-vms: true
  provides-pubips: true
```

**Comment by mkyc** [comment]
[AzKS 0.0.1 release](https://github.com/epiphany-platform/m-azure-kubernetes-service/releases/tag/v0.0.1)

Pull: 
```shell
docker pull epiphanyplatform/azks       
Using default tag: latest
latest: Pulling from epiphanyplatform/azks
df20fa9351a1: Already exists 
bd6d618ddfba: Already exists 
27ee0da89174: Already exists 
d6e31748cf29: Already exists 
d4573f8fa902: Already exists 
1d7ef54b2bcc: Pull complete 
6e1222323b92: Pull complete 
Digest: sha256:7ff6060aeff15f13fe786dbbcb28892e22e95b2a4f0655439d54be115bce92eb
Status: Downloaded newer image for epiphanyplatform/azks:latest
docker.io/epiphanyplatform/azks:latest
```

Run:
```shell
docker run --rm -t epiphanyplatform/azks metadata
#AzKS | metadata | should print component metadata
labels:
  version: 0.0.1.3677
  name: Azure Kubernetes Service
  short: azks
  kind: infrastructure
  provider: azure
```

**Comment by mkyc** [comment]
[AwsBI 0.0.1 release](https://github.com/epiphany-platform/m-aws-basic-infrastructure/releases/tag/v0.0.1)

Pull:
```shell
docker pull epiphanyplatform/awsbi               
Using default tag: latest
latest: Pulling from epiphanyplatform/awsbi
df20fa9351a1: Already exists 
bd6d618ddfba: Already exists 
27ee0da89174: Already exists 
8535ec1ac524: Pull complete 
79f22d7820a9: Pull complete 
f8cd43532c4e: Pull complete 
Digest: sha256:f6b31291282712e993437d26dcf6907a370e6f4fa39a48ec1dc7ab04b3cfffe7
Status: Downloaded newer image for epiphanyplatform/awsbi:latest
docker.io/epiphanyplatform/awsbi:latest
```

Run:
```shell
docker run --rm -t epiphanyplatform/awsbi metadata
#AWSBI | metadata | Display component metadata
labels:
  version: 0.0.1.3680
  name: AWS Basic Infrastructure
  short: awsbi
  kind: infrastructure
  provider: aws
  provides-vms: true
  provides-pubips: true
```

**Comment by mkyc** [comment]
[AwsKS 0.0.1 release](https://github.com/epiphany-platform/m-aws-kubernetes-service/releases/tag/v0.0.1)

Pull:
```shell
docker pull epiphanyplatform/awsks                                               
Using default tag: latest
latest: Pulling from epiphanyplatform/awsks
df20fa9351a1: Already exists 
bd6d618ddfba: Already exists 
27ee0da89174: Already exists 
d6e31748cf29: Already exists 
ca9941ee96f0: Pull complete 
73a2ff7b006d: Pull complete 
997c19111f8a: Pull complete 
84bad2595196: Pull complete 
Digest: sha256:64f602c75297f9f905008ba012d2953197b2a2c7f64f1afcc04e4bb130cf4cfc
Status: Downloaded newer image for epiphanyplatform/awsks:latest
docker.io/epiphanyplatform/awsks:latest
```

Run:
```shell
docker run --rm -t epiphanyplatform/awsks metadata
#AWSKS | metadata | should print component metadata
labels:
  version: 0.0.1.3679
  name: AWS Kubernetes Service
  short: awsks
  kind: infrastructure
  provider: aws
```

**Comment by mkyc** [comment]
I tested it on my own while releasing modules.

**Comment by mkyc** [comment]
Releases modules directory: 

![Modules releases directory](https://user-images.githubusercontent.com/28505782/95853870-5b987a00-0d56-11eb-8b91-8498bad86ce9.png)

Example part of DockerHub release task: 

![DockerHub release tast](https://user-images.githubusercontent.com/28505782/95854004-97334400-0d56-11eb-9252-380f5dc0b69e.png)

Example part of GitHub release task: 

![GitHub release task](https://user-images.githubusercontent.com/28505782/95854054-aca86e00-0d56-11eb-9132-b906cc003cbc.png)

Example release runs: 

![Release runs](https://user-images.githubusercontent.com/28505782/95854139-d366a480-0d56-11eb-85dc-16c7461e5a74.png)

Inside example release run:

![One release run](https://user-images.githubusercontent.com/28505782/95854205-e8433800-0d56-11eb-9fec-8a8a50a36f61.png)

Example release logs: 

![Release logs](https://user-images.githubusercontent.com/28505782/95854263-fabd7180-0d56-11eb-9f10-52e03f4edad2.png)
