### ISSUE TITLE
[FEATURE REQUEST] Pipeline to test Epiphany using AWS infrastructure modules

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1645]
**Is your feature request related to a problem? Please describe.**
This is to create a release pipeline on Azure DevOps to enable automatic cluster deployment on AWS using modularized Epiphany and testing it.

**Describe the solution you'd like**
1. Create a pipeline on AzureDevOps to deploy a cluster
2. Run unit tests / serverspec tests.

**Comment by seriva** [comment]
Closing as the work on modules is halted.
