### ISSUE TITLE
[Low Priority] Multiple regions replication for PostgreSQL

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#166]
Need to implement something like [this](https://docs.microsoft.com/pl-pl/azure/azure-sql/database/active-geo-replication-overview) for all providers to avoid issues with latency in different world parts. Priority is low.

.

**Comment by sk4zuzu** [comment]
@erzetpe was this about high-availability so each of the components of a PostgreSQL cluster get different availability zone in the cloud case (in AWS or Azure)? 🤔

**Comment by erzetpe** [comment]
No, we wanted to have something simiar to this what Microsoft on Azure SQL offers - active geo replication.

More information about this feature is accessible under link:
https://docs.microsoft.com/pl-pl/azure/azure-sql/database/active-geo-replication-overview

**Comment by erzetpe** [comment]
This should be implemented in all providers, but I guess that this story is not important right now or in the nearest future.

**Comment by seriva** [comment]
Closing this as there seems not business case for this ATM.
