### ISSUE TITLE
[FEATURE REQUEST] Update kubernetes-cni package to v0.8.7

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1668]
**Is your feature request related to a problem? Please describe.**
We use older version (0.8.6) of `kubernetes-cni` package than the default for K8s v1.18.6.
Till Epiphany v0.8.0 we installed the latest but introduced setting to managed it (see PR #1666).
This task is also meant to prevent downgrading the package - if cluster was created by Epiphany in version < 0.8 then upgraded using Epiphany v0.8.

**Describe the solution you'd like**
Update kubernetes-cni package to v0.8.7.

**Additional context**
[CNI Plugins v0.8.7 release notes](https://github.com/containernetworking/plugins/releases/tag/v0.8.7)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
Changelog was not updated as this version depends on the version of Kubernetes and they will be changed together in future upgrades.

**Comment by przemyslavic** [comment]
:heavy_check_mark: `kubernetes-cni` package updated to v0.8.7 (tested `epicli apply` and `epicli upgrade` commands)
