### ISSUE TITLE
[FEATURE REQUEST] Filebeat DaemonSet

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1670]
**Is your feature request related to a problem? Please describe.**
We need to be able to start Filebeat as DaemonSet to gather logs from machines on managed Kubernetes services. 

**Describe the solution you'd like**
We would like to install it using helm locally from our container. 
This task should be implementation of findings in task #1608 tested with AKS and (if possible) EKS. 

**Describe alternatives you've considered**
We could also install the DaemonSets using manifests files.

**Additional context**
No context.

**Comment by rpudlowski93** [comment]
Filebeat as DaemonSet added to Epiphany code but still it needs to be tested using helm locally. Blocked by #1640.

**Comment by rpudlowski93** [comment]
- FIlebeat as DaemonSet for "k8s as cloud service" using Helm and archived chart file - Done in PR #1730
