### ISSUE TITLE
[Spike] Check and modify Vault deployment for local kubectl usage

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1672]
**Is your feature request related to a problem? Please describe.**
We want to check and modify if needed existing vault role to use local kubectl to Kubernetes clusters not using AKS/EKS.

**Describe the solution you'd like**
Working deployment of Vault on Kubernetes clusters not using AKS/EKS if needed adapted to use local kubectl and helm deployed to Epiphany container.

**Describe alternatives you've considered**
No.

**Additional context**
This task is a part of work that is started in #1639.

**Comment by erzetpe** [comment]
We need to discuss this as this is more than planned MVP scope. In our MVP scope we only have planned to deploy vault on one master server with local connection to Kubernetes API server.

**Comment by erzetpe** [comment]
After analysis of the code and brief testing it seems that no changes are required at the moment.

**Comment by przemyslavic** [comment]
The installation fails after introducing local `helm`.
The role should be refactored according to the latest changes to use **local `helm`** and **local `kubectl`**.
Issue reported: [[BUG] Vault fails to install after changing helm to use localhost #1729](https://github.com/epiphany-platform/epiphany/issues/1729)

**Comment by mkyc** [comment]
PR related to #1729 is already merged

**Comment by mkyc** [comment]
Task #1754 is also fix for this general one. @erzetpe and @atsikham should we close this one as to general?

**Comment by atsikham** [comment]
> Task #1754 is also fix for this general one. @erzetpe and @atsikham should we close this one as to general?

I think we can close this one, but we need to have some task about vault deployment in AKS/EKS.

**Comment by erzetpe** [comment]
Closing because of deprecation of Hashicorp Vault component.
