### ISSUE TITLE
[FEATURE REQUEST] Prometheus and Node Exporters as DaemonSet

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1673]
**Is your feature request related to a problem? Please describe.**
We need to be able to connect Prometheus to managed Kubernetes services (AKS and EKS) with Autoscaling to gather metrics.. 

**Describe the solution you'd like**
We would like to install node exporter as DaemonSets using helm locally from our container (now, node exporter run as system service). We should use here our seperated repository #1640.
This task should be implementation of findings in task #1607, tested with AKS and (if possible) EKS. 

**Describe alternatives you've considered**
We could also install the DaemonSets using manifests files.

**Additional context**
No context.

**Comment by mum0l** [comment]
This ticket is related to EKS/AWS integration, so this must be completed before testing.

To test it, use the following variable in YAML config file, to enable node-exported installation as Daemonset.
`  cloud:
    k8s_as_cloud_service: False`
