### ISSUE TITLE
[FEATURE REQUEST] Tests for Azure AKS module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1675]
**Is your feature request related to a problem? Please describe.**

We need to have first tests implemented in AzAKS module implemented in #1624

**Describe the solution you'd like**

AFAICT we should implement integration tests for now. 

**Describe alternatives you've considered**

No. 

**Additional context**

If possible, tests results should be readable for Azure DevOps.

**Comment by sk4zuzu** [comment]
I believe implementation should be similar to https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/11 from the basic infastructure module. :+1:

**Comment by atsikham** [comment]
@plirglo and I used created tests in pipelines. Confirm that it works.

**Comment by mkyc** [comment]
So does it mean that you tested it and you can move it to next phases?

**Comment by atsikham** [comment]
@mkyc the question is if @przemyslavic or @to-bar want to test it themselves. IMO it can be moved to DoD.

**Comment by rpudlowski93** [comment]
Tested - works fine.
Small necessary fixes were needed. Fixes done in PR #27
