### ISSUE TITLE
[FEATURE REQUEST] Tests for AWS Basic Infrastructure module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1676]
**Is your feature request related to a problem? Please describe.**

We need to have first tests implemented in AwsBI module implemented in #1637

**Describe the solution you'd like**

AFAICT we should implement integration tests for now. 

**Describe alternatives you've considered**

No. 

**Additional context**

If possible, tests results should be readable for Azure DevOps.

**Comment by atsikham** [comment]
@mkyc could you add some examples of tests in other modules, if they exist?

**Comment by mkyc** [comment]
Yeah, [here is PR with tests](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/11) in Azure Basic Infrastructure module.

**Comment by erzetpe** [comment]
PR [#26](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/26)

**Comment by przemyslavic** [comment]
Added tests for: `init`, `plan`, `apply`, `destroy plan`, `destroy`.
Tests can be run with `make test` or `go test` command.
