### ISSUE TITLE
[FEATURE REQUEST] Tests for AWS EKS Module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1677]
**Is your feature request related to a problem? Please describe.**

We need to have first tests implemented in AWSEKS module implemented in #1636

**Describe the solution you'd like**

AFAICT we should implement integration tests for now. 

**Describe alternatives you've considered**

No. 

**Additional context**

If possible, tests results should be readable for Azure DevOps.

**Comment by mkyc** [comment]
Some first implementation done by @sk4zuzu in https://github.com/sk4zuzu/m-aws-kubernetes-service/tree/feature/integration-tests

**Comment by toszo** [comment]
@seriva please define why this task is "Blocked"

**Comment by atsikham** [comment]
Testing of this task is on hold until Pipeline issues are resolved in the scope of #1643 task.

Problems that have been already found:
1. Usage of default region for AWSBI execution, so infrastructure resources are not removed. Need to explicitly pass "M_REGION" parameters for both modules in integration tests.
2. Need to pass module name during test execution to have unique resource names. At the moment all resources created by tests have similar names.

**Comment by atsikham** [comment]
Tests are in place and work fine itself, but there are 2 tasks created:
* [41](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/41) - improvement
* [42](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/42) - fix resources removal
