### ISSUE TITLE
[FEATURE REQUEST] Run HAProxy using dedicated user instead of root

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1691]
**Is your feature request related to a problem? Please describe.**
Before changes from #1586 we had HAProxy installed as OS package (deb/rpm). The package automatically created OS user and group `haproxy`.

We had automated tests to check the following:

- User "haproxy" is expected to exist
- User "haproxy" is expected to have login shell "/usr/sbin/nologin" or have login shell "/sbin/nologin"
- Group "haproxy" is expected to exist
- User "haproxy" is expected to belong to group "haproxy"
- User "haproxy" is expected to have home directory "/var/lib/haproxy"

Now there is no `haproxy` user.

```
# grep haproxy /etc/shadow
haproxy_exporter:!:18528::::::
```

```
# grep -A3 user /opt/runc/haproxy/config.json
"user": {
    "gid": 0,
    "uid": 0
}
```

**Describe the solution you'd like**
Add `haproxy` user and run the `haproxy` service as this user.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
As a part of this task we should restore automated tests removed in #1692.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
