### ISSUE TITLE
[FEATURE REQUEST] Document installation of Epiphany using AzBI and AzAKS modules

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1696]
**Is your feature request related to a problem? Please describe.**

We need to document how to install Epiphany using modules. It could be nice to have some document design with architecture diagram in order to explain how everything works, and show all necessary logical connections. The documentation should consider: **AzBI** module, **AzAKS** module, **Epiphany** module.

**Describe the solution you'd like**

Documentation tested with entire instruction of installation of epiphany using AzBI and AzAKS and all necessary diagrams (Lucidchart)

**Describe alternatives you've considered**

Record some demo and link it

**Additional context**

None.

**Comment by rafzei** [comment]
The initial version is well described. 
I've created a new issue to improve it a bit: [#1805](https://github.com/epiphany-platform/epiphany/issues/1805).
