### ISSUE TITLE
[RHEL/CentOS] epicli fails on downloading requirements - Docker CE repo not available

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1705]
**Describe the bug**
Docker CE CentOS repository is not available at official URL at least since Sep 24.

Issue reported on Docker community forum at: https://forums.docker.com/t/docker-ce-stable-x86-64-repo-not-available-https-error-404-not-found-https-download-docker-com-linux-centos-7server-x86-64-stable-repodata-repomd-xml/98965

The error message: 
`https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

**To Reproduce**
1. Run `epicli apply`

**OS (please complete the following information):**
 - OS: RHEL7 or CentOS7

**Cloud Environment (please complete the following information):**
 - All

**Additional context**
Official link doesn't work:
https://download.docker.com/linux/centos/7Server/x86_64/stable

Direct link works:
https://download.docker.com/linux/centos/7/x86_64/stable

**Comment by przemyslavic** [comment]
The fix works fine. Tested on RedHat.
