### ISSUE TITLE
[SPIKE] Installation of single instance of Druid on Kubernetes using helm

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1708]
**Is your feature request related to a problem? Please describe.**
We want to install automatically non-clustered single Druid instance on Kubernetes.

**Describe the solution you'd like**
Prior to automatic installation we want to create plan, configuration and documentation of Druid deployment on Kubernetes using helm. 

**Describe alternatives you've considered**
Installation of  non-clustered single Druid instance on Kubernetes without helm.

**Additional context**
No.

**Comment by seriva** [comment]
Will not be part of Epiphany in this form anymore.
