### ISSUE TITLE
[SPIKE] Check if epicli parsing quotes correctly in configuration manifest

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1709]
**Describe the spike**
We had an [issue](#1669) where the parsed initial configuration manifest (apply/init) treats single quotes in a different way.

This spike is to check and verify if we are using [pyyaml](https://pypi.org/project/PyYAML/) (parser lib) in the correct way. 
Maybe it's just the specification of this lib and we should keep one standard to use quotes.

[here](https://github.com/epiphany-platform/epiphany/blob/983f68e798fba180e230b6dc9badad903366aa31/core/src/epicli/data/common/defaults/configuration/postgresql.yml#L12) we used double quotes `"'*'"` as a workaround, and [here](https://github.com/epiphany-platform/epiphany/blob/983f68e798fba180e230b6dc9badad903366aa31/core/src/epicli/data/common/defaults/configuration/filebeat.yml#L8) block scalars `>-`

Please create a new issue with findings or close this spike with comments.

**Comment by seriva** [comment]
Resolved
