### ISSUE TITLE
[FEATURE REQUEST][0.5.x] Back-merge "long lasting certs for Kubernetes" (#1302)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1716]
**Is your feature request related to a problem? Please describe.**
Clients use version 0.5.x with product version certified on this version, and would like to update and extend certs validity. 

**Describe the solution you'd like**
Back merge and verify feature that was done in #1302 to 0.5.x branch. 

**Describe alternatives you've considered**
Documentation can be a poor alternative. 

**Additional context**
Product Team request.

**Comment by atsikham** [comment]
These changes have been already backported, PR #1796 - https://github.com/epiphany-platform/epiphany/blob/v0.5/CHANGELOG-0.5.md
