### ISSUE TITLE
[FEATURE REQUEST] Use built-in Prometheus exporter in HAProxy 2.2

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1739]
**Is your feature request related to a problem? Please describe.**
We recently upgraded HAProxy in Epiphany. We still use old solution for exporting HAProxy metrics to Prometheus though... :'C

**Describe the solution you'd like**
BLOG POST: https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/

Our new HAProxy solution seems to have Prometheus plugin compiled-in https://github.com/docker-library/haproxy/blob/34f7b69c09fa0f16a0834641aa6556523c67b1ed/2.2/alpine/Dockerfile#L40 :+1::innocent: 

How about migrating to compiled-in exporter? :thinking: 

**Describe alternatives you've considered**
We could do nothing! :trollface: 

**Additional context**
N/A

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
It's well described in the blog post. 

Ps. Now its time to stop do nothing :trollface:

**Comment by przemyslavic** [comment]
Tested scenarios:
:heavy_check_mark: `epicli apply` -> `epicli apply` (x86_64 and aarch64)
:heavy_check_mark: `epicli apply` v1.0.1 -> `epicli upgrade` -> `epicli upgrade` (x86_64)
:heavy_check_mark: `epicli apply` v1.2.0 -> `epicli upgrade` -> `epicli upgrade` (aarch64)
:heavy_check_mark: Verified HAProxy metrics in Prometheus and Grafana.
