### ISSUE TITLE
[BUG] epicli upgrade failed on filebeat upgrade

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1747]
**Describe the bug**
Error during an upgrade. Filebeat task file not found.

**To Reproduce**
1. epicli apply (v0.6)
2. epicli upgrade (develop branch)

**Expected behavior**
Successfully upgraded environment.

**OS (please complete the following information):**
 - all

**Cloud Environment (please complete the following information):**
 - all

**Additional context**
```shell
09:46:37 ERROR cli.engine.ansible.AnsibleCommand - ERROR! Could not find specified file in role: tasks/install-filebeat
09:46:37 INFO cli.engine.ansible.AnsibleRunner - Run done in 2163561ms
09:46:37 INFO cli.engine.UpgradeEngine - Run done in 2163562ms
```

**Comment by rpudlowski93** [comment]
Fixed in PR #1752
Upgrade tested and works fine
