### ISSUE TITLE
[FEATURE REQUEST] Separate role vars and manifest vars generation during upgrades

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1756]
**Is your feature request related to a problem? Please describe.**
In this PR https://github.com/epiphany-platform/epiphany/pull/1619 a helper mechanism was introduced to make it possible during upgrades to re-use role config docs taken from manifest.

Currenly it's not enabled for all roles. Also currently enabling manifest vars implies generation of default vars as well. This may cause some issues for certain roles during upgrades.

This FR is about removing this implication and separate those two functionalities to gain fine control over them. Also this separation will surely cause that the whole feature will become more attractive to developers as it may have some potential to simplify the upgrade process. :+1::innocent:

**Describe the solution you'd like**
Split this list https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/cli/engine/ansible/AnsibleVarsGenerator.py#L63 into two. :+1: 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by toszo** [comment]
Currently, upgrade overwrites role vars (as far as I remember) and this FR will fix it? Do I understand that correctly?

**Comment by sk4zuzu** [comment]
Yes, upgrade still overwrites role vars with defaults for specific roles, but we've also added an optional file `vars/manifest.yml` that is placed next to `vars/main.yml` (not instead of it). This extra file contains settings from the real manifest and is not loaded by default. Later (during upgrade) we can call a role with manifest vars instead of default vars (or just load them to a dictionary) if needed, like this:
```yaml
- name: load_balancer | Upgrade haproxy service (runc)
  include_role:
    name: haproxy
    vars_from: manifest
```
Haproxy component is a good example where this is handy as all the important config is provided by the user.

This FR is to improve this mechnism as currently if we want "manifest vars" we generate "default vars' as well. We'd like to separate those two things. :thinking:

**Comment by sk4zuzu** [comment]
I'm sorry I got maybe a little ahead of myself, but the implementation was extremely short and straightforward #1942. I believe this could help with the grooming... :hand_over_mouth:

**Comment by przemyslavic** [comment]
Looks good. Roles tested:
✅repository, image_registry, node_exporter, haproxy
