### ISSUE TITLE
Pipeline to test AzBI module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1760]
**Is your feature request related to a problem? Please describe.**
Create pipeline to run tests on PR merge

**Describe the solution you'd like**
Pipeline should invoke tests already prepared in #1674

**Comment by mkyc** [comment]
This was separated from #1642

**Comment by mkyc** [comment]
@plirglo I believe this one is what you already did in #1641

**Comment by atsikham** [comment]
@plirglo shoudn't this task be closed or moved to DoD?
https://abb-epiphany.visualstudio.com/epiphany/_build/results?buildId=3637&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=29b11093-f299-52c9-fc3e-b4e81abf4ac1

**Comment by mkyc** [comment]
Yeah, it should together with #1641 @plirglo please do things with this task.

**Comment by plirglo** [comment]
I'm moving it to "ready to test" phase since it's already in use but maybe someone ( @przemyslavic ) should look at this before close:

https://abb-epiphany.visualstudio.com/epiphany/_build?definitionId=87

**Comment by mkyc** [comment]
Ok, I added correct PR to this task. @plirglo please assign yourself because in fact it was you who did it.

**Comment by mkyc** [comment]
I can confirm that it works on merge web hook. I was checking it while doing PR's for release. 

![automatic tests](https://user-images.githubusercontent.com/28505782/95864621-ed5bb380-0d65-11eb-9397-4ae8a1ac51e4.png)

**Comment by atsikham** [comment]
@plirglo @mkyc latest pipeline fails. What is this error about?
https://abb-epiphany.visualstudio.com/epiphany/_build/results?buildId=3705&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=29b11093-f299-52c9-fc3e-b4e81abf4ac1

**Comment by mkyc** [comment]
It says nothing. I'm not sure why it says "succeeded with issues" and does not fail. There is visible problem with bash tests ... I think we need to rewrite them ASAP.

**Comment by plirglo** [comment]
I re-run test pipeline and here is result:
https://abb-epiphany.visualstudio.com/epiphany/_build/results?buildId=3711&view=results

Regarding "succeeded with issues" i've unchecked "Continue on error" in "Run tests" task to fail whole pipeline when script's output will not be 0
