### ISSUE TITLE
Pipeline to test AwsBI module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1761]
**Is your feature request related to a problem? Please describe.**
Create pipeline to run tests on PR merge
**Describe the solution you'd like**
Pipeline should invoke tests prepared in #1676
**Describe alternatives you've considered**
No.
**Additional context**
Check #1641 for information how t was done for AZBI module.

**Comment by mkyc** [comment]
This task was separated from #1643

**Comment by ar3ndt** [comment]
PR [#32](https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/32)

**Comment by ar3ndt** [comment]
related [PR](https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/41)

**Comment by przemyslavic** [comment]
The pipeline has been tested and works properly. The test results are visible in the dashboard in Azure DevOps.
