### ISSUE TITLE
[FEATURE REQUEST] Add authentication support to docker repository 

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1765]
**Is your feature request related to a problem? Please describe.**
We need to have authentication option for  communication with docker repository.

**Describe the solution you'd like**
Add authentication support as an option to our docker repository and add capability for its usage for services that are using this.

**Describe alternatives you've considered**
None.

**Additional context**
No.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by sk4zuzu** [comment]
IMHO, things to consider:
1. client certificates
2. password authentication
:)

**Comment by rafzei** [comment]
> IMHO, things to consider:
> 
>     1. client certificates
> 
>     2. password authentication
>        :)

That's the right order, first, we should consider to use certs.
I've found also [to-do comment](https://github.com/epiphany-platform/epiphany/blob/bea20d7385c6362a49a2d80f295e4f429ea256ff/core/src/epicli/data/common/ansible/playbooks/roles/image_registry/tasks/main.yml#L50) in our code

**Comment by sk4zuzu** [comment]
To even consider client cert auth we need to have TLS support fist. :thinking:

**Comment by toszo** [comment]
Correct - and this issue is blocked by #1764
