### ISSUE TITLE
[FEATURE REQUEST] Upgrade Filebeat to the latest version (7.9.2)

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1770]
**Is your feature request related to a problem? Please describe.**
For AKS/EKS we have Filebeat (as daemonset) in version 7.9.2. It could be nice to have the same version for both scenarios.

> We can upgrade Filebeat to 7.9.2 (having Elasticsearch 7.9.1) since according to [7.9.2 release notes]( https://www.elastic.co/guide/en/beats/libbeat/7.9/release-notes-7.9.2.html) it contains one nice to have [bugfix](https://github.com/elastic/beats/pull/21048) and other changes seem to be acceptable for Epiphany.

_Originally posted by @to-bar in https://github.com/epiphany-platform/epiphany/issues/846#issuecomment-707765171_

**Additional context**
According to [this table](https://www.elastic.co/support/matrix#matrix_compatibility), Filebeat 7.8.1 (we already have) should be compatible with Elasticsearch 7.9.1 so this task has no high priority.

**Comment by przemyslavic** [comment]
Tested configurations:
:white_check_mark: `epicli apply`: `AWS/Azure` x `RedHat/Ubuntu`
:white_check_mark: `epicli upgrade` from 0.7 to develop: `AWS/Azure` x `RedHat/Ubuntu`
:white_check_mark: filebeat as DaemonSet
No problems encountered :heavy_check_mark:
