### ISSUE TITLE
[FEATURE REQUEST] Verify OS requirements in Epiphany documentation

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1773]
**Is your feature request related to a problem? Please describe.**
Basically we don't support all systems mentioned in documentation. For RedHat Azure we support only 7-RAW version of OS, and:

```
 {
    "offer": "RHEL",
    "publisher": "RedHat",
    "sku": "7-RAW-CI",
    "urn": "RedHat:RHEL:7-RAW-CI:7.7.2019081601",
    "version": "7.7.2019081601"
  }
``` 
is the latest one.

**Describe the solution you'd like**
Modify documentation part for all releases to ad disclaimer for Azure images

**Describe alternatives you've considered**
In next releases consider support newer images

**Additional context**

**Comment by atsikham** [comment]
@plirglo what is necessary to test in the scope of this task?

**Comment by plirglo** [comment]
The output of this task are documentation pages created in linked PRs
