### ISSUE TITLE
[BUG] [epicli upgrade] Filebeat stops working when legacy Elasticsearch (v6) is used for storing logs

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1774]
**Describe the bug**
Before Epiphany v0.5 there was no `logging` role but `elasticsearch` role was used for storing logs.
After running `epicli upgrade` on Epiphany cluster v0.4.5 Filebeat was upgraded to 7.8.1 and service stopped working because `groups.logging` was undefined. There was the following error in syslog:
```
Exiting: error initializing publisher: empty array accessing 'output.elasticsearch.hosts' (source:'/etc/filebeat/filebeat.yml')
```

**To Reproduce**
Run `epicli upgrade` for cluster created by Epiphany v0.4 

**Expected behavior**
Filebeat should not be upgraded to version 7.x if there is no Elasticsearch v7.x for storing logs.

**Config files**
n/a

**OS**
any

**Cloud Environment**
any

**Additional context**
n/a

**Comment by przemyslavic** [comment]
Checked:

- upgrade from 0.4.5: filebeat update was skipped :heavy_check_mark:

- upgrade from 0.5.5: filebeat updated to 7.8.1 :heavy_check_mark:
