### ISSUE TITLE
[BUG] Upgrade cluster pipelines failed when flag "wait-for-pods" is used. Insufficient CPU resources on worker nodes.

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#1778]
**Describe the bug**
Upgrade cluster failed when flag "wait-for-pods" is used. Problem exists only on Azure with Canal network plugin.
When one of worker nodes is drained, pods located there go into pending state due to insufficient CPU resources on worker nodes. Pods can't recreate on another worker nodes due to the limits. 

- Azure worker nodes are too small (1vcpu) and Canal pods need at least 25% 1vcpu. Flannel pods need only 10% 1vcpu.
- We should consider to create new upgrade pipelines with the flag "--wait-for-pods" enabled by default and  changed there size of worker nodes from Standard DS2 v1 to Standard DS2 v2 or increate number of worker nodes from 3 to at least 4. 

**Steps to reproduce the behavior:**
1. Run upgrade cluster pipelines :  upgrade from 0.6 or higher to develop with "wait-for-pods" flag

**Expected behavior**
The cluster has been upgraded successfully and pipelines finish successfully.

**Actual behavior**
The upgrade process fails after 600 retries, and pods in the cluster are in pending state:

```
NAME                         READY   STATUS    RESTARTS   AGE
pgbouncer-65d7f467d8-phkqd   1/1     Running   0          6h5m
pgbouncer-65d7f467d8-rzbq7   0/1     Pending   0          72m
pgpool-f744b6fdc-d4bpx       0/1     Pending   0          72m
pgpool-f744b6fdc-gkqrs       1/1     Running   0          6h5m
pgpool-f744b6fdc-kvklg       1/1     Running   1          6h58m
```

**OS:**
 - OS: [RHEL7/Ubuntu]

**Cloud Environment:**
 - Cloud Provider [MS Azure]

**Additional context**

**Comment by przemyslavic** [comment]
If it is enough to increase the number of worker nodes, I wouldn't consider it a bug.  Nobody said that we can only have 3 nodes ;) and probably other resource-consuming applications are also being deployed here.  I would just modify the pipeline increasing the number of worker nodes.

**Comment by rpudlowski93** [comment]
It consider only the scenario where we add the flag "—wait-for-pods” which is not added by default in our pipelines. So maybe we should change this task into feature task where we should create new pipelines with the flag? We shouldn’t add the flag to every upgrade pipelines since it will extend time of every upgrade pipeline. Indeed I can agree that resource-consuming application can just need more resources :)

**Comment by seriva** [comment]
Closing as for me this just sounds a resource issue.
