### ISSUE TITLE
[FEATURE REQUEST] Improve Elasticsearch cluster status checking during an upgrade

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1781]
**Is your feature request related to a problem? Please describe.**
Currently, during an upgrade we checking if cluster status is yellow **or** green.

**Describe the solution you'd like**
During an upgrade procedure, verify if we have **single** instance of Elasticsearch or **instance>1** and check cluster state in proper way.

Proper status:
One node = yellow
More than one node = green

**Additional context**
Useful calls:
```
GET _cat/nodes
GET _cat/allocation
GET _cluster/health
GET _cat/shards
```

**Comment by rafzei** [comment]
Things to improve as well:
- tests
- documentation

**Comment by seriva** [comment]
Closing, as this is related to OpenDistro which will be replaced by OpenSearch. New issue can be opened if relevant for that.
