### ISSUE TITLE
[SPIKE] Ensuring zero-downtime cluster upgrade

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#1786]
**Describe the spike**

We have to consider some things related to zero-downtime upgrade in epiphany: 

- Should we stay with the flag "wait-for-pods" for cluster's upgrade with zero-downtime?

- Should we improve our documentation with some description and requirements which should be provided in order to have real zero-downtime. (eg. at least two pods application etc..)? Right now we ensure in our documentation zero-downtime cluster upgrade but it won't work in case of single pod application

- Is there any better solution for the zero-downtime upgrade in compare to the our "wait-for-pods" flag?

- If we decide to stay with the flag "wait-for-pods" with some improvements, should we add by default the flag to our pipelines or should we create new pipelines with the flag?  

- Should we consider to rename the flag to for example flag "no-downtime" in order to make it more readable?

**Comment by sk4zuzu** [comment]
IMO. We have to definitely fix documentation (current one is confusing), also it would be good to add comprehensive guide howto design applications in Kuberentes to make them "zero-downtime". I think this flag will stay in the codebase in the end and if it does I think we need to mitigate "Note: that this can also cause the upgrade to hang indefinitely.", so it's a bit smarter and we dont have to warn users about it. :hand_over_mouth: :hugs:

**Comment by seriva** [comment]
Closing as we don't have a business case for this.
