### ISSUE TITLE
[FEATURE REQUEST] [Ubuntu] Add retry feature for downloading packages in download-requirements.sh

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1789]
**Is your feature request related to a problem? Please describe.**
download-requirements.sh occasionally fails (failing deployment) from many different reasons (such as network issue, repo not available, repo sync in progress).

Example of error to handle:

```
Err:13 https://dl.bintray.com/rabbitmq/debian bionic InRelease", "  502  Bad Gateway [IP: 52.28.44.12 443]

W: Skipping acquire of configured file 'erlang-21.x/i18n/Translation-en' as repository 'http://dl.bintray.com/rabbitmq-erlang/debian bionic InRelease' doesn't have the component 'erlang-21.x' (component misspelt in sources.list?)", "W: Skipping acquire of configured file 'erlang-21.x/cnf/Commands-amd64' as repository 'http://dl.bintray.com/rabbitmq-erlang/debian bionic InRelease' doesn't have the component 'erlang-21.x' (component misspelt in sources.list?)", "W: Failed to fetch https://dl.bintray.com/rabbitmq/debian/dists/bionic/InRelease  502  Bad Gateway [IP: 52.28.44.12 443]", "W: Some index files failed to download. They have been ignored, or old ones used instead."

Package read from requirements file: rabbitmq-server 3.8.3", "Package to download: rabbitmq-server=3.8.3*", "E: Version '3.8.3*' for 'rabbitmq-server' was not found", "E: No packages found
```

**Describe the solution you'd like**
- Increase script verbosity
- Catch error message from `apt` commands and retry
- Generic function for running any command with retries on error

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by przemyslavic** [comment]
Retry functionality has been added to `apt-get download` command.
Related issue: #1710 to extend retry functionality for all network related commands in `download-requirements.sh`.
