### ISSUE TITLE
"Settings schema 'org.gnome.Epiphany.web' does not contain a key named 'enable-itp'[BUG] Short description of the bug

### ISSUE THREAD

**Issue by fabrixx** [epiphany-platform/epiphany#1794]
If i install an old version with ninja and after overwrite with my new package manager version i have the error:
`"Settings schema 'org.gnome.Epiphany.web' does not contain a key named 'enable-itp'`

I try to add that key but not fix.

I reinstalled new source by ninja to readd that key and work again

After the Aur version (/usr/bin epiphany) say:
```
 Settings schema 'org.gnome.Epiphany.web' does not contain a key named 'gsb-api-key'
Rilevato trace/breakpoint (core dump creato)
```
And the ninja build version work (/usr/local/bin/epiphany) work well.

Howto retourn to my official Arch package and clean the ninja installed one?

**Comment by erzetpe** [comment]
Hi, 

Your request probably concenrs different project than ours. :) We are platform related mainly to orchestration of PAAS deployments, not tool related to gnome (but we like gnome, we are using this). That's why we are closing your ticket.

Thanks,
Pawel
