### ISSUE TITLE
[FEATURE REQUEST] Upgrade KeyCloak to at least V10

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1797]
**Is your feature request related to a problem? Please describe.**

We are seeing a problem with Keycloak and AAD integration.  When we are adding a user to groups in AAD the users roles are not automatically added in Keycloak.  We are currently going into to Keycloak and manually adding roles.  We having seen that at minimum Keycloak V10 that it adds a option to Sync with the identity provider.  That option is not there in v9.

**Describe the solution you'd like**
Upgrade to at least v10

**Describe alternatives you've considered**
- Find solution / workaround for issue
- Upgrade to latest version

**Additional context**
This is from the documentation for KeyCloak: Sync Mode
Strategy of how to update user information from the idp through mappers: When choosing legacy, the current behavior is kept, import will never update user data, while force will always update user data when possible. See also the documentation for Identity Provider Mappers for more details.

We believe we need the Force mode.

I believe we need this before going to Production with a client for DE.

https://www.keycloak.org/docs/10.0/server_admin/index.html#_identity_broker

**Comment by mkyc** [comment]
We should check if that makes sense to wait for version 13.

**Comment by seriva** [comment]
We need to make sure we use a multi-arch image for whatever version we have. Steps and repos here:

https://hub.docker.com/repository/docker/epiphanyplatform/keycloak

**Comment by seriva** [comment]
13.0.1 multi arch image available here already: https://hub.docker.com/r/epiphanyplatform/keycloak/tags?page=1&ordering=last_updated

**Comment by przemyslavic** [comment]
:heavy_check_mark: Successfully deployed new clusters with Keycloak application in version 14.0.0
:heavy_check_mark: `epicli apply` v1.0 (Keycloak v9.0.0) -> `epicli upgrade` -> `epicli apply` dev (Keycloak v14.0.0).
Image updated to version 14.0.0. Settings, created users, roles, etc. are still present after the upgrade.
:heavy_check_mark: ARM installation
