### ISSUE TITLE
[FEATURE REQUEST] Additional alerts for Prometheus

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1798]
Consider to create additional alerts for Prometheus

**Describe the solution you'd like**
Request based on internal request - ask @plirglo for details

**Describe alternatives you've considered**
Create template and documentation to easy create / import alerts configuration

**Comment by mkyc** [comment]
Team requesting it already added those alerts to their infrastructure.

**Comment by pprach** [comment]
Check created prometheus alerts and decide which should be used in epiphany.

**Comment by przemyslavic** [comment]
Additional rules have been added for the `alertmanager`. During testing `alertmanager` component and all possible rules have been enabled. Additionally, e-mail notification was enabled and tested to check if the notifications are working properly.
Everything looks fine.

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/747d3295-fd16-45cc-b2c2-0c8631b28e20)

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/3349bb47-47f3-461b-8a60-d1b081970ea2)

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/13903052-9fd0-4ce1-980f-5f9d089ca828)

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/252b4695-c0fa-46b6-bc5b-f3ace691c4e8)
