### ISSUE TITLE
[FEATURE REQUEST] Introduce versioning for the offline package

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1804]
**Is your feature request related to a problem? Please describe.**
Epiphany has no way of validating if an offline package at hand is compatible with ansbile code.

**Describe the solution you'd like**
Offline package should contain some kind of information from which commit or requirement.txt file it was constructed. It should be by default enabled and verified by epicli before any provisioning happens. There should be also a switch to turn this check off for development purposes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by seriva** [comment]
Closing as we will not be doing this for this version of Epiphany anymore.
