### ISSUE TITLE
Decide Istio module scope

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1822]
**Is your feature request related to a problem? Please describe.**
Right now we don't have scenarios and haven't agreed scope for Istio module.

**Describe the solution you'd like**
Based on spike [1821](https://app.zenhub.com/workspace/o/epiphany-platform/epiphany/issues/1821) we need to agree clear scope for Istio module initial development.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by mkyc** [comment]
In this task we should decide scope of Istio module. We have to do basic research what are use cases and identify order of work. Similarly as in #1819 but in that other task, we know scenarios because we already use Kubernetes heavily, and with Istio we're not that skilled.

**Comment by toszo** [comment]
Create an Istio module that will: 
1. Install Istio on Managed and unmanaged K8s - Must Have
1.1 Istio by default will use Third party tokens for authentication - which is not enabled on all platform, using istioctl this will be detected automatically (https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens) or we may "ask K8s" if it is supported before installing Istio
1.2 Istio Operator should be a better option to manage Istio (CR should be well supported by ArgoCD)

2. Support Observability - configure Prometheus to scrape metrics from "Istio Prometheus" - Should Have
3. Default route - configure default route which is recommended security practice "VirtualService with a default route for every service should be set by installer."

@mkyc @rpudlowski93 @seriva please comment if you have any suggestions.

**Comment by atsikham** [comment]
I've read what was done in #1821. There is just a few steps to install/update/uninstall Istio with operator, but we plan to wrap even that with modules. We are going to create an additional level of complexity, when it's not necessary.

**Comment by mkyc** [comment]
> 1. Install Istio on Managed and unmanaged K8s: 

👍 

> 2. Support Observability 

That I would plan when we reach observability modules. 

> 3. Default route 

👍

**Comment by rpudlowski93** [comment]
I've just updated #1821 about upgrade process and I can confirm once again that installing Istio using operator and upgrading/uninstalling is super easy. 

- Using Istioctl and operator looks like the best connection for us 👍
- I'm really curious of opinion from @atsikham that maybe we don't need to wrap it to module, @mkyc can You comment it? 
- Support Observability - it can be done using Mixer component from control plane. "Sidecar agents collect metrics on requests and services and send them to Mixer. Mixer is where Istio aggregates all metrics for telemetry and makes them available to external tools for further analysis."

**Comment by mkyc** [comment]
> I've read what was done in #1821. There is just a few steps to install/update/uninstall Istio with operator, but we plan to wrap even that with modules. We are going to create an additional level of complexity, when it's not necessary.

In general modules approach is designed to remove different ways to operate different components. 

As far as I can imagine now, we would enclose Istio installation steps into some Ansible script. As I just found during [this PR](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/47) terraform modules will be very similar to each other and will be easy to abstract, but still test separately and apply "case by case" modifications where required. I assume very similar situation with "ansible modules" - after some initial struggle one pattern will emerge. 

Istioctl itself is additional level of complexity, ansible is additional layer of complexity, and so on. Those levels are created to achieve different goals: Istioctl goal is to hold tight grip on all what is related to Istio related operations on kubernetes, Ansible goal is to provide unified Python'ish framework to operate OS level, and epiphany modules goal is to provide our users with nice LEGO-like bricks they can put together to build something useful in couple simple steps.

**Comment by atsikham** [comment]
`Istioctl itself is additional level of complexity` - It's not true, as it's created to simplify Istio management and actually It does that.
Ok, let's see how things will go with that module.

**Comment by toszo** [comment]
@mkyc @atsikham is this conversation enough to start working on Istio Module? 
To sum up: 
1. Install Istio on managed and unmanaged K8s. <- that is where we start
It means - create a module that will install Istio Operator which will allow us to maintain Istio config (routing, ingresses, certs) using CR's.

**Comment by seriva** [comment]
For unmanaged K8s we want to use the module to just deploy it on top of our current old stack EpiCLI cluster correct?

**Comment by to-bar** [comment]
Added some [comments](https://github.com/epiphany-platform/epiphany/issues/1821#issuecomment-743130070) in #1821.

**Comment by mkyc** [comment]
Yeah, we should also have decision here if we are required to provide offline mode in first version.

**Comment by seriva** [comment]
So as discussed, we are moving forward like so:

- Use Istio operator
- For managed clusters for now Istio will be implemented in classic Epicli/Epiphany as an additional application deployment. Offline mode should work like other components: #1911
- For EKS and AKS we will create an additional module doing the same. Offline mode will be semi supported by using the flag [`--hub `](https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-operator-init). Users will be required to setup there own docker repo for usage with the flag. #1910

**Comment by mkyc** [comment]
I believe we have decisions and we can proceed to DoD.
