### ISSUE TITLE
[BUG] Kafka  - Disable debug logging and make this option configurable

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1834]
**Describe the bug**
Epiphany delivers Kafka with KAFKA_OPTS=-Djavax.net.debug=all set as default in [service configuration](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/kafka/templates/kafka.service.j2)

That means debug logging is enabled by default and may impact machine performance (when SSL communication between brokers enabled) - High CPU Usage, generates a lot of logs.

Debug option should be disabled by default and should be configurable in defaults.

**To Reproduce**
1. Create Epiphany cluster with Kafka
2. Configure SSL communication between brokers
3. See machine utilization

**Expected behavior**
High CPU usage might be observed

**Config files**
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/kafka/templates/kafka.service.j2

**OS (please complete the following information):**
any

**Cloud Environment (please complete the following information):**
any

**Additional context**
Issue created based on client support request: EP-203.
Should be backported to v. 0.5.x

**Comment by ar3ndt** [comment]
tested - ok
