### ISSUE TITLE
[BUG] Automated tests may give false negative result for PGAudit

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1835]
**Describe the bug**
Test `Checking if the Elasticsearch logs contain queries from the PostrgeSQL database` occasionally fails (randomly) .

**To Reproduce**
1. Use config with enabled PGAudit.
2. Create cluster.
3. Run tests for `postgresql` group many times (`eoicli test` with `-g postgresql`).

**Expected behavior**
Tests should pass.

**OS:**
 - RHEL7

**Cloud Environment:**
 - AWS

**Additional context**
n/a

**Comment by przemyslavic** [comment]
The tests work fine after the fix is made.
