### ISSUE TITLE
[FEATURE REQUEST] Missing Authentication in Zookeeper

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1843]
**Is your feature request related to a problem? Please describe.**
Right now you can access Zookeeper without any authentication. The good thing is that Zookeeper is by default not accessible from the outside network, so this is only a concern for misconfiguration or man in the middle attacks.

**Describe the solution you'd like**
We want to add authentication to Zookeeper.

**Describe alternatives you've considered**
Wait for future release of Kafka without Zookeeper.

**Additional context**

**Comment by seriva** [comment]
Closing this issue as zookeeper will be removed in future upgrades of Kafka.
