### ISSUE TITLE
[BUG] Default Password in Open Distro Elasticsearch, Filebeat, Kibana and Grafana

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1844]
**Describe the bug**
We have default passwords on Elasticsearch, Grafana and  Kibana after installation. This can be changed later on, but we should avoid such situation.

**To Reproduce**
Login to any of the services just after installation.

**Expected behavior**
Usage of provided or automatically generated passwords for those services.

**Config files**
No.

**OS (please complete the following information):**
 - OS:  All

**Cloud Environment (please complete the following information):**
 - Cloud Provider: All

**Additional context**
None.

**Comment by plirglo** [comment]
Result of this task should be disabled default password in these services since it's unacceptable from security perspective.

**Comment by przemyslavic** [comment]
Tested.
✅ `epicli apply`
✅ `epicli upgrade` from 0.6
✅ `epicli upgrade` from 0.7
✅ `epicli upgrade` from 0.8
✅ `epicli upgrade` from 0.9
