### ISSUE TITLE
[BUG] epicli apply fails when rerun for cluster on which 'repmgr standby switchover' was performed

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1846]
**Describe the bug**
Epiphany assumes and requires for PostgreSQL cluster that the first inventory host is always primary node and the second standby. If roles are switched, it fails with error:

```
TASK [postgresql : Register primary with repmgr]
skipping: [ec2-54-208-80-28.compute-1.amazonaws.com]
fatal: [ec2-54-172-24-132.compute-1.amazonaws.com]: FAILED! => {"changed": true, "cmd": "/usr/bin/repmgr primary register -f /etc/postgresql/10/main/repmgr.conf --force --superuser=epi_repmgr_admin", "delta": "0:00:00.047723", "end": "2020-11-12 14:20:29.793961", "msg": "non-zero return code", "rc": 1, "start": "2020-11-12 14:20:29.746238", "stderr": "ERROR: server is in standby mode and cannot be registered as a primary", "stderr_lines": ["ERROR: server is in standby mode and cannot be registered as a primary"], "stdout": "", "stdout_lines": []} 
```

**To Reproduce**
1. Create cluster with PostgreSQL replication enabled.
2. Switchover database nodes, see [how-to doc](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-switchover-database-nodes).
3. Run `epicli apply` again (the same config as in step 1).

**Expected behavior**
`epicli apply` should not fail and allow to have switched roles.

**Config files**
n/a

**OS (please complete the following information):**
 - Found on Ubuntu

**Cloud Environment (please complete the following information):**
 - All

**Additional context**
n/a

**Comment by mkyc** [comment]
Linked with #2074

**Comment by to-bar** [comment]
This issue has been solved in PostgreSQL upgrade related feature branch but we should re-test after merging code to `develop` branch.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed.
Successfully deployed a 3-node cluster, performed a switchover and executed `epicli apply` again.
