### ISSUE TITLE
Update Ansible to v2.8.17

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1848]
**Is your feature request related to a problem? Please describe.**
We use Ansible v2.8.8. The latest available for 2.8 branch is v2.8.17.
See changelog: https://github.com/ansible/ansible/blob/v2.8.17/changelogs/CHANGELOG-v2.8.rst

**Describe the solution you'd like**
We already have feature branch with updated version (created when trying to solve issue with yum).

**Additional context**
n/a

**Comment by przemyslavic** [comment]
Full installation tested, everything works fine.

**Comment by mkyc** [comment]
Please update Components.md.

**Comment by to-bar** [comment]
> 
> 
> Please update Components.md.

Updated in PR #1856
