### ISSUE TITLE
[BUG] epicli upgrade fails when there is no kubernetes_master group in inventory

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1875]
**Describe the bug**
`epicli upgrade` requires `kubernetes_master` group. For AKS/EKS clusters there is no such group.

```
INFO cli.engine.UpgradeEngine - Run done in 20887ms
ERROR epicli - No kubernetes_master to use as repository
```

**How to reproduce**
1. Deploy Epiphany cluster without k8s or with k8s as cloud service (`k8s_as_cloud_service: true`). 
2. Run `epicli upgrade`.

**Expected behavior**
Upgrade succeeded.

**Environment**
- Cloud provider: All
- OS: All

**Additional context**
The error is from `core\src\epicli\cli\engine\ansible\AnsibleInventoryUpgrade.py`.

**Comment by przemyslavic** [comment]
✅ The installation of the cluster without K8s has been checked and the upgrade now works fine.
