### ISSUE TITLE
[BUG] epicli: wrong informations in help messages

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1881]
**Describe the bug**
We have some discrepancies in epicli <command> --help messages.
Example:
```shell
epicli prepare --help
usage: epicli <command> [<args>] prepare [-h] --os
                                         {ubuntu-18.04,redhat-7,centos-7}

Creates a folder with all prerequisites to setup the offline requirements to
install a cluster offline.

optional arguments:
  -h, --help            show this help message and exit
  --os {ubuntu-18.04,redhat-7,centos-7}
                        The OS to prepare the offline requirements for:
                        ubuntu-18.04|redhat-7|centos-7
```
`--os` argument is not optional, it's required to run `epicli prepare`:
```py
(...)
    sub_parser.add_argument('--os', type=str, required=True, dest='os', choices=['ubuntu-18.04', 'redhat-7', 'centos-7'],
                            help='The OS to prepare the offline requirements for: ubuntu-18.04|redhat-7|centos-7')
```
Second example:
```shell
epicli apply --help
usage: epicli <command> [<args>] apply [-h] [-f FILE] [--no-infra]
                                       [--skip-config]
                                       [--offline-requirements OFFLINE_REQUIREMENTS]
                                       [--vault-password VAULT_PASSWORD]
                                       [--profile-ansible-tasks]

Applies configuration from file.

optional arguments:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  File with infrastructure/configuration definitions to
                        use.
```
--file is required, epicli looking nowhere for a file if we don't specify it and error appears:
`12:02:11 ERROR epicli - expected str, bytes or os.PathLike object, not NoneType`

**How to reproduce**
epicli --help
epicli prepare --help
epicli apply --help
epicli init --help 
and so on..

**Expected behavior**
The help messages should reflect reality (code :grimacing: ).

**Comment by przemyslavic** [comment]
Help messages verified for:

- `epicli init`
- `epicli prepare`
- `epicli apply`
- `epicli delete`
- `epicli upgrade`
- `epicli test`
- `epicli backup`
- `epicli recovery`

The messages appear to reflect the actual state and correctly describe the required and optional parameters for each `epicli` command.
