### ISSUE TITLE
[FEATURE REQUEST] Add ansible-lint to epicli devcontainer

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1892]
**Is your feature request related to a problem? Please describe.**
Currently there is no linting, styling for our Ansible suite.

**Describe the solution you'd like**
Add Ansible-lint to the devcontainer and enable it and add a task to generate junit based output so we can run it later in our build infra.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/ansible-community/ansible-lint
https://pypi.org/project/ansible-lint-to-junit-xml/

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Preferably also add possibility to generate output using: https://pypi.org/project/ansible-lint-junit/ so we can publish it later when Azure devops.
