### ISSUE TITLE
[FEATURE REQUEST] Kafka Module

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1894]
**Is your feature request related to a problem? Please describe.**
Currently upgrading Epiphany means - all or nothing, users need to update all components which sometimes can be problematic (like libraries in apps used for Kafka connectivity may not be fully compatible with never version). But in the same time want to update other components - or may update just Kafka.  

**Describe the solution you'd like**
Have a module that will be responsible for Kafka installation and upgrades. 

**Describe alternatives you've considered**
Kafka on VMs and another module for Kafka on Kubernetes (a'la Strimzi?).

**Comment by seriva** [comment]
This will not be done anymore.
