### ISSUE TITLE
[SPIKE] Make Epiphany maintenance-free as much as possible

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1900]
One of our business goals is to make Epiphany maintenance-free to the point where we could leave an on-prem cluster working for years without any crash.

There are many scenarios to consider here, like expiring k8s certificates, overflowing filesystems or faulty hardware. In this spike we would like to first understand what should be such scenarios, then later having this knowledge we would create some guidelines / checklists / DoD-rules for developers of future modules and some recommendations to users.

I believe well-defined strictly followed criteria together with good code review should give some results. :+1::innocent:

We want a design-doc out of his research. :eyes:

**Comment by seriva** [comment]
Closing as this will not be done for this version of Epiphany anymore.
