### ISSUE TITLE
[FEATURE REQUEST] Deploy Istio on unmanaged clusters installed with Epicli

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1911]
**Is your feature request related to a problem? Please describe.**
We would like to have [Istio](https://istio.io/) as our service mesh on unmanaged clusters deployed with Epicli

**Describe the solution you'd like**
An additional application using [Istio Operator](https://istio.io/latest/docs/setup/install/operator/) to deploy [Istio](https://istio.io/) on unmanaged clusters.

Should support offline installation leveraging the existing repository setup in classic Epiphany.

**Describe alternatives you've considered**
*

**Additional context**
Based on the [spike](https://github.com/epiphany-platform/epiphany/issues/1821) we decided to use for the installation process - istioctl, so we have to add istioctl to epicli (container/devcontainer)

**Comment by rpudlowski93** [comment]
Aibility to deploy istio implemented in PR #1925

**Comment by rpudlowski93** [comment]
Added new task for monitoring the Istio in Prometheus : #1931

**Comment by przemyslavic** [comment]
It works fine with `flannel` network plugin.
There are issues with istio-proxy when using Istio with `canal` and `calico`: `Readiness probe failed: HTTP probe failed with statuscode: 503`.
@rpudlowski93 is currently investigating this issue.

**Comment by rpudlowski93** [comment]
I investigated the problem and it looks that there is required to do one additional step from user side. 
Envoy must be able to communicate with the istio-pilot.istio-system service. If in cluster are applied any egress policies to application pods, we must enable access for the namespace where the application is running.

So, in our case if we have by default deny all ingress and all egress traffic by network policy and in the cluster is CNI plugin which support network policy such as: canal or calico (flannel don't support network policy) there will be network issue between Enovy Proxy and Istio core component. So to enable Istio to work, you need to turn off the default network policy enforcement on all nodes and it is recommenced to create secure setup custom network policy which allow intercommunication istio components or for example just add the following network policy in the namespace where the application is running: 

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 namespace: application_namespace
 name: allow-istio-pilot
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress

**Comment by przemyslavic** [comment]
After applying the solution above (for the default namespace) everything seems to work fine. When deploying the application to a dedicated namespace, no network traffic problem was noticed at all.
