### ISSUE TITLE
[SPIKE] Assess possibility of using RKE instead of existing Epiphany solution in new Kubernetes module

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1912]
**Is your feature request related to a problem? Please describe.**
Right now we have assessed RKE, Kubespray and other possible solutions to be used in Epiphany in new Kubernetes module realized in task [Research of kubernetes installing tools](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1818) we need to assess possibility of using RKE in Epiphany Kubernetes module.

**Describe the solution you'd like**
The goals of this task:

1) Create a module with initial configuration to deploy and [upgrade](https://github.com/sk4zuzu/RESEARCH/blob/master/k8s-engines-on-prem/rke/Makefile#L55-L57) k8s cluster on-prem by RKE. Use mentioned above task for details and research [results](https://github.com/sk4zuzu/RESEARCH/tree/master/k8s-engines-on-prem/rke).
2) Deploy components provided by "applications" Ansible role of epicli in created Kubernetes cluster.
3) Validate if [ha solution with haproxy](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/kubernetes-ha/kubernetes-ha.md) works as expected. If it's necessary, remove Nginx ingress controller (suggested by @erzetpe).
4) After the main part of this work is completed, create new tasks with found details:

* [Offline mode](https://github.com/sk4zuzu/RESEARCH/tree/master/k8s-engines-on-prem/rke#3-offline--air-gapped) for RKE.
* Work with existing legacy kubernetes: using RKE with existing clusters deployed by Epiphany, 
process of upgrade of existing Kubernetes clusters deployed by Epiphany, possibility of work with already deployed applications (e.g. Keycloak).
* Separation of OS from applications running on Kubernetes (resource reservation), to prevent OS crash (e.g. in case of running on Kubernetes application memory leak). Take a look at [documentation](https://rancher.com/docs/rancher/v2.x/en/project-admin/resource-quotas/quotas-for-projects/). Use [testing tools]( https://github.com/epiphany-platform/epiphany/tree/develop/tools/development/k8s/memory) provided by @to-bar.
* Possibility to use `hosts` plugin for CoreDNS to have addresses resolved even if there is no upstream dns - currently Epiphany patches CoreDNS. Verify [NodeLocal DNS cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/).
* Check RKE default security related settings and customization options (e.g. admission plugins).

**Describe alternatives you've considered**
None.

**Additional context**
Already mentioned [Research of kubernetes installing tools](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1818)

**Comment by toszo** [comment]
I added grooming-needed label because this does not look clear to me. 

> What is required to switch to RKE in Kubernetes module from module perspective
What does it mean? It does not clearly specify what is to do. 
> What is required to switch to RKE from other components perspective
Same here.
> Offline mode for RKE
Is it not covered by spile that @sk4zuzu  did? 

> Work with existing legacy kubernetes - can be RKE used with existing clusters deployed by Epiphany,
process of upgrade of existing Kubernetes clusters deployed by Epiphany, possibility of work with already deployed applications (e.g. Keycloak)
IMO this thing should be tested (maybe in another spike?) is the transition from Kubeadm Kubernetes -> RKE. I'm pretty sure there are ppl in the world that tried that. 
> Separation of OS from applications running on Kubernetes (resource reservation), to prevent OS crash (e.g. in case of running on Kubernetes application memory leak)
This should be another task that should be done anyway (not in this scope). 
> Is it possible to use hosts plugin for CoreDNS - currently Epiphany patches CoreDNS
The goal of using hosts plugin is to have addresses resolved even if there is no upstream dns (like some on-prem installations). Maybe RKE is worked this out somehow?

**Comment by atsikham** [comment]
Additional comments were left.
> 
> > What is required to switch to RKE in Kubernetes module from module perspective
> 
> What does it mean? It does not clearly specify what is to do.
> 
I suppose that the goal of this task is to create an initial module configuration with an ability to deploy k8s cluster on prem
>
> > What is required to switch to RKE from other components perspective
> 
Probably the idea is to check main components installation, "applications" Ansible role, with epicli in the k8s cluster that is created by a new module
>
> Same here.
> 
> > Offline mode for RKE
> 
> Is it not covered by spike that @sk4zuzu did?
> 
@sk4zuzu could you comment that?
>
> > Work with existing legacy kubernetes - can be RKE used with existing clusters deployed by Epiphany,
> > process of upgrade of existing Kubernetes clusters deployed by Epiphany, possibility of work with already deployed applications (e.g. Keycloak)
> 
> IMO this thing should be tested (maybe in another spike?) is the transition from Kubeadm Kubernetes -> RKE. I'm pretty sure there are ppl in the world that tried that.
>
I see that there is an ability to import existing clusters to the RKE. @sk4zuzu did you tested that or we need an additional spike for upgrade action?
> 
> > Separation of OS from applications running on Kubernetes (resource reservation), to prevent OS crash (e.g. in case of running on Kubernetes application memory leak)
> 
> This should be another task that should be done anyway (not in this scope).
> 
This is described in Rancher [documentation](https://rancher.com/docs/rancher/v2.x/en/project-admin/resource-quotas/quotas-for-projects/) and should/can be done by using project and namespace resource quotas.
>
> > Is it possible to use hosts plugin for CoreDNS - currently Epiphany patches CoreDNS
> 
> The goal of using hosts plugin is to have addresses resolved even if there is no upstream dns (like some on-prem installations). Maybe RKE is worked this out somehow?
>
There is an [ability](https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#configuring-nodelocal-dns) to use [NodeLocal DNS cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/), isn't it what we need?

@erzetpe @sk4zuzu @toszo Please comment that. At the moment it's unclear how to proceed with this task and which tasks should be created in addition.

**Comment by sk4zuzu** [comment]
Offline mode - it's not fully supported in the sense that Epiphany provides it, RKE supports "airgapped" clusters, but does not provide automatic collection of packages and images (none of the known solutions supports full Epiphany-like offline mode). But with RKE it's really basic and simple to implement all that (just look at the research here https://github.com/sk4zuzu/RESEARCH/blob/master/k8s-engines-on-prem/rke/Makefile#L29-L44). :+1::innocent:

Upgrades - are simple and straightforward and I tested them in the spike like here https://github.com/sk4zuzu/RESEARCH/blob/master/k8s-engines-on-prem/rke/Makefile#L55-L57

Node local DNS - that needs to be confirmed

Resource separation - that's something external to RKE, but needs to be addressed, here https://github.com/epiphany-platform/epiphany/tree/develop/tools/development/k8s/memory (thanks @to-bar !) we have some testing tools.

**Comment by mkyc** [comment]
I would consider this spike done. To summarise current state: 
 - additional tests were made
 - example installation and integration with OpenEBS was made
 - additional findings are described in internal "Possibility of using RKE in Epiphany" document
