### ISSUE TITLE
Add checking in preflight if hostnames of machines where Epiphany is installed are propery set.

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1916]
**Is your feature request related to a problem? Please describe.**
We don't have hostname validation prior to Epiphany installation.

**Describe the solution you'd like**
We need to check in preflight if hostnames are meeting the rule: hostnames must be static and transient names consists only of 7 bit ASCII lower-case characters, no spaces or dots, and limits itself to the format allowed for DNS domain name labels.

**Describe alternatives you've considered**
None.

**Additional context**
This is the following story for [1388](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1388).

Recommendation from [hostname]( https://www.freedesktop.org/software/systemd/man/hostname.html).

**Comment by atsikham** [comment]
I was finally able to create SP with following steps:

* `e environment new`
* `az account clean`
* `az login`
* `e az sp create --name atsikham-test --subscriptionID <subscription-id> --tenantID <subscription-id>`

Created new issues #22, #23, #24, #25

**Comment by seriva** [comment]
Already something that is done with validation, so closing.
