### ISSUE TITLE
[FEATURE REQUEST] Implement monitoring for Istio

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#1931]
**Is your feature request related to a problem? Please describe**.
We would like to monitor parameters of Istio (control plane and envoy proxy) on unmanaged clusters deployed with Epicli.
In compare to managed cluster (AKS/EKS) Istio pods are working in internal cluster network which is not accessible by external prometheus server win epiphany.

**Describe the solution you'd like**
We would like to scrape metrics from Istio Control Plane and Envoy Proxy in our external Prometheus service (monitoring machine). In order to make it, we should implement schema with Prometheus Federation.

I would like to have Prometheus locally in cluster which scrape metrics from Istio components and external Prometheus should be able to get metrics using Ingress Gateway as endpoint and the mentioned local Prometheus .

**Describe alternatives you've considered**
Deploy node port service without local prometheus and federations.

**Additional context**
How to monitor Istio using external Prometheus: [link](https://istio.io/latest/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/)

**Comment by rpudlowski93** [comment]
After short research it looks that in order to send metrics from istio mesh to our external monitoring instances we need to: 
- Deploy prometheus inside of our istio mesh cluster in order to scrape metrics from sidecar proxies 
- Expose the prometheus service outside of the cluster using virtual service, gateway and destination rules: 

```
$ cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-prom
      protocol: HTTP
    hosts:
    - "prometheus.${INGRESS_DOMAIN}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
  - "prometheus.${INGRESS_DOMAIN}"
  gateways:
  - prometheus-gateway
  http:
  - route:
    - destination:
        host: prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF
```

More here: [link](https://istio.io/latest/docs/tasks/observability/gateways/) and here: [link](https://istio.io/latest/docs/tasks/observability/metrics/querying-metrics/)

**Comment by mkyc** [comment]
We should first ensure Istio usage and future.

**Comment by erzetpe** [comment]
Closing because of deprecation of Istio component.
