### ISSUE TITLE
Unable to pass arguments

### ISSUE THREAD

**Issue by diwa2508** [epiphany-platform/epiphany#1940]
**Describe the bug**

Am trying to pass debug arguments to the epicli, but getting the below error.

==========================================================================
12:13:14 ERROR epicli - 'Namespace' object has no attribute 'func'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/epicli.py", line 127, in main
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
12:13:17 INFO dump_debug_info - Error dump has been written to: /shared/epicli_error_20210111-121314.dump
============================================================================

**How to reproduce**
1. execute `epicli --debug 4`

**Comment by seriva** [comment]
closed as this is not a bug but just additional input is missing. Use **epicli --help** to see what you actually need to include in epicli commands.
