### ISSUE TITLE
[BUG] RabbitMQ automated tests fail after upgrading to 3.8.9

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1945]
**Describe the bug**
RabbitMQ automated tests are not adjusted to changes made in #1889.
Failing test: `Checking RabbitMQ version Command "rabbitmqctl version" stdout is expected to match /^$/`

**How to reproduce**
1. Deploy cluster with RabbitMQ
2. Execute `epicli test -b <BUILD_DIR> -g rabbitmq`

**Expected behavior**
Tests succeeded.

**Additional context**
Definition of RabbitMQ version was moved to the `roles/rabbitmq/defaults/main.yml` file.

**Comment by przemyslavic** [comment]
✅ RabbitMQ tests fixed.
