### ISSUE TITLE
[FEATURE REQUEST] Upgrade ansible to 2.10.x

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1952]
**Is your feature request related to a problem? Please describe.**
We're currently using ansible 2.8.x in Epiphany and we'd like to have it upgraded to 2.10.x. I strongly believe we have to constantly modernize our tools. Also PRs like https://github.com/epiphany-platform/epiphany/pull/1879 would greatly simplify.

**Describe the solution you'd like**
Upgrade and test, that's it.

**Describe alternatives you've considered**
We could wait longer and risk to be left behind. It's only gonna get worse in the future. :innocent: 

**Additional context**
N/A

**Comment by przemyslavic** [comment]
Tested:
✔ `epicli apply` with all components enabled
✔ `epicli upgrade` from 0.6, 0.7 HA, 0.8 to develop
