### ISSUE TITLE
[BUG] Elasticsearch Curator version out of date

### ISSUE THREAD

**Issue by sunshine69** [epiphany-platform/epiphany#1955]
**Describe the bug**
Elastic Curator version out of date for Ubuntu/Redhat/Centos (5.8.1)
We should upgrade Elasticsearch Curator to version which is available on all supported os distributions (5.8.3)

**How to reproduce**
Run the normal build regression test daily

**Expected behavior**
Build passed

**Additional context**
PR has been created please see https://github.com/epiphany-platform/epiphany/pull/1960

**Comment by przemyslavic** [comment]
✅ Installation with enabled `elasticsearch-curator` component tested. No issues found.
