### ISSUE TITLE
[FEATURE REQUEST] Advanced configuration type validation

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#196]
**Is your feature request related to a problem? Please describe.**
Currently there are is only basic type schema validations inside Epicli using jsonschema version 7.

**Describe the solution you'd like**
Add advanced type validations (enums, regex, ranges etc) inside the schema in the following folders:

- /workspaces/epiphany/core/src/epicli/data/azure/validation/infrastructure
- /workspaces/epiphany/core/src/epicli/data/aws/validation/infrastructure
- /workspaces/epiphany/core/src/epicli/data/azure/validation/infrastructure

**Describe alternatives you've considered**
*

**Additional context**
We probably want to break this down into smaller stories because of the amount of documents and fields to cover stories.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo this anymore for Epiphany.
