### ISSUE TITLE
[SPIKE] Compare K8s options

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1963]
**Is your feature request related to a problem? Please describe.**
We want to have additional comparison of our solution and tools analyzed in #1818

**Describe the solution you'd like**
In this spike, we should compare all of tools from task #1818 and our k8s code in one table. We should consider at least what was researched in previous task, and also: 
 * Installation
* Maintenance
 * Troubleshooting
 * Upgrades
 * Migration of existing products

**Describe alternatives you've considered**
None.

**Additional context**
In task #1818 there was performed research on what external tools there are and what options do we have.

**Comment by rpudlowski93** [comment]
Small update: First version of the comparison done [here](https://github.com/rpudlowski93/research/blob/rke-vs-epiphany/rke-vs-epiphany/rke-vs-epiphany.md). Generally we focused on comparing RKE with our code but in order to have clear score of the spike we just need to add to the table other tools such as: kubeone and kubespray. After that I will create PR in Epiphany repo.

**Comment by mkyc** [comment]
Is this research focused on RKE or RKE2?

**Comment by rpudlowski93** [comment]
@mkyc - RKE :)

**Comment by rpudlowski93** [comment]
Update: RKE2 also added to the table :) PR #[2017](https://github.com/epiphany-platform/epiphany/pull/2017)

SPIKE done :)
- https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/k8s-engines-on-prem/k8s-engines-on-prem-table.md

**Comment by rpudlowski93** [comment]
Moving to DoD since there is nothing more what what we can add right now.

**Comment by rpudlowski93** [comment]
Documentation temporarily moved to confluence : 

https://pgga-es.atlassian.net/wiki/spaces/EPI/pages/1415448563/ON-PREM+KUBERNETES+AUTOMATION+RESEARCH+RESULTS
