### ISSUE TITLE
Azure Files Persistent Volume Support

### ISSUE THREAD

**Issue by alajmo** [epiphany-platform/epiphany#1974]
**Is your feature request related to a problem? Please describe.**
We don't have support for Azure Storage solutions.

**Describe the solution you'd like**
We want to provide solution for Azure Storage that can be mounted for deployments. 

**Describe alternatives you've considered**
None.

**Additional context**

Original issue - reformated to the form of our issues.

Does Epiphany have or plan to support different Azure Storage solutions, such as Azure files via the `kubernetes.io/azure-file` provisioner? Or is there any other persistent filesystem we can mount to deployments? 

I saw in the code that a persistent volume was created along with a persistent volume claim, with `storageClassName` azurefile, but there doesn't seem to be any storage class of that name when I browse existing scs (`kubectl get sc`) and I get same issue as https://github.com/epiphany-platform/epiphany/issues/308 when I try to create one.

I'm using Epicli 0.8.0 

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by soalhn** [comment]
I have the same issue, I think it should be a similar approach to the AKS, sth like this:
```
NAME                                              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/azurefile             kubernetes.io/azure-file   Delete          Immediate              true                   15h
storageclass.storage.k8s.io/azurefile-premium     kubernetes.io/azure-file   Delete          Immediate              true                   15h
storageclass.storage.k8s.io/default (default)     kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   15h
storageclass.storage.k8s.io/managed-premium       kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   15h
```

**Comment by atsikham** [comment]
Documentation was updated, It's possible to use Azure files.
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/PERSISTENT_STORAGE.md
