### ISSUE TITLE
[BUG] When custom repo is used backup/recovery stops working

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1991]
**Describe the bug**
Backup/recovery uses `resolved_repository_hostname` which does not point to the correct VM when custom repository is used.

**How to reproduce**
1. use custom repository during `epicli apply`
2. enable something (anything really) to backup and run `epicli backup`

**Expected behavior**
No error, ansible stores backup artifacts correctly on a proper node.

**Config files**
N/A

**Environment**
- Cloud provider: all
- OS: all

**Additional context**
N/A

**Comment by rpudlowski93** [comment]
- Tested, works as expected ✅

I created new cluster with custom repository and postgresql + load balancer machines and after that I executed backup of the postgresql and load balancer instances and everything passed well, backups are stored on master node.
