### ISSUE TITLE
[BUG] Need special deal with azure subscription name if it has slash

### ISSUE THREAD

**Issue by sunshine69** [epiphany-platform/epiphany#2001]
**Describe the bug**
If you subscription name has a slash and even you set it in your service principal yaml epicli will fail at terraform stage.

The problems coming from Azure API itlself, while it allows to use slash `/` in the subscription name however the endpoint URI will not respect that. PLease see the comment in the PR for more information.

PR included (or a suggestion of the fix)

https://github.com/epiphany-platform/epiphany/pull/2000

What I found is that even I use the subscription ID in the sp.yaml in epiphany after load the yaml it converts it back to the subscription name. So add the logic if the name has `/` then we set the TF env var to use the ID.

This PR has been working in my test which fix out issue.

**Comment by seriva** [comment]
Closing as per comment left on discussion for #2000.
