### ISSUE TITLE
Do not install Filebeat when there is no Elasticsearch (Backport to 0.8)

### ISSUE THREAD

**Issue by ar3ndt** [epiphany-platform/epiphany#2002]
Related [task ](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1941)to be backported.

**Comment by rafzei** [comment]
Nothing fancy here, just backport [changes](https://github.com/epiphany-platform/epiphany/pull/1941/files).

**Comment by przemyslavic** [comment]
✔️ Fixed. Filebeat installation as DaemonSet is skipped if there is no logging component.
