### ISSUE TITLE
[FEATURE REQUEST] Create GH Issue Template for with release checklist 

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2022]
**Is your feature request related to a problem? Please describe.**
We do not have checklist template to be created for each release in GH. Due to this we miss some important points. 

**Describe the solution you'd like**
Discuss and add GH Issue Template with Checklist inside. 

**Describe alternatives you've considered**
We also discussed internal Confluence list, but that sounds less visible. 

**Additional context**
We released last version with old OS version.

**Comment by mkyc** [comment]
After it's decided we should reflect this Checklist into another repositories.

**Comment by przemyslavic** [comment]
For next releases, we have to follow the checklist provided in the `Release version` template.
