### ISSUE TITLE
[FEATURE REQUEST] Introduce "post provisioning chores module"

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2024]
**Is your feature request related to a problem? Please describe.**
Data disks is new AzBI module’s feature. They are created but not ready to use without manual actions. 

**Describe the solution you'd like**
Create partitions on data disks and mount them automatically. 

**Describe alternatives you've considered**
No. We need to mount them :) 

**Additional context**
It was discussed during development of data disks feature. I talked with multiple people and general common feeling was that adding this into terraform infrastructure modules would look bad. It leads directly to conclusion that there should be kind of "post provisioning chores module" where for example disks mounts would be configured in ansible. Other possible things here are package updates or basic firewall settings. In general all the "post-provisioning" steps might be introduced here in future.

**Comment by esurio** [comment]
exactly what you need is in the internal jira, expect PR soon. 
EP-268

**Comment by esurio** [comment]
this might be partially or fully resolved by out internal jira: EP-269
lets talk - we probably can deliver what you need fairly easy.

**Comment by mkyc** [comment]
New [m-host-init module with initialisation PR](https://github.com/epiphany-platform/m-host-init/pull/1) was created. I will have additional look at resources provided by @esurio in internal jira to have some idea what was proposed there.

**Comment by przemyslavic** [comment]
New tasks created as a result of tests:
[[BUG] Flags '--shared' and '--resources' don't seem to work.](https://github.com/epiphany-platform/m-host-init/issues/9)
[[BUG] The 'plan' command may not work properly. ](https://github.com/epiphany-platform/m-host-init/issues/10)
[Make log output more verbose by default (INFO level) ](https://github.com/epiphany-platform/m-host-init/issues/11)
[[BUG] The apply command does not change the state file](https://github.com/epiphany-platform/m-host-init/issues/12)
