### ISSUE TITLE
[FEATURE REQUEST] Populate output from modules to epicli automatically

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2025]
**Is your feature request related to a problem? Please describe.**
Currently you need to populate epicli configuration file with output from modules manually. 

**Describe the solution you'd like**
Prepare Design Doc and discuss what is preferred way to generate epicli configuration file in transition period. 

**Describe alternatives you've considered**
No. 

**Additional context**
No.

**Comment by seriva** [comment]
Modules are deprecated so closing this.
