### ISSUE TITLE
[FEATURE REQUEST] Refactor Grafana upgrade role

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2028]
**Is your feature request related to a problem? Please describe.**
We keep grafana_version in two places (Grafana role defaults and hardcoded in grafana upgrade task)

**Describe the solution you'd like**
We need to refactor these roles to use in upgrade role grafana_version from grafana defaults. This should not be hardcoded in upgrade task.

**Comment by przemyslavic** [comment]
Tested together with #2699.
