### ISSUE TITLE
Remove old “architectures” leftover code

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2029]
**Is your feature request related to a problem? Please describe.**
Previously Epiphany had a support of ARM architecture, but after introducing "offline" mode it was deprecated. There are still a few [places](https://github.com/epiphany-platform/epiphany/search?q=architecture_map) with architecture references. Now we have a requirement to support ARM and the idea is to remove all related configuration parts that were created before to start implementation from scratch. 

**Describe the solution you'd like**
Remove all "architecture" related configuration parts.

**Describe alternatives you've considered**
No.

**Comment by przemyslavic** [comment]
This was just to clean up the code from unused ARM references.
