### ISSUE TITLE
Ensure that there are packages for all required components available for ARM architecture

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2032]
- Analyze all packages required during Epiphany deployment process and confirm that ARM architecture is supported by them.
- Find replacement for not supported packages (if any)
- Use requirements.txt files as base

**Comment by mkyc** [comment]
Here is script to setup ARM machine in AWS: https://github.com/mkyc/aws-arm-simple-setup

**Comment by ar3ndt** [comment]
Not all packages are available. These are missing:

elasticsearch-curator-5.8.3
opendistroforelasticsearch-kibana-1.10.1*
pgbouncer-1.10.*
rh-haproxy18
rh-haproxy18-haproxy-syspaths
repmgr10-4.0.6

epel that works for aarch64:

`[epel]
name=Epel for arm
baseurl=http://dl.fedoraproject.org/pub/epel/7/aarch64
enabled=1
gpgcheck=0`

**Comment by ar3ndt** [comment]
other [PR](https://github.com/epiphany-platform/epiphany/pull/2079) includes changes from this task

**Comment by przemyslavic** [comment]
It looks like a spike result. Nothing to test at this point.
