### ISSUE TITLE
Install and test all Epiphany components on ARM architecture

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2034]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
- We want to install and test all Epiphany components we need to support on an Arm64 based cluster with CentOS 7. The following components need to work:
    1. Kubernetes
    2. Kafka
    3. HAProxy
    5. Keycloak (This is the only deployment we need to support from the ```applications``` role)
    6. PostgreSQL (Would only be used by keycloak and does not needs to support a single deployment)
    7. RabbitMQ
    8. Logging (ELK + filebeat)
    9. Monitoring (Prometheus + Grafana + Exporters)
  Any other components we need to test if they are prevented from installing on ARM. 

- We also want to test if the normal x86_64 installations on the different OS`s  and upgrades are still working properly.

**Describe alternatives you've considered**
None.

**Additional context**
Maybe this task needs to be split into separate tasks. 

The list of components:

- [x] Repository
- [x] Kubernetes
- [x] Load Balancer
- [x] Kafka
- [x] Keycloak
- [x] PostgreSQL
- [x] Monitoring
- [x] Logging
- [x] RabbitMQ

**Comment by mkyc** [comment]
divide into buckets of components in correlation to #2033

**Comment by przemyslavic** [comment]
Done in #2036 (CI pipelines: add ARM testing).
