### ISSUE TITLE
[ARM] Create a documentation

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2035]
After the solution is ready...
Create a documentation consist of:
- requirements (what components, os etc.. are supported)
- how to prepare configuration manifest (if there will be any changes in comparison to a 'standard')
- how to run the deployment

**Comment by rafzei** [comment]
@mkyc  please put some more words here. Is this task for creating documentation about which Epiphany components have to be supported or something different?

**Comment by seriva** [comment]
I think we are waiting for @toszo to define that in this task: #2031

**Comment by mkyc** [comment]
This task is for documentation. As mentioned in #2039 we know about 8 or 9 components required by our customers. So after we do all the work, we need to document exactly what is supported not to mislead someone that all the features are supported on ARM.

**Comment by rafzei** [comment]
Ok, I've updated it a little bit, feel free to add something if it came to your mind ;)
