### ISSUE TITLE
CI pipelines: add ARM testing

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2036]
**Is your feature request related to a problem? Please describe.**
We don't have CI pipeline to test deployments on ARM architecture, so we need to create environments based on ARM architecture.

**Describe the solution you'd like**
We need to create pipeline to test environments based on ARM architecture

**Describe alternatives you've considered**
No.

**Additional context**
First of all we need to do #2034

**Comment by przemyslavic** [comment]
A pipeline for ARM testing has been created in Azure DevOps:
- provider: `AWS`
- OS: `CentOS`
- image: `CentOS 7.9.2009 aarch64`

Enabled components:
- repository - 1 vm
- kubernetes master: 1 vm
- kubernetes node: 2 vms
- load balancer: 1 vm
- kafka 2 vms (clustered)
- logging 2 vms (clustered)
- monitoring: 1 vm
- postgresql: 1 vm
- rabbitmq: 2 vms (clustered)
- ignite: 2 vms (clustered)
- opendistro: 1 vm
- keycloak deployment `epiphanyplatform/keycloak:9.0.0`
