### ISSUE TITLE
CI pipelines: add upgrade tests for ARM architecture

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2037]
**Is your feature request related to a problem? Please describe.**
We don't have CI pipeline to test upgrade deployments on ARM architecture

**Describe the solution you'd like**
We need to create pipeline to test upgrade process based on ARM architecture.

**Describe alternatives you've considered**
No.

**Additional context**
First of all we need to do: #2036

**Comment by przemyslavic** [comment]
A [pipeline](https://dev.azure.com/abb-epiphany/epiphany/_release?definitionId=234&view=mine&_a=releases) for testing upgrades from v1.1 to develop for aarch64 has just been created.
