### ISSUE TITLE
Test with external contacts that their load works correctly on provided environment

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2038]
This task is about going through all ARM supported components and final check with teams that everything works as expected.

The list of components:

- [x] Repository
- [x] Kubernetes
- [x] Load Balancer
- [x] Kafka
- [x] Keycloak
- [x] PostgreSQL
- [x] Monitoring
- [x] Logging
- [x] RabbitMQ

**Comment by rafzei** [comment]
If I understand the title correctly, we have to perform some tests & checks (maybe setup some pipelines?) on target environments based on ARM. Am I right @mkyc ?

**Comment by mkyc** [comment]
In general, after we test that Epiphany itself installs, starts, upgrades, etc. we need to help our users to install and run their applications on top of Epiphany. So all the tests and checks for Epiphany itself should be already done in previous tasks in epic. Here we want to focus on our clients.

**Comment by mkyc** [comment]
We should finish this task by the end of May.
