### ISSUE TITLE
[BUG] Failing test: /etc/prometheus is expected to be owned by root

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2046]
**Describe the bug**
Automated test fails with error message:
> expected File "/etc/prometheus".owned_by?("root") to be truthy, got false

`/etc/prometheus` is expected to be owned by `root` but it's owned by `prometheus` user.

Change introduced by #1990.

**How to reproduce**
1. Deploy cluster with `monitoring` component.
2. Run `epicli test` for `prometheus` group. 

**Expected behavior**
No failed tests.

**Environment**
All

**Additional context**
[cloudalchemy/ansible-prometheus](https://github.com/cloudalchemy/ansible-prometheus) [uses](https://github.com/cloudalchemy/ansible-prometheus/blob/2201713a60fa4b215c6b15b76c891e32d454d6e2/tasks/install.yml#L29):
```
owner: root
group: prometheus
mode: 0770
```

**Comment by przemyslavic** [comment]
Tests have been adjusted to development: `/etc/prometheus` directory is now owned by `prometheus` user.
