### ISSUE TITLE
[SPIKE] Review existing Kafka deployment architecture

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2051]
**Is your feature request related to a problem? Please describe.**
Right now we have relatively simple Kafka architecture. After our findings [1526](https://github.com/epiphany-platform/epiphany/issues/1526) we can apply some changes to improve reliability.

**Describe the solution you'd like**
We need to update our architecture to improve scalability and reliability of our Kafka deployment solution - e.g. assign proper number of Kafka, Zookeeper instances and apply Cruise Control.

**Describe alternatives you've considered**
None.

**Additional context**
Task [1526](https://github.com/epiphany-platform/epiphany/issues/1526).

**Comment by rpudlowski93** [comment]
About monitoring, right now we use only JMX and Kafka exporter and Prometheus and Grafana for scapping metrics and visualize them. There are some section which we can improve - maintenance, analysis, rebalancing based on tracking resource utilization, anomaly detection, showing statistics etcs.. . In our solution there are some things which are missing, we could apply additioinal tools and replace existing ones based on [1526](https://github.com/epiphany-platform/epiphany/issues/1526)

**Comment by rpudlowski93** [comment]
https://banzaicloud.com/blog/kafka-alert/ - scenario used in this article looks really nice :)

**Comment by seriva** [comment]
Not needed anymore.
