### ISSUE TITLE
[BUG] [CentOS] download-requirements.sh fails on extracting tar with backed up repos

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2066]
**Describe the bug**
download-requirements.sh fails with error:

```
Executing: tar --extract --verbose --file /tmp/prepare_scripts/download-requirements.sh-yum-repos-backup-tmp-do-not-remove.tar
etc/yum.repos.d/CentOS-fasttrack.repo
etc/yum.repos.d/CentOS-CR.repo
etc/yum.repos.d/CentOS-Debuginfo.repo
etc/yum.repos.d/CentOS-Media.repo
etc/yum.repos.d/CentOS-Sources.repo
etc/yum.repos.d/CentOS-Base.repo
etc/yum.repos.d/CentOS-Vault.repo
tar: etc/yum.repos.d/CentOS-SCLo-scl-rh.repo: Not found in archive
tar: etc/yum.repos.d/CentOS-SCLo-scl.repo: Not found in archive
tar: etc/yum.repos.d/epel-testing.repo: Not found in archive
tar: etc/yum.repos.d/epel.repo: Not found in archive
tar: Exiting with failure status due to previous errors
ERROR: Extracting tar failed: /tmp/prepare_scripts/download-requirements.sh-yum-repos-backup-tmp-do-not-remove.tar
```

**How to reproduce**
1. Run `epicli prepare --os centos-7` 
2. Run container with CentOS, for example: `winpty docker run -it --rm -v c:\\github\\epiphany\\core\\src\\epicli://shared centos:7.6.1810`
3. Run `/shared/prepare_scripts/download-requirements.sh /tmp`

**Environment**
- Cloud provider: None
- OS: CentOS 7

**Additional context**
Quotation is missing for pattern in the command:
`tar --extract --verbose --file /tmp/prepare_scripts/download-requirements.sh-yum-repos-backup-tmp-do-not-remove.tar --directory /etc/yum.repos.d --strip-components=2 etc/yum.repos.d/*.repo`

**Comment by przemyslavic** [comment]
Fixed.
Successfully extracted repository backups using CentOS image.
