### ISSUE TITLE
[BUG] [CentOS] epicli fails on task [repository : Create epirepo repository]

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2069]
**Describe the bug**
epicli apply fails with error:

```
Error: Package: libxml2-python-2.9.1-6.el7.5.x86_64 (/libxml2-python-2.9.1-6.el7.5.x86_64)
Requires: libxml2 = 2.9.1-6.el7.5
Installed: libxml2-2.9.1-6.el7_2.3.x86_64 (@anaconda)
```

**How to reproduce**
1. Prepare VM using CentOS-7-x86_64-Minimal-1810.iso
2. Download requirements for offline installation (`epicli prepare --os centos-7`)
3. Run epicli apply (provider: any)

**Expected behavior**
epirepo created.

**Environment**
- Cloud provider: None
- OS: CentOS 7.6

**Additional context**
There is no `libxml2` package in `packages\repo-prereqs` subdirectory.

**Comment by przemyslavic** [comment]
Fixed.
Successfully created epirepo in offline mode using CentOS minimal image.
