### ISSUE TITLE
[UPGRADE] Upgrade of PgBouncer [Kubernetes]

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2076]
**Is your feature request related to a problem? Please describe.**
We need to upgrade PgBouncer if possible and needed to the newer version. This task should be done after we will upgrade PostgreSQL to v13.
This task applies to K8s application

**Describe the solution you'd like**
We want to upgrade if possible and needed to the newer version of PgBouncer.

**Describe alternatives you've considered**
None.

**Additional context**
This task should be done after upgrade of PostgreSQL to v13.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license

**Comment by przemyslavic** [comment]
We are currently using PgBouncer v1.10.
As for now the latest available is v1.15.0.
Need to update OS packages and docker image for application deployment on kubernetes.

**Comment by atsikham** [comment]
Steps:
1. Fix installation (apply) of a new verion(there is Python3 dependency - create a new role to install).
2. Upgrade with taking into account notes [here](https://github.com/epiphany-platform/epiphany/pull/1845#pullrequestreview-531363344).
3. ARM support?

**Comment by plirglo** [comment]
This tasks basically includes two different tasks:
- Upgrade and configuration pgbouncer as a k8s instance
- Upgrade and configuration pgbouncer installed directly on database hosts as standalone application. In this case Python  dependency is needed (blocked by #2334). Created: [#2453](https://github.com/epiphany-platform/epiphany/issues/2453)

This might be good to split this task up to two different ones.

**Comment by plirglo** [comment]
PR #2462

**Comment by przemyslavic** [comment]
:heavy_check_mark: New installations have been tested, as well as the upgrade from v1.12. I've also deployed a sample application on k8s with `psql` and connected/executed test queries via `pgbouncer` to `postgresql` without any problems.
