### ISSUE TITLE
[UPGRADE] Upgrade of PGAudit

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2077]
**Is your feature request related to a problem? Please describe.**
We need to upgrade PGAudit if possible and needed to the newer version. This task should be done after we will upgrade PostgreSQL version (probably to v12).

**Describe the solution you'd like**
We want to upgrade if possible and needed to the newer version of PGAudit.

**Describe alternatives you've considered**
None.

**Additional context**
This task should be done after upgrade of PostgreSQL.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by atsikham** [comment]
This task can be done even before, as PgAudit installation is the smallest one and probably will require only package version change. PgAudit and PostgreSQL versions compatibility should be checked.

**Comment by mkyc** [comment]
Check if that is not in ARM, and then test on Centos if yes.

**Comment by erzetpe** [comment]
This task has been done by: @atsikham. I have tested this and it worked on Red Hat 7.8 and Ubuntu 18.04 on amd64 platform and on CentOS 7.8 on ARM. Code should be reviewed with the changes from @plirglo together with other upgraded PostgreSQL components.

This task should be tested along with: #1861.

**Comment by atsikham** [comment]
PR #2468

**Comment by atsikham** [comment]
Merged to feature/upgrade-postgresql-13 branch, but moved to 'on hold' as waiting for other postgres parts to be merged.

**Comment by przemyslavic** [comment]
:heavy_check_mark: PGAudit 1.5 tested on `RHEL`, `Ubuntu` and `CentOS`, including aarch64 installation.
Logs are stored in the path `/var/log/postgresql/` and visible in Kibana.
New installations and the upgrade from PGAudit 1.2 have been tested.
