### ISSUE TITLE
[FEATURE REQUEST] Update RHEL images in CI pipelines and docs

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2080]
**Is your feature request related to a problem? Please describe.**
Until resolving #1355 Epiphany is limited to support RHEL images on Azure only with versions up to 7.7.
So CI pipelines use quite old images (`RedHat:RHEL:7-RAW:7.7.2019090418`).

There are also references to old images in docs (in OS_PATCHING.md and CLUSTER.MD). 

**Describe the solution you'd like**
1) Update CI pipelines to use RHEL 7.9
2) Update docs to not contain any references to RHEL 7.7 (update to 7.9)

**Describe alternatives you've considered**
n/a

**Additional context**
This will allow to resolve #1776.

NOTE: Switching to `RedHat:RHEL:7lvm-gen2:7.9.2020111205` (or newer) requires OS disk in size of 64 GB or you will get such error:
`Message="The specified disk size 32 GB is smaller than the size of the corresponding disk in the VM image: 64 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size." Target="osDisk.diskSizeGB"`.

Example query to get images for RHEL 7.9:
`az vm image list --publisher RedHat --offer RHEL --all --location westeurope --output table | grep '7\.9' | grep -v byos`

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by rafzei** [comment]
Does this error regarding disk size ( 32 instead of 64 ) appear when disk size is set to 64 and root partition shows still 32?

If we change our docs & pipelines at first - we have to immediately fix the disk size issue because deployments will fail, am I right?

**Comment by to-bar** [comment]
The error will occur when you set for OS disk less than 64GB. Currently the Epiphany default is `disk_size_gb: 32` so this default should be changed in the scope of this task. However, it's possible to overwrite the default - but this has to be done for each component, which is not convenient and error prone.

**Comment by rpudlowski93** [comment]
CI pipelines updated by @przemyslavic, I only updated documentation and checked if RHEL version is the latest one - yes it it. 

RHEL:7-LVM:7.9.2020111202, (kernel 3.10.0-1160.el7.x86_64) - used. 

PR for the task: #2137

**Comment by przemyslavic** [comment]
Updated also `AWS RHEL` image to `RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2`.
