### ISSUE TITLE
[FEATURE REQUEST] Replace Skopeo with Crane

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2081]
**Is your feature request related to a problem? Please describe.**
Currently we use an older version of [Skopeo](https://github.com/containers/skopeo) to download Docker image requirements for our repository. However upgrading to a newer version of Skopeo in #1877 presents the following problems:

1. No support for universal Go binaries anymore. Each OS would need to have each own build version we need to ship instead of the single multi OS binary we use now.
2. With the additional requirement to support ARM in the future we need to be able to download images from ARM based systems. However the ARM support on Skopeo is sketchy and the builds for that are not straight forward.
3. Skopeo does not provide easy to use binaries anymore. Only through the package managers from various OS`s. This however is not ideal on how we need to deliver it to customers.

**Describe the solution you'd like**
Replace Skopeo with a tool called [Crane](https://github.com/google/go-containerregistry) which will work similar.

To get an image:

```bash
./crane pull --insecure docker://jboss/keycloak:9.0.0 "keycloak.tar"
```

To add that image to the repository:

```bash
docker load --input keycloak.tar
```
Instead of creating a new PyPi packages as we did for Skopeo [here](https://github.com/epiphany-platform/skopeo-bin), the easiest approach would be to add the proper binaries from [here](https://github.com/google/go-containerregistry/releases) straight into the repository role. This will simplify the setup.

**Describe alternatives you've considered**
*

**Comment by przemyslavic** [comment]
Looks good. I have successfully deployed 10 clusters with all components turned on.
Tested on `AWS`/`Azure` x `Ubuntu`/`RHEL` x `flannel`/`calico`/`canal`.
