### ISSUE TITLE
[SPIKE] Check possibility of downloading packages for offline installation on different architecture than targeted one

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2082]
**Is your feature request related to a problem? Please describe.**
Right now architecture where we are downloading dependencies for offline installation must match the environment where Epiphany will be installing.

**Describe the solution you'd like**
We need to check if it is possible to download for Ubuntu and Centos/Red Hat packages for offline installation on architecture that is not matching the targeted one.

**Describe alternatives you've considered**
None.

**Additional context**

---

**Comment by mkyc** [comment]
Let's try to go with @to-bar scenario with docker mimicking different architecture. 

Imagined scenario is: "As admin user with my old x86 laptop I need to download stuff now, because tomorrow they will close me offline in server room full of ARM machines and I will need to install Epiphany on them".

**Comment by to-bar** [comment]
Test succeeded ✌🏻
However, downloading was slow.

Run on x86-64 laptop with Windows 10:

```
# Arch test:
$ docker run --platform linux/arm64 --rm arm64v8/centos:7.9.2009 uname --machine
aarch64
```

```
# Download test:
docker run --platform linux/arm64 --rm -it arm64v8/centos:7.9.2009
[root@fe21f03da626 /]# cd root
[root@fe21f03da626 ~]# curl -L -O https://github.com/epiphany-platform/epiphany/archive/refs/heads/ARM.zip
[root@fe21f03da626 ~]# yum -y install unzip
[root@fe21f03da626 ~]# unzip ARM.zip
[root@fe21f03da626 ~]# chmod +x epiphany-ARM/core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
[root@fe21f03da626 ~]# epiphany-ARM/core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh /tmp

# download-requirements.sh finished, execution time: 00h:31m:49s
[root@fe21f03da626 ~]# ls -la /tmp/images/ | wc -l
24
[root@fe21f03da626 ~]# ls -la /tmp/files/ | wc -l
19
[root@fe21f03da626 ~]# ls -la /tmp/packages/ | wc -l
305
```

**Comment by mkyc** [comment]
Nice, add document it after ARM branch is merged. Please synchronise it after #2035.

**Comment by seriva** [comment]
I tested offline installation with downloaded requirements through containers for:

1: Ubuntu 18.04 x86_64
2: RedHat 7.x x86_64
3: CentOS 7.x x86_64
4: CentOS 7.x  arm64

A few additional commands where needed depending on the container used for a specific OS, but generally I did not encounter any issues. 

I documented everything in the attached pull requested but marked it as not supported for now as I feel there might be issues with customer OS installs which might cause this to fail.
