### ISSUE TITLE
[FEATURE REQUEST] Add Crane for ARM architecture

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2086]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architecture but moving forward we also need to support the ARM architecture. We only have Crane for x86_64 architecture so we have add the Crane ARM binary which allows us to  download image requirements on ARM.

**Describe the solution you'd like**
- Add the Crane ARM binary to the repository role.
- Update the requirements-download.sh scripts to automatically chose between the x86_64 and ARM versions of Crane using:

```shell
uname -i
```

**Describe alternatives you've considered**
*

**Additional context**
*

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license

**Comment by przemyslavic** [comment]
Crane v0.4.1 ARM binary can be found under [this](https://github.com/google/go-containerregistry/releases) link.

**Comment by seriva** [comment]
Closing this issue as this is pretty much done in #2099. We only need to add the custom proper [Crane binary](https://github.com/google/go-containerregistry/releases)  in the requirements.txt for ARM.
