### ISSUE TITLE
[FEATURE REQUEST] Add support for alternative file URLs to download-requirements

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2090]
**Is your feature request related to a problem? Please describe.**
The download speed of Ignite binary from current [link](https://archive.apache.org/dist/ignite/2.9.1/apache-ignite-2.9.1-bin.zip) is very slow ~100KB/s,  therefore it takes about an hour just to download a 400MB file.

**Describe the solution you'd like**
Mirrors are available only for the latest version (and alpha):
https://dist.apache.org/repos/dist/release/ignite/

More info: https://infra.apache.org/mirrors.html

Older versions are not mirrored (available at separate archive URL):
https://archive.apache.org/dist/ignite/2.9.0/apache-ignite-2.9.0-bin.zip

We can introduce an improvement such as:
1) For latest version, one can define two links in requirements.txt
- `main` # mirrored (fast)
- `alternative` # archived (slow)
2) Test whether `main` link works
3) If the test succeeds, use `main` link, otherwise use `alternative`

NOTE: Solution should be generic (should work for other Apache provided files as well).

**Additional context**
Official Ignite page: https://ignite.apache.org/download.cgi#binaries
Official link to [Ignite binary:](https://apache.mirrors.tworzy.net//ignite/2.9.1/apache-ignite-2.9.1-bin.zip) with download speed ~3MB/s.

**Alternative solution**
Use deb/rpm packages instead of zip file:
https://ignite.apache.org/docs/latest/installation/deb-rpm

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by seriva** [comment]
Moved back to grooming after this PR discussion here about speed and redundancy for download links:

https://github.com/epiphany-platform/epiphany/pull/2091

**Comment by przemyslavic** [comment]
As commented in [PR](https://github.com/epiphany-platform/epiphany/pull/2091#issuecomment-789538829), the download speed seems to be back to normal now :)

![image](https://user-images.githubusercontent.com/43173646/109777169-b4808600-7c03-11eb-9c2b-639893a900ff.png)

**Comment by rpudlowski93** [comment]
@seriva  Should we close the task? As I can see, the download mirror was changed in the mentioned PR or we want something else here?

**Comment by mkyc** [comment]
PR was not merged but closed, so I assume this task is intended to be changed into something more like "allow multiple download urls".

**Comment by seriva** [comment]
Updated this to reflect the new download-requirements in 2.0. We will not bother implementing this backwards.
