### ISSUE TITLE
[FEATURE REQUEST] [Modules] Check GH Issue Template for with release / issue / feature request checklist

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2092]
See #2022

**Is your feature request related to a problem? Please describe.**
We do not have checklist template to be created for each release in GH. Due to this we miss some important points.

**Describe the solution you'd like**
Discuss and add GH Issue Template with Checklist inside.

**Describe alternatives you've considered**
We also discussed internal Confluence list, but that sounds less visible.

**Additional context**
We released last version with old OS version.

**Comment by seriva** [comment]
No longer valid
