### ISSUE TITLE
[FEATURE REQUEST] Remove the Crane binary from the repo.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2099]
**Is your feature request related to a problem? Please describe.**
Currently the crane binary is stored inside the repository: ```data\common\ansible\playbooks\roles\repository\files\crane```
After some discussion it was decided that the repository is not the best place for binaries, so we want to make it available in a different manner.

**Describe the solution you'd like**
Let the ```download-requirements.sh``` script download it straight from the GitHub release page here:

https://github.com/google/go-containerregistry/releases/

Which version and arch can come from an additional block inside the ```requirements.txt```:

```
[crane]
https://github.com/google/go-containerregistry/releases/download/v0.4.1/go-containerregistry_Linux_x86_64.tar.gz
```

This will also do away with the need to have logic in the requirements.txt later on for which binary to choose for ARM64 as we can already define it in the ```requirements.txt``` for that architecture.

**Describe alternatives you've considered**
Adding the crane binary on inside the container during the docker build: ```/resources/crane/crane_x86_64``` and make  Epicli move it from there to ```/tmp/crane_x86_64```  for Ansible to use it.

**Additional context**
*

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license

**Comment by przemyslavic** [comment]
What has been tested:
✅ `epicli apply` (dev)
✅ `epicli upgrade` (0.6 to dev)
✅ `epicli upgrade` (0.9 to dev)
✅ `epicli upgrade` (dev to dev)

The `repository` role works fine.
