### ISSUE TITLE
[BUG] Java not installed as pre-requisite of opendistro-for-elasticsearch

### ISSUE THREAD

**Issue by ks4225** [epiphany-platform/epiphany#2100]
**Describe the bug**
Using Epiphany 0.9, it looks like opendistro-for-elasticsearch machines are created without any Java runtime.

**How to reproduce**
Any standard cluster build with Epiphany 0.9.

**Expected behavior**
Java is used in some ElasticSearch scripts (e.g. securityadmin.sh). However, on the Epiphany 0.9 clusters we have built, Java is not being installed as a prerequisite of opendistro-for-elasticsearch.

**Config files**
If applicable, add config files to help explain your problem.

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 18.04.4 LTS

**epicli version**: 0.9.0

**Additional context**
I think this commit is the cause: https://github.com/epiphany-platform/epiphany/commit/dd6fded9c884bffddd7853c4cfe9bab8dfbf1f82

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved

**Comment by ks4225** [comment]
I now realise this isn't strictly required as there is a JDK bundled with ElasticSearch. 
We are able to use the bundled JDK when running `securityadmin.sh`

**Comment by rafzei** [comment]
Hello @ks4225,
yes. That's, why we decided to get rid of it. Can I close this issue or there is something more?

**Comment by ks4225** [comment]
Yes, that's fine, I'll close this now.
