### ISSUE TITLE
[FEATURE REQUEST] Add arm64 support to 'monitoring' component

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2117]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
- We want the ability to install the logging component on an arm64 machine running CentOS.
- Only the latest versions we support.
- Any requirements missing or not added in #2033 will be added for the effected roles.
- Will also include all exporters
- filebeat can be skipped at this point.

Effected Ansible roles:
- prometheus
- grafana
- node-exporter
- kafka-exporter
- jmx-exporter
- haproxy-exporter
- postgres-exporter
- download
- firewall

Skip the following Ansible roles for now by using a custom ```feature-mapping``` config:
- filebeat

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Extra info**
Design document and resources:
https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/arm

Terraform scripts for ARM hardware on AWS:
https://github.com/mkyc/aws-arm-simple-setup

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by rpudlowski93** [comment]
Done in the PR: #2207

In scope of the PR, postgres exporter also updated to version 0.9.0 (support ARM)

**Comment by przemyslavic** [comment]
:white_check_mark: The monitoring component has been tested. Prometheus and Grafana were checked. The metrics from the following targets are visible in Prometheus:
- `node-exporter`
- `jmx-kafka`
- `jmx-zookeeper`
- `kafka-exporter`
- `haproxy-exporter`
- `postgres-exporter`
