### ISSUE TITLE
[BUG] Erlang package versions specified in the requirements are missing from the external repository (RedHat/CentOS).

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2121]
**Describe the bug**
Erlang packages in the version specified in the `requirements.txt` file are missing from the RabbitMQ Erlang repository.
It looks like new patches have been uploaded and old packages have been removed.
The script `download-requirements.sh` fails with error `ERROR: repoquery failed: package erlang-23.1.4 not found`.
Older epicli versions are also affected: `ERROR: repoquery failed: package erlang-21.3.8.7 not found`.

**How to reproduce**
1. Deploy any RHEL/CentOS cluster (repository vm is enough to reproduce)

**Expected behavior**
The cluster has been deployed successfully (epirepo has been set up with no issues)

**Environment**
- Cloud provider: [all]
- OS: [RHEL]

**Additional context**
```
[root@a5c2e1ce1548 /]# yum --showduplicates list erlang-21*
Available Packages
erlang.x86_64	21.3.8.14-1.el7	rabbitmq_erlang
erlang.x86_64	21.3.8.15-1.el7	rabbitmq_erlang
erlang.x86_64	21.3.8.16-1.el7	rabbitmq_erlang
erlang.x86_64	21.3.8.18-1.el7	rabbitmq_erlang
erlang.x86_64	21.3.8.21-1.el7	rabbitmq_erlang
```

```
[root@a5c2e1ce1548 /]# yum --showduplicates list erlang-23*
Available Packages
erlang.x86_64	23.1.2-1.el7	rabbitmq_erlang
erlang.x86_64	23.1.5-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.1-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.3-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.4-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.5-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.6-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.7-1.el7	rabbitmq_erlang
erlang.x86_64	23.2.7-2.el7	rabbitmq_erlang
```

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible) :information_source: self-tested at runtime
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by atsikham** [comment]
Discussed this issue with @to-bar and assigned it to him.

**Comment by przemyslavic** [comment]
Packages changed to version `23.1.5`, repository changed to `bintray`.
Tested `epicli apply` and `epicli upgrade`. After the fix it works fine.

**It requires backporting to all previous epicli versions.**
