### ISSUE TITLE
[FEATURE REQUEST] Create CI pipeline for CentOS 7 based deployment

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2125]
**Is your feature request related to a problem? Please describe.**
Epiphany supports CentOS based deployment but the support is not automatically tested.

**Describe the solution you'd like**
Create at least one CI QA pipeline to verify whether it is possible to deploy Epiphany cluster on CentOS.
It will be nice to have pipeline to test upgrades.

**Describe alternatives you've considered**
Testing using local lab.

**Additional context**
There were 3 blocking issues reported recently by external user.
Consult configuration with QA Team

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by przemyslavic** [comment]
The ability to build and test CentOS-based clusters in both Azure and AWS has been added to existing pipelines (`epicli apply` and `epicli upgrade` from 0.9 to dev).
