### ISSUE TITLE
[BUG] [upgrade] Configuration in elasticsearch.yml is overwritten 

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2128]
**Describe the bug**
Settings from /etc/elasticsearch/elasticsearch.yml are overwritten by the defaults during `epicli upgrade`.

**How to reproduce**
1. Deploy Epiphany cluster with logging component enabled.
2. Change the default configuration (for example specification.cluster_name)
3. Run `epicli upgrade`

**Expected behavior**
Custom settings should be preserve after upgrade.

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: develop

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by rpudlowski93** [comment]
Done in the [PR](https://github.com/epiphany-platform/epiphany/pull/1994)

**Comment by przemyslavic** [comment]
✅Fixed in #1844 [PR #1994].
