### ISSUE TITLE
[FEATURE REQUEST] [Upgrade] Add migration from ODFE demo certificates to generated ones

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2129]
**Is your feature request related to a problem? Please describe.**
We should remove demo certificates and replace them with self-generated.

**Describe the solution you'd like**
Using admin certificate is convenient for authentication to API. Installation of ODFE creates demo certificates and one of them is for admin user (kirk). This certificate can be used in `apply` mode but at the end it should be removed  (other certificates to be checked). So it will be not available for `upgrade` mode.

Possible solutions (all assume that at least demo admin cert is removed):
1) Generate self-signed certificates
2) For upgrade mode use only password
3) Allow user to provide their own certificates
4) Mix from 1-3

**Describe alternatives you've considered**
See above.

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by mkyc** [comment]
Passwords approach sounds simplest for now.

**Comment by rpudlowski93** [comment]
Done in PR : https://github.com/epiphany-platform/epiphany/pull/1994

**Comment by przemyslavic** [comment]
Looks like it's partially done. Changes were introduced in #1844 [PR #1994] for `epicli apply` and partially reverted in #2170 [PR #2174] for `epicli upgrade`.
Moving back to TODO to finish this task later or close it after discussion.

**Comment by mkyc** [comment]
@to-bar @przemyslavic shouldn't it go first to 1.1.0 and then be back ported to 1.0.x?

**Comment by to-bar** [comment]
@mkyc Yes, it should. Updated `Releases`.

**Comment by przemyslavic** [comment]
Tested logging component after refactoring:
✔️ `epicli apply`
✔️ `epicli re-apply`
✔️ `epicli upgrade` from v0.7 to develop
✔️ `epicli upgrade` from v0.8 to develop
