### ISSUE TITLE
[Spike] Check possibility of using Elasticsearch Curator with Opendistro for Elasticsearch

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2149]
**Is your feature request related to a problem? Please describe.**

After moving to Opendistro for Elasticsearch, Elasticsearch curator stopped working since there is a different way of authentication.

**Describe the solution you'd like**
Describe configuration of using Elasticsearch Curator with Opendistro

**Additional context**

See [this](https://www.softwarefactory-project.io/moving-to-opendistro-for-elasticsearch.html) article.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license

**Comment by rafzei** [comment]
What I see Index Management for ODFE was created to replace Curator [see](https://github.com/opendistro-for-elasticsearch/index-management/issues/1) or [RFC](https://github.com/opendistro-for-elasticsearch/index-management/issues/1)

So the aim of this spike is to check possibilities to continue using Curator and describe how complex it would be. This will help us compare both solutions later on.

**Comment by erzetpe** [comment]
As Open Distro for Elasticsearch is using basic authentication, we can use this with already implemented in Elasticsearch Curator authentication. On Epiphany side this would require to create proper Open Distro role with access to the given indexes with password authentication. 

Thing to check is probably how to secure passwords stored inside Curator configuration.

More you can find under links below:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#username
https://discuss.opendistrocommunity.dev/t/curator-set-up-with-keys-and-certificates/1368

**Comment by mkyc** [comment]
This should probably also solve #2153

**Comment by erzetpe** [comment]
This task is a spike for the task: [#2423](https://github.com/epiphany-platform/epiphany/issues/2423)
