### ISSUE TITLE
[SPIKE] ILM for OpenSearch

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#2153]
**NOTE: This should be reflected to OpenSearch.**

**Is your feature request related to a problem?**
We don't use ILM for Opendistro Elasticsearch but we still have elasticsearch curator role in our Epiphany code and official elastic documentation says that Elastic Curator and ILM should be compatible with our version of ElasticSearch-OSS 7.x. Right now, for log rotation we use only the plugin: ISM - Index State Management.

**Describe the solution you'd like**
I would like to investigate if we can use elastic curator and ILM as it was before. Using ILM we can manage indices and setup some important policies based on log's size. If we could use it, I would like to create task in order to adjust our code to the current version of our elasticsearch.   

**Describe alternatives you've considered**
If it is possible to use ILM for Opendistro Elasticsearch, I would like to remove elasticsearch curator role from our code.

**Additional context**
Useful information related to ILM and ISM were described in PR 2107
[Information about ISM](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/LOGGING.md
)

---

**DoD checklist**

* [ ] Ability for reader to understand results of spike is key value. 
* [ ] If possible, results of spike should be presented in table to show simply what are compared or researched parameters. Each value / cell should be also described more briefly later. 
* [ ] If possible, spike demo should be automated as much as possible.

**Comment by rpudlowski93** [comment]
@to-bar @plirglo  Could You groom it ?

**Comment by ar3ndt** [comment]
Looks like after moving to opendistro ILM support was skipped. Imo if this is part we supported before and still have partially (curator) then it is worth to check. Theoretically compatibility should be still in place. 
Is curator strictly related to ILM (cause you propose to remove curator)?

**Comment by rpudlowski93** [comment]
As far as I know, but for sure @plirglo is the most oriented person in this topic, we removed curator since there is no longer any possibilities to use it with our new version of Opendistro Elasticsearch and in order to somehow replace the tool, we implemented and support ILM. But I looked at the documentation and it looks that curator should works with our Elasticsearch. ILM doesn't have a few of the capabilities which curator has. 

@plirglo could You comment it? If You are not sure or we don't have any strong reason why we "removed" curator,  we should try to spike the topic and try to implement curator with our Elasticsearch. 

I would suggest to wait for @plirglo or @to-bar and after any information from them, we should close the topic or move it to to-do section.

**Comment by plirglo** [comment]
From my understanding the main problem is that opendistro for elasticsearch use more advanced security configuration than older Elasticsearch. That means Curator is not able to connect until specify configuration and roles will be created. To achieve i believe we need to:
- create solution for use self-signed certificates (#2129)
- create custom role for curator. [here](https://www.softwarefactory-project.io/moving-to-opendistro-for-elasticsearch.html), and [here](https://discuss.opendistrocommunity.dev/t/curator-set-up-with-keys-and-certificates/1368) i found something that could be interesting regarding this topic. Maybe after this curator will start working. There is separate [spike](https://github.com/epiphany-platform/epiphany/issues/2149) for this.

Regarding ILM, officially there is no [support for ILM in Opendistro](https://github.com/opendistro-for-elasticsearch/sample-code/issues/77), opendistro uses [Index Management](https://github.com/opendistro-for-elasticsearch/index-management) instead.

But this is only my understanding, that's why we need this spike - to check these possibilities.

**Comment by to-bar** [comment]
We need to remove old indices based on two combined conditions: size OR age. Even when index is younger than X days but it takes Y bytes it should be deleted.
  
Before securing Elasticsearch this requirement was fulfilled using Curator (run by `cron`).
Haven't checked but It looks like both `Curator` and `Open Distro for Elasticsearch Index Management` can do this job.

I would start with comparing those tools and then make decision which one is better for us. We may need only one of them.

**Comment by plirglo** [comment]
Except what @to-bar mentioned we need to have possibility to rollover index after some amount of time and/or index size.
There is another spike created which is connected to this one, and i believe should be done as a first:  [#2149](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/2149).
Added as dependency.

**Comment by erzetpe** [comment]
ILM implementation should be considered as separate task from implementation of Elasticsearch Curator. Right now configuration of ILM requires much more work than Elasticsearch Curator to achieve similar behavior, so the task #2423 has been created.

**Comment by rafzei** [comment]
@erzetpe I see the above link is wrong - you probably meant #2423 ? 
Are we going to work on ILM implementation?

**Comment by rafzei** [comment]
I believe this can be closed since we already have issues:
 - For implementing ILM: https://github.com/epiphany-platform/epiphany/issues/2441
 - For implementing Curator: https://github.com/epiphany-platform/epiphany/issues/2423

**Comment by to-bar** [comment]
Let's start with spiking use case from [this comment](https://github.com/epiphany-platform/epiphany/issues/2423#issuecomment-932107778). Then we should be able to decide whether just ISM will meet our needs or we need Curator (for Filebeat) and ISM could be used optionally for non-Filebeat indices. From theese 3 solutions (ISM, Curator, ILM) we will probably not implement ILM. I see rather ISM or Curator.

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
