### ISSUE TITLE
[FEATURE REQUEST] CI pipelines: re-run epicli apply to test idempotency

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2167]
**Is your feature request related to a problem? Please describe.**
We do not have a CI pipeline for idempotency testing.

**Describe the solution you'd like**
We need to create a pipeline for idempotency testing by adding a step to the existing pipelines to re-run the `epicli apply` command.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license

**Comment by seriva** [comment]
Clossing after input from @przemyslavic
