### ISSUE TITLE
[FEATURE REQUEST] Remove un-used images, files and packages used only for deprecated Epiphany installations (< 0.7.0)

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2179]
**Is your feature request related to a problem? Please describe.**
Currently we have a number of images, files and possibly packages which are no longer required for installing and upgrading the latest version of Epiphany using Epicli. This increases the installation time and disk requirements for the repository.

**Describe the solution you'd like**
1) Remove all un-used images, packages and files required only for unsupported versions  (< 0.7.0).
2) Add information to docs or changelog that at least cluster in v0.7 is required to run `epicli upgrade` - or add preflight check if possible (there is no easy way to get cluster version).  

**Describe alternatives you've considered**
x

**Additional context**
x

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by atsikham** [comment]
Moved to blocked as ARM branch should be merged first.

**Comment by przemyslavic** [comment]
Successfully deployed clusters with all components enabled:
✔️ `epicli apply:` `Azure`/`AWS` x `Ubuntu`/`RHEL`/`CentOS`
✔️ `epicli apply:` `AWS` x `CentOS` (ARM)
✔️ `epicli upgrade` from v0.7 to develop
