### ISSUE TITLE
[BACKPORT] [0.7] PostgreSQL replication with repmgr: hot_standby not set in config file

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2204]
Backport of #1273  into 0.7 (include into 0.7.4 Release version)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by przemyslavic** [comment]
It looks like one more backport is missing here: #1280 (PR #1845). 
@atsikham please let me know if it should also be backported?

**Comment by przemyslavic** [comment]
Tested after #2317. 
✔️ `epicli apply:` `AWS`/`Azure` x `Ubuntu`/`RHEL`
Looks good 😀
