### ISSUE TITLE
[BUG] Grafana does not show metrics from kafka and haproxy exporters

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#2215]
**Describe the bug**
Grafana does not show metrics from kafka and haproxy exporters. The problem occurs for the standard dashboards such as [Kafka Exporter Overview Dashboard](https://grafana.com/grafana/dashboards/7589). Looks like a problem with Grafana since using Prometheus it is possible to scrape metrics from the mentioned above exporters.

**How to reproduce**
1. execute `epicli init ... `
2. edit config file and add logging, loadbalancer and kafka components
3. execute `epicli apply ...`
4. check grafana dashboard

**Expected behavior**
I would like to check metrics from kafka and haproxy exporters in Grafana dashboards.

**Environment**
- Cloud provider: [AWS | Azure, On-prem]
- OS: all[ARM][AMD]

**epicli version**: 0.10.0

**Additional context**

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
Check if Prometheus targets & Grafana's sources are set properly if so test with other dashboards.

**Comment by rpudlowski93** [comment]
Done in PR #2304

**Comment by przemyslavic** [comment]
Imported `Kafka Exporter Overview` and `HAProxy` dashboards.
After generating traffic (e.g. after running tests), metrics for both exporters were visible.
