### ISSUE TITLE
Add arm64 support for RabbitMQ and Ignite K8s applications

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2225]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
-  RabbitMQ and Ignite K8s application deployments
- Ignite image should be usable as a multi-arch image we need to build ourselves like we did for KeyCloak

Affected Ansible roles:
- applications

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Extra info**
Design document and resources:
https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/arm

Terraform scripts for ARM hardware on AWS:
https://github.com/mkyc/aws-arm-simple-setup

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by przemyslavic** [comment]
✔️ Tested Ignite and RabbitMQ deployments on Kubernetes (CentOS AArch64).
Everything works as expected.

✔️ Updated ARM pipeline to deploy applications (Keycloak, Ignite, RabbitMQ) automatically when executing the pipeline.
