### ISSUE TITLE
[BUG] `filebeat` communication error for AKS

### ISSUE THREAD

**Issue by wkalbar** [epiphany-platform/epiphany#2233]
**Describe the bug**
During installation filebeat get host as hostname, this name isn't added into `/etc/hosts` so after installation filebeat cannot resolve it, so cannot communicate to AKS

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file
3. execute `epicli apply ...`

**Expected behavior**
`filebeat` communicate properly

**Config files**
n/a

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 18.04.5 LTS

**epicli version**: 0.10.0

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Lets start with ensuring documentation that we have kubernetes daemon there.

**Comment by wkalbar** [comment]
After manually added entries into `/etc/hosts` `filebeat` started working fine.

**Comment by przemyslavic** [comment]
For AKS we have Filebeat as a DaemonSet running on Kubernetes. It can be enabled by setting the `k8s_as_cloud_service` flag to `true` in the cluster [configuration file.](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/azure/defaults/configuration/minimal-cluster-config.yml#L12)

**Comment by wkalbar** [comment]
Yes, I know and it was setted that way.

OK, from the begining, steps that was taken:

1. `azbi`
2. `azks`
3. `epicli init`
4. `kubeconfig` file from `azks` copied to epicli build folder
5. `k8s_as_cloud_service` flag changed to `true` (and other settings for cluster configured)
6.  `epicli apply`
Deploy was successfull, but prometheus didn't get connection to AKS - manually added peering between cluster and AKS helped.

Then we noticed, that filebeat don't work wor AKS nodes, mannually added entries into `/etc/hosts` helped

**Comment by mkyc** [comment]
@wkalbar thanks for details, we will investigate it. Looking from AKS nature point of view (changes in machines list due to scale up/down) using `/etc/hosts` doesn't sound like preferred solution. It's good as temporary solution.

**Comment by wkalbar** [comment]
@mkyc little update (and possible solution):
We've dig deeper into this, and problem isn't on epiphany cluster side, but on AKS pods configuration.
There are 2 filebeat pods in namespace `epi-logging` on every node, named `filebeat-filebeat-[5 alphanumeric id here]`, for example `filebeat-filebeat-mnl8p`
This pods during `epicli apply` get hostname of our logging vm, but this hostname is unresolvable for them. We can manually add it to `/etc/hosts` on this pod, but if this pod/node next creation this entry will be deleted.

Solution working for us now is to edit `daemonsets` object (`kubectl -n epi-logging edit daemonset filebeat-filebeat`) and add block:
`     hostAliases:
      - hostnames:
        - prefix-clustername-logging-vm-0
        ip: ip.address.of.logging.vm
`

After this, every new pod created will have in his `/etc/hosts` entry like below:
`
# Entries added by HostAliases.
ip.address.of.logging.vm     prefix-clustername-logging-vm-0
`

Now for this issue it should be added during `epicli apply` in `filebeat` part, or loging vm ip address should be added instead of hostname.

**Comment by wkalbar** [comment]
@mkyc little update (and possible solution):
We've dig deeper into this, and problem isn't on epiphany cluster side, but on AKS pods configuration.
There are 2 filebeat pods in namespace `epi-logging` on every node, named `filebeat-filebeat-[5 alphanumeric id here]`, for example `filebeat-filebeat-mnl8p`
This pods during `epicli apply` get hostname of our logging vm, but this hostname is unresolvable for them. We can manually add it to `/etc/hosts` on this pod, but if this pod/node next creation this entry will be deleted.

Solution working for us now is to edit `daemonsets` object (`kubectl -n epi-logging edit daemonset filebeat-filebeat`) and add block:
```     hostAliases:
      - hostnames:
        - prefix-clustername-logging-vm-0
        ip: ip.address.of.logging.vm
```

After this, every new pod created will have in his `/etc/hosts` entry like below:
```
# Entries added by HostAliases.
ip.address.of.logging.vm     prefix-clustername-logging-vm-0
```

Now for this issue it should be added during `epicli apply` in `filebeat` part, or loging vm ip address should be added instead of hostname.

**Comment by wkalbar** [comment]
@mkyc little update (and possible solution):
We've dig deeper into this, and problem isn't on epiphany cluster side, but on AKS pods configuration.
There are filebeat pods in namespace `epi-logging` , named `filebeat-filebeat-[5 alphanumeric id here]`, for example `filebeat-filebeat-mnl8p`
This pods during `epicli apply` get hostname of our logging vm, but this hostname is unresolvable for them. We can manually add it to `/etc/hosts` on this pod, but if this pod/node next creation this entry will be deleted.

Solution working for us now is to edit `daemonsets` object (`kubectl -n epi-logging edit daemonset filebeat-filebeat`) and add block:
```    hostAliases:
      - hostnames:
        - prefix-clustername-logging-vm-0
        ip: ip.address.of.logging.vm
```

After this, every new pod created will have in his `/etc/hosts` entry like below:
```
# Entries added by HostAliases.
ip.address.of.logging.vm     prefix-clustername-logging-vm-0
```

Now for this issue it should be added during `epicli apply` in `filebeat` part, or loging vm ip address should be added instead of hostname.

**Comment by rafzei** [comment]
@wkalbar Thanks for further investigation. I will move this issue to the to-do section.

**Comment by przemyslavic** [comment]
Logs from AKS are now visible in Kibana:

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/69af9631-e142-40c6-a796-ba7f2a3429eb)

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/4583ea8b-765c-4a4a-a35c-7d8e99353325)

Also works fine after scaling up the cluster:

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/3273e8cd-f066-4a20-a2a7-754fda8c2638)

Additionally checked Grafana and it looks like Prometheus is also able to scrape metrics from AKS nodes.

![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/b9f91cc1-5528-4647-80d3-2515a1679fc1)

✔️ Moving to DoD.

**Comment by plirglo** [comment]
@atsikham Please confirm if we should backport this fix (all supported versions?)

**Comment by mkyc** [comment]
@atsikham please create backport tasks to 0.9.x and 1.0.x.
