### ISSUE TITLE
Create table with implemented / to implement testing scenarios

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2242]
**Describe the solution you'd like**
Create document which includes test scenarios we follow and describe paths which should be tested. 
Make discussions with Team about what is expected.

**Additional context**
Some draft created in Confluence, contact with @plirglo 

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by plirglo** [comment]
Document has been created and it's placed in Confluence. This needs to be discussed with QA firstly.

**Comment by mkyc** [comment]
Please update release type issue template in GitHub.

**Comment by przemyslavic** [comment]
:heavy_check_mark: release template in GitHub and docs in Confluence updated.
