### ISSUE TITLE
[FEATURE REQUEST] Configure Elasticsearch to use static (single) ports instead of ranges

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2243]
**Is your feature request related to a problem? Please describe.**
We use Elasticsearch REST API. To access it we need to know the http port. When it's not configured (by default), it defaults to a range and the node will bind to the first available port in the range. This means that the port can be dynamic, which is more difficult to handle. It's also better to open single port on firewall than a range.

**Describe the solution you'd like**
`http.port` and `transport.port` defined as single values.

**Describe alternatives you've considered**
n/a

**Additional context**
More info: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/modules-network.html#common-network-settings

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested logging component:
:heavy_check_mark: `epicli apply`
:heavy_check_mark: `epicli upgrade` from v0.8 to develop

**Comment by przemyslavic** [comment]
Tested logging component again after refactoring:
✔️ `epicli apply`
✔️ `epicli re-apply`
✔️ `epicli upgrade` from v0.8 to develop
