### ISSUE TITLE
[BUG] [Upgrade] Automated tests fail when run after upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2247]
**Describe the bug**
Automated tests fail after upgrade for the following groups:
- logging
- kibana
- filebeat 

**How to reproduce**
1. Deploy a cluster using `epicli` v0.8.2 with logging component 
2. Run `epicli upgrade` using version 0.10.0. 
3. Run `epicli test`

**Expected behavior**
All tests should pass.

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: 0.10.0

**Additional context**
For versions older than 0.10.0 there is no `admin_password` nor `kibanaserver_password` properties in specification (manifest).

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Successfully upgraded v0.8 cluster to develop.
✔️ `epicli upgrade:` `AWS`/`Azure` x `Ubuntu`/`RHEL`.
✔️ All tests passed.
