### ISSUE TITLE
CI pipelines: offline mode scenario on ARM

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2248]
**Is your feature request related to a problem? Please describe.**
We don't have pipelines for testing offline mode scenario with ARM architecture. 

**Describe the solution you'd like**
We would like to create pipelines in order to test offline mode scenario on ARM architecture using CentOS image and a1.xxx vm sizes.

**Describe alternatives you've considered**
No.

**Additional context**
No.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Added task to enable Vault installation.

**Comment by rpudlowski93** [comment]
Important note ‼️

It was necessary to enable the emulation on build server in order to run container with ARM architecture on AMD host: 

```
sudo apt-get install qemu binfmt-support qemu-user-stati
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```
