### ISSUE TITLE
[FEATURE REQUEST] Allow specifying resource quotas for K8s applications

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2253]
**Is your feature request related to a problem? Please describe.**
After an investigation in #1415 task it became visible that there is no ability to specify resource quotas in Epiphany config for K8s applications. There is still a way to do it manually.

**Describe the solution you'd like**
Allow resource quotas specification in Epiphany config, leave it unlimited by default, update documentation.

**Describe alternatives you've considered**
No.

**Additional context**
No.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
