### ISSUE TITLE
[0.8] [Backport] Upgrade filebeat to 7.9.2

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2260]
- Backport upgrade Filebeat into v 0.8

- Upgrade was done in PR #1793

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
This is new functionality so we are not back porting it.
