### ISSUE TITLE
[BUG] Error while downloading reports to PDF/PNG using Kibana UI

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#2261]
**Describe the bug**
I can't download reports from dashboards or visualisation to PDF/PNG using Kibana UI. I'm getting the following error: "Download error, There was an error generating this report."  Under the hood, there error appears with "{statusCode: 404, error: "Not Found", message: "Not Found"}"

More details related to the error:
`opendistroReportsKibana.plugin.js:1 POST http://VM_IP:5601/app/api/reporting/generateReport?timezone=Europe/Warsaw 404 (Not Found)`

Request header which is generated automatically to API: 
```
POST /app/api/reporting/generateReport?timezone=Europe/Warsaw HTTP/1.1
Host: VM_IP:5601
Connection: keep-alive
Content-Length: 140021
pragma: no-cache
accept: */*
accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6
kbn-version: 7.10.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/MY_IP Safari/537.36
Content-Type: application/json
Origin: http://VM_IP:5601
Referer: http://VM_IP:5601/app/visualize/
Accept-Encoding: gzip, deflate
Cookie: security_authentication=....
```

**Steps to reproduce the behavior:**

1. Create cluster using epicli
2. OpendistroReportsKibana installed by default
3. Login to Kibana UI
4. Discover some logs, visualize it and try to download report to PDF or PNG

**Environment**

Cloud provider: AWS
OS: RHEL 7.9
Kibana reports plugin version: 1.13.2

**Additional context**
Everything else is working fine, it is possible for example to inspect visualization and generate CSV file. 

I already reported the problem as a bug to official repository of kibana reports plugin and I would suggest to follow the task and wait : [link](https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/365)

**Comment by seriva** [comment]
Closing as we are moving to OpenSearch.
