### ISSUE TITLE
[BUG] [Ubuntu] elasticsearch-curator in version 5.8.3 is not available from APT repo

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2262]
**Describe the bug**
Epicli installation fails while downloading requirements as the `elasticsearch-curator` package in version 5.8.3 is no longer available in the Curator APT repository.

**How to reproduce**
1. execute `epicli apply` (repository vm is enough)

**Expected behavior**
Repository has been set up properly.

**Config files**

**Environment**
- OS: [Ubuntu]

**epicli version**: [`epicli --version`]
All epicli versions affected

**Additional context**
```
root@ip-10-1-11-41:~# apt-cache policy elasticsearch-curator
elasticsearch-curator:
  Installed: (none)
  Candidate: 5.8.4
  Version table:
     5.8.4 500
        500 https://packages.elastic.co/curator/5/debian stable/main amd64 Packages
     5.2.0-1 500
        500 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: `epicli apply`: `AWS`/`Azure` x `Ubuntu`/`RHEL`/`CentOS` with `elasticsearch-curator` enabled in feature-mapping.

**Comment by to-bar** [comment]
:heavy_check_mark: `epicli upgrade`: `AWS`/`RHEL` on `v0.8.2` cluster with `elasticsearch_curator` added to inventory and manually installed older version of Curator (`5.8.1`) before running the upgrade.
