### ISSUE TITLE
[BUG] Changing variable `expiration_days` in yml file is ignored

### ISSUE THREAD

**Issue by wkalbar** [epiphany-platform/epiphany#2270]
**Describe the bug**
Changing this variable have no effect, after deployment certificate expiration date will be 365 days

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file, change `expiration_days` to any value different than 365
3. execute `epicli apply ...`
4. check expiration date of k8s certificate

**Expected behavior**
k8s certificate expiration date set to value of `expiration_days` variable

**Config files**
n/a

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 18.04.5

**epicli version**: 0.10.0

**Additional context**
n/a

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
Hello @wkalbar, please attach used configuration and verification commands. Did you set `renew: true` according to the [doc](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/CERTIFICATES.md)?

**Comment by wkalbar** [comment]
Sorry, my stupid mistake. Of course I didn't set it, as of course I didn't RTFM...
