### ISSUE TITLE
[FEATURE REQUEST] Change versioning from 0.10.x to 1.0.0 and 0.11.x to 1.1.x.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2277]
**Is your feature request related to a problem? Please describe.**
Currently for Epiphany we don't use Major.Minor.Patch versioning but more something like Minor.Patch. 

**Describe the solution you'd like**
We want to start using Major.Minor.Patch release versioning from 0.10.x, which will become 1.0.x. The following things need to be done:

* [x] Create new 1.0 branch from v0.10 branch - @seriva 
* [x] Fix changelogs: @plirglo / @rafzei 
  CHANGELOG-0.10.md - add clear "discontinuation" info (develop/v0.10 branches)
  CHANGELOG-1.0.md - add
  CHANGELOG-0.11.md -> CHANGELOG-1.1.md (develop branch)
* [x] Change CHANGELOG-0.xx.md entries from 0.11.x to 1.1.x (develop/v0.10(v1.0) branches) @plirglo / @rafzei 
* [x] Add entries in CHANGELOG-1.0.md and CHANGELOG-1.1.md @plirglo / @rafzei 
* [x] Change all 0.10.x and reference in the documentation to 1.0.x  (develop/v1.0 branches) @plirglo / @rafzei 
* [x] Change cli/version.txt.py from 0.10.0 to 1.0.0 (v1.0) branch) @plirglo / @rafzei 
* [x] Change cli/version.txt.py from 0.11.0 to 1.1.0 (develop branch) @plirglo / @rafzei 
* [x] Update build pipelines to point to the proper branches @przemyslavic 
* [x] #2272 @atsikham / @rpudlowski93 
* [x] #2259 @to-bar
* [x] Release 1.0.0 with integration of this fixes: #2272, #2259 @przemyslavic 
* [x] Release a new 1.1.0alpha1 from develop for APM @seriva 
* [x] Change releases to reflect v1.0.0 and v 1.1.0 on ZenHub @mkyc 
* [x]  Communicate to users the version change @mkyc 

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
I have list of people to send communication to after we release.
