### ISSUE TITLE
[FEATURE REQUEST] Allow to preserve OS images when run 'epicli apply' for existing cluster

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2288]
**Is your feature request related to a problem? Please describe.**
When we release version with updated default OS image and run it for existing cluster deployed with older image, Terraform will detect the difference and may destroy existing VMs.

For AWS, it fails:
```
14:14:44 ERROR cli.engine.terraform.TerraformCommand - Error: error deleting Autoscaling Launch Configuration (aws-rhel-infra-test-repository-launch-config): ResourceInUse: Cannot delete launch configuration aws-rhel-infra-test-repository-launch-config because it is attached to AutoScalingGroup aws-rhel-infra-test-repository-asg-0
14:14:44 INFO cli.engine.terraform.TerraformCommand -   status code: 400, request id: 1c892f6e-2abb-4eba-ba05-134bbe27e6fd
```

For Azure, it did nothing (no failure) after changing from `7-RAW/7.6.2018103108` to `7-RAW/7.7.2019090418` but failed after changing from `7-RAW/7.6.2018103108` to `7-LVM/7.9.2020111202`:

```
14:48:58 ERROR cli.engine.terraform.TerraformCommand - Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ConflictingUserInput" Message="Disk az-infra-test-repository-vm-0-os-disk already exists in resource group AZ-INFRA-TEST-RG. Only CreateOption.Attach is supported." Target="/subscriptions/XXX/resourceGroups/az-infra-test-rg/providers/Microsoft.Compute/disks/az-infra-test-repository-vm-0-os-disk"
```
 
Because we have:
`delete_os_disk_on_termination = "false"`
the OS disk was not removed.

We want to have a setting or mode to avoid such errors without modifying infrastructure when only OS image was changed.

**Describe the solution you'd like**
Implement a mechanism to use the current OS images in case of fresh deployment, in case of upgrade between minor/path versions user will stay with the initial ones.

**Describe alternatives you've considered**
n/a

**Additional context**
Special requirements for LTS versions (`apply` after `upgrade`).

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested:
✅ `apply` v0.9 -> `upgrade` to dev -> `apply` dev
✅  `apply` dev -> `apply` dev

I checked different values for `default_os_image` parameter:
- `ubuntu-18.04-x86_64`

- `redhat-7-x86_64`

- `centos-7-x86_64`

- `centos-7-arm64`

- `default`

also with changed default specification:
```yaml
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: default
specification:
  os_full_name: RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2
```
both for `Azure` and `AWS`.
