### ISSUE TITLE
[FEATURE REQUEST] Update Python dependencies to solve some of the security alerts.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2297]
**Is your feature request related to a problem? Please describe.**
We currently have a few outstanding [security issues](https://github.com/epiphany-platform/epiphany/security) regarding first and second layer Python dependencies:

![image](https://user-images.githubusercontent.com/11056665/117301617-1915c680-ae7b-11eb-90f7-403a12f4fb95.png)

**Describe the solution you'd like**
We would like to update the first layer dependencies and see if we can resolve some of these security issues. More information on how to update the first layer dependencies can be found [here](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/.devcontainer/requirements.md).

Looking at the attached [dependency.txt](https://github.com/epiphany-platform/epiphany/files/6435250/dependency.txt) we should be able to update the following:
1: jinja2 from 2.11.2 to 2.11.3 as its a direct dependency
2: azure-cli as urllib3 is a requirement and needs >=1.21.1,<1.27 and needs to be bumped from 1.26.2 to 1.26.4
3:  azure-cli and or ansible as cryptography is a requirement and needs >= 3.2 if possible. 

This should also include:
- Update of the [licenses.py](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/cli/licenses.py)
- Update of the [COMPONENTS.md](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/COMPONENTS.md#epicli-python-dependencies)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Successfully deployed clusters with all components enabled.
✔️ `epicli apply:` `Azure`/`AWS` x `RHEL`/`Ubuntu`
