### ISSUE TITLE
[Spike] Persistent volume shared between clusters

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2300]
**Describe the solution you'd like**
Check possibility of using persistent volume replicated between clusters. Replica has only read access. Both are accessible from two clusters and have the same state of data.

This probably might be done with Rook Ceph, but check also other possibilities.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by olek-work** [comment]
Few details about the use case:

The system has two parts: _trusted_ and _untrusted_.
_Trusted_ part is highly protected, i.e. it **forbids** "outside world" to change its data (including _untrusted_ part) and allows only selected users to connect to it from selected machines (adequately protected).
_Untrusted_ part has been added to allow wider audience of users from less secured machines to have view of the data from _trusted_ part.

**Idea**
Two clusters have their persistent volume replicated from _trusted_ to _untrusted_, with _untrusted_ side being "read-only" (to avoid merge conflicts).

**Motive behind the idea** 
Delegate replication of the data from each app/database to infrastructure with single mechanism.

![Persistent volume replication](https://user-images.githubusercontent.com/79196968/117410880-41510400-af13-11eb-842a-e02058fa3c16.png)

**Comment by olek-work** [comment]
I've looked into [MinIO's replication](https://blog.min.io/active-active-replication/) and just wanted to share with you that it looks promising. Tested it with a quick Docker setup (see setup details below) and so far there seem to be no red flags from our usecase perspective.

> Note: I haven't looked into configuring Kubernetes persistent storage using MinIO yet.

# Docker setup to test MinIO replication
Create source-minio and dest-minio servers
```
docker network create minio
docker run --rm -p 9000:9000 --net minio --name source-minio minio/minio server /data{1..4}
docker run --rm -p 9001:9000 --net minio --name dest-minio minio/minio server /data{1..4}
```
Start console: mc (MinIO Console)
```
docker run --rm -it --entrypoint=/bin/sh --net minio minio/mc
```

From console:
- create aliases
```
mc alias set source-minio http://source-minio:9000 minioadmin minioadmin
mc alias set dest-minio http://dest-minio:9000 minioadmin minioadmin
```
- create buckets (with versioning enabled)
```
mc mb source-minio/bucket-1
mc mb dest-minio/bucket-1
mc version enable source-minio/bucket-1
mc version enable dest-minio/bucket-1
```
- set up replication
```
mc admin bucket remote add source-minio/bucket-1 http://minioadmin:minioadmin@dest-minio:9000/bucket-1 --service "replication"
// use genereted arn in next command
mc replicate add source-minio/bucket-1 --remote-bucket bucket-1 --priority 1 --arn arn:minio:replication::<GENERATED ARN>:bucket-1 --replicate "delete,delete-marker"
```

From [source-minio web UI](http://localhost:9000) uploaded, changed and deleted file to `bucket-1` all of which got propagated to [dest-minio web UI](http://localhost:9001).

**Comment by mkyc** [comment]
My current plan for this spike is: 

1. Since we already [reviewed](https://github.com/epiphany-platform/epiphany/issues/1449) [Rook](https://github.com/epiphany-platform/epiphany/issues/1450) [with](https://github.com/epiphany-platform/epiphany/issues/1451) [Ceph](https://github.com/epiphany-platform/epiphany/issues/1453) I will refresh this research and I will also check cluster replication. Entrypoint resources are [Ceph mirroring document](https://docs.ceph.com/en/latest/rbd/rbd-mirroring/) and [Rook mirroring document](https://github.com/rook/rook/blob/master/Documentation/ceph-rbd-mirror-crd.md). 
2. Since there is possible problem with Ceph replication direction (pull model) it's worth to also consider MinIO. I already checked that there is [CSI Driver](https://github.com/minio/direct-csi) so it might be able to cover our needs. 

Solutions need to be compared.
