### ISSUE TITLE
[Spike] Redundant network interfaces

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2309]
- Connecting Epiphany with redundant network interfaces (possible solution: network bonding/teaming, whole cluster still sees it as single network interface) 

Request comes from [olek-work](https://github.com/olek-work) user.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
Bonding or network bonding is also called port trunking or link aggregation which simply means combining several network interfaces into one link, providing either high-availability, load-balancing, maximum throughput, or a combination of these. 
Bonded NIC is a virtual interface that 'bond' physical interfaces.


Before creating a bond interface, you need to ensure that the kernel module `bonding` is present, and loaded at boot time.
Creating a bonded interface is quite easy, to do so you have to create a new network interface.
Bonded NIC can be used like any other normal NIC and it is configured using static network information.
Bondings are highly configurable. All bonding options are listed here: https://wiki.linuxfoundation.org/networking/bonding#bonding_driver_options

How to bond interfaces on Ubuntu: https://help.ubuntu.com/community/UbuntuBonding

How to bond interfaces on RHEL/CentOS7: https://devopsconsultant.wordpress.com/2016/09/02/nic-bonding-netwokrk-ha-channel-bonding-achieving-higher-data-rates/

Simple test scenario (let's assume we already have configured and worked two NIC's: eth0 & eth1):
1. Create bonded interface (eg. bond0)
2. Edit configuration of physical interfaces
2a. Verify configuration (cat /proc/net/bonding/bond0)
3. Ping to bond0 interface
4. Put down eth0 or eth1
5. Ping again bond0
5a. Verify configuration (cat /proc/net/bonding/bond0)

In the case of container networking, there is a CNI plugin to provide bonded interfaces inside a pod: https://github.com/intel/bond-cni which is working well with other CNI plugins like [Multus](https://github.com/k8snetworkplumbingwg/multus-cni). 
Multus add a possibility to attach multiple network interfaces to pods.


In the case of implementation in Epiphany, we would need to give users the possibility to bond interface on every VM. Hence I would see an option to add it as a new role and optionally assign it to specific components.
For non-clastered components, this shouldn't be tricky, but for clustered or HA additional steps may be needed.
