### ISSUE TITLE
[Backport][0.9.3] Filebeat communication error for AKS

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2342]
Backport task #2233 PR #2276

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
✔️ Fixed. Logs from AKS are now visible in Kibana:
![image.png](https://images.zenhubusercontent.com/5efee1bcbc19f75eaba5ce61/833805c1-ce7c-455b-8a40-625966b4c6a8)
