### ISSUE TITLE
[PostgreSQL] Allow more than 2 nodes installation with Repmgr

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2346]
Consider to provide more than two postgres nodes in HA configuration. Currently we support only 2. More nodes may give users possibility to create more redundant configuration and possibilities handle higher traffic.

_Originally posted by @plirglo in https://github.com/epiphany-platform/epiphany/pull/2330#discussion_r638756954_

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
Merged to feature/upgrade-postgresql-13 branch, but moved to 'on hold' as waiting for other postgres parts to be merged.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested with 3 PostgreSQL nodes (1 master and 2 ready-only replicas). The cluster was working fine (tested on sample data). Additionally, a switchover was performed. No problems found.

**Comment by mkyc** [comment]
It will be back ported with Postgres 13 task.
