### ISSUE TITLE
[FEATURE REQUEST] Add option to skip downloading Docker images and creating local registry 

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2348]
**Is your feature request related to a problem? Please describe.**
Downloading Docker images (in upgrade mode) takes about 4 min.
Running `image_registry` role takes about 9 min.

When a cluster without k8s is needed (often for development purposes),  about 13 minutes is wasted since Docker images are not needed.

**Describe the solution you'd like**
Add `download_strategy` setting to `epicli`. By default it could have `smart` (or `selective`) value - to download only requirements for enabled/used components. The alternative value would be `full` (or `everything`).

This will require adding option(s) to the download_requirements.sh scripts as well.

This task is about implementing such option just for images (most time consuming) but later it would be nice to extend it for other components (roles).

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
