### ISSUE TITLE
Add Molecule to devcontainer

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2349]
At the moment we have Ansible Molecule tests for PostgreSQL, but no any configuration was done to execute it in devcontainer. As docker backend is used here, it should be investigated how to run those tests.

`Also would be cool if we can run these tests from the container and not only externally.`

_Originally posted by @seriva in https://github.com/epiphany-platform/epiphany/pull/2330#discussion_r638799166_

Things to do:
1) Add Docker to devcontainer
 Steps from https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker#enabling-root-user-access-to-docker-in-the-container (tested only on Windows)
2) Add molecule and ansible-lint
https://molecule.readthedocs.io/en/latest/installation.html
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/postgresql/molecule/README.md
3) Check if we can avoid `sudo su -` before running molecule tests.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Not adding this anymore
