### ISSUE TITLE
[BUG] [Upgrade] epicli may fail after re-running

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2360]
**Describe the bug**
When `epicli upgrade` fails (e.g. after network issue) and it's re-run, you can get `Directory /var/www/html/epirepo/packages must exist` error like below:

```
FAILED! => {"changed": true, "cmd": "set -o pipefail && /tmp/epi-repository-setup-scripts/create-repository.sh /var/www/html/epirepo false |& tee /tmp/epi-repository-setup-scripts/create-repository.log", "delta": "0:00:00.403076", "end": "2021-05-31 15:21:51.253095", "msg": "non-zero return code", "rc": 1, "start": "2021-05-31 15:21:50.850019", "stderr": "", "stderr_lines": [], "stdout": "Loaded plugins: amazon-id, search-disabled-repos, versionlock\nPackage httpd-2.4.6-97.el7_9.x86_64 already installed and latest version\nPackage createrepo-0.9.9-28.el7.noarch already installed and latest version\nPackage yum-utils-1.1.31-54.el7_8.noarch already installed and latest version\nNothing to do\nDirectory /var/www/html/epirepo/packages must exist", "stdout_lines": ["Loaded plugins: amazon-id, search-disabled-repos, versionlock", "Package httpd-2.4.6-97.el7_9.x86_64 already installed and latest version", "Package createrepo-0.9.9-28.el7.noarch already installed and latest version", "Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version", "Nothing to do", "Directory /var/www/html/epirepo/packages must exist"]}
```

**How to reproduce**
1. Run `epicli upgrade`
2. Fail after all requirements are downloaded (flag file must already exists: /tmp/epi-download-requirements/download-requirements-done.flag)
3. Run `epicli upgrade` again without waiting (since there is default: `download_done_flag_expire_minutes: 120`)

**Expected behavior**
No failure.

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: 0.10.0, 1.0.0 and develop branch (1.1.0)

**Additional context**
Issue introduced with PR #2162.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested:
:heavy_check_mark: `epicli apply` -> `epicli upgrade` -> force stop `epicli upgrade` -> re-run `epicli upgrade` -> success 👍
