### ISSUE TITLE
[BUG] Failed to fetch Grafana repo on downloading requirements

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2361]
**Describe the bug**
From time to time you may get such an error (result of `apt update` called by `roles\repository\files\download-requirements\ubuntu-18.04\add-repositories.sh`):
```
E: Failed to fetch https://packages.grafana.com/oss/deb/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (22262 != 22243). Mirror sync in progress? [IP: 199.232.66.217 443]
   Hashes of expected file:
    - Filesize:22243 [weak]
    - SHA512:79a1802f007db601ff133cd93779ab10e739952db3a7ed1aaf6c853b577a51275ee08ce35fd497fa756db6f9b834d0f080402f0cc7928d9306f41e91e48f5d15
    - SHA256:ead555f7a43091dd81ce2e91b17cac78c1c748a0790713f1ad2406853025192d
    - SHA1:6722098bfacad840ae211bddb4f3975f24a6bcc8 [weak]
    - MD5Sum:217027fca4e16f5a174c12526a31af02 [weak]
    - Release file created at: Wed, 19 May 2021 13:39:14 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

After this occurs, every re-run fails. To fix such state and make re-running successful, the `apt-get clean` command has to be run on the `repository` host.

**How to reproduce**
Issue is non-deterministic (occurs from time to time).

1. Run epicli apply or upgrade many times

**Expected behavior**
No failure on re-run.

**Environment**
- Cloud provider: All
- OS: Ubuntu 18.04

**epicli version**: All

**Additional context**
None.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by seriva** [comment]
Can be closed as this is solved with: https://github.com/epiphany-platform/epiphany/pull/2475/files where Grafana is downloaded from file.
