### ISSUE TITLE
Update Python dependencies to solve more of the security alerts.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2362]
**Is your feature request related to a problem? Please describe.**
We have a bunch of new security issues regarding Python dependencies:

![image](https://user-images.githubusercontent.com/11056665/120479425-3bcdc900-c3ae-11eb-8e2f-0fe5058fd55b.png)

**Describe the solution you'd like**
Update the dependencies to resolve any issues.

**Additional context**
We should resolve these before BDS scan.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Multiple clusters have been successfully deployed with all components enabled.
✔️ `epicli apply:` `Azure`/`AWS` x `RHEL`/`Ubuntu`
