### ISSUE TITLE
[FEATURE REQUEST] Check possibility of blocking direct connections to postgres when HA enabled

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2364]
**Is your feature request related to a problem? Please describe.**
Some customers met with problem of wrong configured services (created by they own) connecting directly to database not through pgbouncer / pgpool. This can cause split braining problems.

**Describe the solution you'd like**
Implement switch to enable / disable direct connections to database

**Describe alternatives you've considered**
Use different ports depend on configuration.

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
