### ISSUE TITLE
Update documentation about scaling up/down HAProxy, monitoring & repository

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2368]
**Describe the solution you'd like**
We should update documentation about scaling up/down HAProxy, monitoring & repository

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
A documentation update is required by more than mentioned components in the context of scaling up/down so I've created a new issue.. https://github.com/epiphany-platform/epiphany/issues/2396
