### ISSUE TITLE
[FEATURE REQUEST] Document air gapped installation

### ISSUE THREAD

**Issue by shakeel** [epiphany-platform/epiphany#2370]
On-premise air gapped installation without internet access requires creating tar balls with the Kubernetes application deployed and available in a local Docker or Container registry.

Various teams have created their own ad-hoc solutions to package tar balls and create Docker registries. 

The Epiphany CLI installation configures tar images in [image-registry.yml](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/defaults/configuration/image-registry.yml) and is available for air gapped installations.

Teams should use the above image-registry to package the Kubernetes application, however teams need documentation on how to modify it and test it.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
@shakeel thanks for filling this issue! 

Just note that we do not only have to document it, but we also have to prepare packaging logic for teams using our registry to provide application images.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
