### ISSUE TITLE
[BUG] download-requirements --no-logfile skipped on Ubuntu

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2378]
**Describe the bug**
In repository role in download-requirements.sh file we hardcoded:
```
shell: >-
    set -o pipefail && /tmp/epi-download-requirements/download-requirements.sh /var/www/html/epirepo --no-logfile |&
    tee >(systemd-cat --identifier=download-requirements.sh)
```
--no-logfile so we expect no output from shell command written on disk.

It works for Centos/Rhel but not on Ubuntu. It's not implemented properly:

```
logfile="${script_path}/log"
...
echol() {
	echo -e "$1" | tee --append "$logfile"
}
```

**How to reproduce**
Execute epicli apply on configuration manifest with repository count:1

**Expected behavior**
Log shouldn't be written.

**Config files**
None

**Environment**
- Cloud provider: [All]
- OS: [Ubuntu ]

**epicli version**: [1.1.0]

**Additional context**
None

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Closing as this should not effect the new download requirements. Not something we will fix for older versions anymore.
