### ISSUE TITLE
[Backport] [1.0.x] Add migration from ODFE demo certificates to generated ones

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2379]
We need to backport #2129.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
✔️ `epicli apply` - Ubuntu / RHEL / CentOS
✔️ `epicli` re-`apply` - Ubuntu / RHEL / CentOS
✔️ `epicli upgrade` from v0.8.3 - Ubuntu / RHEL
✔️ `epicli upgrade` from v0.9.2 - Ubuntu / RHEL / CentOS
Tested on a cluster with 3 logging vms (clustered) and 1 opendistro vm (as a separate component).
