### ISSUE TITLE
[FEATURE REQUEST] Document troubleshooting during failed epicli run

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2388]
**Is your feature request related to a problem? Please describe.**
We do not have any mechanism and even documented steps on how to handle situations where `epicli apply` fails during download-requirements script execution. Because download-requirements scripts base on external repositories it's highly exposed to failure. 

**Describe the solution you'd like**
Document steps on how to restore system repositories in case epicli fail during download-requirements script execution.

**Describe alternatives you've considered**
None

**Additional context**
As described in issue #2324  we do not have a mechanism to automatically restore(enable) system repositories in case of epicli fail.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
Please describe the whole procedure (the steps to successfully execute epicli apply again in case of failure).
