### ISSUE TITLE
[FEATURE REQUEST] Restart CoreDNS pods conditionally

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2397]
**Is your feature request related to a problem? Please describe.**
There is no need to restart CoreDNS on each `epicli` run unless cluster hosts have been changed. This is follow-up task to changes done in PR #2394.

**Describe the solution you'd like**
Restart CoreDNS only when needed.

**Describe alternatives you've considered**
Test newer version of CoreDNS to check whether it solves issue #2345.

**Additional context**
Code already prepared by @to-bar. 

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
✔️ Verified pgpool status and connection to PostgreSQL nodes after scaling up PostgreSQL component from 1 to 2 nodes.
CoreDNS pods are restarted  conditionally, depending on changes to `/etc/hosts` and CoreDNS patching.
