### ISSUE TITLE
Upstream monitoring

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#24]
Research and support different third party monitoring components as an upstream for Epiphany Platform.

**Comment by mmakow** [comment]
Current (initial) scope: push data from Prometheus to upstream Prometheus. 

Other tools will be added if needed. Requires discussions with @patrick-ryan1 and applications (starting with APM)

**Comment by toszo** [comment]
For the step 1 - federation of Prometheus - only documentation changes was applied. 
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/HOWTO.md#how-to-configure-scalable-prometheus-setup
