### ISSUE TITLE
[BUG] [Upgrade] [Filebeat] All settings for multiline feature are lost after upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2406]
**Describe the bug**
In Filebeat config file there are settings related to the multiline feature.

They are configurable via properties:
- specification.common_input.multiline
- specification.postgresql_input.multiline
- specification.container_input.multiline

The properties are not defined in upgrade mode and they are removed from config file during upgrade.

The difference can be seen running this command:
`diff /etc/filebeat/filebeat.yml.bak_7.9.2 /etc/filebeat/filebeat.yml`

**How to reproduce**
1. Deploy cluster using epicli v0.8.3.
2. Upgrade the cluster using epicli v1.1.0rc1
3. Compare Filebeat config file - current vs backed up

**Expected behavior**
Multiline settings preserved.

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: 1.1.0rc1 and develop

**Additional context**
The bug was found by automated tests (PostgreSQL with enabled pgAudit).

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Filebeat support for multi-line messages has been tested after cluster upgrade.
✔️ upgrade from v0.8 to v1.1
✔️ upgrade from v0.9 to v1.1
✔️ upgrade from v1.0 to v1.1
