### ISSUE TITLE
[Backport] [v1.0] CoreDNS requires restart after scaling up nodes to be able to resolve new hostnames

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2415]
Backport fix for #2345 to v1.0.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
:heavy_check_mark:  Tested automatically in the pipeline by scaling up PostgreSQL from 1 to 2 nodes with pgpool deployment enabled. Pgpool is able to connect to both nodes without any problems and shows the correct status of PostgreSQL nodes (including the new one).
