### ISSUE TITLE
[Backport] [v1.0] [Upgrade] [Filebeat] All settings for multiline feature are lost after upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2416]
Backport fix for #2406 to v1.0.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
Filebeat support for multi-line messages has been tested after cluster upgrade (checked filebeat configuration file on vms and additionally executed tests for PostgreSQL to test multiline logs from PostgreSQL in elasticsearch).
✔️ upgrade from v0.8.3 to v1.0.1
