### ISSUE TITLE
[SPIKE] Research support for additional Istio components and configurations.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2418]
**Is your feature request related to a problem? Please describe.**
Currently we install Istio only with the basic profiles as described here:

https://istio.io/latest/docs/setup/additional-setup/config-profiles/

**Describe the solution you'd like**
While the above profiles are good for basic usage, real word usage often involves specific configuration of the Istio control plane components. This spike should document what is required by teams and what what things we should support:

**Describe alternatives you've considered**
-

**Additional context**
More information here:
https://istio.io/latest/docs/setup/additional-setup/customize-installation/

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by erzetpe** [comment]
Closing because of deprecation of Istio component.
