### ISSUE TITLE
[BUG] Grafana - Changing password from epicli does not work

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2420]
**Describe the bug**
Changing grafana password from epicli does not work. Still have old password configured by first epicli run

**How to reproduce**
1. Build cluster with some basic Grafana config
2. Edit config file changing Grafana password
3. Re-run `epicli apply`

**Expected behavior**
Grafana password should be changed

**Environment**
- Cloud provider: All
- OS: Tested on Ubuntu

**epicli version**: 1.0.0

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by sbbroot** [comment]
Since we do not officially support loading variables from both config file and default file at the same time during the upgrade mode, this part will not be added.
