### ISSUE TITLE
[SPIKE] Check if it is possible to use backup and restore feature with new Epiphany version

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2431]
**Is your feature request related to a problem? Please describe.**
In version 0.7 we have introduced backup/restore feature and we need confirmation that it works fully as expected with newer Epiphany versions.

**Describe the solution you'd like**
We want to confirm that backup/restore still works for the version 1.0 and newer of Epiphany and create a list of features that are currently being backed up properly and which need to be fixed.

**Describe alternatives you've considered**
None.

**Additional context**

Previously mentioned components were backed up:
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/BACKUP.md#4-how-backup-and-recovery-work

---

**DoD checklist**

* [x] Ability for reader to understand results of spike is key value. 
* [x] If possible, results of spike should be presented in table to show simply what are compared or researched parameters. Each value / cell should be also described more briefly later. 
* [ ] If possible, spike demo should be automated as much as possible. 
* [x] design doc updated

**Comment by mkyc** [comment]
For each component we need to check that both data and configuration is restored after backup.

**Comment by erzetpe** [comment]
### Conclusion:

Backup and restore works only on the same environment. The main goal was to provide backup/restore on already deployed environments
for example as an option before performing upgrade. This can be used to fix issues on existing environments with the same setup (IPs, and so on).

Procedures for backup and restore were taken from our documentation:
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/BACKUP.md

Given procedure work as described in the documentation (restore of K8s hasn't been tested), but the scope and the way how they are performed should be discussed.
We will need to implement additional automation or update our documentation (with some scripts?) to use existing backup/restore solution.

For Kubernetes also previously considered in Epiphany velero seems to be an interesting option.
https://github.com/vmware-tanzu/velero

### Test Results:

Backups for all components are by default stored on each machine and on repository host in location /epibackup/mounted.

List of generated files on repository-machine:

root@repository-machine:/epibackup/mounted# tree
.
├── grafana_data_20210716-052323.tar.gz
├── grafana_data_20210716-052323.tar.gz.sha1
├── haproxy_etc_20210715-142306.tar.gz
├── haproxy_etc_20210715-142306.tar.gz.sha1
├── haproxy_etc_20210716-050457.tar.gz
├── haproxy_etc_20210716-050457.tar.gz.sha1
├── haproxy_etc_20210716-052218.tar.gz
├── haproxy_etc_20210716-052218.tar.gz.sha1
├── k8s_snapshot_20210716-093422.tar.gz
├── k8s_snapshot_20210716-093422.tar.gz.sha1
├── postgresql_20210716-052725.tar.gz
├── postgresql_20210716-052725.tar.gz.sha1
├── postgresql_20210716-081301.tar.gz
├── postgresql_20210716-081301.tar.gz.sha1
├── prometheus_etc_20210716-052323.tar.gz
├── prometheus_etc_20210716-052323.tar.gz.sha1
├── prometheus_snapshot_20210716-052323.tar.gz
├── prometheus_snapshot_20210716-052323.tar.gz.sha1
├── rabbitmq_definitions_20210716-081704.tar.gz
├── rabbitmq_definitions_20210716-081704.tar.gz.sha1
├── rabbitmq_etc_20210716-081704.tar.gz
└── rabbitmq_etc_20210716-081704.tar.gz.sha1


1. Kubernetes

- Backup:
Epiphany performs etcd snapshot, backups Public Key Infrastructure /etc/kubernetes/pki and Kubeadm configuration files.

root@machine:/epibackup/backup# tree
.
├── etcd-snapshot.db
├── etcd_ver.txt
├── kubeadm-config.yml
└── pki
    ├── apiserver-etcd-client.crt
    ├── apiserver-etcd-client.key
    ├── apiserver-kubelet-client.crt
    ├── apiserver-kubelet-client.key
    ├── apiserver.crt
    ├── apiserver.key
    ├── ca.crt
    ├── ca.key
    ├── ca.srl
    ├── etcd
    │   ├── ca.crt
    │   ├── ca.key
    │   ├── etc-encryption.conf
    │   ├── healthcheck-client.crt
    │   ├── healthcheck-client.key
    │   ├── peer.crt
    │   ├── peer.key
    │   ├── server.crt
    │   └── server.key
    ├── front-proxy-ca.crt
    ├── front-proxy-ca.key
    ├── front-proxy-client.crt
    ├── front-proxy-client.key
    ├── sa.key
    └── sa.pub

- Restore:
No automatic restore option. Restore needs to be performed manually.

2. HA Proxy
- Backup:
Epiphany backups automatically configuration and certificates from HAProxy configuration directory.

root@machine:/epibackup/backup# tree
.
├── haproxy
│   ├── dhparam
│   └── haproxy.cfg
└── ssl
    └── haproxy
        └── self-signed-test.tld.pem

- Restore:
Restores properly configuration files and certificate.

3. Monitoring

- Backup:
Backups properly configuration files and data from grafana and prometheus.

root@machine:/epibackup/backup-grafana# tree
.
├── dashboards
├── grafana.db
├── plugins
└── png

root@ec2-34-249-254-105:/epibackup/backup-prometheus-etc# tree
.
├── file_sd
│   ├── haproxy-exporter-ec2-54-74-170-183.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-18-202-240-19.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-3-248-202-204.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-3-250-163-76.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-240-68-31.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-241-191-248.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-244-4-159.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-249-254-105.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-250-26-26.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-34-254-181-99.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-52-212-221-159.eu-west-1.compute.amazonaws.com.yml
│   ├── node-ec2-54-74-170-183.eu-west-1.compute.amazonaws.com.yml
│   └── postgres-exporter-ec2-3-250-163-76.eu-west-1.compute.amazonaws.com.yml
├── prometheus.yml
└── rules

root@machine:/epibackup/backup-prometheus-snapshot# tree
.
├── 01FAP6C0EAX85JDGS9Q2GH712T
│   ├── chunks
│   │   └── 000001
│   ├── index
│   ├── meta.json
│   └── tombstones
├── 01FAPM3DMQRF61SD4EGCJZ4FFD
│   ├── chunks
│   │   └── 000001
│   ├── index
│   ├── meta.json
│   └── tombstones
├── 01FAPM3FCFZ7RHHFNH0Q2SKGR8
│   ├── chunks
│   │   └── 000001
│   ├── index
│   ├── meta.json
│   └── tombstones
├── 01FAPTZ4WBRJJ64FTACXER7PZ5
│   ├── chunks
│   │   └── 000001
│   ├── index
│   ├── meta.json
│   └── tombstones
└── 01FAPWA2CJ4KQHMT8X5HVHFJ7X
    ├── chunks
    │   └── 000001
    ├── index
    ├── meta.json
    └── tombstones

- Restore:
Restores configuration files with data.

4. Postgresql

- Backup:
Performs backup of configuration and databases. 
Paths are right now related to postgres 10 so need to be update after posgres upgrade.

root@machine:/epibackup/backup# tree
.
├── configs
│   ├── pg_ctl.conf
│   ├── pg_hba.conf
│   ├── pg_ident.conf
│   ├── postgresql-epiphany.conf
│   ├── postgresql.conf
│   └── start.conf
└── data
    └── database_dump.sql

- Restore:
Performs only restore of the databases without restoring the configuration. 
If the configuration is broken it needs to be manually restored.

5. Rabbitmq

- Backup:
Backups configuration and messages definitions without messages.

root@machine:/epibackup/backup-definitions# tree
.
└── definitions-20210716-081704.json

root@machine:/epibackup/backup-etc# tree
.
├── enabled_plugins
├── rabbitmq-env.conf
└── rabbitmq.conf

- Restore:
Restores configuration and messages definitions without messages.

6. Logging

- Backup:
Needs security implemented to work with Open Distro.

- Restore:
Needs security implemented to work with Open Distro.

**Comment by seriva** [comment]
For K8s, shouldn't we at least try to do a manual restore to see what we backup is actually enough?

Rest looks ok.

**Comment by mkyc** [comment]
1. Do we know what are required changes for OpenDistro?
2. Do we know why PostgreSQL configuration files are not restored? 
3. Did you remove machines? In prometheus section IPs are visible. 
4. Do I see it correctly that each component backups to different "random" directory?
5. Can you describe what would be required to fix to allow restore on new infrastructure?

**Comment by erzetpe** [comment]
@seriva From the point of restore I think that we should look for different solution than existing one in Epiphany. Right now I think that we should focus on finding the new backup solution for K8s.

**Comment by erzetpe** [comment]
@mkyc 

1. Do we know what are required changes for OpenDistro?
Yes, we need to add authentication to backup.
2. Do we know why PostgreSQL configuration files are not restored?
According to @plirglo this should be done manually as it can be problematic sometimes during restoring cluster.
3. Did you remove machines? In prometheus section IPs are visible.
No, I have remove and restore the whole blocks of data on disk.
4. Do I see it correctly that each component backups to different "random" directory?
No, they are stored in /tmp/epibackup on given server and also in the directory /tmp/epibackup/mounted as tar.gz files. Here I just have extracted tar.gz and give meaningful names to extracted folder to easier distinct what is what.
5. Can you describe what would be required to fix to allow restore on new infrastructure?
The thing that doesn't work at the moment is Open Distro, because of lack of authentication and we should probably find a new way to backup Kubernetes.

**Comment by mkyc** [comment]
Ok LGTM.
