### ISSUE TITLE
[SPIKE] Check time needed for backup of each component

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2432]
**Is your feature request related to a problem? Please describe.**
In version 0.7 we have introduced backup/restore feature. Right now we want to check how long it takes to back up each component and create list with times for each component for the given amount of data.

**Describe the solution you'd like**
we want to check how long it takes to back up each component and create list with times for each component for the given amount of data(e.g. 1 GB, 10 GB, 100 GB).

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

* [ ] Ability for reader to understand results of spike is key value. 
* [ ] If possible, results of spike should be presented in table to show simply what are compared or researched parameters. Each value / cell should be also described more briefly later. 
* [ ] If possible, spike demo should be automated as much as possible. 
* [ ] design doc updated

**Comment by seriva** [comment]
More important factor would be storage types, machine configs and networks this would be running on. Amount of data is usually pretty trivial as it can be derived from a fixed set in most cases. So I would say to at least expand this to take in to account some of that and not only size of the dataset.

**Comment by erzetpe** [comment]
Yes, this is a basic description and it needs grooming.

**Comment by seriva** [comment]
Closing this for now.
