### ISSUE TITLE
[FEATURE REQUEST] Python 3 installation

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2434]
**Is your feature request related to a problem? Please describe.**
PgBouncer installation on database host requires Python3, we need to consider installation of it.

**Describe the solution you'd like**
Python3 installed on all VMs. 

**Additional context**
This should on Red Hat 7 be additional python installation, as changing default python 2.7 will break system tools installed with Red Hat. On Ubuntu 18.04 by default python 3 in version 3.6.9 is installed.

This task partially blocks:  [#2076](https://github.com/epiphany-platform/epiphany/issues/2076)

---

**DoD checklist**

* [x] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by erzetpe** [comment]
Python 3 should be installed on all machines as it is required by some Ansible modules and also there is a difference between Ubuntu and Red Hat as on Ubuntu 18.04 Python 3 is installed by default on all machines.

**Comment by mkyc** [comment]
this issue will influence: 
 - pgbouncer
 - download-requirements planned improvements
 - some ansible modules work just on p3

**Comment by przemyslavic** [comment]
:heavy_check_mark: Successfully installed python3 package on RHEL and CentOS machines. Tested on Azure and AWS (including arm).
```
[centos@ec2-1-1-1-1 ~]$ python --version
Python 2.7.5
[centos@ec2-1-1-1-1 ~]$ python3 --version
Python 3.6.8
```
