### ISSUE TITLE
[FEATURE REQUEST] ILM for Open Distro Elasticsearch

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2441]
**Is your feature request related to a problem?**
We don't use ILM for Open Distro Elasticsearch. 

**Describe the solution you'd like**
We want to implement ILM for Open Distro and apply automatically it's configuration.

**Describe alternatives you've considered**
We can adapt the old solution with Elasticsearch Curator to work with Open Distro security.

**Additional context**
Useful information related to ILM and ISM were described in PR 2107
[Information about ISM](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/LOGGING.md
).
Spike about ILM [2153](https://github.com/epiphany-platform/epiphany/issues/2153).
Information about using Elasticsearch Curator was described in task [2423](https://github.com/epiphany-platform/epiphany/issues/2423).

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Closing as we should first do the spike and then decide and create the proper issues: https://github.com/epiphany-platform/epiphany/issues/2153
