### ISSUE TITLE
[BACKPORT][v1.0.2] - [Elasticsearch] Error when having multiple VMs and non-clustered mode

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2442]
Source issue [2332](https://github.com/epiphany-platform/epiphany/issues/2332)
Pull request [2426](https://github.com/epiphany-platform/epiphany/pull/2426)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Clustering of logging component is set automatically depending on the number of nodes
