### ISSUE TITLE
[BACKPORT][1.0] Upgrade Keycloak to v14

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2445]
Backport PR to LTS branch: https://github.com/epiphany-platform/epiphany/pull/2429

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: `epicli apply`
:heavy_check_mark: `epicli` re-`apply`
:heavy_check_mark: `epicli upgrade` from v0.8.3 to v1.0.2 -> `epicli apply` v1.0.2
:heavy_check_mark: `epicli upgrade` from v1.0.0 LTS to v1.0.2 -> `epicli apply` v1.0.2
:heavy_check_mark: pipelines updated to use `epiphanyplatform/keycloak:14.0.0` image
