### ISSUE TITLE
[FEATURE REQUEST] Bonding network interfaces

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2446]
**Describe the solution you'd like**
Implement network interfaces bonding as an option in Epiphany Platform

**Additional context**
Request from Epiphany Office Hours. Spike for this was done here: https://github.com/epiphany-platform/epiphany/issues/2309

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
