### ISSUE TITLE
[FEATURE REQUEST] Remove dependencies for K8s v1.17

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2454]
**Is your feature request related to a problem? Please describe.**
The latest supported Epiphany version is 0.8, but there are still some leftovers for 0.7 and k8s v1.17.7. Removal of these dependencies at least will allow not to download unnecessary images.

**Describe the solution you'd like**
Clean up configuration. Affected files (there can be other ones):

- docs/home/howto/UPGRADE.md
- defaults/configuration/image-registry.yml
- playbooks/roles/preflight/tasks/upgrade.yml
- requirements.txt for repository
- playbooks/roles/upgrade/tasks/kubernetes/upgrade-master0.yml

**Describe alternatives you've considered**
No

**Additional context**
No

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested `epicli apply` and `epicli upgrade` from v1.1.0 to v1.3.0dev
