### ISSUE TITLE
[SPIKE] Check components possibility to perform site mirroring

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2463]
In this spike we need to identify (and preferably test) possible solutions for continuous site mirroring of persistence  components. 

Components: 
 - kafka
 - postgresql
 - elastic search / open distro
 - rabbit
 - prometheus
 - kubernetes PVs

Check:
 - what are possible solutions for each component
 - which one of solution is most mature / widely used
 - how exactly it works
 - what OS'es are supported for solution

Test:
 - setup two clusters in different locations
 - install solution manually
 - put some data in each component
 - observe if and how fast that was mirrored
 - what will happen when target location goes offline for some time? Will mirroring starts again when target location goes back online? 

This task is followup task of #2431

---

**DoD checklist**

* [x] Ability for reader to understand results of spike is key value. 
* [x] If possible, results of spike should be presented in table to show simply what are compared or researched parameters. Each value / cell should be also described more briefly later. 
* [ ] If possible, spike demo should be automated as much as possible. 
* [x] design doc updated

**Comment by atsikham** [comment]
K8s part is splitted between "site mirroring" and "incremental sync" parts.

**Comment by mkyc** [comment]
Detailed results are described in internal document. This task findings correspond with #2464. 

General summary is following:
1. Kafka: MirrorMaker2.0 (same as for incremental)
2. PostgreSQL: Repmgr Cascading Replication (same as for incremental)
3. Elastic Search/Open Distro for Elasticsearch: Cross Cluster Repliaction (same as for incremental)
4. RabbiitMQ: Federation Plugin (same as for incremental)
5. Ignite: not checked
6. Prometheus: Federation
7. Kubernetes: KubeFed?

7 requires more discussion before choosing solution.

LGTM
