### ISSUE TITLE
[SPIKE] Check components possibility to perform incremental sync

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2464]
In this spike we need to identify (and preferably test) possible solutions for "near-continuous" site synchronization of persistence  components. 

This task is different from #2463 in required time of data synchronization. In #2463 synchronization should be continuous and constant. In this task it's required to find solutions which synchronize data every time period (i.e., every hour). 

Components: 
 - kafka
 - postgresql
 - elastic search / open distro
 - rabbit
 - ignite (?)
 - prometheus
 - kubernetes PVs

Check:
 - what are possible solutions for each component
 - which one of solution is most mature / widely used
 - how exactly it works
 - what OS'es are supported for solution

Test:
 - setup two clusters in different locations
 - install solution manually
 - put some data in each component
 - observe if data was synchronized
 - what will happen when target location goes offline for some time? Will synchronization be able to sent missing data batches when target location goes back online? 

This task is followup task of #2431

---

**DoD checklist**

* [x] Ability for reader to understand results of spike is key value. 
* [x] If possible, results of spike should be presented in table to show simply what are compared or researched parameters. Each value / cell should be also described more briefly later. 
* [x] If possible, spike demo should be automated as much as possible. 
* [x] design doc updated

**Comment by atsikham** [comment]
Got an information from @mkyc about K8s part:

I think that this one point is not quite correct, guess just "kubernetes" would be more correct. I was talking about this point with Pawel once and I think we do not care about PVs in kubernetes as we do not support real correct persistence under kubernetes right now in epiphany, but my feeling is that if someone stores Secrets, Configuration or whatever other objects it's more of our interest. So overall feeling is that this part of research is also to define what parts of kubernetes environment we want to cover here: when cluster is operational and someone changes object ConfigMap it should be reflected somehow to mirror cluster.

**Comment by mkyc** [comment]
I reviewed internal document and left some comments. Please have look at those @erzetpe @sbbroot @rafzei and @atsikham

**Comment by mkyc** [comment]
Detailed results are described in internal document. 

General initial summary is following: 
1. Kafka: MirrorMaker2.0
2. PostgreSQL: Repmgr Cascading Replication
3. Elastic Search/Open Distro for Elasticsearch: Cross Cluster Repliaction
4. RabbiitMQ: Federation Plugin
5. Ignite: not checked
6. Prometheus:  Thanos? 
7. Kubernetes: Admiralty?

6, 7 requires more discussion before choosing solution. 

LGTM
