### ISSUE TITLE
[BACKPORT][v1.0.0] - Basic configuration type and schema validation.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2477]
Backport: #195, #2425
PR: #2470, #2474

**Comment by przemyslavic** [comment]
✔️ Schema validation has been added (and updated after backporting) for yaml files.
Additionally all `'y', 'Y', 'yes', 'Yes', 'YES'` / `'n', 'N', 'no', 'No', 'NO'` values are converted to booleans: `true/false`.
