### ISSUE TITLE
[BACKPORT][v1.1.0] - Implement proper merging of lists of dictionaries for epicli yaml docs

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2480]
Backport: #1294, #1370
PR: #2465

**Comment by przemyslavic** [comment]
✔️ `_merge` parameter has been introduced for named lists. If not provided or set to false (by default), the user must provide all list items as it will override the defaults. If set to true, the values provided by the user will be merged with the defaults.
