### ISSUE TITLE
[FEATURE REQUEST] Multiple PostgreSQL nodes only in clustered mode.

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2495]
**Is your feature request related to a problem? Please describe.**
Right now we have option for multiple non clustered nodes of PostgreSQL.

**Describe the solution you'd like**
We want to provide only option for multiple clustered nodes of PostgreSQL and change logic to automatically cluster PostgreSQL instances when node count is higher than 1. Also we want to update documentation accordingly.

**Describe alternatives you've considered**
None.

**Additional context**
No.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
This is the current behavior, which has to be changed here: https://github.com/epiphany-platform/epiphany/issues/3082. So closing this for now.
