### ISSUE TITLE
[BUG] Don't create directories without intent 

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2496]
**Describe the bug**
We are creating directory /etc/kafka and not using this after creation:

https://github.com/epiphany-platform/epiphany/blob/ddf0bddd33017bf892bafc93559a6406bbbd36b4/core/src/epicli/data/common/ansible/playbooks/roles/kafka/tasks/setup-kafka.yml#L104

We have also commented out code for symlink, that should be removed or uncommented.
https://github.com/epiphany-platform/epiphany/blob/ddf0bddd33017bf892bafc93559a6406bbbd36b4/core/src/epicli/data/common/ansible/playbooks/roles/kafka/tasks/setup-kafka.yml#L111

**How to reproduce**
Create machine with kafka and check content of /etc/kafka directory.

**Expected behavior**
Don't create resources without intent and left commented out in the code.

**Config files**
None.

**Environment**
- Cloud provider: [AWS | Azure | All | None]
- OS: [e.g. Ubuntu 18.04.4 LTS, you can use `cat /etc/os-release`]

**epicli version**: [`epicli --version`]

**Additional context**

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by to-bar** [comment]
@erzetpe please change the title :construction_worker:
