### ISSUE TITLE
[PostgreSQL upgrade] Test upgrade using databases with real (imported) data

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2498]
After PostgreSQL upgrade feature is fully implemented and tested on any database (probably very small), we want to test it using one or two databases containing some real (product) data (bigger volume expected).

In order to prepare such databases, we need to organize data dumps (backups or sample data) from other projects.
@plirglo is talking to teams to get database dumps.

Scenario:
1. Import database dump.
2. Check output for particular selects / check possibilities to alter data.
3. Upgrade to Postgresql v13.
4. Re-run command from p. 2 and compare results: p. 2 vs p. 4

**Comment by plirglo** [comment]
QA dumps from two teams are shared. please ask @plirglo for dumps in case you start testing.

**Comment by to-bar** [comment]
Upgrade succeeded for PGML dumps (pgml_repository, pgml_runtime).

**Comment by to-bar** [comment]
Tests succeeded using dump with 13 GB database. However, during testing I found a bug #2656.
Moreover, we need additional preflight check (e.g. for Vagrant env after restoring VMs from snapshot), issue #2655.
