### ISSUE TITLE
[Backport to v1.0] Upgrade PostgreSQL to v13

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2503]
**Is your feature request related to a problem? Please describe.**
We need to back port task #1861 to v1.0 branch.

In this task **we should keep all known PRs related to PostgreSQL upgrade until the feature is back ported**.

**Known related PRs**
- #2500
- #2501
- #2519
- #2522
- #2539 
- #2545
- #2546
- #2566
- #2598
---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc

**Comment by mkyc** [comment]
This is new functionality so we are not back porting it.
