### ISSUE TITLE
[REVERT] Upgrade Docker-CE to version 20.10.8

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2505]
Revert backported changes done in #2487 

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Docker reverted to v19.03.14.
Tested on `Ubuntu`/`RHEL`/`CentOS` (branches v1.0 and v1.1)
