### ISSUE TITLE
[FEATURE REQUEST] Add possibility to use / import more users than the main one

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2508]
**Is your feature request related to a problem? Please describe.**
Currently Epiphany by default configures one administrator user with sudo privileges with name "operatiaons"
Consider to add possibility to create other users, or create documentation how this should be done by administrator to avoid sharing the same user and keys by many operators / administrators.

**Describe the solution you'd like**
Add role to create users and add them correct privileges and public keys imported from file, eg:
```bash
epicli apply --users --from-file file_with_usernames_and_pub_keys
```

**Describe alternatives you've considered**
1. Create script to add users, eg:
```bash
create_users.sh -u admin_user_name -i inventory_file -f file_with_users_and_pub_keys
```
2. Create documentation how this should be done and why this is not necessary 
**Additional context**

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by to-bar** [comment]
We already have such functionality. Does it meet requirements?
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/SECURITY.md#how-to-addremove-additional-users-tofrom-os
