### ISSUE TITLE
Upgrade Python packages to at least the latest patch version.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2511]
**Is your feature request related to a problem? Please describe.**
We have a bunch of CEV warnings from GitHub which we should fix.

**Describe the solution you'd like**
Update all Python packages at least to the latest patch version to fix these CEV warnings.

**Describe alternatives you've considered**
None

**Additional context**
This will also be required for the new BlackDuck scan as these are going to put more emphasis on security besides licensing.  

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: I have tested deploying the clusters for the following configurations: `AWS` / `Azure` x `Ubuntu` / `RHEL` / `CentOS` with all components enabled (at least 1 vm) and did not run into any problems.

**Comment by przemyslavic** [comment]
Tested again after #2540. No issues found.
