### ISSUE TITLE
[FEATURE REQUEST] Add Molecule execution into test pipelines

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2513]
**Is your feature request related to a problem? Please describe.**
We started to create Molecule tests that at the moment exist for PostgreSQL. The idea is to include them into existing test pipelines in Azure DevOps.

**Describe the solution you'd like**
Add an additional step. It runs in Docker containers, so some adjusment may be needed.

**Describe alternatives you've considered**
No.

**Additional context**
Consider [pytest-molecule](https://pypi.org/project/pytest-molecule/) to run scenarios in parallel.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
