### ISSUE TITLE
[BACKPORT][1.1] Upgrade Keycloak to v14

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2514]
Backport PR to v1.1 branch: #2429

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
This is new functionality so we are not back porting it.
