### ISSUE TITLE
[spike] plan kubernetes upgrade

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2523]
- choose which version we are upgrading to, probably not the latest but the latest stable
 - check changelogs about what was deprecated
 - check upgrade guides https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/ - is there only incremental upgrade possible?
 - check changes in our code since https://github.com/epiphany-platform/epiphany/pull/1501 
 - check support policies https://kubernetes.io/releases/version-skew-policy/
 - if there is enough time, try to upgrade manually to find pitfalls
 - create result tasks and assign to "Kubernetes upgrade" epic

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [x] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [x] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [x] Design doc updated

**Comment by atsikham** [comment]
The result of this spike is combining of related tasks into one Epic - https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/2620

Besides existing tasks, new ones were created:

#2657 - Add additional preflight check for upgrade
#2093 - Renamed to "Upgrade Kubernetes to 1.19.x"
#2658 - Upgrade Kubernetes to 1.20.x
#2659 - Upgrade Kubernetes to 1.21.x
#2660 - Upgrade Kubernetes to 1.22.x
#2661 - Update documentation
#2662 - Refactor K8s roles - may be done later and even in the scope of another epic

Upgrades should be incremental, so there is a separate task for each version. Moreover, it will allow us test them separately, find issues on earlier stages and release versions that we are able to complete upgrade for.

**Comment by mkyc** [comment]
Thanks @atsikham. LGTM.
