### ISSUE TITLE
[PostgreSQL] repmgr upgrade fails when replication is disabled but repmgr package is present

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2526]
**Describe the bug**
In Epiphany < v1.1 repmgr package was installed even when replication was disabled (by default). On upgrade usage of repmgr is detected based on package existence and logic gets false positive. On Ubuntu there is no config file, on RHEL there is just sample config (which doesn't work) so upgrade fails.

**How to reproduce**
1. Deploy cluster with PostgreSQL using Epiphany < v1.1 with default config (no replication)
2. Run `epicli upgrade`

**Expected behavior**
Upgrade succeeded.

**Environment**
- Any

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed. Repmgr package is first removed if there is no configuration file or just a sample configuration. Tested when upgrading from v1.0 to dev with postgresql replication disabled.
