### ISSUE TITLE
[PostgreSQL] Upgrade creates scripts in /var/log/postgresql directory

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2528]
**Describe the bug**
The `pg_upgrade` tool that runs from `/var/log/postgresql` directory and that creates two scripts there:
1) analyze_new_cluster.sh
2) delete_old_cluster.sh

**How to reproduce**
1. Run the `epicli upgrade` for a cluster with PostgreSQL

**Expected behavior**
In the `/var/log/postgresql` directory there should be only logs. 

**Additional context**
The scripts are for:
```
Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade so,
once you start the new server, consider running:
    ./analyze_new_cluster.sh

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
```

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed. Now the upgrade is run from `/var/lib/pgsql/upgrade/13/` / `/var/lib/postgresql/upgrade/13/` directories depending on the OS and scripts are created there.
`/var/log/postgresql` directory contains only log files.
