### ISSUE TITLE
[SPIKE] Improve structure of sources in Git repository

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2533]
**Is your spike related to a problem or idea? Please describe.**
The structure of `epiphany` repo doesn't follow good practice conventions. For example, we have many changlog files in root directory, tests in two different locations (`core\src\epicli\tests` and `core\src\epicli\data\common\tests`), most often changed files have long path (`core\src\epicli\data\common\ansible\playbooks`).

Examples:
- [Microsoft Windows Terminal](https://github.com/microsoft/terminal)
- [Ansible](https://github.com/ansible/ansible)

**Describe the outcome you'd like**
List of changes to do in order to have a clean and clear structure that suites our needs.

**What is the reason or source for the spike**
The current structure does not allow for comfortable work and isn't clear.

**Additional context**
Related to #2532.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
I feel this has been all addressed with the major workspace overhaul we did for 1.3 so closing this.
