### ISSUE TITLE
[FEATURE REQUEST] Add PyTest to build pipeline

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2536]
**Is your feature request related to a problem? Please describe.**
Currently we have the ability to use PyTest in the devcontainer and output the results in junit format. And this is already partially integrated in the build pipelines.

**Describe the solution you'd like**
We want to integrate this into the Azure build pipelines as well and publish the results:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml

**Describe alternatives you've considered**
None

**Additional context**
See https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/.vscode/tasks.json how PyTest can be executed.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Consider using GitHub Actions.

**Comment by asciible** [comment]
This feature is already implemented:

![image.png](https://images.zenhubusercontent.com/61829fc12d88f7c22394fcee/44de401f-7030-4e9a-ad2f-c652f75c1d69)
