### ISSUE TITLE
[FEATURE REQUEST] [PostgreSQL] [upgrade] Do not remove new packages automatically in rollback

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2537]
**Is your feature request related to a problem? Please describe.**
When PostgreSQL upgrade fails, Epiphany performs automatic rollback (Ansible rescue block) during which the following operations are done:
- remove PostgreSQL related packages (new version)
- remove new version data directory
- restore repmgr symlinks
- start and enable old PostgreSQL service
- start and enable old repmgr service

When operator wants to debug/analyze a failure, there is no new binaries, so reproducing an issue (re-run the failed command) is difficult.

**Describe the solution you'd like**

The rollback creates a file (can be script) with instructions how to uninstall new binaries instead removing them automatically.

**Describe alternatives you've considered**
No automatic rollback, all commands in a file.

**Additional context**
The upgrade is run based on the condition: `when: not pg_data_dir.stat.exists or pg_data_dir_files.matched == 0`.
So the rollback must remove files from data dir.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
:rocket:

**Comment by mkyc** [comment]
Before merging PR for this task decide with @przemyslavic if it can be merged to 1.2.0 release branch.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested `apply` and `upgrade` from v1.0.x to v1.3.0dev with rollback procedure,
Single-node installation and cluster deployment with replication enabled have been checked.
