### ISSUE TITLE
[BUG] Non critical error in epicli if no 'path' is provided

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2542]
**Describe the bug**
I faced the issue in devcontainer:
``` bash 
vscode@c91ba3ea365b:/workspaces/epiphany/core/src/epicli$ epicli --version
1.2.0dev
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
It also occurs with any help (usage) message.

**How to reproduce**
Steps to reproduce the behavior in devcontainer:
1. alias epicli="PYTHONPATH=$(pwd) python3 cli/epicli.py"
2. execute `epicli --version`, `epicli init -h ...` or any different --help 

**Expected behavior**
No error message

***epicli version**: [`epicli --version`]
1.2.0dev

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Fixed.
Also added the possibility to run `epicli` commands directly from the terminal, without having to use a debugger :heart:
```
vscode@25a37e0ee9e8:/workspaces/epiphany/core/src/epicli$ epicli --version
1.2.0dev
vscode@25a37e0ee9e8:/workspaces/epiphany/core/src/epicli$ epicli init -h
usage: epicli <command> [<args>] init [-h] -p {aws,azure,any} -n NAME [--full]

Creates configuration file in working directory.

required arguments:
  -p {aws,azure,any}, --provider {aws,azure,any}
                        One of the supported providers: azure|aws|any
  -n NAME, --name NAME  Name of the cluster.

optional arguments:
  -h, --help            show this help message and exit
  --full                Use this flag if you want to create verbose
                        configuration file.
```
