### ISSUE TITLE
[FEATURE REQUEST] Refactoring and removal of old code from Ansible inventory creator and upgrade

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2547]
**Is your feature request related to a problem? Please describe.**
Right now we have the code that should be refactored from Ansible inventory creator and upgrade and some parts needs to be removed.

**Describe the solution you'd like**
We want to refactor and clean up the code from Ansible inventory creator and upgrade.

**Describe alternatives you've considered**
None.

**Additional context**
Code from the part BUILD_LEGACY upgrade should be removed.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
@przemyslavic When testing this pls also run one upgrade. Not only for this but also #2643 and #2666.

**Comment by przemyslavic** [comment]
The following `epicli` commands have been tested:
✔️ `init` (`--full`)
✔️`apply` + re-`apply`
✔️`backup`
✔️`recovery`
✔️`prepare`
✔️`test`
✔️`upgrade` from v1.1 to dev 
✔️`delete`
