### ISSUE TITLE
[FEATURE REQUEST] Upgrade Python from 3.7 to 3.10 and apply needed changes

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2548]
**Is your feature request related to a problem? Please describe.**
Right now we are using for development and in devcontainer Python 3.7. 

**Describe the solution you'd like**
We want to upgrade python for our development to version 3.9 and apply changes needed to the code.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
@asciible I think we should also update agent pool on Azure DevOps to use Python 3.10, not Python 3.7 for running unit tests and linters.
Files that probably needs to be updated:
https://github.com/epiphany-platform/azure-pipelines-agents/blob/main/docker-image/Dockerfile
https://github.com/epiphany-platform/azure-pipelines-agents/blob/main/docker-image/configure-tool-cache.sh
and then we have to re-deploy Azure pipelines agents.

**Comment by przemyslavic** [comment]
#2947 created
