### ISSUE TITLE
[FEATURE REQUEST] Add more tags to created resources - e.g. who created, date of creation

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2549]
**Is your feature request related to a problem? Please describe.**
Right now we have a problem with finding the details when some resource and by whom it has been created.

**Describe the solution you'd like**
We want to have additional tags to be able to find resource owner and the date of creation. Additional tags can be also included.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Not something we will do for this Epiphany version anymore, so closing.
