### ISSUE TITLE
[FEATURE REQUEST] Add new tests for Infrastructure generators

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2550]
**Is your feature request related to a problem? Please describe.**
Right now we have limited number of tests for Infrastructure generators.

**Describe the solution you'd like**
We want to add new tests to cover more cases for Infrastructure generators.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
