### ISSUE TITLE
[FEATURE REQUEST] Add new tests for data_loader.py and build_saver.py

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2551]
**Is your feature request related to a problem? Please describe.**
Right now we don't have tests for data_loader.py and build_saver.py

**Describe the solution you'd like**
We want to provide new tests for data_loader.py and build_saver.py.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: 22 unit tests have been added for build saver (15) and data loader (7).
Several fixes made by @seriva in https://github.com/epiphany-platform/epiphany/pull/2671/commits/24dc8852c1a032e3c3eb13084516cf900ec23446
