### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by AnnaKlank** [epiphany-platform/epiphany#2553]
Due to Docker CE repository on github being deprecated and going to be archived I would like to ask you to update components.md for all Epiphany versions (e.g., https://github.com/epiphany-platform/epiphany/blob/v0.7/docs/home/COMPONENTS.md) to a new Repo/Website: **https://docs.docker.com/engine/release-notes/**.
Thank you in advance,
Anna

**Comment by mkyc** [comment]
Hi @AnnaKlank do you want to create PR with this update?

**Comment by mkyc** [comment]
@AnnaKlank thanks for your PRs! 🎉
