### ISSUE TITLE
[FEATURE REQUEST] Add Rubocop to build pipeline

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2559]
**Is your feature request related to a problem? Please describe.**
Currently we have the ability to use Rubocop  in the devcontainer and output the results in junit format.

**Describe the solution you'd like**
We want to integrate this into the Azure build pipelines as well and publish the results:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml

**Describe alternatives you've considered**
None

**Additional context**
See https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/.vscode/tasks.json how Rubocop  can be executed.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
Consider using GitHub Actions.

**Comment by cicharka** [comment]
Proposed new Agent job in Azure Pipeline (go to [draft pipeline](https://dev.azure.com/abb-epiphany/epiphany/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=126) to see all steps):

---

1. Running Rubocop linter task:
```bash
cd $(System.DefaultWorkingDirectory)

mkdir -p linting_tests && \
rubocop ./tests \
-c .rubocop.yml \
--require rubocop/formatter/junit_formatter \
--format RuboCop::Formatter::JUnitFormatter \
--out linting_tests/rubocop_results.xml \
--fail-level error
```

2. Assertion for linter failures:
```bash
# Fetch number of detected failures from results file, then test if it does not exceed the declared threshold 
# rubocop_linter_threshold is set based on latest linter results performed after code cleaning

detected_failures=$(grep -o 'failures=.[0-9]*.' linting_tests/rubocop_results.xml | grep -o '[0-9]*')

echo -e "Number of detected failures: $detected_failures\nFailures threshold value: $(rubocop_linter_threshold)"

test  $detected_failures -le $(rubocop_linter_threshold)
```

---

Notes:
* To do not let new linting errors coming with the commit, we are restricting in rubocop with `--fail-level error`
* We already have some warning and info severity linting problems, so to do not let new coming, we want to monitor number of tests failed (note that Rubocop linter by itself is not supporting any 'score' number , see e.g. pylint score), so we have to do a workaround -> see step 2 above

**Comment by to-bar** [comment]
1) Install Ruby dependencies - I would install requirements in Dockefile, just to save time
2) Have you tested if the linting task would fail after appending any command after calling rubocop (i.e. whether we need to add `set -e` or not)?
3) grep option -o can be not obvious (not so popular) so maybe better to use long form (`--only-matching`)?
4) Maybe `printf` would be more readable than `echo -e`?

**Comment by cicharka** [comment]
@to-bar, see my answers and code below:
1. That is something that we can solve when we will have agreement on repos related to the pipelines and Azure.
2. As I was not adding any commands after test under that particular task before, I have not noticed that issue. Tested now, `set -e` added.
3. I changed it, now it is more informative
4. Do you want to changed only the command or also play with the formatting?
```bash
# Fetch number of detected failures from results file, then test if it does not exceed the declared threshold 
# rubocop_linter_threshold is set based on latest linter results performed after code cleaning

set -e 

detected_failures=$( \
    grep --only-matching 'failures=.[0-9]*.' linting_tests/rubocop_results.xml | \
    grep --only-matching '[0-9]*')

printf "Number of detected failures: $detected_failures\nFailures threshold value: $(rubocop_linter_threshold)"

test  $detected_failures -le $(rubocop_linter_threshold)
```

**Comment by to-bar** [comment]
@cicharka

1. I'm going to update the Dockerfile soon for a different reason (update Docker image, currently `ubuntu:bionic-20200807`) so I can add/update dependencies as well. Sources from `azure-pipelines-agent` directory will be moved to a new GitHub repo. `sonarqube` probably will stay untouched - up to @erzetpe. 

4. My intention was to avoid `-e` switch. Please choose what you like more (I prefer the first option and not tested the second):

```
echo "Number of detected failures: $detected_failures"
echo "Failures threshold value: $rubocop_linter_threshold"
```

or 

```
printf "Number of detected failures: %d\nFailures threshold value: %d\n" $detected_failures $rubocop_linter_threshold
```

**Comment by cicharka** [comment]
2. Updated step in the `CI build` pipeline with the first option (echo in separate lines)
