### ISSUE TITLE
[BUG] Investigate pgpool memory leaks

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2561]
**Describe the bug**
Contenerized pgpool used in epiphane has got kind of memory leaks. When container is removed using extend command (like kill), recreated pod uses more memory than previous instance. Also during normal work, memory used by pod slowly rising.

**How to reproduce**
1. Deploy cluster with k8s deployed pgpool
2. Check resource usage after few days or kill running container and compare resources usage by newly created pod with old one.

**Expected behavior**
Every instance of pod should use same amount of memory

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: all versions with pgpool (older version of pgpool also includes this bug)

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by rafzei** [comment]
Please update documentation if there will be any findings or workarounds:
[DATABASES.md](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md)
