### ISSUE TITLE
[FEATURE REQUEST] Adjust PostgreSQL tests to be executed on all nodes

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2562]
**Is your feature request related to a problem? Please describe.**
So far, our PostgreSQL tests are based on the assumption that we have at most one master and one standby node (as it was implemented). Now we have introduced the ability to install more than 2 nodes, so we should update our tests to run on all nodes. In addition, a mechanism should be introduced in the tests that automatically detects the master (and not rely on the assumption that it is always the first node in the inventory, because the order may change in the case of re-running epicli)

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: The tests have been adjusted to support a multi-node (+2) installation.
Tested single machine and a 3-node cluster.
Additionally, the functionality has been introduced so that the tests are run first on the master (on which the tables are created, etc.) and then on standby nodes :heart:

**Comment by to-bar** [comment]
Ported to `develop` in #2654

**Comment by to-bar** [comment]
Ported to `develop` in #2654
