### ISSUE TITLE
[BUG] [Keycloak] [EPI 1.0.0] No resources request in yaml - PODS cannot initiate after any other pods installed on the same node 

### ISSUE THREAD

**Issue by batus82** [epiphany-platform/epiphany#2574]
As described in the topic - spotted on Epi 1.0.0 
Keycloak pods were immediately going down and stuck in Init state after APM's pods are present on the same node. 

Fixed by adding resource requests in Keycloak's statefulsets.apps for already deployed environemnt. 

Please add the missing section to the installation yaml file.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by plirglo** [comment]
Thank you @batus82 for creating this issue

W don't set up resource requests and limits parameters which might very dangerous for cluster stability.
I will take care on this issue and try to add this to one of following sprints.

@epiphany-platform/epiphany-team We need to set up requests and limits for application(s).

**Comment by atsikham** [comment]
Please also look at #2253 and #776 as they are related to the same topic and might be solved/closed at one time.
