### ISSUE TITLE
[SPIKE] Check if we can remove Istio from Epiphany

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2577]
**Is your spike related to a problem or idea? Please describe.**
Check if anyone using Istio

**Describe the outcome you'd like**
We would like to know if we can remove Istio from Epiphany

**What is the reason or source for the spike**
The source of this issue is #2456  and comment:
https://github.com/epiphany-platform/epiphany/issues/1931#issuecomment-846989413

**Additional context**
Other Istio-related issues we've got:  #1931 

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by erzetpe** [comment]
Closing because of deprecation of Istio component.
