### ISSUE TITLE
[FEATURE REQUEST] Apply private/protected convention for class members

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2581]
**Is your feature request related to a problem? Please describe.**
Currently we don't use private/protected (_|__) prefixes inside our Python code.

**Describe the solution you'd like**
We need to check which members can be changed to private/protected and add the prefix _ or __ if needed.

**Describe alternatives you've considered**
None.

**Additional context**
https://www.geeksforgeeks.org/access-modifiers-in-python-public-private-and-protected/

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Pls put this form of the feature request templates we have.

**Comment by seriva** [comment]
Not blocked, just on hold to finish stuff for 1.2.0 first.

**Comment by seriva** [comment]
Looked at a bunch of high profile projects like Azure-CLI etc, and these do not seem to abide these practices. For now I will close it I think the time can be spend on improving more important things in the python code base.
