### ISSUE TITLE
[SPIKE] Monitoring component(Prometheus,Grafana) in HA 

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2586]
**Is your spike related to a problem or idea? Please describe.**
The current monitoring component is only available in standalone mode.
At least Prometheus should be in HA in a production environment.

**Describe the outcome you'd like**
- check if there is a need to provide such functionality (eg. ask teams)
- check if we can use it as K8s apps

**What is the reason or source for the spike**
We do not have monitoring production-ready

**Additional context**
The spike about incremental sync can be useful here

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
