### ISSUE TITLE
[FEATURE REQUEST] Upgrade Ansible to 4.x (ansible-core 2.11)

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2590]
**Is your feature request related to a problem? Please describe.**
Ansible 2.10 doesn't have `split` filter, it was added in version 2.11 (see [PR](https://github.com/ansible/ansible/pull/73532)).

**Describe the solution you'd like**
Current Ansible version in `epicli` container, see https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html

**Additional context**
As temporary solution `split.py` has been added to `core\src\epicli\data\common\ansible\playbooks\filter_plugins`.
This file should be removed after Ansible is upgraded.

Way to upgrade the Python packages can be found here: https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/.devcontainer/requirements.md

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by asciible** [comment]
Superseded by https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/2847
