### ISSUE TITLE
[FEATURE REQUEST] Update OS cloud images to the latest

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2591]
**Is your feature request related to a problem? Please describe.**
Update Ubuntu 18.04-LTS/RHEL 7/CentOS 7 images used in the cloud to the latest version before releasing v1.2.0.

**Describe the solution you'd like**
Update Azure DevOps pipelines, documentation and epicli defaults.

Some files to be updated:

Azure:
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/azure/defaults/infrastructure/virtual-machine.yml
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/azure/defaults/infrastructure/cloud-os-image-defaults.yml

AWS:
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/aws/defaults/infrastructure/virtual-machine.yml
https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/aws/defaults/infrastructure/cloud-os-image-defaults.yml

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Latest images as for today:

Azure
`Canonical:UbuntuServer:18.04-LTS:18.04.202109130`
`RedHat:RHEL:7-LVM:7.9.2021051701`
`OpenLogic:CentOS:7_9:7.9.2021071900`

AWS
`ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210907`
`RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2` - currently used
`CentOS 7.9.2009 x86_64`  - currently used
`CentOS 7.9.2009 aarch64` - currently used

**Comment by przemyslavic** [comment]
Updated defaults, documentation and pipelines.
