### ISSUE TITLE
[FEATURE REQUEST] Update template for new features with update security information.

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2596]
**Is your feature request related to a problem? Please describe.**
We don't have a pointed related to security in template in task section. We want to have it to remember about updating SECURITY.md and other security related documentation.

**Describe the solution you'd like**
 Update template for new features with update security information.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
