### ISSUE TITLE
[FEATURE REQUEST] Ensure automatic PostgreSQL clusterization

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2597]
**Is your feature request related to a problem? Please describe.**
Right now we have an option to install multiple non clustered PostgreSQL clusters. 

**Describe the solution you'd like**
We want to remove the possibility of installation multiple non clustered nodes for PostgreSQL and automatically cluster PostgreSQL servers if the number of nodes is higher than 1.

**Describe alternatives you've considered**
None.

**Additional context**
This task should make our approach to installation of components more concise in Epiphany and follow the approach from https://github.com/epiphany-platform/epiphany/pull/2426 and https://github.com/epiphany-platform/epiphany/issues/2332.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested:
:heavy_check_mark: `apply`
:heavy_check_mark: re-`apply`
:heavy_check_mark: `upgrade` from v1.0 (PostgreSQL v10)
:heavy_check_mark: `upgrade` from v1.2 (PostgreSQL v13)
:heavy_check_mark: `apply` and `upgrade` for `aarch64`

The above scenarios were tested with 1 PostgreSQL node and with a 2- or 3- node cluster.
