### ISSUE TITLE
Enable autoscaling groups for Epiphany components

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#26]
This is equivalent of Availability Sets in Azure

**Comment by przemyslavic** [comment]
Support for Azure availability sets was added in [#1411](https://github.com/epiphany-platform/epiphany/pull/1411).
We should consider autoscaling Azure virtual machines via virtual machine scale sets.
https://docs.microsoft.com/pl-pl/azure/architecture/best-practices/auto-scaling
https://docs.microsoft.com/pl-pl/azure/virtual-machine-scale-sets/overview

**Comment by rpudlowski93** [comment]
Regarding to our conception with modules, we introduce autoscaling in the new approach (autoscaling in AKS/EKS) and the ticket can be closed.
