### ISSUE TITLE
[FEATURE REQUEST] Change epicli output structure :weary:

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2600]
**Is your feature request related to a problem? Please describe.**
_I'm always frustrated when..._ reading epiphany log

**Describe the solution you'd like**
Get rid of unnecessary columns in log

**Our current log:**
```
{"asctime": "05:53:57", "levelname": "INFO", "name": "cli.engine.schema.DefaultMerger", "message": "Starting run"}
{"asctime": "05:53:57", "levelname": "INFO", "name": "cli.engine.schema.DefaultMerger", "message": "Merging: epiphany-cluster name: default"}
{"asctime": "05:53:57", "levelname": "INFO", "name": "cli.engine.schema.DefaultMerger", "message": "Merging: configuration/feature-mapping name: default"}
{"asctime": "05:53:57", "levelname": "INFO", "name": "cli.engine.schema.DefaultMerger", "message": "Merging: configuration/shared-config name: default"}
{"asctime": "05:53:57", "levelname": "INFO", "name": "cli.engine.schema.DefaultMerger", "message": "Merging: configuration/logging name: default"}
```
The above can be acceptable in debug level (epicli [..] --debug ) 3 or 4

**What I wish to see as normal output:**
```
05:53:57, INFO, Starting run
05:53:57, INFO, Merging: epiphany-cluster name: default
05:53:57, INFO, Merging: configuration/feature-mapping name: default
05:53:57, INFO, Merging: configuration/shared-config name: default
05:53:57, INFO, Merging: configuration/logging name: default
```

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
THe JSON log file output was original meant for the Epicli web interface but never used as we never started work on that. 

So for this we should just output the plain text log as default as set by the ```--log-type``` flag and use that same flag to make the log output type configurable. If people still want JSON output they can then use ```--log-type json``` to get it.

I don`t think we should change the proposed log format and leave it as it. People can use ```--log-format``` if they want to change it.

**Comment by przemyslavic** [comment]
Added the possibility to save log files as `plain` text (by default), not just `json` (as it was before) and this can be controlled by the `--log-type` flag.
The output format can be modified with the `--log-format` and `--log-date-format` flags.
