### ISSUE TITLE
[BACKPORT][1.2] Fix postgres backup and recovery

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2602]
Merge #2598 into 1.2 branch.

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested similarly as #2565.

Tested backup and recovery for the following configuration:
:heavy_check_mark: 1 PostgreSQL node
:heavy_check_mark: 2 clustered PostgreSQL nodes
:heavy_check_mark: 3 clustered PostgreSQL nodes

Please note that the backup is made for the database `data`/`metadata` and the `* .conf` configuration files.
When running `recovery` command, only the data is restored. The configuration files should be restored manually. Additionally, to restore data, `postgresql` and `repmgr` services must be running. In case of problems, it's recommended to run `apply` again and then `recovery` as described in the [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/BACKUP.md#postgresql).
