### ISSUE TITLE
[BACKPORT][v1.0] Refactor Keycloak to work with Postgresql HA configuration

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2607]
Backport to v.1.0 branch #2556

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
This should be done after all PR regarding Postgres13 are backported

**Comment by mkyc** [comment]
This is new functionality so we are not back porting it.
