### ISSUE TITLE
[BUG] [RedHat] [PostgreSQL] [upgrade] Old and new PostgreSQL services enabled after upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2619]
**Describe the bug**

After upgrade two PG services are enabled:

```
systemctl list-unit-files --type service --state enabled,generated | grep -e postgresql
postgresql-10.service                      enabled
postgresql-13.service                      enabled
```

**How to reproduce**
1. Run `epicli upgrade`

**Expected behavior**
Only one enabled PG service: `postgresql-13.service `

**Environment**
- Cloud provider: All
- OS: RHEL/CentOS

**Additional context**
n/a

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Fixed. Old PostgreSQL service is now disabled after upgrading.

**Comment by to-bar** [comment]
Ported to `develop` in #2654
