### ISSUE TITLE
[BUG] [RedHat] [PostgreSQL] [upgrade] wrong repmgr service is running after rollback

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2622]
**Describe the bug**
When PostgreSQL upgrade fails rollback tasks are run. They should restore old PostgreSQL and repmgr services.

On CentOS after rollback:
```
systemctl list-unit-files --type service --state enabled,generated | grep -e postgresql -e repmgr
postgresql-10.service                      enabled
```
Bug 1: missing repmgr service

```
systemctl list-units --type=service --state=running | grep -e postgresql -e repmgr
  postgresql-10.service            loaded    active running PostgreSQL 10 database server
● repmgr13.service                 not-found active running repmgr13.service
```
Bug 2:  `repmgr13` service running instead of `repmgr10`

**How to reproduce**
1. Run `epicli upgrade` (modified Ansible code to simulate upgrade failure)

**Expected behavior**
Old repmgr service enabled and running.

**Environment**
- OS: CentOS/RHEL

**Additional context**
Behavior of rollback feature will be changed in epicli 1.3 (#2537).

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Fixed. `postgresql-10` and `repmgr10` services are enabled and running after the rollback procedure is performed.

**Comment by to-bar** [comment]
Ported to `develop` in #2654
