### ISSUE TITLE
[BUG] [Ubuntu] [PostgreSQL] [upgrade] Incorrect config file used by repmgrd service after upgrade

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2623]
**Describe the bug**
After PostgreSQL upgrade repmgrd service uses incorrect config file, i.e. `/etc/postgresql/10/main/repmgr.conf` instead of `/etc/postgresql/13/main/repmgr.conf`

```
root@pg1:~# systemctl status repmgrd
● repmgrd.service - LSB: Start/stop repmgrd
   Loaded: loaded (/etc/init.d/repmgrd; generated)
   Active: active (running) since Fri 2021-09-24 13:12:26 UTC; 12s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 1 (limit: 2239)
   CGroup: /system.slice/repmgrd.service
           └─32685 /usr/lib/postgresql/13/bin/repmgrd --config-file /etc/postgresql/10/main/repmgr.conf --daemonize=false
```

**How to reproduce**
1. Prepare config with 2 `postgresql` VMs and `replcation` enabled.
2. execute `epicli upgrade`

**Environment**
- OS: Ubuntu

**Additional context**
n/a

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Fixed. New config file for `repmgr` service is used after upgrade.

**Comment by mkyc** [comment]
@to-bar please create also PR to develop.

**Comment by to-bar** [comment]
Ported to `develop` in #2654
