### ISSUE TITLE
[FEATURE] Add possibility to scale up PostgreSQL cluster

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2626]
**Is your feature request related to a problem? Please describe.**
Currently Epiphany does not support scaling up of PostgreSQL cluster. I think we should consider to add such option in v2.0

**Describe the solution you'd like**
Changing the number of PostgreSQL nodes extending database cluster without losing any database data

**Additional context**
We need to save working state and use it before cluster extension to avoid:
- node_id duplication in repmgr
- cluster re-creation while running apply

Scaling down is not require

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
