### ISSUE TITLE
[FEATURE REQUEST] Restructure Epicli project folder

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2643]
**Is your feature request related to a problem? Please describe.**
Currently the core of the project "Epicli" lives in /core/src/epicli with the idea that this would extended with different additional projects. However as we now know we will transition to modules down the line. This setup does not make it very intuitive to work with as the devcontainer needs to be opened in /core/src/epicli and for documentation an extra windows needs to be opened.

**Describe the solution you'd like**
Because of this we want to restructure the project:
- Move the content of /core/src/epicli to the root of the project so that we can open the project in one single workspace/devcontainer. The structure of what is inside  /core/src/epicli will be left in tact for now.
- Merge /core/src/epicli/.gitignore into /.gitignore
- Fix paths for docker build inside:
   -  /core/src/epicli/setup.py
   - /.dockerignore
   - /Dockerfile
- Remove old certificate code in /core/src/epicli/.devcontainer/cert. This has not been maintained/tested properly when COVID started.
- Move CHANGELOG-x.x.md files to a subfolder inside docs and update CHANGELOG.md paths to these version
- Update /docs/home/DEVELOPMENT.md
- Add markdownlint plugin to devcontainer
- Adjust build pipelines for development branch

**Describe alternatives you've considered**
None

**Additional context**
https://docs.python-guide.org/writing/structure/

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested together with #2666 (part 2).
