### ISSUE TITLE
[BUG] Add validation to check hostnames for on-prem deployment

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2644]
**Describe the bug**
Deployment on-prem cluster failed due to the wrong hostname format.

``` 
kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\\nnodeRegistration.name: 
Invalid value: \\\"apm_master\\\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\\n
```

Check validations for _provider: any_  
currently, we have (https://github.com/epiphany-platform/epiphany/blob/develop/schema/any/validation/infrastructure/machine.yml): 
```
  properties:
    hostname:
      type: string
    ip:
      type: string
```
Proposal is to use the above regex as a pattern

**Expected behavior**
Validation should find wrong hostnames just before cluster setup

**Environment**
- Found during on-prem deployment
- OS: Ubuntu 18.04

**epicli version**: [`epicli --version`]
Found in v0.8.3 version but as I see in develop is still the same 
K8s 1.18.6

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
There are already similar [validations](https://github.com/epiphany-platform/epiphany/blob/develop/schema/common/validation/epiphany-cluster.yml) that can be used as example. I remember that I did something similar and it worked for sure - https://github.com/epiphany-platform/epiphany/pull/1814/files.

Also check [this](http://json-schema.org/understanding-json-schema/reference/regular_expressions.html#example) doc.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Hostname validation for `any` provider has been added.
A `DNS-1123` subdomain must consist of lower case alphanumeric characters, `-` or `.`, and must start and end with an alphanumeric character.
