### ISSUE TITLE
[FEATURE REQUEST] [PostgreSQL] Add "repmgr node check" to upgrade preflight checks and auto-tests

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2655]
**Is your feature request related to a problem? Please describe.**
In PostgreSQL upgrade preflight checks we run `repmgr cluster show` command to assert that PostgreSQL cluster is healthy.
However, we need to also run `repmgr node check` command on each node to ensure expected state.

For example issues with replication lag or WAL archiving are not detected now:

```
$ repmgr node check
Node "pg1":
        Server role: OK (node is primary)
        Replication lag: OK (N/A - node is primary)
        WAL archiving: CRITICAL (775 pending archive ready files, critical threshold: 128)
        Downstream servers: CRITICAL (1 of 1 downstream nodes not attached; missing: pg2 (ID: 2))
        Replication slots: OK (node has no replication slots)
```

```
$ repmgr node check
Node "pg2":
        Server role: OK (node is standby)
        Replication lag: CRITICAL (6750954 seconds, critical threshold: 600))
        WAL archiving: OK (0 pending archive ready files)
        Downstream servers: OK (this node has no downstream nodes)
        Replication slots: OK (node has no replication slots)
```

**Describe the solution you'd like**
1) Add `repmgr node check` command to `postgresql\tasks\preflight\upgrade.yml` and check for `\bCRITICAL\b` pattern in the output. There shouldn't be any matches.
2) Add `repmgr node check` command to Serverspec tests.

**Describe alternatives you've considered**
n/a

**Additional context**
Healthy PostgreSQL cluster is a **prerequisite for upgrade**. 

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: A new preflight check has been added to check the health of PostgreSQL nodes before starting the upgrade.
