### ISSUE TITLE
[BUG] [PostgreSQL] WAL files are not removed from $PGDATA/pg_wal directory

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2656]
**Describe the bug**
Before version 1.2.0 (PostgreSQL 13) we had set `archive_command` parameter to `'test ! -f /dbbackup/{{ inventory_hostname }}/backup/%f && gzip -c < %p > /dbbackup/{{ inventory_hostname }}/backup/%f'`.

Till version 1.1.0 this was OK since we had the task for creating target directory for WAL files to be archived:
```
# Placed here to avoid errors in log due to nonexistent directory
- name: Create directory for archiving WAL files
  file:
    path: /dbbackup/{{ inventory_hostname }}/backup/
    state: directory
    owner: postgres
    group: postgres
```

In version 1.1.0 the above task has been removed but without changing the `archive_command`.

There are two consequences of such mismatched configuration:
1) WAL files are not removed because they are not considered as archived.
Example after importing a database with size of 13 GB:
```
ls -la /var/lib/postgresql/10/main/pg_wal | wc -l

780

du -sh /var/lib/postgresql/10/main/pg_wal

13G
```

With correct configuration it would be:
```
ls -la /var/lib/postgresql/10/main/pg_wal | wc -l

69

du -sh /var/lib/postgresql/10/main/pg_wal

1.1G
```

2) A lot of warnings in PostgreSQL log file (~1/min), for example:
```
grep -c "archive command failed with exit code 2" /var/log/postgresql/postgresql-10-main.log
891
```

This bug was found during testing PostgreSQL upgrade after importing ~ 6 GB dump file.

**How to reproduce**
1. Deploy PostgreSQL cluster using epicli 1.1.0
2.  Create new database, e.g. `psql template1 -c 'create database test'`
3. Import roles, e.g. `psql test < /tmp/cicd17-autotest17-202108191758UTC.pgdumpall-roles.sql`
4. Import data, e.g. `psql test < /tmp/cicd17-autotest17-202108191758UTC.pgdump.sql`
5. Run `sudo find /var/lib/postgresql/10/main/pg_wal -maxdepth 1 -type f | wc -l`

**Expected behavior**
~ 65 files (or less) in /var/lib/postgresql/10/main/pg_wal/

```
$ repmgr node check | grep WAL
        WAL archiving: OK (0 pending archive ready files)
```

**Config files**
Defaults with replication enabled.

**Environment**
- Cloud provider: All
- OS: Ubuntu, RHEL not checked

**epicli version**: 1.1 or upgrade from 1.1

**Additional context**
Example solution (Ubuntu specific, for generic check https://www.postgresql.org/docs/10/sql-altersystem.html):

```
# On primary node:
$ psql -c "ALTER SYSTEM SET archive_command TO '/bin/true'"
ALTER SYSTEM

$ psql -c "SHOW archive_command"
                               archive_command
-----------------------------------------------------------------------------
 test ! -f /dbbackup/pg1/backup/%f && gzip -c < %p > /dbbackup/pg1/backup/%f
(1 row)

$ /usr/bin/pg_ctlcluster 10 main reload

$ psql -c "SHOW archive_command"
 archive_command
-----------------
 /bin/true
(1 row)
```

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
should also be back ported when finished, but only to 1.1

**Comment by przemyslavic** [comment]
:x: Works fine for new deployments, but doesn't work properly for upgrades.
Tasks to change the archive command are skipped, which results in the preflight check not fixing the setting:
```
2021-10-25T12:05:10.3902985Z 12:05:10 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Get archive_command value] ***********************************
2021-10-25T12:05:11.1332161Z 12:05:11 WARNING cli.engine.ansible.AnsibleCommand - [WARNING]: Database name has not been passed, used default database to connect
2021-10-25T12:05:11.1333487Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - to.
2021-10-25T12:05:11.1334412Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - ok: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com]
2021-10-25T12:05:11.1947877Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - ok: [ec2-2-2-2-2.eu-west-1.compute.amazonaws.com]
2021-10-25T12:05:11.2045299Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - 
2021-10-25T12:05:11.2046284Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Set archive_command to a new default (/bin/true)] ************
2021-10-25T12:05:11.2377626Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com]
2021-10-25T12:05:11.2392743Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-2-2-2-2.eu-west-1.compute.amazonaws.com]
2021-10-25T12:05:11.2498212Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - 
2021-10-25T12:05:11.2499281Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Reload PostgreSQL configuration] *****************************
2021-10-25T12:05:11.2828132Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com]
2021-10-25T12:05:11.2855944Z 12:05:11 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-2-2-2-2.eu-west-1.compute.amazonaws.com]
```
From what I was able to debug, the possible reason is a command `pg_invalid_archive_command` written on two lines
```
        pg_invalid_archive_command: |-
          test ! -f /dbbackup/{{ inventory_hostname }}/backup/%f && \
            gzip -c < %p > /dbbackup/{{ inventory_hostname }}/backup/%f
```
so additional characters will appear, and thus the condition is never met.
The value for `archive_command` is changed later during the upgrade, so it seems fine after the upgrade, but we want to have this fixed here in preflight check.
```
TASK [preflight : Get archive_command value] ***************************************************************************************************************
[WARNING]: Database name has not been passed, used default database to connect to.
ok: [ci-11todevazrhflannel-postgresql-vm-1]
ok: [ci-11todevazrhflannel-postgresql-vm-0]

TASK [preflight : debug pg_archive_command.query_result[0].archive_command] ********************************************************************************
ok: [ci-11todevazrhflannel-postgresql-vm-1] => {
    "msg": "test ! -f /dbbackup/ci-11todevazrhflannel-postgresql-vm-1/backup/%f && gzip -c < %p > /dbbackup/ci-11todevazrhflannel-postgresql-vm-1/backup/%f"
}
ok: [ci-11todevazrhflannel-postgresql-vm-0] => {
    "msg": "test ! -f /dbbackup/ci-11todevazrhflannel-postgresql-vm-0/backup/%f && gzip -c < %p > /dbbackup/ci-11todevazrhflannel-postgresql-vm-0/backup/%f"
}

TASK [preflight : debug pg_invalid_archive_command] ********************************************************************************************************
ok: [ci-11todevazrhflannel-postgresql-vm-1] => {
    "msg": "\"test ! -f /dbbackup/ci-11todevazrhflannel-postgresql-vm-1/backup/%f && \\\n  gzip -c < %p > /dbbackup/ci-11todevazrhflannel-postgresql-vm-1/backup/%f\""
}
ok: [ci-11todevazrhflannel-postgresql-vm-0] => {
    "msg": "\"test ! -f /dbbackup/ci-11todevazrhflannel-postgresql-vm-0/backup/%f && \\\n  gzip -c < %p > /dbbackup/ci-11todevazrhflannel-postgresql-vm-0/backup/%f\""
}

TASK [preflight : debug pg_archive_command.query_result[0].archive_command == pg_invalid_archive_command] **************************************************
ok: [ci-11todevazrhflannel-postgresql-vm-1] => {
    "msg": false
}
ok: [ci-11todevazrhflannel-postgresql-vm-0] => {
    "msg": false
}
```
Moving back to TODO.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed.
:heavy_check_mark: `epicli apply` v1.1.x
:heavy_check_mark: `epicli upgrade` v1.1.0 to v1.3.0dev
