### ISSUE TITLE
[FEATURE REQUEST] Refactor K8s roles

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2662]
**Is your feature request related to a problem? Please describe.**
The idea of this task is to have K8s-related tasks decoupled from other ones. For PostgreSQL we already have `preflight` and  `upgrade` tasks in one place.

**Describe the solution you'd like**
Plan and refactor K8s roles.

**Describe alternatives you've considered**
-

**Additional context**
- Related K8s roles: `kubernetes_*`.
- Shouldn't be done in parallel with K8s upgrade tasks.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
