### ISSUE TITLE
[FEATURE REQUEST] Project re-structure part 2

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2666]
**Is your feature request related to a problem? Please describe.**
In our current setup we have a 2 stage build for the **Epicli** container. The first stage builds a Python package of **Epicli** which is then installed in the second stage inside the final docker image. This introduces a few issues:

- Builds of the container take longer.
- We have some of our code in the **_/data/_** folder  which is only needed because of the Python package:
   - Ansible code: **_/data/common/ansible_**
   - Spec tests: **_/data/common/tests_**
   - Terraform scripts: **_/data/aws/terraform, /data/azure/terraform_**
  These locations are not intuitive when developing **Epicli**.

The Python package was meant to be distributed on the PyPi registry, however because of all the various dependencies we have, we now know this will never be the case.  

**Describe the solution you'd like**
- Remove the build of the PyPi package and add the needed folders directly to the image inside **_/epicli_**
- Python dependencies can be installed directly using Pip and **_/.devcontainer/requirements.txt_** as in the devcontainer
- Calling epicli as a command can be done using an **alias** as is done in devcontainer.
- Restucture the **_/data_** folder to make more sense, contant of the folders will remain unchanged: 
  - Move current content of **_/tests/_** inside a subfolder **_/tests/unit_** and adjust the paths accordingly.
  - Move **_/data/common/tests_** content to **_/tests/spec_**  and adjust the paths accordingly.
  - Move   **_/data/common/ansible_** content to  **_/ansible_** and adjust the paths accordingly.
  - Move   **_/data/aws/terraform_** content to  **_/terraform/aws_** and adjust the paths accordingly.
  - Move   **_/data/azure/terraform_** content to  **_/terraform/azure_** and adjust the paths accordingly.
  - Rename remaining **_/data_** folder to **_/schema_**  is this will only contain defaults and validation files. Then adjust the paths accordingly.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Successfully deployed `Ubuntu`/`RHEL`/`CentOS` clusters with all components enabled in the pipeline. Additionally, unit tests and spec tests were executed. Also tested in devcontainer.
