### ISSUE TITLE
[FEATURE REQUEST] Always GENERATE a new password for Ansible-vault

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2668]
**Is your feature request related to a problem? Please describe.**
Restarting the epicli installation process keeps the old ansible-vault password stored in the file
even though it asks for a new password at the very beginning of the process.

So if one will fall into temptation of generating **a new** password then the installation process will fail with the error described below.

**Describe the solution you'd like**
It would be good to delete the old password if the new one is being asked for at the process begining.

**Additional context**
The error that occurs when using the new password:
```
TASK [kubernetes_master : Create PKI files] fatal: [ubu1804a]: FAILED! => {
    "msg": "Decryption failed (no vault secrets were found that could decrypt)"
}
```

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
