### ISSUE TITLE
Remove PgBouncer standalone installation

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2680]
**Is your feature request related to a problem? Please describe.**
We say in [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-set-up-postgresql-connection-pooling) that PgBouncer standalone installation is deprecated and will be removed.

**Describe the solution you'd like**
1. Remove ability to specify this setting in configuration, modify schema
2. Clean up Ansible configuration
3. Update documentation

**Describe alternatives you've considered**

-

**Additional context**

-

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Lets remember about very clear change log entry.

**Comment by rafzei** [comment]
It's clear for me, links:

Defaults:
https://github.com/epiphany-platform/epiphany/blob/e64dd05451d6d81ff4322ab6f2319353d0579e0b/schema/common/defaults/configuration/postgresql.yml#L90-L91

Schema:
https://github.com/epiphany-platform/epiphany/blob/e64dd05451d6d81ff4322ab6f2319353d0579e0b/schema/common/validation/configuration/postgresql.yml#L71-L75

Role:
https://github.com/epiphany-platform/epiphany/tree/develop/ansible/playbooks/roles/postgresql

Docs:
https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-set-up-postgresql-connection-pooling

**Comment by to-bar** [comment]
pgBouncer causes the following error when installing on Ubuntu 20.04 (Azure & AWS) on `Extensions | PgBouncer | Restart systemd service` task:
```
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: Stopping LSB: start pgbouncer...
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 pgbouncer[25630]:  * Stopping PgBouncer pgbouncer
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 pgbouncer[25634]: start-stop-daemon: matching only on non-root pidfile /var/run/postgresql/pgbouncer.pid is insecure
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 pgbouncer[25630]:    ...fail!
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: pgbouncer.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: pgbouncer.service: Failed with result 'exit-code'.
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: Stopped LSB: start pgbouncer.
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: pgbouncer.service: Found left-over process 24592 (pgbouncer) in control group while starting unit. Ignoring.
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: Starting LSB: start pgbouncer...
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 pgbouncer[25635]:  * Starting PgBouncer pgbouncer
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 pgbouncer[25635]:    ...fail!
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: pgbouncer.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: pgbouncer.service: Failed with result 'exit-code'.
Dec  2 18:21:02 ci-devazurubuflannel-postgresql-vm-0 systemd[1]: Failed to start LSB: start pgbouncer.
```
hence this task will be done before #1331.

**Comment by przemyslavic** [comment]
Looks like everything still works fine without `pgbouncer` :boar:
