### ISSUE TITLE
[FEATURE REQUEST] :bookmark_tabs: Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2698]
**Is your feature request related to a problem? Please describe.**
People don't really know how to contribute. 

**Describe the solution you'd like**
Create CONTRIBUTING.md [(example)](https://github.com/github/docs/blob/main/CONTRIBUTING.md) as a how-to guide
Add in README.md the link and info that we are open to new contributors.

**Additional context**
Consider creating [CODE_OF_CONDUCT.md](https://opensource.guide/code-of-conduct/) as well
- template generator: https://bttger.github.io/contributing-gen-web/
- may be useful: https://mozillascience.github.io/working-open-workshop/contributing/ 

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
We already have this documentation in place.
