### ISSUE TITLE
[UPGRADE] Upgrade Prometheus to v2.31.1 and Alertmanager  to v0.23.0

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2700]
**Is your feature request related to a problem? Please describe.**
Upgrade Prometheus and Alertmanager to the latest version:
- Prometheus  [2.31.1](https://github.com/prometheus/prometheus/releases/tag/v2.31.1)
- Alertmanager  [0.23.0](https://github.com/prometheus/alertmanager/releases/tag/v0.23.0)

Check if there are any breaking changes we should take care of when upgrading.

**Additional context**
Internal request

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by sbbroot** [comment]
Alertmanager also needs to be upgraded to version: [0.23.0](https://github.com/prometheus/alertmanager/releases/tag/v0.23.0)

**Comment by przemyslavic** [comment]
:heavy_check_mark: `apply` Prometheus + Alertmanager x86_64
:heavy_check_mark: `apply` Prometheus + Alertmanager aarch64
:heavy_check_mark: `upgrade` from v1.0 Prometheus + Alertmanager x86_64
:heavy_check_mark: `upgrade` from v1.1 Prometheus + Alertmanager aarch64

Tested on all OSes.
