### ISSUE TITLE
[FEATURE REQUEST] Upgrade Terraform to at least v0.12.31

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2706]
**Is your feature request related to a problem? Please describe.**
Currently we use Terraform v0.12.6.
This version of Terraform has an outdated GPG key and is unable to verify new provider releases.
[HCSEC-2021-12 - Codecov Security Event and HashiCorp GPG Key Exposure](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512)

```
11:03:25 INFO cli.engine.terraform.TerraformCommand - Running: "terraform init -no-color /shared/build/devawsubuflannel/terraform/"
11:03:25 INFO cli.engine.terraform.TerraformCommand - 
11:03:25 INFO cli.engine.terraform.TerraformCommand - Initializing the backend...
11:03:25 INFO cli.engine.terraform.TerraformCommand - 
11:03:25 INFO cli.engine.terraform.TerraformCommand - Initializing provider plugins...
11:03:25 INFO cli.engine.terraform.TerraformCommand - - Checking for available provider plugins...
11:03:25 INFO cli.engine.terraform.TerraformCommand - - Downloading plugin for provider "aws" (hashicorp/aws) 2.26.0...
11:03:28 INFO cli.engine.terraform.TerraformCommand - 
11:03:28 INFO cli.engine.terraform.TerraformCommand - 
11:03:28 INFO cli.engine.terraform.TerraformCommand - Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
11:03:28 INFO cli.engine.terraform.TerraformCommand - 
11:03:28 INFO cli.engine.terraform.TerraformCommand - 
11:03:28 INFO cli.engine.terraform.TerraformCommand - Terraform has been successfully initialized!
11:03:28 INFO cli.engine.terraform.TerraformCommand - 
11:03:28 INFO cli.engine.terraform.TerraformCommand - You may now begin working with Terraform. Try running "terraform plan" to see
11:03:28 INFO cli.engine.terraform.TerraformCommand - any changes that are required for your infrastructure. All Terraform commands
11:03:28 INFO cli.engine.terraform.TerraformCommand - should now work.
```

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
This would also be a good one to move away from the https://github.com/epiphany-platform/terraform-bin installation and just install it straight in the (dev)container.

**Comment by cicharka** [comment]
[This PR](https://github.com/epiphany-platform/epiphany/pull/2852) is upgrading Terraform up to 1.1.3
