### ISSUE TITLE
[FEATURE REQUEST] Create a pipeline for automatic testing of backup and recovery feature

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2712]
**Is your feature request related to a problem? Please describe.**
Create a pipeline for automatic testing of backup and recovery of supported components.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Added to epic #2961, lets set this up properly from the start:)

**Comment by przemyslavic** [comment]
@seriva we already have a pipeline to test backup and recovery: https://dev.azure.com/abb-epiphany/epiphany/_release?_a=releases&view=all&definitionId=253
I would just close this task, as migrating to the YAML-based pipelines will apply to all pipelines.

**Comment by seriva** [comment]
Closing as per @przemyslavic  suggestions
