### ISSUE TITLE
[FEATURE REQUEST] Change user login message after #1306 is completed

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2715]
**Is your feature request related to a problem? Please describe.**
There was a [discussion](https://github.com/epiphany-platform/epiphany/pull/2714#issuecomment-947454999) which login message user should see. It was decided to have something like the current Epiphany version installed and the link to history file created in #1306.

**Describe the solution you'd like**

- Change login message. Before starting a task discuss and confirm what exactly should be displayed.
- Add automated tests for file creation and its contents (task #1306)
- Update documentation for this task and #1306 

**Describe alternatives you've considered**
No.

**Additional context**
https://github.com/epiphany-platform/epiphany/blob/b724f7d1968308f8324cc9c3a6dc1138cb4f509f/ansible/playbooks/roles/common/tasks/main.yml#L92

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
I would vote for some short note from the last entry with info about log location like:

```
Current epicli version: 1.3.0dev, see details: /var/lib/epiphany/history.yml
```

**Comment by plirglo** [comment]
Ubuntu apply:
![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/7c863473-9b66-4df7-9d56-c1ef6a3df505)

**Comment by plirglo** [comment]
Red Hat apply:
![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/751506a9-740e-44e6-91e2-eeae3e7bd413)

**Comment by plirglo** [comment]
Ubuntu upgrade from 1.0.1 to 1.3dev:
![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/5611b9c9-3152-4cd0-83f6-901beae22263)

**Comment by plirglo** [comment]
Red Hat upgrade from 1.0.1 to 1.3dev:
![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/6bc8d815-05ab-4d5a-b193-1b992b7bb32c)

**Comment by plirglo** [comment]
@przemyslavic i think we can merge this, i'm moving it to DoD, move back if you have any doubts
