### ISSUE TITLE
[FEATURE REQUEST] Change container runtime

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2716]
**Is your feature request related to a problem? Please describe.**
Dockershim deprecation notice - https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Describe the solution you'd like**
Switchc container runtime to the new one as of the outcome of the blocking spike.

**Describe alternatives you've considered**
No.

**Additional context**
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [x] updated
  - [ ] not needed
- [x] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [x] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by mkyc** [comment]
Brief description of decisions we made:

In this task:
1) reconfigure kubernetes to use Containerd directly
2) remove docker from epicli clusters
3) test if filebit consumes containers logs correctly

In another task: 
- install Podman

**Comment by mkyc** [comment]
We decided to move it to version 2.0.0.

**Comment by rafzei** [comment]
As above, there is no pressure for this change. The changes were mostly done for the current code state. After v1.3 release we should check/change:
- if there are additional steps needed after the k8s upgrade (#2659 and #2660)
- changelog and documentation

The changes are in [feature/containerd](https://github.com/epiphany-platform/epiphany/tree/feature/containerd) branch.
Im moving it back to to-do section

**Comment by atsikham** [comment]
May be useful - https://jimangel.io/post/dockershim-kubernetes-v1.24/
