### ISSUE TITLE
[SPIKE] Check versions of Prometheus and its surrounding to which we want to upgrade

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2719]
**Is your spike related to a problem or idea? Please describe.**
Prepare to Prometheus environment upgrade. 

**Describe the outcome you'd like**
We need to know versions of all Prometheus-related components (prometheus, Grafana, exporters, etc) which we want to upgrade to. 

**What is the reason or source for the spike**
Upgrade of Prometheus stuff is planned for this Q. 

**Additional context**
N/A

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by mkyc** [comment]
This is also about exporters.

**Comment by sbbroot** [comment]
**Current component versions**:
- Prometheus: 2.10.0
- Alertmanager: 0.17.0
- Grafana: 7.3.5

**exporters**:
- Node Exporter: 1.0.1
- Kafka Exporter: 1.2.0
- HAProxy Exporter: 0.10.0
- JMX Exporter: 0.12.0
- Postgres Exporter: 0.9.0


**Newest available stable component versions**:
- Prometheus: [2.31.1](https://github.com/prometheus/prometheus/releases/tag/v2.31.1)
- Alertmanager: [0.23.0](https://github.com/prometheus/alertmanager/releases/tag/v0.23.0)
- Grafana: [8.2.4](https://github.com/grafana/grafana/releases/tag/v8.2.4)

**exporters**:
- Node Exporter: [1.2.2](https://github.com/prometheus/node_exporter/releases/tag/v1.2.2)
- Kafka Exporter: [1.4.2](https://github.com/danielqsj/kafka_exporter/releases/tag/v1.4.2)
- HAProxy Exporter: [0.12.0](https://github.com/prometheus/haproxy_exporter/releases/tag/v0.12.0)
- JMX Exporter: [0.16.1](https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.16.1)
- Postgres Exporter: [0.10.0](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.0)

**Comment by seriva** [comment]
Epic is created with all necessary tasks groomed.  IMO we can move this to DoD.
