### ISSUE TITLE
[SPIKE] Find and analyze alternatives for Docker

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2720]
**Is your spike related to a problem or idea? Please describe.**
The latest release of the RHEL 8 / CentOS 8. Red Hat has built its own tools, buildah and podman, which aim to be compatible with existing Docker images and work without relying on a daemon. As well Kubernetes stopped support Docker as container runtime. 

**Describe the outcome you'd like**
Find and analyze alternatives for Docker container engine (containerd, cri-o, any other) and Docker command compatible with k8s and supported by Ubuntu 20.04 and RHEL8

**What is the reason or source for the spike**
Kubernetes is deprecating native support for Docker and Red Hat is switching default containers to Podman on RHEL 8.x.

**Additional context**
- [RHEL 8.x documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index)
- [Kubernetes Changelog 1.20 - deprecation](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation)

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [x] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [x] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by atsikham** [comment]
In the scope of this spike please also check:
* container runtime [options](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) and how they are compatible with Podman.
* which components we need a client like Podman/Docker for - may be this compatibility mentioned above is not necessary, like images are built/pushed by Podman and then containers run in K8s with containerd.

**Comment by to-bar** [comment]
Docker related Filebeat feature (to be checked whether it works with other container runtime or Filebeat has equivalent processor):
https://github.com/epiphany-platform/epiphany/blob/7ad0c14c58fcab8f92da85ab63a6b068b16d8289/ansible/playbooks/roles/filebeat/templates/filebeat.yml.j2#L126

**Comment by seriva** [comment]
Besides the comparison for the runtime and management options is there any conclusion to be drawn that can be added or is that up for discussion?

On a side note from the dev perspective, docker will remain the tool of choice, from what I know corporate license is going to be provided for everyone in the org.
