### ISSUE TITLE
[FEATURE REQUEST] Document upgrade Red Hat / CentOS 7 to v 8.x

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2734]
See comments below:

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [x] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by plirglo** [comment]
_This task is about inplace upgrade Epiphany cluster based on Red Hat / Cent OS 7 to system version 8, if you are looking for RHEL8 fresh installation task check [here](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1332)_

System upgrade process should be conducted by user with documentation provided by Red Hat and Cloud provider with additional documentation provided by Epiphany. 
Output of this task should be consistent documentation of tested path to upgrade OS on existing cluster based on Epiphany LTS 1.0.x to system version 8.x.

Helpful resources:
- [Red Hat docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index)
- [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-in-place-upgrade)

Known issues / limitations:
- system must be upgraded to latest minor version ```yum -y update```
- PAM module pam_pkcs11 is no longer available in RHEL-8 since it was replaced by SSSD, pam_pkcs11 needs to be disabled:
  ```leapp answer --section remove_pam_pkcs11_module_check.confirm=True --add```
- pata_acpi kernel module needs to be removed before upgrade:
  ```rmmod pata_acpi```
- Some packages may be removed from system since they are not signed by Red Hat - this impacts Postgresql10 - application is removed during upgrade (only application, not data) - this needs to be investigated, please see [this document](https://access.redhat.com/articles/4977891#actors) 

Please check spike results place in Conluence page before start

**Comment by to-bar** [comment]
Related task: #2849
