### ISSUE TITLE
[FEATURE REQUEST] Skip download images if custom_registry provided

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2736]
**Is your feature request related to a problem? Please describe.**
Currently, if you provide custom_registry IP address in `shared_config` all k8s deployments will use that for images source.
In that case, the repository machine will be created obviously, but with unnecessary `the images part`.

**Describe the solution you'd like**
Refactor repository role to do not download images if custom_registry is in place.
In addition, check why ansible creates `[image_registry]` group in inventory pointing to the repository machine (and if we can change that)

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by rafzei** [comment]
This could be done right after #805

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
