### ISSUE TITLE
[FEATURE REQUEST] update repo description

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2740]
**Is your feature request related to a problem? Please describe.**
Our description says that Epiphany is a full industrialized automation of Kubernetes and Docker plus additional builtin services/components. 

**Describe the solution you'd like**
We should update that general description that its more about all other middleware components with Ansible and Terraform usage. Not only docker. 

We also need to make it shorter to fit into short description box. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Already updated a while back, so closing.
