### ISSUE TITLE
[BUG] epicli generates cluster definitions with value unsuitable to the specified cloud provider

### ISSUE THREAD

**Issue by asciible** [epiphany-platform/epiphany#2742]
**Describe the bug**
`epicli init` generates a cluster definition with incorrect **admin_user** value for AWS
Subsequently, this generates a failure to connect to the created instances during the configuration phase with ansible.

**How to reproduce**
1. `epicli init -n demo1 -p aws`
2. `grep -A1 admin_user build/demo1/demo1.yml`
    > admin_user:
    >   name: operations

**Expected behavior**
**admin_user** value should be `ubuntu` for AWS instances with default OS.

**Environment**
- Cloud provider: AWS
- OS: Ubuntu 18.04.4 LTS

**epicli version**:1.2.0

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
@asciible this has already been fixed in [develop](https://github.com/epiphany-platform/epiphany/pull/2677/commits/4d1dce553f4dcce5a03332f34213d59e0857f9d9). 
And it looks like it has been decided not to backport it (original task #2497).
