### ISSUE TITLE
[UPGRADE] Upgrade Node exporter to v1.3.1

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2747]
**Describe the solution you'd like**
Node exporter needs to be upgraded to the newest version: [1.3.1](https://github.com/prometheus/node_exporter/releases/tag/v1.3.1)

---

**DoD checklist**

* [ ] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Spike about versions was in #2719.

**Comment by romsok24** [comment]
What was done:

- requrements* file updated for every distro  ( details in [the branch](https://github.com/epiphany-platform/epiphany/tree/feature/upgr-node-eporter-2747) )
- changes tested with epicli on ubu18
  - run the: epicli test -b ....... -g <component ie. node_exporter>
  - tested epicli upgrade -b build/dir/ (node_exporter is not in the scope of epicli upgrade command )
- [the PR](https://github.com/epiphany-platform/epiphany/pull/2761) was created ans passed for running the test build pipelines of updated code.

**Comment by romsok24** [comment]
@sbbroot Are we ok to upgrade to the currently newest version which is already not the one described in this issue and [here](https://github.com/epiphany-platform/epiphany/issues/2719)?

**Comment by sbbroot** [comment]
@romsok24 Yes.

**Comment by przemyslavic** [comment]
✔️ Tested `apply` and `upgrade` from v1.0 (x86_64) and from v1.1 (aarch64).

Upgrade of Node Exporter as a DaemonSet is tracked in #2782.
