### ISSUE TITLE
[UPGRADE] Upgrade Kafka exporter to v1.4.0

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2748]
**Describe the solution you'd like**
Kafka exporter needs to be upgraded to the newest version: [1.4.2](https://github.com/danielqsj/kafka_exporter/releases/tag/v1.4.2)

Update: We have chosen version 1.4.0 since 1.4.1 and 1.4.2 contain critical bug.

**Additional context**
Check if this fixes #1221.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Spike about versions was in #2719.

**Comment by przemyslavic** [comment]
I found a problem with the `/metrics` endpoint not responding is some cases (Prometheus is not able to scrape any data). More investigation in progress.

The issue occurs with new deployments and also with upgraded clusters and seems to be nondeterministic.

**Comment by to-bar** [comment]
> I found a problem with the `/metrics` endpoint not responding is some cases (Prometheus is not able to scrape any data). More investigation in progress.
> 
> The issue occurs with new deployments and also with upgraded clusters and seems to be nondeterministic.

Due to the issue we decided to upgrade to version 1.4.0 instead of 1.4.2 (1.4.1 also affected).

**Comment by przemyslavic** [comment]
✔️ Tested `apply` and `upgrade` from v1.0 (x86_64) and from v1.1 (aarch64).

Additional PR #2796.
