### ISSUE TITLE
[UPGRADE] Upgrade HAProxy exporter to the newest version

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2749]
**Describe the solution you'd like**
HAProxy exporter needs to be upgraded to the newest version: [0.12.0](https://github.com/prometheus/haproxy_exporter/releases/tag/v0.12.0)

**Additional context**
Maybe consider #1739 to see if its viable in this scope.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Spike about versions was in #2719.

**Comment by mkyc** [comment]
This one references #1739
