### ISSUE TITLE
[UPGRADE] Upgrade JMX exporter to the newest version

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2750]
**Describe the solution you'd like**
JMX exporter needs to be upgraded to the newest version: [0.16.1](https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.16.1)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Spike about versions was in #2719.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested `apply` and `upgrade` from v1.0 (x86_64) and from v1.1 (aarch64).
