### ISSUE TITLE
[UPGRADE] Upgrade Postgres exporter to the newest version

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2752]
**Describe the solution you'd like**
Postgres exporter needs to be upgraded to the newest version: [0.10.0](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.0)

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
Version proposition is in #2719 but ensure that it's still the newest one.

**Comment by przemyslavic** [comment]
Tested scenarios:
:heavy_check_mark: `epicli apply` -> `epicli apply` (x86_64 and aarch64)
:heavy_check_mark: `epicli apply` v1.0.1 -> `epicli upgrade` -> `epicli upgrade` (x86_64)
:heavy_check_mark: `epicli apply` v1.2.0 -> `epicli upgrade` -> `epicli upgrade` (aarch64)
:heavy_check_mark: Verified PostgreSQL metrics in Grafana.
