### ISSUE TITLE
[BUG] Failing offline upgrade: 'download_script_subdir' is undefined

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2753]
**Describe the bug**
Offline upgrade i is failing because of missing 'download_script_subdir' variable [dev / 1.3]

**How to reproduce**
1. Install 1.0.x cluster`
2. Execute upgrade to latest dev version:\
```
epicli upgrade -b build/prjx-cluster/ --offline-requirements /shared/requirements
```

**Expected behavior**
Cluster should be upgraded to latest version

**Environment**
- Cloud provider: All
- OS:  Ubuntu 18.04.4 LTS

**epicli version**: 1.3 [dev]

**Additional context**
Error:
```
08:25:22 INFO cli.engine.ansible.AnsibleCommand - TASK [repository : Remove old files from epirepo] ******************************
08:25:22 ERROR cli.engine.ansible.AnsibleCommand - fatal: [prjx-node1]: FAILED! => {"msg": "{{ files_found | difference(files_to_preserve) }}: {{ requirements_file_lines | select('match', 'https?://') | map('regex_replace', '\\s+#.*$', '') | map('trim') | map('regex_replace', '^.+[/\\s](?P<filename>[\\S]+)$', '\\g<filename>') }}: {{ lookup('file', _requirements_file_path).split('\n') }}: download-requirements/{{ download_script_subdir }}/requirements.{{ ansible_architecture }}.txt: 'download_script_subdir' is undefined"}
```

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by cicharka** [comment]
Solution PR #2754 tested with steps:
- cluster created with version 1.0.1
- kubernetes component upgraded with version 1.3.0dev, PR #2754 

Result on k8s master vm:
![image](https://user-images.githubusercontent.com/93913624/143203094-65d96775-f9a0-4ac6-840d-b2a5973c91db.png)
