### ISSUE TITLE
[FEATURE REQUEST] Upgrade Python dependencies to the latest

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2755]
**Is your feature request related to a problem? Please describe.**
Currently there are several CEV issues related to Python libraries.

**Describe the solution you'd like**
Upgrade all Python dependencies to the latest versions to mitigate security issues. 

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested `epicli apply` with all components enabled on all supported OSs + aarch64
