### ISSUE TITLE
[FEATURE REQUEST] install podman

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2757]
**Is your feature request related to a problem? Please describe.**
due to planned changes in #2716 we will need to have podman on machines to be able to interact with containers

**Describe the solution you'd like**
Replace Docker with Podman

**Describe alternatives you've considered**
None

**Additional context**
#2720

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
When we change the container runtime to containerd (#2716) Docker itself would only be used on the repository machine for running the registry and retagging images. 

Re-tagging images could alternatively done by Skopeo but the image registry would require Docker/[Podman](https://thenewstack.io/tutorial-host-a-local-podman-image-registry/).

For me I don't feel the switch from Docker -> Podman on the registry machine makes any sense. Also it is confusing for the teams as docker is part of their workflow and known. Yes Podman is similar and we can even do an alias, but that would make it even more confusing IMO.

I say we don't switch it for.

**Comment by atsikham** [comment]
If RHEL still supports Docker, I would rather work on Containerd switch, put this task on hold and review after container runtime switching / os upgrade.

**Comment by erzetpe** [comment]
@atsikham proposal is very sound in my opinion.

**Comment by to-bar** [comment]
We use Docker CE, not EE, which is not supported on RHEL. First I would check whether Docker CE works fine on RHEL 8. If yes, I would agree with @seriva to keep it on repository host as is (we can switch later to something else - we need 1) tool for loading images (skopeo?) and 2) tool for hosting image registry, both are done by Docker CE now). Otherwise (when Docker CE will not work on RHEL 8) we will need a spike to switch in sync with RHEL upgrade.

**Comment by seriva** [comment]
Ok so lets move forward with runtime replacement to containerd and upgrade of RedHat. During this RedHat upgrade if it turns out that Docker CE is not working we can still block this task by this.

**Comment by to-bar** [comment]
After getting more knowledge I see the following options to consider:

**1. Docker CE for hosting image registry (on `image_registry` host) and crictl on K8s nodes (for debugging)**

**Pros:**
- No image registry migration from Docker to Podman required
- Compatibility for single machine installation - Docker provides containerd as dependency
- crictl is already installed (as kubeadm dependency)

**Cons:**
- Docker uses a daemon
- Docker uses more space (see below)
- Docker installation takes more time (see below)

```
--- Docker
Install  19 Packages

Total download size: 93 M
Installed size: 388 M

real    0m59.927s
user    0m43.510s
sys     0m2.402s

--- Podman
Install  22 Packages

Total download size: 40 M
Installed size: 135 M

real    0m46.485s
user    0m37.660s
sys     0m2.072s
```

**2. Podman for hosting image registry (on `image_registry` host) and crictl on K8s nodes (for debugging)**

**Pros:**
- Podman has a daemon-less architecture
- Podman uses less space
- Podman installation takes less time (see below)

**Cons:**
- Image registry migration from Docker to Podman required (`epicli upgrade` mode)
- Single machine installation may fail: podman-1:3.4.2 requires runc >= 1.0.0-57 which conflicts with containerd.io (1.4.12)
**On RHEL 8 I was not able to install Podman having containerd.io (1.4.12) already installed.**

Info about setting up image registry with Podman:
https://computingforgeeks.com/create-docker-container-registry-with-podman-letsencrypt/
https://thenewstack.io/tutorial-host-a-local-podman-image-registry/

**3. containerd for hosting image registry (on `image_registry` host) and crictl on K8s nodes**

**Pros:**
- No Docker nor Podman (less dependencies)

**Cons:**
- Spike needed to confirm
- Uncommon `ctr` command syntax
- "Migration" from Docker required
