### ISSUE TITLE
[BACKPORT][v1.0.2] - Logging component backup fix

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2764]
Please backup PR [#2744](https://github.com/epiphany-platform/epiphany/pull/2744) into Epiphany v1.0

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested backup and recovery of logging component
