### ISSUE TITLE
[BUG] Issue creating service principal on Azure.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2774]
**Describe the bug**
Under certain azure ad account creation of the service principle will fail with the message:

**Values of IdentifierUris property must use a verified domain of the organization or its subdomain**

Solution is to upgrade the version of azure-cli from 2.23 ->  2.29.0 (Not 2.31.0, see comment below.) 

**How to reproduce**
Ask @przemyslavic  or @seriva to create a cluster ...  :neutral_face:

**Expected behavior**
Not to give this error  :neutral_face:

**Environment**
- Cloud provider: Azure
- OS: All

**Additional context**
https://stackoverflow.com/questions/69591788/getting-hostnamenotonverifieddomain-when-setting-appid-uri-on-azure-ad-applica
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested locally in devcontainer - created service principal without any issues.
:heavy_check_mark: Tested in the pipeline - deployed clusters with all components enabled.

**Comment by seriva** [comment]
Re-opening as Azure-cli 2.31.0 breaks non SP logins for our Terraform provider because of new token mechanism:

https://docs.microsoft.com/en-us/cli/azure/msal-based-azure-cli

2.29.0 does not have new token mechanism and it solves the problem described in this issue so downgrading from 2.31.0 to 2.29.0 again.

**Comment by przemyslavic** [comment]
Tested both `devcontainer` and `epicli` container:
✔️ `use_service_principal: false`
✔️ `use_service_principal: true` - creating a new service principal
✔️ `use_service_principal: true` - using an existing service principal
