### ISSUE TITLE
[BACKPORT][v1.0.2] - Fix kafka-exporter service doesn't start after restarting kafka VMs

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2776]
Backport fix for kafka-exporter service from PR [#2772](https://github.com/epiphany-platform/epiphany/pull/2772)

kafka-exporter.service file modifications need to re-used.

```
ExecStartPre=/bin/bash -c '(while ! ss -H -t -l -n sport = :9092 | grep -q "^LISTEN.*:9092"; do echo "Waiting for Kafka Broker port to be listening..."; sleep 2; done)'
```

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Kafka-exporter service starts with no issues after system reboot waiting for kafka broker port to be listening.
