### ISSUE TITLE
[FEATURE REQUEST] Remove hardcoded tag version from infra config

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2780]
**Is your feature request related to a problem? Please describe.**
The tag version is hardcoded pointing to the old epicli version and not in all resources. [Link](https://github.com/epiphany-platform/epiphany/blob/develop/schema/aws/defaults/infrastructure/virtual-machine.yml#L14-L15)

**Describe the solution you'd like**
The tag should refer to the deployed epicli version and should be assigned to every resource (after epicli apply). We should use the placeholder `SET_BY_AUTOMATION` in defaults.

**Describe alternatives you've considered**
None

**Additional context**
Applied only for aws, but check if we could follow the same approach in azure.

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Tested together with #2853.
