### ISSUE TITLE
[BUG] The target namespace for node-exporter is not coherent

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2782]
**Describe the bug**
The component node-exporter within the k8s daemonset  installation variant ( k8s as cloud service )
is not coherent in the context of target namespace:
 - on one one hand [the component defaults](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/node_exporter/defaults/main.yml) are targeting it to the dedicated ns (_epi-monitoring_) 
 - on the other hand the component upgrade procedure (ie. [check for existence task](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/upgrade/tasks/node-exporter.yml#:~:text=command%3A%20helm%20list%20%2D%2Doutput%20json) or [uninstall task](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/node_exporter/tasks/uninstall-node-exporter-as-daemonset.yml) ) will try to operate on the _default_ ns only 

This will cause the node-exporter component to not being updated upon the epiphany upgrade process.

The bug perceived by @przemyslavic .

**How to reproduce**
A ) install epiphany in the `k8s_as_cloud_service: True` mode
B ) upgrade epiphany 

**Expected behavior**
The node-exporter component should be operated (installed, upgraded) from within the one and only k8s namespace 

**Environment**
Epiphany installation with  k8s daemonset installation enabled ( `k8s_as_cloud_service` configuration parameter set to True )

**epicli version**: [`epicli --version`]
1.3.0dev

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
The purpose of these tasks was to uninstall node exporter from the default namespace (it was installed there at the beginning) and to install it in dedicated `epi-monitoring`. It was a kind of fix. Now, when upgrading, we should take into account both variants, that node exporter can be in default namespace or dedicated.
This is exactly what task name says:
`- name: Reinstall Node Exporter as DaemonSet from default namespace to dedicated namespace for "k8s as cloud service"`
so I would not consider it as a bug. It just needs to be adjusted to the new case - upgrading node exporter that was installed as a DaemonSet.

**Comment by plirglo** [comment]
Please update changelog about node exporter update

**Comment by atsikham** [comment]
Tested the second time on AWS/Ubuntu and Azure/RHEL after [this](https://github.com/epiphany-platform/epiphany/pull/2807#issuecomment-1002277665) comment:

✅  apply develop + upgrade + upgrade
✅  apply 1.0 + upgrade + upgrade

Behaves as expected, idempotence covered, metrics are in place
![image](https://user-images.githubusercontent.com/6271862/147938316-c880e051-3614-4ac4-a8bb-eb860dbd23ab.png)
