### ISSUE TITLE
[BACKPORT][v1.0.2] - Issue creating service principle on Azure.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2784]
Backport Issue: #2774 
PRs:  #2775, #2783

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested:

✔️ `use_service_principal: false`
✔️ `use_service_principal: true` - creating a new service principal
✔️ `use_service_principal: true` - using an existing service principal
