### ISSUE TITLE
Implement preflight checks for the repository machines disk space

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2787]
> @atsikham Do we need any preflight checks for the repository machines disk space when we are pulling in so many new images? I remember @to-bar was doing somethings for that before. Maybe it needs to be adjusted?

I only added removing old image files (*.tar) from epirepo that no longer exist in requirements.txt to free up disk space. However old images are not removed from image registry so we may still have "snowball effect" and something to do with this. In the future we can add size attribute for each image and count how much space is needed to download them and load into registry.

_Originally posted by @to-bar in https://github.com/epiphany-platform/epiphany/issues/2771#issuecomment-991109511_

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by romsok24** [comment]
I was trying to groom this task but I'm not really sure if one can understand its goals & scope....
The topic is pointing into preflight checks for the disk space while description is narrowing the problem to only one particular file types....

**Comment by seriva** [comment]
I think this maybe needs to be a spike? First to see how to move forward with cleaning some un-used stuff from the repo with an upgrade run, as old images/files should not accumulate. Secondly I think we know what we downloads and what should be there so this check even could be something dynamic IMO for spacemanagement on the machine.

**Comment by atsikham** [comment]
We also already have a check to have 16GB free space for repository.
