### ISSUE TITLE
[FEATURE REQUEST] Upgrade K8s CNI plugins to the latest available versions

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2791]
**Is your feature request related to a problem? Please describe.**
New versions are released, so need to upgrade Flannel, Calico and Canal

**Describe the solution you'd like**
Upgrade CNI plugins

**Describe alternatives you've considered**
No

**Additional context**
- https://github.com/flannel-io/flannel
- https://github.com/projectcalico/calico

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
@atsikham Few questions:

1: This is not something needed for the K8s 1.22.4 upgrade right?
2: Would it make sense to split this in 3 separate tasks? On for each plugin.
3: Maybe this is redundant as we might want to disconinue support for 3 plugins? @erzetpe Maybe something consider for this deprecation plan you are working on?

**Comment by atsikham** [comment]
1. Right
2. Might be 2 - [flannel](https://github.com/flannel-io/flannel) and [calico/canal](https://github.com/projectcalico/calico)
3. May be

**Comment by cicharka** [comment]
@atsikham and @erzetpe, as there is plan to create a spike about Calico deprecation do we still need to include Calico plugin in this upgrade ticket?

**Comment by erzetpe** [comment]
@cicharka Yes, as this is not planned for 1.3 or 2.0 release.

**Comment by plirglo** [comment]
Please also ix documentation, since ```calico``` version provided in [COMPONENTS.md](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/COMPONENTS.md) file is not correct. Check this for all systems and both architectures.
