### ISSUE TITLE
[SPIKE] Test KMinion as alternative to kafka_exporter

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2801]
**Is your spike related to a problem or idea? Please describe.**
Two latest versions of kafka_exporter (1.4.1 and 1.4.2) do not work well. See https://github.com/epiphany-platform/epiphany/issues/2748#issuecomment-996744865 and danielqsj/kafka_exporter#273. 

**Describe the outcome you'd like**
We want to test KMinion as alternative to kafka_exporter.

**What is the reason or source for the spike**
- Critical issue in latest kafka_exporter versions
- No response for danielqsj/kafka_exporter#273

GitHub repo: https://github.com/cloudhut/kminion

**Additional context**
n/a

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
