### ISSUE TITLE
[FEATURE REQUEST] Extend K8s config validation

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2812]
**Is your feature request related to a problem? Please describe.**
Right now K8s [validation](https://github.com/epiphany-platform/epiphany/blob/develop/schema/common/validation/configuration/kubernetes-master.yml) doesn't cover all [configuration](https://github.com/epiphany-platform/epiphany/blob/develop/schema/common/defaults/configuration/kubernetes-master.yml) parameters that we have, so it's even possible to place there some parameters that we don't support, but they will be applied, for example, if they are valid for kubeadm config.

**Describe the solution you'd like**
Extend validation.

**Describe alternatives you've considered**
No.

**Additional context**
Other validation configurations might be checked in addition.
---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [x] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by atsikham** [comment]
As discussed with @seriva, there is no possibility for now to check additional fields and that's done by purpose and such behavior was requested before.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Validation for `kubernetes_master` component verified.
