### ISSUE TITLE
[BACKPORT][v1.0.2] - Added hostname_domain_extension.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2813]
Backport issue: #2768
Pull request: #2790

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: A hostname domain extension with basic validation has been added for the Azure provider
