### ISSUE TITLE
[FEATURE REQUEST] Automatic TLS configuration for Kibana connections

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2816]
**Is your feature request related to a problem? Please describe.**
We have possibility to turn on TLS manually in Kibana for https connection, but we don't have any automation to do this.

**Describe the solution you'd like**
We want to update have this automatically accessible from Epiphany.

**Describe alternatives you've considered**
None.

**Additional context**
We need to consider if we should do this before or after migration to OpenSearch.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
