### ISSUE TITLE
[FEATURE REQUEST] eplicli preflight checks

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2821]
**Is your feature request related to a problem? Please describe.**

When we run an epicli upgrade procedure on existing epiphany installation with an k8s app enabled (ie. node-exporter in daemonset mode) an upgrade procedure is failing ( stating that no clusters/build/test-node-expr/kubeconfig file was found).
 
**Describe the solution you'd like**
Perhaps we can implement some additional preflight test to ensure the k8s config file was provided by a user before starting the upgrade? We can even copy the needed kubeconfig from the k8s master cause we have an ssh key to this machine ( to be decided yet ).

Additional checks to implement:
- Node-exporter chart is not installed more than 1 time. It will dismiss questions [here](https://github.com/epiphany-platform/epiphany/pull/2807/files#diff-2365fca8b023aeddb1fab9cf7d05838dce5170df488bb942e97e3718e7165480R21).
- `k8s_as_cloud_service` is set to `true` only for managed K8s or `node-exporter` feature mapping is disabled when it's set to `true`. Otherwise there is an error:

```text
level=error ts=2021-12-28T10:51:54.086Z caller=node_exporter.go:194 err="listen tcp 0.0.0.0:9100: bind: address already in use"
```

**Describe alternatives you've considered**
No

**Additional context**
Workarounds:
 - for the first case it's possible to copy the existing kubeconfig file from the K8s control plane node to the machine that runs epicli
 - for the 3rd it is possible to manually stop the conflicting node-exporter installed as a service:
   ```systemctl stop prometheus-node-exporter.service``` 
   one need to do it on all nodes and for persistent change it one should use ```systemctl disable ...```

---

**DoD checklist**

* [x] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
Please, double check in the rest k8s apps.

**Comment by atsikham** [comment]
1. Main statement notes:
- We don't upgrade 'applications', if we need to update a version, at the moment we only re-apply configuration.
- Kubeconfig is copied for the usual Kubernetes installation -  https://github.com/epiphany-platform/epiphany/blob/21cdd70dd6479a280c8c57d5578eb9dd7ead25e4/ansible/playbooks/kubernetes_master.yml#L53
- There are 3 components that use local kubeconfig (where described issue can occur) - node_exporter, prometheus, filebeat.

Taking that into account, I decided to add a validation that kubeconfig (`kubeconfig.local`) file exists when `k8s_as_cloud_service: true` in upgrade mode (#3021).

2. Preflight check is added #3011 to check a single Helm release for Node Exporter.
3. To avoid an execution of different Node Exporter installation types (system service, daemonset), task conditions were modified, no preflight checks are necessary in this case (#3021).
