### ISSUE TITLE
[BACKPORT][v1.0.2] - Upgrade to Open Distro to latest 1.13.x to solve the log4j issues

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2823]
Source issue #2788
Pull request #2806

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Affected Log4j *.jar files have been deleted and replaced with newer versions.
