### ISSUE TITLE
[BUG] Review the code in terms of correctness

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2827]
This issue is related to problems similar as the one described [here](https://github.com/epiphany-platform/epiphany/pull/2807#:~:text=things%20were%20found%3A-,Task%20Get%20information%20about%20helm%20releases%3A%20need%20to%20add%20changed_when%3A%20false.,-Task%20Check%20if). Basically, Epiphany code should be reviewed to reflect the rule not to mark the task status as changed if the task was only related to some kind of information gathering activity. 
The cited comment was already included in the changes within the [#2782](https://github.com/epiphany-platform/epiphany/issues/2782) but some other occurrences [can exists](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/upgrade/tasks/filebeat.yml).

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
This can be changed after Molecule tests introduction as in this case 'idempotence' test step will fail.
@romsok24 is it also about avoiding execution of upgrade if version is not changed?
