### ISSUE TITLE
K8s improvements

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#2828]
- Please create an issue for removing (or adding comment about) `--ignore-preflight-errors all` and add the issue number here as a comment.

  _Originally posted by @to-bar in https://github.com/epiphany-platform/epiphany/pull/2805#discussion_r776771057_

- We re-generate apiserver certificates [here](https://github.com/epiphany-platform/epiphany/blob/fccc22a4ac86e7bc82f9e2283d3eda58507cff69/ansible/playbooks/roles/kubernetes_master/tasks/main.yml#L38) for issue #1520. But in fact cert SANs patching should be moved to [patching apiserver configuration](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/upgrade/tasks/kubernetes/patch-kubeadm-apiserver.yml) in upgrade and executed here only after promotion to ha. Check [kubeadm configuration](https://github.com/epiphany-platform/epiphany/blob/558ef84f61be9dfa0ac519f4939899904265c767/ansible/playbooks/roles/kubernetes_master/templates/kubeadm-config.yml.j2#L12).

  To summarize: 
  - in apply apiserver cert SANs could be checked and if there is not all necessary addresses, re-generate
  - in upgrade kubeadm config should be patched

  Following cases will be covered:
  - changing the number of control plane nodes (downscale is not supported)
  - idempotence in applying the same configuration
  - upgrade from previous versions

  Example of check: `openssl x509 -in /etc/kubernetes/pki/apiserver.crt -text -noout | grep DNS:`

- Condider adding block/rescue for certificates generation to handle failures:
  - [doc](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/kubernetes/CERTIFICATES.md)
  - [tasks](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/kubernetes_master/tasks/generate-certificates.yml)

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested:
- single master + x nodes, promote to HA, HA cluster, single machine
- upgrades
- certificates renewal
- kubeadm reset + re-apply

However, it is not recommended to renew certificates after executing  `kubeadm reset` command as it may fail in some edge cases - documentation updated.
