### ISSUE TITLE
[BACKPORT][v1.0.2] - Fix postgres-exporter service errror:  Error opening connection to database

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#2831]
**Is your feature request related to a problem? Please describe.**
When creating cluster with  postgres-exporter role enabled, the result is that the postgres-exporter service is not exporting metrics at all due to the `Error opening connection to database`:
```bash
Jan 04 09:26:57 cicharka-postgres-test-centos-postgresql-vm-0 postgres_exporter[23084]: time="2022-01-04T09:26:57Z" level=error msg="Error opening connection to database (postgresql://:PASSWORD_REMOVED@): malformed dsn \"\"" source="postgres_exporter.go:1474"
```

**Describe the solution you'd like**
Solution is to remove additional quotation marks from the systemd unit [template](https://github.com/epiphany-platform/epiphany/blob/033d870aa2f16a46b5c6cf3b2e9c20a1d6d0c54a/ansible/playbooks/roles/postgres_exporter/templates/postgres-exporter.service.j2) for Environment field:
```bash
Environment="{{ specification.systemd_environment|default("DATA_SOURCE_NAME=postgresql://postgres@:5432/postgres?host=/var/run/postgresql/&sslmode=disable") }}"
```

**Environment**
Found in epicli v1.0.1, only on machines that run CentOS

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: The service template has been fixed.
