### ISSUE TITLE
[FEATURE REQUEST] Removal of Logstash component

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2833]
**Is your feature request related to a problem? Please describe.**
The functionality that Logstash is serving in Epiphany - exporting csv can right now be achieved using Open Distro for Elasticsearch plugin.

**Describe the solution you'd like**
We want to remove unused Logstash component as it double the functionality with Open Distro for Elasticsearch plugin.

**Describe alternatives you've considered**
None.

**Additional context**
Logstash in this version is prone to log4j issue and this is also the reason why should be removed.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Important is to remove everything:

- Ansible
- Python (if present)
- Defaults
- Validation
- Documentation
- etc

From documentation only leave things that are part of design docs.

**Comment by rafzei** [comment]
Hi @cicharka, shouldn't you also remove spec test for logstash? see [here](https://github.com/epiphany-platform/epiphany/blob/develop/tests/spec/spec/filebeat/filebeat_spec.rb#L57-L68)

**Comment by cicharka** [comment]
Hello @rafzei, as I understand it, the test you pointed to is related to `filebeat` component.
Unfortunately name 'logstash' was not only used for `logstash` component name, but also as username for `elasticsearch` [here](https://github.com/epiphany-platform/epiphany/blob/66e11f3e2e3d3be750952cc0e010af26b04ddc69/ansible/playbooks/roles/opendistro_for_elasticsearch/tasks/configure-es.yml#L217) and also in `filebeat` [here](https://github.com/epiphany-platform/epiphany/blob/2b12e87535df2d45c84b9308bc242b0e913f31af/ansible/playbooks/roles/filebeat/templates/filebeat.yml.j2#L315).
Please correct me if I wrong @przemyslavic or point out who can verify it :)

**Comment by rafzei** [comment]
Probably you have right, but let's wait for @przemyslavic. Maybe we could change the username?

**Comment by przemyslavic** [comment]
Updated all develop pipelines by removing Vault, Istio, Logstash and Ignite components/apps.

**Comment by plirglo** [comment]
Please create documentation regarding deprecation: what steps are needed from admin to remove packages or create ansible tasks for this. We should not leave not use components and dependencies on machines.

**Comment by cicharka** [comment]
Logstash component has no dependencies or any other package is not dependent on it (both Ubuntu and RedHat) therefore its removal can be performed easily. Added more information in docs.
