### ISSUE TITLE
[FEATURE REQUEST] Removal of Istio component

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2836]
**Is your feature request related to a problem? Please describe.**
We are considering replacement of Istio component with different solutions and Istio causes problems during upgrade of Kubernetes.

**Describe the solution you'd like**
Remove Istio role from Epiphany.

**Describe alternatives you've considered**
Replace Istio with different service mesh solution.

**Additional context**
None.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Important is to remove everything:

- Ansible
- Python (if present)
- Defaults
- Validation
- Documentation
- etc

From documentation only leave things that are part of design docs.

**Comment by przemyslavic** [comment]
Updated all develop pipelines by removing Vault, Istio, Logstash and Ignite components/apps.
