### ISSUE TITLE
[FEATURE REQUEST] Removal of Apache Ignite

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2837]
**Is your feature request related to a problem? Please describe.**
Apache Ignite is prone to 1.x log4j issue.

**Describe the solution you'd like**
We want to remove role for Apache Ignite from Epiphany.

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [x] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by seriva** [comment]
If we move forward with this we should be able to close this one: #2789

**Comment by seriva** [comment]
ALso this should be both the on VM and K8s deployments.

**Comment by seriva** [comment]
Important is to remove everything:

- Ansible
- Python (if present)
- Defaults
- Validation
- Documentation
- etc

From documentation only leave things that are part of design docs.

**Comment by przemyslavic** [comment]
Updated all develop pipelines by removing Vault, Istio, Logstash and Ignite components/apps.

**Comment by plirglo** [comment]
Please create documentation regarding deprecation: what steps are needed from admin to remove packages or create ansible tasks for this. We should not leave not use components and dependencies on machines.
