### ISSUE TITLE
[BUG] Incorrect link in release info for v1.1.0rc1

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2841]
**Describe the bug**
This is a low prio bug.

The link to the CHANGELOG.md file for [version v1.1.0rc1](https://github.com/epiphany-platform/epiphany/releases/tag/v1.1.0rc1) seems to be malformed.
Instead of currently used:
```https://github.com/epiphany-platform/epiphany/blob/develop/CHANGELOG-1.1.md#110rc1-2021-06-18```
we should consider this one:
```https://github.com/epiphany-platform/epiphany/blob/v1.1.0rc1/CHANGELOG-1.1.md#110rc1-2021-06-18```

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Closing as its a bit irrelevant.
