### ISSUE TITLE
[SPIKE] Supported Kubernetes CNI plugins comparison

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2842]
**Is your spike related to a problem or idea? Please describe.**
We want to minimize the number of CNI plugins supported by the Epiphany as it is hard to test right now multiple options and the functionality doubles between the plugins.

**Describe the outcome you'd like**
We want to compare CNI plugins supported by Epiphany also in the context of cloud provider.

**What is the reason or source for the spike**
We want to deprecate some CNI plugins and this task should be a base for making the decision about deprecation plan, because functionalities of some are doubling between them.

**Additional context**
None.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
