### ISSUE TITLE
[FEATURE REQUEST] Refactor K8s upgrade task in order to simplify its flow

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#2844]
**Is your feature request related to a problem? Please describe.**
Kubernetes [upgrade task](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/upgrade/tasks/kubernetes.yml) can have simpler flow. Currently we are using 3 factors (kubelet version, cluster version and upgrade flag file status) to decide if we need to upgrade - but truly we can decide only based on kubelet version and upgrade flag file existence.

**Describe the solution you'd like**
Brief solution is described in comment [for k8s upgrade flag PR](https://github.com/epiphany-platform/epiphany/pull/2766#discussion_r778195838) and will be enhanced by adding comment about code structure under this ticket.

---

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [x] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
:heavy_check_mark: upgrade 1 master + 2 nodes
:heavy_check_mark: HA upgrade
:heavy_check_mark: single machine upgrade
