### ISSUE TITLE
[BUG] Incorrect order of multiple conditions check in jmx_exporter upgrade task

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#2845]
**Describe the bug**
postgres_exporter_version.old/new variables are undefined when upgrade flag file exists. This will fail the build as the whole block where we set facts is not executed.

**How to reproduce**
Break the upgrade procedure after creating upgrade flag. In next iteration it will fail.

**Expected behavior**
Upgrade procedure should succeed in case there was a failure before and upgrade flag file was present.

**Environment**
Any

**epicli version**: [`epicli --version`]
1.3.0

**Additional context**
Solution is to change condition order so the flag file existence is evaluated first.
See comment from @przemyslavic -> [issue in postgres exporter](https://github.com/epiphany-platform/epiphany/pull/2795#pullrequestreview-844424262)

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested `upgrade` from v 1.0.1 -> upgrade canceled after `jmx-exporter-upgrade-in-progress.flag` flag was created -> re-run upgrade when flag exists
