### ISSUE TITLE
[FEATURE REQUEST] Upgrade Ansible to 5.2.0

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2847]
**Is your feature request related to a problem? Please describe.**
If there is Python 2 & 3 at the same time, ansible-core 2.11 will choose Python 2 by default. Due to Ubuntu release upgrade we've changed setting `interpreter_python` from `auto_legacy_silent` to `auto` in ansible.cfg. However, this config file may by not applied when running playbooks manually (for developing) unless `ANSIBLE_CONFIG` is set. ansible-core 2.12 solves this issue since it uses different default value for `interpreter_python` (`auto`).

**Describe the solution you'd like**
Ansible in latest version.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by asciible** [comment]
waiting for https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/2852 to be merged for component docs update

**Comment by przemyslavic** [comment]
Tested scenarios:

:heavy_check_mark: `apply` + :x: re-apply x86_64 (fails on Ubuntu #2940)
:heavy_check_mark: `apply` + re-apply aarch64
:heavy_check_mark: `upgrade` from v1.0 x86_64
:heavy_check_mark: `upgrade` from v1.2 aarch64
:heavy_check_mark: `epicli init`
:heavy_check_mark: `epicli prepare`
:heavy_check_mark: `epicli delete`
:heavy_check_mark: `epicli test`
:x: `epicli backup` #2942
:x: `epicli recovery` #2942
:heavy_check_mark: offline installation x86_64
:heavy_check_mark: offline installation aarch64

Issues reported:
#2940
#2942
