### ISSUE TITLE
[SPIKE] Check how to upgrade Ubuntu from 18.04 to 20.04 in air-gapped environment

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2848]
**Is your spike related to a problem or idea? Please describe.**
In version 1.3 we require Ubuntu 20.04 but already existing clusters have Ubuntu 18.04.
We may be asked how to deal with upgrade in air-gapped environment.

**Describe the outcome you'd like**
We need to check what steps are needed to upgrade OS release in air-gapped environment and whether it's possible to use OS installation image (ISO) to provide required packages.

**What is the reason or source for the spike**
Support for Ubuntu 20.04

**Additional context**
n/a

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by cicharka** [comment]
Document that describe upgrade procedure using Local APT repository: [Ubuntu 18.04 LTS to Ubuntu 20.04 LTS upgrade in air-gapped environment](https://pgga-es.atlassian.net/wiki/spaces/EPI/pages/2559738340/Ubuntu+18.04+LTS+to+Ubuntu+20.04+LTS+upgrade+in+air-gapped+environment)

**Comment by seriva** [comment]
I read the document and its ok for me.
