### ISSUE TITLE
[FEATURE REQUEST] Change autoscaling_group approach in AWS provider in favor of plain VM creation.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2853]
**Is your feature request related to a problem? Please describe.**
Currently for AWS we use autoscaling_groups to create a set of VMs for a given component group. This approach however has several issues as we cant guaranty the order of the VMs when changing/updating the cluster. This in turn causes issues with scaling some of the components in our cluster.

**Describe the solution you'd like**
We would like to have the same approach as we have in the Azure provider where we create the VMs ourselves. 

Also it would be nice to include the use_network_security_groups feature which is currently unimplemented in AWS. In shirt this should disable the use of any network security rules for the VPC and subnets.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [x] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
:heavy_check_mark: creating plain VMs on AWS (without autoscaling groups)
:heavy_check_mark: added sorting in inventory (hostnames are created the same as for Azure)
:heavy_check_mark: added support for `use_network_security_groups`. When set to `false`, ssh is not allowed.
:heavy_check_mark: added names/tags for resources
:heavy_check_mark: added support for data disks

Upgrades from older clusters are not supported.
