### ISSUE TITLE
[BUG] Validation fails during upgrade -f with default configuration on Azure

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#2854]
**Describe the bug**
Validation fails for `use_cloud_init_custom_data` during upgrade -f with default configuration on Azure

**How to reproduce**
1. execute `epicli init -p azure -n cluster_name --full`
2. execute `epicli upgrade -b cluster_name -f cluster_name/cluster_name.yml`

**Expected behavior**
Validation should pass without any problem

**Config files**
Default config file with epicli init --full -p azure

**Environment**
- Cloud provider: Azure

**epicli version**: v1.3

**Additional context**
![upgrade_fail.jpg](https://images.zenhubusercontent.com/60d335008b0f92baf11ab200/36f374e0-767b-4d38-8a1f-f6e3e9a47117)

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
I cannot reproduce this issue in the steps described.  epicli init removes any fields which have a default SET_BY_AUTOMATION as these would be fields that users should not touch to begin with:

https://github.com/epiphany-platform/epiphany/blob/be26c16d97ab3cddf1cee99e9e6fdc5e023de330/cli/engine/InitEngine.py#L52

 The only way this can occur if a user would add these on purpose in the input documents, which will cause this error  and is valid as this is a wrong config according to the schema. IMO nothing we should fix as the these would not be returned when generating a config.

**Comment by sbbroot** [comment]
I'm closing this issue as I could not reproduce it anymore.
