### ISSUE TITLE
[SPIKE] Compare Terraform with ARM Templates, ARM Bicep and Pulumi

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2857]
**Is your spike related to a problem or idea? Please describe.**
We want to decide in which direction we should go with our infrastructure for Azure module and we want to compare Terraform with ARM Templates, ARM Bicep and Pulumi.

**Describe the outcome you'd like**
We want to compare  Terraform with ARM Templates, ARM Bicep and Pulumi.

**What is the reason or source for the spike**
Make easier to choose final approach for Azure infrastructure module.

**Additional context**
None.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Closing this as its no longer relevant.
