### ISSUE TITLE
[FEATURE REQUEST] Make Ruby spec tests code compliant with rubocop lint rules

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#2858]
**Is your feature request related to a problem? Please describe.**
After adding `rubocop` linter to Azure Pipeline it reports many failures in tests/spec code and as we don't want to have workaround for checking failures threshold we have to correct tests/spec code.

**Describe the solution you'd like**
After running autocorrect proposed by rubocop we can manually updated rest of the failures. As the result there should be no failures reported by rubocop.

**Additional context**
This needs to be tested to ensure that any change in code is not breaking the tests.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
All test cases run correctly. The failures reported by linter have been significantly reduced.
