### ISSUE TITLE
[FEATURE REQUEST] Upgrade Kafka 

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2871]
**Is your feature request related to a problem? Please describe.**
Currently the version of Kafka we use is 2.6.0. Newer versions have been released which fix a bunch of issues.

**Describe the solution you'd like**
Upgrade Kafka to 2.8.1 to resolve some of these bugs and issues. 

**Describe alternatives you've considered**
Upgrade to Kafka 3.x, however this introduces a number of breaking changes over Kafka 2.x which we currently don't want to introduce as this would require teams to upgrade there existing code to this newer version.

**Additional context**

---

**DoD checklist**

* [x] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by atsikham** [comment]
Do not forget: Kafka/Zookeeper are the components that for now require openjdk-8-jre-headless/java-1.8.0-openjdk-headless packages. It might be removed during upgrade.
