### ISSUE TITLE
[BUG] [v1.2] [RHEL/CentOS] pgbouncer-1.16.0 not available in pgdg-common repository

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2878]
**Describe the bug**
Pgbouncer v1.16.0 package is no longer available in  `pgdg-common` repository. Download-requirements.sh script fails trying to download it:
`repoquery failed: package pgbouncer-1.16.0 not found`.

Affected versions: v1.2

V1.3 and develop are not affected as we have already got rid of standalone pgbouncer and v1.1 is out of support.
In v1.0 we have pgbouncer v1.10 from 2ndquadrant repo.

**How to reproduce**
1. Try to deploy any v1.2 cluster.

**Expected behavior**
Downloading packages should be successful.

**Config files**

**Environment**
- Cloud provider: [all]
- OS: [RHEL/ CentOS]

**epicli version**: v1.2

**Additional context**
```
[ec2-user@ip-10-1-11-154 ~]$ yum list available pgbouncer                                                                                                                          2/2
Available Packages
pgbouncer.x86_64                                                         1.16.1-1.rhel7                                                          pgdg-common
```
https://www.pgbouncer.org/changelog.html#pgbouncer-116x
We should bump pgbouncer to v1.16.1 or download v1.16.0 from different source.
It is also worth noting that there is a risk that the package for Ubuntu may also be removed in the coming days.

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Closing as there will be no @1.2.1
