### ISSUE TITLE
[FEATURE REQUEST] Define additional disks with defined sizes to VMs for Azure

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2888]
**Is your feature request related to a problem? Please describe.**
We need to provide disks for Cloud Native Storage for Azure provider.

**Describe the solution you'd like**
We want to provide a storage that fulfils requirements stated in comment to issue: https://github.com/epiphany-platform/epiphany/issues/139#issuecomment-731028343:
1. be generic enough to allow defining extra disks and mount points per component
2. allow to destroy clusters without destroying disks (if possible)

**Describe alternatives you've considered**
Trying to use modules for disk creation like in tasks: 
- https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/42

**Additional context**
Historical task for define additional disks with discussion: https://github.com/epiphany-platform/epiphany/issues/139.
Kubernetes storage comparison: https://github.com/mkyc/k8s-pv.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by cicharka** [comment]
Base on that [comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/1701#issuecomment-409870513) and verification with `epicli apply` and `epicli delete`, we are not able to implement easily removal of epi cluster without disks removal. Flag `delete_data_disks_on_termination` will not work when removing whole resource group.
