### ISSUE TITLE
[FEATURE REQUEST] Define additional disks with defined sizes to VMs for AWS

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2889]
**Is your feature request related to a problem? Please describe.**
We need to provide disks for Cloud Native Storage for Azure provider.

**Describe the solution you'd like**
We want to provide a storage that fulfils requirements stated in comment to issue: https://github.com/epiphany-platform/epiphany/issues/139#issuecomment-731028343:
1. be generic enough to allow defining extra disks and mount points per component
2. allow to destroy clusters without destroying disks (if possible)

**Describe alternatives you've considered**
Trying to use modules for disk creation like in tasks: 
- https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/37

**Additional context**
Historical task for define additional disks with discussion: https://github.com/epiphany-platform/epiphany/issues/139.
Kubernetes storage comparison: https://github.com/mkyc/k8s-pv.

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Support for data disks introduced in #2939.
