### ISSUE TITLE
[BUG] Not possible to add PostgreSQL component to existing environment

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2904]
**Describe the bug**
When you have Epiphany cluster deployed with no PostgreSQL (0 nodes) and want to add it, epicli fails with error:
`Postgresql scaling is not supported yet. Please revert your 'postgresql' node count to previous value.`

**How to reproduce**
1. Deploy cluster with `components.postgresql.count = 0`.
2. Edit config file increasing the value from 0 to 1 or 2.
3. Execute `epicli apply`.

**Expected behavior**
It should be possible to "scale up" when starting from 0.

**Environment**
- Cloud provider: All

**epicli version**: 1.2.0

**Additional context**
n/a

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed.
NOTE: https://github.com/epiphany-platform/epiphany/pull/2902#issuecomment-1016426332
