### ISSUE TITLE
[BACKPORT][v1.2.1] Not possible to add PostgreSQL component to existing environment

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2913]
Please backport task #2904 (PR #2902) to v1.2 branch.

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
1.2.0 is out of support.
