### ISSUE TITLE
[FEATURE REQUEST] Rook/Ceph Kubernetes Native Storage for on premise.

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2914]
**Is your feature request related to a problem? Please describe.**
We don't have support for Kubernetes Native Storage in Kubernetes at the moment.

**Describe the solution you'd like**
We want to add support for  Kubernetes Native Storage for Kubernetes based on Rook/Ceph solution that based on our comparison: https://github.com/mkyc/k8s-pv is the best option.

**Describe alternatives you've considered**
None.

**Additional context**
Historical task for define additional disks with discussion: #139.
Kubernetes storage comparison: https://github.com/mkyc/k8s-pv.

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Already finalized, so closing.
