### ISSUE TITLE
[BACKPORT][v1.0.3] Re-running epicli may fail for clustered Postgres

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2935]
Please backport task #1702 (PR#2501).
This was fixed in v1.2 when upgrading PostgreSQL to v13, but here it has to be adjusted to v1.0 (PostgreSQL v10).
The main goal is to detect the master automatically and not to rely on the assumption that node[0] is always the master.

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Just wondering if this is worth fixing in 1.0.x. As we added host sorting with this backport #2936 which should make the use of node[0] consistent for at least the Azure and Any providers AWS as we know is not for production anyway. 

Also Postgres 10 support will be dropped soon so from that perspective people should move to newer version of Epiphany anyways:

![image.png](https://images.zenhubusercontent.com/5efee199ee690405efd9d38b/a4dc1902-aca7-493f-9e66-63d4392983dc)

**Comment by przemyslavic** [comment]
PR #3016 should work around the problem 👍

**Comment by seriva** [comment]
So lets close this maybe?

**Comment by cicharka** [comment]
I will just quickly check if sorting from #3016 fixes that and we can close it.

**Comment by cicharka** [comment]
Sorting included in #3016 ensures that `when: groups.postgresql[0] == inventory_hostname` condition is always using same host.
Tested by re-applying cluster with 3 postgresql nodes 3 times.
