### ISSUE TITLE
[FEATURE REQUEST] Create new Ansible filter plugin to parse .env files

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2943]
**Is your feature request related to a problem? Please describe.**
There are a few places where we parse env files like:
[here](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/postgresql/tasks/extensions/replication/extension.yml#L108-L112)

**Describe the solution you'd like**
According to @to-bar comment: 
```
I would see this e.g. as from_env parser (Ansible filter like we have from_ini) to load variables to Ansible dictionary, process it using Ansible, convert to env file format then replace the env file with one shot. Now we probably produce more backup files than needed (replace task in loop).
```

**Describe alternatives you've considered**

**Additional context**
More places can be found in code by grep `lineinfile`,  `replace` or this issue id

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
