### ISSUE TITLE
Refactor InitEngine class to be agnostic to changes in ApplyEngine and UpgradeEngine

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2944]
**Is your feature request related to a problem? Please describe.**
We have temporary workarounds here:
https://github.com/epiphany-platform/epiphany/blob/c687e8eca0347fda6dd7a0b092deafeccdb53fb6/cli/engine/InitEngine.py#L63

One was added in PR #2861

**Describe the solution you'd like**
Be able to add options for `apply` and `upgrade` mode without breaking `init` mode.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Tested `init`, `init --full`, `apply` and `upgrade` commands with `--ping-retries` and `--ansible-forks` flags.
Reported 2 minor issues (not related to these changes, but related to the init engine ):
#2966
#2968
