### ISSUE TITLE
[BUG] epicli apply sleeps 10 seconds after creating inventory

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2945]
**Describe the bug**
We have unconditional sleep call in epicli code:
https://github.com/epiphany-platform/epiphany/blob/c687e8eca0347fda6dd7a0b092deafeccdb53fb6/cli/engine/ansible/AnsibleRunner.py#L109

**How to reproduce**
1. execute `epicli apply ...`

**Expected behavior**
Run without wasting time for sleeping or wait for something conditionally (explicitly) as long as needed instead of static 10 seconds.

**Environment**
- Any

**epicli version**: 1.3.0 and older

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
Tested together with #2944.
