### ISSUE TITLE
[FEATURE REQUEST] CLI refactor to make it more consistent

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2950]
**Is your feature request related to a problem? Please describe.**
Currently the structure of the CLI code is not very consistent and should be re-organized.

**Describe the solution you'd like**

1. Re-name **epiphany/cli/engine** to **epiphany/cli/src**
2. Move **epiphany/cli/models** to **epiphany/cli/src/models**
3. Move **epiphany/cli/helpers** to **epiphany/cli/src/helpers**
4. Move the **<Commands>Engine.py** inside **epiphany/cli/src/command**
5. Rename the **<Commands>Engine.py** files and classes to **<Commands.py**
6. Fix up all tests.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [x] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Tested:
:heavy_check_mark: `init` -> `apply`
:heavy_check_mark: `init --full` -> `apply`
:heavy_check_mark: `prepare`
:heavy_check_mark: `apply` -> `apply`
:heavy_check_mark: `upgrade`
:heavy_check_mark: `delete`
:heavy_check_mark: `test`
:heavy_check_mark: `backup`
:heavy_check_mark: offline mode
