### ISSUE TITLE
[SPIKE] Run Docker daemon as non-root user (rootless mode)

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2971]
**Is your spike related to a problem or idea? Please describe.**
According to [Docker docs](https://docs.docker.com/engine/security/rootless/):

> Rootless mode allows running the Docker daemon and containers as a non-root user to mitigate potential vulnerabilities in the daemon and the container runtime.
> 
> Rootless mode does not require root privileges even during the installation of the Docker daemon, as long as the [prerequisites](https://docs.docker.com/engine/security/rootless/#prerequisites) are met.
> 
> Rootless mode was introduced in Docker Engine v19.03 as an experimental feature. Rootless mode graduated from experimental in Docker Engine v20.10.

**Describe the outcome you'd like**
- Check if it is possible (and what is needed) to switch Docker on `image_registry` host from standard to rootless mode.

**What is the reason or source for the spike**
Mitigation of potential vulnerabilities in the daemon and the container runtime.

**Additional context**
Alternative option is to use only containerd (`ctr` command) without Docker. See point 3 of https://github.com/epiphany-platform/epiphany/issues/2757#issuecomment-1017795143.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
