### ISSUE TITLE
[FEATURE REQUEST] Refactor Apply command

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2974]
**Is your feature request related to a problem? Please describe.**
Currently the Apply command, loads, validates and applies configurations in different stages. This causes the code to be messy and not easily readable. Also it causes some cases which should fail early to only fail after the Terraform apply stage.

**Describe the solution you'd like**

Restructure the code to:
1. Load needed resources from files and possible existing build output
2. Process the documents
3. Validate the document
4. Assert on certain edge cases
5. Apply Terraform infrastructure (if applicable)
6. Apply Ansible

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [x] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [x] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [x] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Every `epicli` command has been tested. After some minor fixes, no more issues were found.
