### ISSUE TITLE
[FEATURE REQUEST] Allow for custom Terraform scripts

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2976]
**Is your feature request related to a problem? Please describe.**
Currently when Epicli is run it cleans out all *.tf Terraform template files. This restricts the ability of the user to add any kind of custom Terraform scripts to a deployment outside of what Epiphany generates.

**Describe the solution you'd like**
Only remove the Terraform templates from the build directory that are actually generated by Epiphany with the following regex:

'''[0-9][0-9][0-9]_*.tf'''

And document the steps for people to add custom Terraform templates to a deployed cluster.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [x] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
The ability to add custom terraform scripts has been tested. The functionality seems to be working fine. Created and removed additional resources in AWS and Azure with `epicli`.
