### ISSUE TITLE
Using AKS and EKS Terraform configuration directly with Epiphany.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2982]
**Is your spike related to a problem or idea? Please describe.**
Currently we have modules to deploy EKS and AKS alongside an Epiphany cluster. As these Terraform deployments work separate from each other both have separate Terraform states making it hard to maintain the 2 configured together.

**Describe the outcome you'd like**
With the following issue completed: #2976 it should be possible to deploy custom Terraform templates alongside the ones Epicli generates. With this spike we want to deploy an Epiphany cluster and see if we can deploy AKS and EKS alongside it using custom Terraform which can be partially re-used from the modules:

Modules:
https://github.com/epiphany-platform/m-azure-kubernetes-service
https://github.com/epiphany-platform/m-aws-kubernetes-service

Note that this should also take into account the custom things we did with '''k8s_as_cloud_service''' to facilitate the original Epiphany+ modules deployment.

The outcome should preferable consist of the abstracted Terraform from the AWS and Azure modules, documentation how to deploy them. This can be a separate repo on our GitHub.

**What is the reason or source for the spike**
The module approach might not be something we want to continue to develop long-term. This approach should make it easier to integrate EKS/AKS with Epiphany and more maintainable from the Terraform perspective.

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [x] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by cicharka** [comment]
As a result of this Spike, there are 3 PRs:
- https://github.com/epiphany-platform/k8s-modules/pull/1 -> separate repository with Terraform template files and documentation how to use them
- https://github.com/epiphany-platform/epiphany/pull/3146 -> update of modules documentation in main Epi repo
- https://github.com/epiphany-platform/epiphany/pull/3141 -> updated of template for filebeat for k8s_as_cloud_service

**Comment by seriva** [comment]
> As a result of this Spike, there are 3 PRs:
> 
> * [AKS and EKS modules k8s-modules#1](https://github.com/epiphany-platform/k8s-modules/pull/1) -> separate repository with Terraform template files and documentation how to use them
> * [[2.0.1] k8s-modules: update documentation #3146](https://github.com/epiphany-platform/epiphany/pull/3146) -> update of modules documentation in main Epi repo
> * [[2.0.1] Filebeat: update template for new version #3141](https://github.com/epiphany-platform/epiphany/pull/3141) -> updated of template for filebeat for k8s_as_cloud_service

4 PRs: https://github.com/epiphany-platform/k8s-modules/pull/2
