### ISSUE TITLE
[FEATURE REQUEST] Make RabbitMQ Plugins configurable

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2985]
**Is your feature request related to a problem? Please describe.**
Currently `enabled_plugins` configurations is hardcoded in jinja configuration file [here](https://github.com/epiphany-platform/epiphany/blob/a5fb61ade3b13d3103afd14c6f042ece3d7e5356/ansible/playbooks/roles/applications/templates/rabbitmq/03-rabbitmq.yml.j2#L32).

Currently user has to edit `ConfigMap` to enable plugins - this should change.

**Describe the solution you'd like**
We should move this into `defaults/configuration/applications.yml` to give user possibility to adjust the list.

**Additional context**
This issue is connected to RebbitMQ deployed in k8s cluster.

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [x] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [ ] All conversations in PR resolved
- [x] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
It looks like it's possible to "specify" RabbitMQ plugins:
https://github.com/epiphany-platform/epiphany/blob/develop/schema/common/defaults/configuration/applications.yml#L25
https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/applications/tasks/applications/rabbitmq/set-variables.yml#L20
but it is not applied to the ConfigMap 😢

**Comment by przemyslavic** [comment]
Plugins for RabbitMQ can be enabled by overwriting the default values for the application.
