### ISSUE TITLE
[BUG] Task `Remove swap from /etc/fstab` does not remove swap entry from file

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2989]
**Describe the bug**
Test if [remove swap](https://github.com/epiphany-platform/epiphany/blob/d2ac0d973490b10a819b9f928e9daa7fe287e045/ansible/playbooks/roles/common/tasks/main.yml#L27) task works correctly on every supported platform. On Ubuntu 18.04 task does not remove swap entry.

**How to reproduce**
1. execute `epicli apply ...`
2. confirm in /etc/fstab if swap is disabled

**Expected behavior**
According to task ```swap``` entry should be removed, and swap should be disabled after reboot.

**Config files**
N/A

**Environment**
- Cloud provider: [None]
- OS: Ubuntu 18.04 / 20.04 (vagrant's generic/ubuntu) but should be similar on other platforms

**epicli version**: 1.2

**Example:**
This is how ```/etc/fstab``` file looks like on vagrant's generic/ubuntu2004:

![image](https://user-images.githubusercontent.com/48471627/155493930-fa7c7562-a8db-4dad-8c1c-df6986f96b10.png)

```none``` instead ```swap``` in mount point column causes that no changes will be done by existing task.

*Create backport task to v1.0 before close this one*
Backport task: #2993 

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed
