### ISSUE TITLE
[BUG] Unnecesary domain validation

### ISSUE THREAD

**Issue by wkalbar** [epiphany-platform/epiphany#2996]
**Describe the bug**
There is `hostname_domain_extension` validation set to: `^[a-zA-Z0-9.-]{0,20}$`
With our domain it let us space only for 5 chars for subdomain.

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file and set `hostname_domain_extension` to value longer than 20 chars
3. execute `epicli apply ...`

**Expected behavior**
Change validation to at last `^[a-zA-Z0-9.-]{0,25}$`. If this limitation is caused by whole VM name, please change `kubernetes` in VM name to `k8s` (`kubernetes-master` is the longest name in whole cluster).

**Config files**
n/a

**Environment**
- Cloud provider: Azure

**epicli version**: 1.0.2

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by rafzei** [comment]
@seriva there is any requirement to have this 20chars limitation?

**Comment by przemyslavic** [comment]
@rafzei I guess it is more complex. Linux host name cannot exceed 64 characters in length.
```
ERROR cli.engine.terraform.TerraformCommand - Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Linux host name cannot exceed 64 characters in length or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \\ | ; : ' \" , < > / ?." Target="computerName"
```

We allow prefix to be 2-8 characters and cluster name 3-20.
Consider the opendistro component:
    `prefix` - `cluster name` - `component name` - `vm` - `x`
`12345678-12345678901234567890-opendistro-for-elasticsearch-vm-0`
It is already 63 characters long without domain extension.
It strictly depends on the chosen cluster name, prefix and components used.

Maybe it would be better to turn off the validation and then Azure API will return an error if the limit is exceeded.

**Comment by wkalbar** [comment]
Please consider change `kubernetes` into `k8s` in kubernetes node/master VM names. It'll cut 7 chars from longest names in cluster (and you can then limit component name to 15 instead of 20, and then domain name can be 25 instead 20 (for example).
