### ISSUE TITLE
[FEATURE REQUEST] [download-requirements.py] Add failed command to error message

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#3001]
**Is your feature request related to a problem? Please describe.**
Error message doesn't contain failed command.

Example:
`[ERROR]: repoquery failed for package postgresql13-server, reason: package not found`

**Describe the solution you'd like**
Extend error message to contain failed command.

Example:
`[ERROR]: repoquery failed for package `postgresql13-server`, reason: package not found, command: repoquery --quiet --queryformat %{name}-%{version}-%{release}.%{arch} --archlist=x86_64,noarch --assumeyes postgresql13-server`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [x] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by sbbroot** [comment]
Pushed to the feature/upgrade_rhel branch (#1332)
