### ISSUE TITLE
[BUG][2.0.0dev] install 'containerd.io=1.4.12-*' failed, when upgrade from v1.3.0 to 2.0.0dev

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#3006]
**Describe the bug**
When doing upgrade from v1.3.0 to 2.0.0dev, `epicli upgrade` fails on task `Install Docker packages` from `ansible/playbooks/roles/docker/tasks/main.yml` with error (full error message in additional context):
`install 'containerd.io=1.4.12-*'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", ...`

##### Possible issue:
1. `containerd.io` in epicli v1.3.0 is installed without version specification, see task `ansible/playbooks/roles/docker/tasks/main.yml`.
2. In v2.0.0dev we are specifying its version with `- 'containerd.io=1.4.12*'`, see task `ansible/playbooks/roles/docker/tasks/main.yml` and `roles/containerd/defaults/main.yml` 
3. And finally investigation on repository machine shows that version installed with v1.3.0 is higher than specified in v2.0.0dev:
`[operations@cicharka-zoo-kaf-repository-vm-0 ~]$ containerd --version
containerd containerd.io 1.4.13 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d`

**How to reproduce**
1. `epicli init` and `epicli apply` with v1.3.0
4. `epicli upgrade` with v2.0.0dev

**Expected behavior**
`epicli upgrade` should perform upgrade successfully

**Config files**
Components used in config file:
```yaml
  components:
    repository:
      count: 1
    kubernetes_master:
      count: 0
    kubernetes_node:
      count: 0
    logging:
      count: 1
    monitoring:
      count: 1
    kafka:
      count: 2
    postgresql:
      count: 1
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
version: 1.3.0
```

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 20.04.3 LTS, **RH should be checked as well**

**epicli version**:
v2.0.0dev

**Additional context**
Full Error message:
`ERROR cli.src.ansible.AnsibleCommand - fatal: [cicharka-zoo-kaf-repository-vm-0]: FAILED! => {"cache_update_time": 1646650726, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'containerd.io=1.4.12-*'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.\n", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages will be DOWNGRADED:\n  containerd.io\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 15 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages will be DOWNGRADED:", "  containerd.io", "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 15 not upgraded."]}`

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [x] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by rafzei** [comment]
So using the latest released version of containerd in epi v2.0 should solve the problem.
