### ISSUE TITLE
[FEATURE REQUEST] Create more accurate exception output for dnf_repoquery.py command

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#3037]
**Is your feature request related to a problem? Please describe.**
After changes in dnf_repoquery command we run list of all packages in one repoquery call. That means when some of paczage is not found we get excpetion with list of all packages and it difficult to find package is the reason of issue.

```code
        def output_handler(output: str):
            """ In addition to errors, handle missing packages """
            if not output:
                raise PackageNotfound(f'repoquery failed for packages `{packages}`, reason: some of package(s) not found')
            elif 'error' in output:
                raise CriticalError(f'repoquery failed for packages `{packages}`, reason: `{output}`')
```

**Describe the solution you'd like**
Try to modify code to get only packages in which problem occured

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [x] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [x] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by rafzei** [comment]
The solution that came to my mind is to store the log from dnf command in tmp, if the error will occur, it should point the user to this log file.
Moreover, we could grep this file and show a short msg with the failed package.

**Comment by sbbroot** [comment]
In my opinion in such case: `len(stdout) == 0` we should also check the `stderr`.
Handlers should take `stderr` as a second argument.
Here:
![image](https://user-images.githubusercontent.com/86356638/165508685-8d36bc91-0b8a-48d3-97bb-dbdd5a34cbde.png)

**Comment by to-bar** [comment]
Previously we were querying packages one by one instead of one big shot.

I see two alternative solutions:
1) Parse error message and [after the original (probably long) error message] print a short, human friendly message.
2) Catch exception and retry but switching from the current (batch) mode to the old (serial) - querying one by one should tell us which package is problematic.
