### ISSUE TITLE
[BUG] HAProxy upgrade fails on re-run trying to remove haproxy_exporter

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3049]
**Describe the bug**
There is an issue with haproxy exporter removal when executing the upgrade command twice.
After the first upgrade, the service is already removed, but after executing the upgrade command again, it tries to remove the nonexistent service.

The condition used in task `load_balancer | Remove haproxy-exporter` is as follows:
```
  when: ansible_facts.services["prometheus-haproxy-exporter.service"] is defined
```
But after ansible update, `prometheus-haproxy-exporter.service` is still visible in ansible_facts.services but it's status is `not-found`, which causes some tasks to be re-executed.
```
14:58:56 INFO cli.src.ansible.AnsibleCommand -         "prometheus-haproxy-exporter.service": {
14:58:56 INFO cli.src.ansible.AnsibleCommand -             "name": "prometheus-haproxy-exporter.service",
14:58:56 INFO cli.src.ansible.AnsibleCommand -             "source": "systemd",
14:58:56 INFO cli.src.ansible.AnsibleCommand -             "state": "stopped",
14:58:56 INFO cli.src.ansible.AnsibleCommand -             "status": "not-found"
14:58:56 INFO cli.src.ansible.AnsibleCommand -         },
```
This means that the condition is insufficient and must be extended (similar to https://github.com/epiphany-platform/epiphany/pull/2962).

**How to reproduce**
1. deploy v1.0.x cluster with load balancer and montoring
2. upgrade to 2.0.0dev
3. upgrade to 2.0.0dev

**Expected behavior**
The upgrade should be successful.

**Config files**

**Environment**
- Cloud provider: [all]
- OS: [all]

**epicli version**: 2.0.0dev

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by atsikham** [comment]
https://github.com/epiphany-platform/epiphany/issues/2940#issuecomment-1032587119
