### ISSUE TITLE
[SPIKE][download-requirements] Add manifest handling for downloading only needed data

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#3071]
**Is your spike related to a problem or idea? Please describe.**
By default download-requirements should download all the data defined in the requirements files.
If manifest file is provided for the download-requirements script, it should parse it and choose the only needed data for target cluster.

**Describe the outcome you'd like**
Separate issues should be created for implementing:
- handling the manifest file
- dashboards download
- files download
- images download
- packages download
With full description on how to implement the solution

**What is the reason or source for the spike**
This is a long wanted feature for the download-requirements script to work much faster.

**Additional context**
-

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by sbbroot** [comment]
Separate SPIKE was added for the packages (#3094)

**Comment by sbbroot** [comment]
Issue regarding the manifest was created (#3097)

**Comment by sbbroot** [comment]
images - (#3106)
files - (#3116)

**Comment by sbbroot** [comment]
dashboards - no need for optimization since downloading all of them takes roughly 2 - 5 seconds:
![image.png](https://images.zenhubusercontent.com/60d335008b0f92baf11ab200/d89894c1-5f2a-4e2f-bdf2-4405e5ce452b)

**Comment by to-bar** [comment]
> dashboards - no need for optimization since downloading all of them takes roughly 2 - 5 seconds

I would opt for adding the adaptive functionality also for dashboards but in this case not because of speed but for scenario when a dashboard's URL is broken and user doesn't want to deploy Grafana. Having adaptive mode for dashboards would allow to deploy a cluster successfully despite the broken link(s).

**Comment by sbbroot** [comment]
I agree that dashboards should not be downloaded when Grafana is not on a list of components that will be used. As for URLs there is a separate issue on adding alternative URLs.

**Comment by sbbroot** [comment]
Added issue for Grafana dashboards: (#3131).
