### ISSUE TITLE
Failed to get Azure Cloud Provider

### ISSUE THREAD

**Issue by michalmarszalek-epm** [epiphany-platform/epiphany#308]
Failed to create provisioner: Failed to get Azure Cloud Provider. GetCloudProvider returned <nil> instead

Unable to create StorageClass with provisioner: kubernetes.io/azure-file.
Unable to create PersistentVolumeClaim which based on StorageClass which uses azure-file provisioner.

Expected: 
K8s has azure provisioners or StorageClasses when deployed on Azure.

**Comment by erzetpe** [comment]
We will review this.

**Comment by alkaja** [comment]
Fixed.
