### ISSUE TITLE
[FEATURE REQUEST] PostgreSQL - Add possibility to deploy selectable number of individual instances

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#3082]
**Is your feature request related to a problem? Please describe.**
Currently when more than one instance of PostgreSQL is deployed it's always treated as a cluster. Consider to add possibility to configure more than one clustered PostgreSQL databases in one Epiphany cluster

**Describe the solution you'd like**
For one of project is required to setup several independent instances of PostgreSQL (each with replication). This means that there should be possible to define in manifest more then one PostgreSQL server which will be deployed as separate instance. Each instance should support replication (redundant servers). 

This is first stage to support TimescaleDB cluster (it is build on top of independent PostgreSQL databases) 

**Additional context**
Discuss and spike this task to check possibilities / alternatives.
Source: Jira request EP-386

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by plirglo** [comment]
After additional discussions with Requestor we agreed that we need to add feature to create more than one clustered Postgres instances with replication based on `repmgr` - this will be easier to adjust to future HA configuration.

**Comment by norbix** [comment]
**Capabilities to code :**
1. provision arbitrary number of PostgreSQL 2 node clusters deployments (HINT: min 4 clusters)
2. provision extension 'Time Scale' to PostgreSQL deployments

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
