### ISSUE TITLE
[SPIKE] Rabbitmq cluster - verify if default deployment follows guidance rules

### ISSUE THREAD

**Issue by cicharka** [epiphany-platform/epiphany#3092]
**Is your spike related to a problem or idea? Please describe.**
Verify if we are up to date with clustering guide for deploying rabbimq as k8s app -> see [Clustering Guide](https://www.rabbitmq.com/clustering.html) to learn more.

**Describe the outcome you'd like**
Rabbitmq default deployment follows Clustering Guide

**What is the reason or source for the spike**
Default number of replicas in epi cluster is equal to **2**, while clustering guide for [node-count](https://www.rabbitmq.com/clustering.html#node-count) states that `Two node clusters are highly recommended against`. 

**Additional context**
If possible and necessary, verify other k8s applications if they follow their guidance rules.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
