### ISSUE TITLE
[SPIKE][download-requirements] Optimize packages downloading using the manifest file.

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#3094]
**Is your spike related to a problem or idea? Please describe.**
Currently we download all available packages regardless of what the user has chosen (components wise).

**Describe the outcome you'd like**
Download only needed packages for the components used.

**What is the reason or source for the spike**
To speed up download-requirements script and also reduce the amount of downloaded data.

**Additional context**
.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
