### ISSUE TITLE
[BUG] dnf repoquery checks only latest kube* packages

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#3123]
**Describe the bug**
The dnf repoquery checks only the newest kube* packages due to flag used in its argument:
`--latest-limit=1`

**How to reproduce**
Run epicli apply with repository host and check downloaded packages

**Expected behavior**
All specified in packages.yml packages should be fetched.

**Config files**
If applicable, add config files to help explain your problem.

**Environment**
- Cloud provider: All
- OS: RHEL

**epicli version**: (develop branch)

**Additional context**
output after applying changes from feature [branch](https://github.com/epiphany-platform/epiphany/tree/feature/dnf-improvements):
```yaml
2022-05-04 10:21:58,450 [ERROR]: repoquery failed. Missing packages: ['kubeadm-1.18.6', 'kubeadm-1.19.15', 'kubeadm-1.20.12', 'kubeadm-1.21.7', 'kubectl-1.18.6', 'kubectl-1.19.15', 'kubectl-1.20.12', 'kubectl-1.21.7', 'kubelet-1.18.6', 'kubelet-1.19.15', 'kubelet-1.20.12', 'kubelet-1.21.7', 'kubernetes-cni-0.8.6-0']
```
---

**DoD checklist**

- Changelog
  - [ ] updated
  - [x] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by sbbroot** [comment]
Kubernetes packages will be separated under a different key `multiple_versioned` in the packages.yml file.
Such packages will be downloaded without the ` --latest-limit=1` flag.

**Comment by seriva** [comment]
Should be pulled to both dev and 2.0.0 branch when done.
