### ISSUE TITLE
[FEATURE REQUEST] Update ARM doc for 2.0.1

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#3143]
**Is your feature request related to a problem? Please describe.**
ARM installation moved from CentOS to AlmaLinux but the documentation does not reflect this.

**Describe the solution you'd like**
Update [ARM doc](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/ARM.md)

**Describe alternatives you've considered**
*

**Additional context**
*

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Fixed with #3151
