### ISSUE TITLE
[BUG] Use a stable tag for the `quay.io/ceph/ceph:v16.2.7` image

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3152]
**Describe the bug**
Recently, after the release of epicli 2.0.0, the `quay.io/ceph/ceph:v16.2.7` image tag has been updated, thus its checksum has changed, which resulted in the installation failure while downloading requirements.

As a workaround, the checksum has been updated and the `allow_mismatch` flag has been added.

We need to investigate why the patch version has been updated and do something to prevent it from happening in the future.
E.g. use an image with a specific release date, e.g.
`v16.2.7-20220510`
Worth checking out for all the other rook images.

It is also worth checking if the following information about the quay.io repository affects us:
`On June 15, 2022, Repository Signing and App Registry will be removed from quay.io. Users should migrate to use alternatives which are now natively supported (Cosign & Helm respectively)`

**Expected behavior**
A given tag should not change over time.

**Environment**
- Cloud provider: [all]
- OS: [all]

**epicli version**: 2.0.0, 2.0.1dev

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by cicharka** [comment]
Regarding information `Repository Signing and App Registry will be removed from quay.io. Users should migrate to use alternatives which are now natively supported (Cosign & Helm respectively)`:
- its affecting only repo signing and feature appr which are not related to image registry used for ceph images
- please see: [Moving On From Applications and Legacy Signing on Quay.io](https://cloud.redhat.com/blog/moving-on-from-applications-and-legacy-signing-on-quay.io#:~:text=As%20a%20registry%2C%20Quay.io,Repository%20Signing%20from%20our%20service.) for more information

**Comment by cicharka** [comment]
As described in repository information under https://quay.io/repository/ceph/ceph:
`new version with a different build date will be built when there is a base image update` - therefore when there is an image update a same tag is assigned to the new build, which caused checksum mismatch. 

To avoid this kind of situation it is recommended to use tag `suffixed with an 8-digit build date in the form YYYMMDD` - note from information: `These tags are intended for use when precise control over image upgrade is desired and are recommended for production use.`

**Comment by cicharka** [comment]
Investigation of other ceph/rook images used in Epiphany:
- only ceph/ceph image is described by a tag with build date suffix which gives additional security to have stable tags, all other images doesn't provide this option

See ticket https://github.com/epiphany-platform/epiphany/issues/3196 - it can help prevent from having mismatched checksums in the future for container images.
