### ISSUE TITLE
[BUG] Set the fixed version of `containerd` package.

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3164]
**Describe the bug**
In v1.0, we do not set a specific `containerd` version, neither in requirements.txt nor in particular ansible tasks.
This means that the latest available version is downloaded and installed.
In epicli v1.3 and v2.0, we use the fixed version `1.15.1`. 
This leads to issues during the upgrade as in v1.0 we have a newer version v1.6.4 and then we want to install v1.5.11.
There are a few places that should be checked, e.g.:
- requirements
- https://github.com/epiphany-platform/epiphany/blob/v1.0/core/src/epicli/data/common/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-Debian.yml
- https://github.com/epiphany-platform/epiphany/blob/v1.0/core/src/epicli/data/common/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-RedHat.yml
- https://github.com/epiphany-platform/epiphany/blob/v1.0/core/src/epicli/data/common/ansible/playbooks/roles/docker/tasks/main.yml

_**This should be also fixed in develop to avoid such issues in the future (the way it is done in docker role)**_
https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/docker/tasks/main.yml
- set fixed version and allow downgrade:
- https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-RedHat.yml
- https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-Debian.yml

_**This should be also fixed in v1.3**_
- allow downgrade (yum module)
- remove newer packages (apt module)"
- https://github.com/epiphany-platform/epiphany/blob/v1.3/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-RedHat.yml
- https://github.com/epiphany-platform/epiphany/blob/v1.3/ansible/playbooks/roles/haproxy_runc/tasks/install-packages-Debian.yml

**Expected behavior**
A fixed version of `containerd` package should always be installed.

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by rafzei** [comment]
@seriva. @przemyslavic do we need to hardcode containerd version in v1.0? Now, all supported upgrades handle downgrades.
