### ISSUE TITLE
[BUG] terraform fails when `use_network_security_groups` is set to `false`

### ISSUE THREAD

**Issue by wkalbar** [epiphany-platform/epiphany#3179]
**Describe the bug**
When `use_network_security_groups` is set to `false`, terraform fails with error:
```
11:54:42 INFO cli.src.providers.azure.InfrastructureBuilder - Starting step
11:54:42 INFO cli.src.providers.azure.InfrastructureBuilder - Step finished in: 0.01s
11:54:42 ERROR epicli - local variable 'subnet_nsg_association' referenced before assignment
11:54:44 INFO dump_debug_info - Error dump has been written to: /shared/epicli_error_20220601-115442.dump
11:54:44 WARNING dump_debug_info - This dump might contain sensitive information. Check before sharing.
11:54:44 INFO run_time - Total run time: 2.98s
```
when switched back to `true` it works fine, with all other settings in config file left unchanged.

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file
3. change `use_network_security_groups` to `false`
4. execute `epicli apply ...`

**Expected behavior**
Working like in previous releases.

**Config files**
Not applicable, just this one option is changed.

**Environment**
- Cloud provider: Azure

**epicli version**: 2.0.0

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
It looks like the `subnet_nsg_association` variable is not assigned if `use_network_security_groups` is set to `false` but it's used later anyway.
![image](https://user-images.githubusercontent.com/43173646/171576764-4268ab6d-2693-4008-9f7a-79e803f15d7c.png)

![image](https://user-images.githubusercontent.com/43173646/171576809-2c28d91a-ddc7-4651-883a-f76c15a1abe2.png)

**Comment by seriva** [comment]
Jup, already testing a fix for just that:)
