### ISSUE TITLE
Unable to deploy Lumada 1.10 cluster on Epiphany 1.0.0 owing to failing task "Run download-requirements script...."

### ISSUE THREAD

**Issue by jsmith085** [epiphany-platform/epiphany#3198]
**Describe the bug**
Deploys of an additional Lumada 1.10 (using Epiphany 1.0.0) are failing at task "repository : Run download-requirements script.....".  Examination of the task output (attached) suggests the problem to be related to an inability to download erlang packages.    We've logged into the repository VM that has been created (and partially loaded with packages) and confirmed that we cannot use apt-get to download the erlang packages specified in the requirements.txt that it uses to iterate through.
Luuk van-Vennrooij suggested we got to v1.0.4 as there were issues apparently in this areas that have been resolved.  However, a  review of the v1.0.4 requirements.txt file relevant for an Ubuntu target suggest no change to the package versions in relation to erlang between 1.0.0 and 1.0.4.  
We have also confirmed that the package we're trying to source under 1.0.0 (and 1.0.4) is 23.1.5 which does appear to be available on at https://packages.erglang-solutions.com/ubuntu, the apt repositor location configured on the repository VM.  
We don't understand why we're having this issue and need some assistance.
This problem is causing some major delays to project timelines and is a top priority for FMECA project and ultimately PGES.

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file
3. execute `epicli apply ...`

**Expected behavior**
We expect the "Download reuqirements" task to complete successfully on the repository VM.

**Config files**
Cluster yaml we are using attached

**Environment**
Ubuntu 18.04 (bionic) on Azure 

**epicli version**: 1.0.0
---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
Fixed in https://github.com/epiphany-platform/epiphany/pull/3200
Released `epiphanyplatform/epicli:1.0.5` image.
