### ISSUE TITLE
Typo in epiphan_azure_cert.pem name

### ISSUE THREAD

**Issue by lukurde** [epiphany-platform/epiphany#32]
https://github.com/epiphany-platform/epiphany/blob/b6d22f43d81b1f030b49b4d4d2f81f1f717e0954/core/core/src/scripts/azure/run_build.sh#L136

Missing `y`. When this file is even created? I cannot find any other occurrence in all of the source code on github.

**Comment by alkaja** [comment]
Not an issue anymore.
