### ISSUE TITLE
[BUG] Repositories for OpenDistro are shutdown

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#3243]
**Describe the bug**
The repositories for OpenDistro are shutdown as of 1 of August: https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/ 

This will cause issues when trying to install a 1.0.5 or 2.0.0 cluster.
Download-requirements script will fail with the following issues trying to import a gpg key:
```
Executing: rpm --import https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch", "error: https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch: key 1 not an armored public key."
```
or
```
gpg: no valid OpenPGP data found
```

**How to reproduce**
Try and install an new 1.0.5 or 2.0.0

**Expected behavior**
That the cluster installs fine with Opendistro/logging.

**Config files**
Any configuration with the logging or opendistro components enabled.

**Environment**
Ubuntu/RHEL/CentOS/AlmaLinux

**Additional context**
-

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [x] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved

**Comment by apopaa** [comment]
Does this apply to 1.3.x?
