### ISSUE TITLE
Upgrade ansible-core to 2.13 (ansible 6)

### ISSUE THREAD

**Issue by tomasz-baran** [epiphany-platform/epiphany#3257]
**Is your feature request related to a problem? Please describe.**
ansible-core 2.13 contains a lot of bugfixes: [ansible-core 2.13 Release Notes](https://github.com/ansible/ansible/blob/stable-2.13/changelogs/CHANGELOG-v2.13.rst)
[Ansible 6 Release Notes](https://github.com/ansible-community/ansible-build-data/blob/main/6/CHANGELOG-v6.rst)

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [x] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [x] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by seriva** [comment]
Can be probably done at the same time as #3177 as this will also touch the Python requirements.
