### ISSUE TITLE
[FEATURE REQUEST][download-requirements] Add mechanism to use manifest's configuration/image-registry doc to download wanted images

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#3261]
**Is your feature request related to a problem? Please describe.**
Currently we filter images in such way:

1. If there is no `configuration/image-registry` doc filter images based on used features.
2. If there is `configuration/image-registry` doc then ignore filtering and download everything in that doc.

Such mechanism is confusing and leads to problems

**Describe the solution you'd like**
It would be good to implement a flag such as `--use-image-registry-doc` so that images would be downloaded explicitly.

**Describe alternatives you've considered**
.

**Additional context**
Current mechanism must be based on a flag used instead of a document check.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by seriva** [comment]
Replica of https://github.com/epiphany-platform/epiphany/issues/3260 so closing.
