### ISSUE TITLE
[SPIKE] Terraform not to log any sensitive data by epicli

### ISSUE THREAD

**Issue by sbbroot** [epiphany-platform/epiphany#3290]
**Is your spike related to a problem or idea? Please describe.**
Terraform logs contain sensitive data which should not be visible.

**Describe the outcome you'd like**
Any sensitive data produced by terraform should not be logged or should be masked with '*' character.

**What is the reason or source for the spike**
#3257

**Additional context**
.

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
