### ISSUE TITLE
[Issue] epicli - 'NoneType' object has no attribute 'specification' issue  while running Epiphany through .yml file

### ISSUE THREAD

**Issue by GaneshHitachi** [epiphany-platform/epiphany#3291]
**Describe the bug**

**How to reproduce**
1. Created and configured .yml file 
2. Installed Docker Desktop in local system  and connected to remote system via Mobaxterm
3. execute epicli sample command : docker run -it -v "D:\Advantech1":/shared --name=epicli  epiphanyplatform/epicli:2.0.1
4. execute `epicli apply sample command: `epicli  --debug 4 apply -f newonprem.yml --vault-password 1234567890 --no-infr

**Expected behavior**
Since we are trying to run epiphany latest version-2.0.1, it should generate run properly and generate all files properly and eventually run properly with no errors

**Config files**
.yml file

**Environment**
- 
- OS: [e.g. Ubuntu 20.04.3 LTS, you can use `cat /etc/os-release`]

**epicli version**: [`epicli --version`]    2.0.1 

**Additional context**
Error screenshots attached
![Screen1](https://user-images.githubusercontent.com/115778189/195796776-058ef42f-9990-423b-8382-9d13784840ac.jpg)
![Screen2](https://user-images.githubusercontent.com/115778189/195796789-c62b1a51-c5fc-464b-aa9d-1db982424ab4.jpg)

Yml file Screenshots : I have attached yml file contents in text file as shown below: 
[opnprem.txt](https://github.com/epiphany-platform/epiphany/files/9783907/opnprem.txt)

**Comment by przemyslavic** [comment]
@GaneshHitachi 
I know this error doesn't say much but the problem is with your data yaml file.
In the `epiphany-cluster` document you specify the machine for `kafka` to be `default-kafka1` but you do not provide a definition for this vm (there is only a doc for `default-kafka` vm).
You should use `default-kafka` or `default-kafka1` in both places and this will solve the issue you ran into.

**Comment by GaneshHitachi** [comment]
Thanks przemyslavic for the reply. Now I am SSH connection failure issue with the host. Please check the screenshot.
![failedtoconnect](https://user-images.githubusercontent.com/115778189/195831878-dcdf48bc-ef00-4df4-9a27-c1268e8813c3.jpg)

**Comment by seriva** [comment]
> @GaneshHitachi I know this error doesn't say much but the problem is with your data yaml file. In the `epiphany-cluster` document you specify the machine for `kafka` to be `default-kafka1` but you do not provide a definition for this vm (there is only a doc for `default-kafka` vm). You should use `default-kafka` or `default-kafka1` in both places and this will solve the issue you ran into.

@GaneshHitachi Additionally you also still are using the configuration/feature-mappings document which was deprecated in 2.0.1: https://github.com/epiphany-platform/epiphany/blob/v2.0/docs/changelogs/CHANGELOG-2.0.md#breaking-changes

If you made any changes to the mappings you need to add them to configuration/feature-mapping.

**Comment by seriva** [comment]
> Thanks przemyslavic for the reply. Now I am SSH connection failure issue with the host. Please check the screenshot. ![failedtoconnect](https://user-images.githubusercontent.com/115778189/195831878-dcdf48bc-ef00-4df4-9a27-c1268e8813c3.jpg)

Could you provide the logfile, as far as I can see you might have some issue with your SSH keys.

**Comment by GaneshHitachi** [comment]
> > Thanks przemyslavic for the reply. Now I am SSH connection failure issue with the host. Please check the screenshot. ![failedtoconnect](https://user-images.githubusercontent.com/115778189/195831878-dcdf48bc-ef00-4df4-9a27-c1268e8813c3.jpg)
> 
> Could you provide the logfile, as far as I can see you might have some issue with your SSH keys.

sure.
[log.log](https://github.com/epiphany-platform/epiphany/files/9785520/log.log)

**Comment by seriva** [comment]
> > > Thanks przemyslavic for the reply. Now I am SSH connection failure issue with the host. Please check the screenshot. ![failedtoconnect](https://user-images.githubusercontent.com/115778189/195831878-dcdf48bc-ef00-4df4-9a27-c1268e8813c3.jpg)
> > 
> > 
> > Could you provide the logfile, as far as I can see you might have some issue with your SSH keys.
> 
> sure. [log.log](https://github.com/epiphany-platform/epiphany/files/9785520/log.log

I saw in the config that your SSH key is coming from the shared folde and your running on Windows, did you move the SSH key into the container storage: 

https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/PREREQUISITES.md#note-for-windows-users
