### ISSUE TITLE
[BUG] air-gapped infrastructure installation not downloading for ubuntu-18.04

### ISSUE THREAD

**Issue by rahulrajanrepo** [epiphany-platform/epiphany#3295]
Hi Team,

I'm trying to trigger air-gapped script for ubuntu-18.04 but seems like it is not working out,

![image](https://user-images.githubusercontent.com/49981814/199480601-213cfe8b-2daa-49b9-abbe-74479c4617aa.png)

![image](https://user-images.githubusercontent.com/49981814/199480767-f97c5085-4b11-481a-b839-b0474ddc0d27.png)

**Comment by seriva** [comment]
This is just a message stating that the OS you want to install a specific version of Epiphany on is not supported. We have some restrictions which operating systems are supported by different versions of Epiphany. Check point 2 in the following links:

- [1.0.x](https://github.com/epiphany-platform/epiphany/blob/v1.0/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-existing-infrastructure)
- [2.0.x](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-existing-infrastructure)

**Comment by seriva** [comment]
Closing as this is not an issue.
