### ISSUE TITLE
Epiphany 2.0.5 not working with Rhel air gap installation.

### ISSUE THREAD

**Issue by ravi8643** [epiphany-platform/epiphany#3342]
Hi team we are facing issue with the  Epiphany 2.0.5 while installing offline in Rhel 8.7 version.
**Error:**
07:18:10 INFO cli.src.ansible.AnsibleCommand - TASK [download : Set files in repository as fact] ******************************
07:18:10 INFO cli.src.ansible.AnsibleCommand - ok: [hapg-master]
07:18:10 INFO cli.src.ansible.AnsibleCommand -
07:18:10 INFO cli.src.ansible.AnsibleCommand - TASK [download : Find and return the newest archive's name and version (using pattern: ^helm-v([0-9.]+)-linux-amd64.tar.gz$)] ***
07:18:10 INFO cli.src.ansible.AnsibleCommand - fatal: [hapg-master]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ _version_to_name_map[_version_to_name_map.keys() | max] }}: No aggregated item, sequence was empty.\n\nThe error appears to be in '/shared/build/uat-cluster/ansible/roles/download/tasks/pick_newest.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Find and return the newest archive's name and version (using pattern: {{ archive_name_regexp }})\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
07:18:10 INFO cli.src.ansible.AnsibleCommand -
07:18:10 INFO cli.src.ansible.AnsibleCommand - PLAY RECAP *********************************************************************
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-elk                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-loadbalancer          : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-master                : ok=103  changed=4    unreachable=0    failed=1    skipped=43   rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-monitoring            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-node1                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand - hapg-node2                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
07:18:10 INFO cli.src.ansible.AnsibleCommand -
07:18:10 INFO cli.src.commands.Apply - Step finished in: 10m 45.07s
07:18:10 ERROR epicli - Error running: "ansible-playbook -i /shared/build/uat-cluster/inventory --vault-password-file /home/epiuser/.epicli/vault.cfg /shared/build/uat-cluster/ansible/kubernetes_master.yml"
07:18:13 INFO dump_debug_info - Error dump has been written to: /shared/build/uat-cluster/epicli_error_20230424-071810.dump

**Comment by seriva** [comment]
Current version of RedHat we support is 8.6. We will not support 8.7 as it is a minor release with limited support:

https://access.redhat.com/support/policy/updates/errata#RHEL8_Planning_Guide

8.8 is still in beta so its not supported jet.
