### ISSUE TITLE
Grafana download failed due to checksum mismatch, WARNING someone might have replaced the file

### ISSUE THREAD

**Issue by rahulrajanrepo** [epiphany-platform/epiphany#3392]
**Describe the bug**
I was trying to setup an onprem machine with all the required installation so was running the ansible part (no-infra) as infra is already available, while executing the script getting the following error and I've attached by yaml file along with this, please help tp resolve this issue, thanks.

Error-
TASK [repository : Run download-requirements script, this can take a long time (optimized with manifest)
16:44:07 INFO cli.src.ansible.AnsibleCommand - fatal: [repo-log-mon]: FAILED! => {
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "changed": true,
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "cmd": "set -o pipefail && \"/var/tmp/epi-download-requirements/download-requirements.py\"    /var/www/html/epirepo    \"ubuntu-20.04\"    --manifest \"/var/tmp/epi-download-requirements/manifest.yml\"    --no-logfile    --repos-backup-file /var/tmp/enabled-system-repos.tar    --verbose |&\ntee >(systemd-cat --identifier=download-requirements.py)",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "delta": "0:00:25.728569",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "end": "2023-09-10 16:44:07.209823",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "invocation": {
16:44:07 INFO cli.src.ansible.AnsibleCommand -         "module_args": {
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "_raw_params": "set -o pipefail && \"/var/tmp/epi-download-requirements/download-requirements.py\"    /var/www/html/epirepo    \"ubuntu-20.04\"    --manifest \"/var/tmp/epi-download-requirements/manifest.yml\"    --no-logfile    --repos-backup-file /var/tmp/enabled-system-repos.tar    --verbose |&\ntee >(systemd-cat --identifier=download-requirements.py)",
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "_uses_shell": true,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "argv": null,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "chdir": null,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "creates": null,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "executable": "/bin/bash",
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "removes": null,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "stdin": null,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "stdin_add_newline": true,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "strip_empty_ends": true,
16:44:07 INFO cli.src.ansible.AnsibleCommand -             "warn": false
16:44:07 INFO cli.src.ansible.AnsibleCommand -         }
16:44:07 INFO cli.src.ansible.AnsibleCommand -     },
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "msg": "non-zero return code",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "rc": 1,
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "start": "2023-09-10 16:43:41.481254",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "stderr": "",
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "stderr_lines": [],
16:44:07 INFO cli.src.ansible.AnsibleCommand -     "stdout": "2023-09-10 16:43:41,519 [INFO]: Info summary:\n--------------------------------------------------\nOS Arch: x86_64\nOS Type: ubuntu-20.04\nScript location: /var/tmp/epi-download-requirements\nDirectories used:\n- files:              /var/www/html/epirepo/files\n- grafana dashboards: /var/www/html/epirepo/grafana_dashboards\n- images:             /var/www/html/epirepo/images\n- packages:           /var/www/html/epirepo/packages\nRepos backup file: /var/tmp/enabled-system-repos.tar\nManifest used: /var/tmp/epi-download-requirements/manifest.yml\nVerbose mode: True\nRetries count: 3\n--------------------------------------------------\n2023-09-10 16:43:41,601 [INFO]: Manifest summary:\n--------------------------------------------------\nComponents requested:\n- kafka\n- kubernetes_master\n- kubernetes_node\n- logging\n- monitoring\n- repository\n\nFeatures requested:\n- applications\n- filebeat\n- firewall\n- grafana\n- helm\n- image-registry\n- jmx-exporter\n- kafka\n- kafka-exporter\n- keycloak\n- kubernetes-master\n- kubernetes-node\n- logging\n- node-exporter\n- opensearch-dashboards\n- prometheus\n- repository\n- rook\n- zookeeper\n\nFiles to download:\n- alertmanager\n- apache-zookeeper\n- filebeat-chart\n- helm\n- jmx-prometheus-javaagent\n- kafka\n- kafka-exporter\n- keycloak\n- node-exporter\n- node-exporter-chart\n- opensearch\n- opensearch-dashboards\n- opensearch-perf-top\n- prometheus\n- rook-ceph-chart\n- rook-ceph-cluster-chart\n\nDashboards to download:\n- grafana_dashboard_10991\n- grafana_dashboard_11074\n- grafana_dashboard_179\n- grafana_dashboard_1860\n- grafana_dashboard_315\n- grafana_dashboard_405\n- grafana_dashboard_4279\n- grafana_dashboard_455\n- grafana_dashboard_6663\n- grafana_dashboard_7249\n- grafana_dashboard_7589\n- grafana_dashboard_789\n- grafana_dashboard_9628\n\nImages to download:\n- bitnami/pgbouncer:1.16.0\n- bitnami/pgpool:4.2.4\n- calico/cni:v3.15.0\n- calico/cni:v3.20.3\n- calico/cni:v3.23.3\n- calico/kube-controllers:v3.15.0\n- calico/kube-controllers:v3.20.3\n- calico/kube-controllers:v3.23.3\n- calico/node:v3.15.0\n- calico/node:v3.20.3\n- calico/node:v3.23.3\n- calico/pod2daemon-flexvol:v3.15.0\n- calico/pod2daemon-flexvol:v3.20.3\n- docker.io/busybox:1.32\n- haproxy:2.2.2-alpine\n- k8s.gcr.io/coredns/coredns:v1.8.0\n- k8s.gcr.io/coredns/coredns:v1.8.4\n- k8s.gcr.io/coredns:1.6.7\n- k8s.gcr.io/coredns:1.7.0\n- k8s.gcr.io/etcd:3.4.13-0\n- k8s.gcr.io/etcd:3.4.3-0\n- k8s.gcr.io/etcd:3.5.0-0\n- k8s.gcr.io/kube-apiserver:v1.18.6\n- k8s.gcr.io/kube-apiserver:v1.19.15\n- k8s.gcr.io/kube-apiserver:v1.20.12\n- k8s.gcr.io/kube-apiserver:v1.21.7\n- k8s.gcr.io/kube-apiserver:v1.22.4\n- k8s.gcr.io/kube-controller-manager:v1.18.6\n- k8s.gcr.io/kube-controller-manager:v1.19.15\n- k8s.gcr.io/kube-controller-manager:v1.20.12\n- k8s.gcr.io/kube-controller-manager:v1.21.7\n- k8s.gcr.io/kube-controller-manager:v1.22.4\n- k8s.gcr.io/kube-proxy:v1.18.6\n- k8s.gcr.io/kube-proxy:v1.19.15\n- k8s.gcr.io/kube-proxy:v1.20.12\n- k8s.gcr.io/kube-proxy:v1.21.7\n- k8s.gcr.io/kube-proxy:v1.22.4\n- k8s.gcr.io/kube-scheduler:v1.18.6\n- k8s.gcr.io/kube-scheduler:v1.19.15\n- k8s.gcr.io/kube-scheduler:v1.20.12\n- k8s.gcr.io/kube-scheduler:v1.21.7\n- k8s.gcr.io/kube-scheduler:v1.22.4\n- k8s.gcr.io/pause:3.2\n- k8s.gcr.io/pause:3.4.1\n- k8s.gcr.io/pause:3.5\n- k8s.gcr.io/sig-storage/csi-attacher:v3.4.0\n- k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0\n- k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0\n- k8s.gcr.io/sig-storage/csi-resizer:v1.4.0\n- k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1\n- kubernetesui/dashboard:v2.3.1\n- kubernetesui/metrics-scraper:v1.0.7\n- quay.io/ceph/ceph:v16.2.7-20220510\n- quay.io/cephcsi/cephcsi:v3.5.1\n- quay.io/coreos/flannel:v0.12.0\n- quay.io/coreos/flannel:v0.12.0-amd64\n- quay.io/coreos/flannel:v0.14.0\n- quay.io/coreos/flannel:v0.14.0-amd64\n- quay.io/coreos/flannel:v0.15.1\n- quay.io/csiaddons/k8s-sidecar:v0.2.1\n- quay.io/csiaddons/volumereplication-operator:v0.3.0\n- quay.io/keycloak/keycloak:19.0.2\n- rabbitmq:3.8.9\n- registry:2.8.0\n- rook/ceph:v1.8.8\n--------------------------------------------------\n2023-09-10 16:43:41,601 [INFO]: Installing base packages...\n2023-09-10 16:43:42,302 [INFO]: Done installing base packages.\n2023-09-10 16:43:42,302 [INFO]: Restoring repository files...\n2023-09-10 16:43:42,305 [INFO]: Done restoring repository files.\n2023-09-10 16:43:42,305 [INFO]: Adding third party repositories...\n2023-09-10 16:43:54,528 [INFO]: Done adding third party repositories.\n2023-09-10 16:43:54,528 [INFO]: Downloading packages from repos...\n2023-09-10 16:44:02,875 [INFO]: Done downloading packages from repos.\n2023-09-10 16:44:02,876 [INFO]: Downloading packages from urls...\n2023-09-10 16:44:03,185 [INFO]: Done downloading packages from urls.\n2023-09-10 16:44:03,185 [INFO]: Downloading files...\n2023-09-10 16:44:06,408 [INFO]: Done downloading files.\n2023-09-10 16:44:06,409 [INFO]: Downloading grafana dashboards...\n2023-09-10 16:44:06,409 [INFO]: - https://grafana.com/api/dashboards/11074/revisions/9/download\n2023-09-10 16:44:07,201 [ERROR]: - https://grafana.com/api/dashboards/11074/revisions/9/download - download failed due to checksum mismatch, WARNING someone might have replaced the file.",

[onprem.zip](https://github.com/hitachienergy/epiphany/files/12569259/onprem.zip)

**Comment by seriva** [comment]
Please always use the latest version as this was already fixed in 2.0.7:
https://github.com/hitachienergy/epiphany/blob/develop/docs/changelogs/CHANGELOG-2.0.md#fixed

Issues: #3374
