### ISSUE TITLE
[BUG] Short description of the bug

### ISSUE THREAD

**Issue by yuvarajpublicgithub** [epiphany-platform/epiphany#3433]
Epiphany doesnot support Rhel 9. 
We tried downloading package for Rhel 9 for air gap installation, Got following error:
epicli <command> [<args>] prepare [-h] --os {almalinux-8,rhel-8,ubuntu-20.04} --arch {aarch64,x86_64} [-o OUTPUT_DIR]
epicli <command> [<args>] prepare: error: argument --os: invalid choice: 'rhel-9' (choose from 'almalinux-8', 'rhel-8', 'ubuntu-20.04')
11:06:17 INFO run_time - Total run time: 0.02s
 
epicli asking to choose only these OS
![image (3)](https://github.com/hitachienergy/epiphany/assets/157709215/2a4f13be-e3ae-46f7-939c-4ac0052a49af)

**Comment by seriva** [comment]
RedHat 9 will not be supported anymore as Epiphany is in maintenance mode. RedHat8 is supported until EOL of Epiphany 2.x:

[RedHat 8 support](https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,OpenShift%20Container%20Platform%204)
[Epiphany 2.x support](https://github.com/hitachienergy/epiphany/blob/develop/docs/home/LIFECYCLE.md)
