### ISSUE TITLE
[BUG] 2ndQuadrant repo GPG public key expired

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3448]
**Describe the bug**
The public key for 2ndQuadrant repo has expired on 08.03.2024 which causes epicli installation to fail.
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
pub   rsa4096 2018-03-14 [SC] [expired: 2024-03-08]
      8565305CEA7D0B664933D2509904CD4BD6BAF0C3
uid                      Public repository signing key 2ndQuadrant <ci@2ndquadrant.com>
```
```

--------------------------------------------------
2024-03-10 23:12:41,094 [INFO]: Installing base packages...
2024-03-10 23:12:42,058 [INFO]: Done installing base packages.
2024-03-10 23:12:42,093 [INFO]: Adding third party repositories...
2024-03-10 23:12:50,917 [WARNING]: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: GPG error: https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease: The following signatures were invalid: EXPKEYSIG 9904CD4BD6BAF0C3 Public repository signing key 2ndQuadrant <ci@2ndquadrant.com>
E: The repository 'https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease' is not signed.

2024-03-10 23:12:54,098 [WARNING]: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: GPG error: https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease: The following signatures were invalid: EXPKEYSIG 9904CD4BD6BAF0C3 Public repository signing key 2ndQuadrant <ci@2ndquadrant.com>
E: The repository 'https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease' is not signed.

2024-03-10 23:12:57,399 [WARNING]: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: GPG error: https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease: The following signatures were invalid: EXPKEYSIG 9904CD4BD6BAF0C3 Public repository signing key 2ndQuadrant <ci@2ndquadrant.com>
E: The repository 'https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease' is not signed.

2024-03-10 23:12:57,399 [WARNING]: Retries count reached maximum, command: `apt update`
```

Original issue: https://github.com/2ndQuadrant/pglogical/issues/464

Need to wait until the key is updated.
As a workaround (**strictly not recommended**), one can add the 2ndquadrant repository to trusted ones.

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file
3. execute `epicli apply ...`

**Expected behavior**

**Config files**
If applicable, add config files to help explain your problem.

**Environment**
- Cloud provider: [AWS | Azure | All | None]
- OS: [e.g. Ubuntu 20.04.3 LTS, you can use `cat /etc/os-release`]

**epicli version**: [`epicli --version`]

**Additional context**

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved

**Comment by przemyslavic** [comment]
The gpg public key for 2ndQuadrant repo has been updated and should be valid till 11.03.2026.

**Comment by rahulrajandevops** [comment]
Hi Team, 
Is this issue got fixed, my execution is getting failed with similar issue.
I use epiphany 2.0.13
Error-
05:13:41 INFO cli.src.ansible.AnsibleCommand -     "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely
, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http
s://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant InRelease: The following signatures were invalid: EXPKEYSIG 9904CD4BD6BAF0C3 Publi
c repository signing key 2ndQuadrant <ci@2ndquadrant.com>, E:The repository 'https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant I
nRelease' is not signed.",
