### ISSUE TITLE
lodash.template < 4.5.0 vulnerability

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#354]

**Comment by seriva** [comment]
Its in one of the React tooling build dependencies so it wont effect the actual running code. I suggest waiting when they update this.

**Comment by erzetpe** [comment]
Okay, so I will close this until then.

**Comment by erzetpe** [comment]
Reopen not to loose it.

**Comment by alkaja** [comment]
Fixed.
