### ISSUE TITLE
Update KeyCloak

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#397]
- Update KeyCloak application deployment  to the latest version.
- Update the Keycloak examples to the latest version.
- Add properly self signed certificate for KeyCloak TLS communication inside the cluster (Ask Luuk).
- Data migration from old version to a new one

**Comment by gj25** [comment]
Just to confirm that the update will be to the latest 8.0.2 release, which contains the fix for the Chrome 80 Same Site cookie update:
https://www.keycloak.org/2020/02/keycloak-802-released.html

Thanks

**Comment by usshmah** [comment]
Keycloak 9.0.0 was released on Monday February 17 2020 https://www.keycloak.org/2020/02/keycloak-900-released.html

**Comment by gj25** [comment]
@toszo Do you have a date when will Epiphany with the upgraded Keycloak be released? Thanks.

**Comment by toszo** [comment]
@gj25 It is planned for 0.6.0 release (end of March'20).
