### ISSUE TITLE
Deployment/Application role fails because Kubernetes cluster is not ready after reboot

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#407]
On slower VMs sometimes the Deployment/Application fails because the Kubernetes cluster is not ready after reboot causing execution of Kubectl commands to timeout.

**Fix to be implemented:** Check if the cluster is ready before the Deployment/Application role continues.

**Workarround**: Re-run Epiphany installation to finish the application Deployment/Application role.

**Comment by przemyslawdy** [comment]
Fixed in #467
