### ISSUE TITLE
Move Kubernetes installation to binary install

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#414]
Use binary installation for Kubernetes installation (try with HyperKube) https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube

**Comment by lukurde** [comment]
I'm working on a different approach involving local repo served from one of the VMs in cluster (probably k8s-master). Shouldn't mess with our code as much as binary installations and it'll make tracking of rpms unnecessary. Closing for now.
