### ISSUE TITLE
Misleading error message if you miss "provider" property

### ISSUE THREAD

**Issue by piripinui** [epiphany-platform/epiphany#472]
Hi,

If you miss the "provider" property in an epicli configuration for an application, you will get an error when running "epicli apply..." using that file. The error that is presented to you from epicli in not very easy to understand...

15:50:15 ERROR epicli - No such attribute: provider

It would be helpful if the error said something like "Missing attribute: provider" and a reference to the section of the YAML file it is missing in (maybe the line number of the start of the section).

Thanks.

**Comment by seriva** [comment]
Hey we have some stories in place to enhance the current document validation. Ill be sure to add this.
