### ISSUE TITLE
Don't rely on git for path creation

### ISSUE THREAD

**Issue by lukurde** [epiphany-platform/epiphany#51]
https://github.com/epiphany-platform/epiphany/blob/0b98ea8ea843e29a8adeff6c8030ce4a0d605d3c/core/core/src/templates/azure/gen_sp.sh.j2#L28

We shouldn't depend on the files being inside of a Git controlled repo. What if someone downloads .zip or copy epiphany without hidden .git/ dir?

**Comment by seriva** [comment]
Jup that is a known issue for a while already. It is also the reason why we need to do git init in the deploy docker image for now when we add the platform. The plan is to get rid of this when we move from bash/shell to python.

**Comment by toszo** [comment]
Agree with both you, this is issue that we want to handle.

**Comment by seriva** [comment]
Not going todo this since we are moving Azure to epicli.
