### ISSUE TITLE
[FEATURE REQUEST]  Change Filebeat config to not use root account

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#63]
**Is your feature request related to a problem? Please describe.**
Filebeat config uses root account

**Describe the solution you'd like**
Change Filebeat config to not use root account

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
@rafzei and @to-bar can you please check if this is still relevant?

**Comment by to-bar** [comment]
> 
> 
> @rafzei and @to-bar can you please check if this is still relevant?

There is no description so hard to say.

If this task is about ownership of Filebeat configuration file, then there is nothing to do and can be closed.

I've checked (on RHEL) that the config file's attributes after deployment are the same as defined in rpm package:
```
# ls -la /etc/filebeat/filebeat*
-rw-r--r--. 1 root root 79382 Oct 16 08:21 /etc/filebeat/filebeat.reference.yml
-rw-------. 1 root root  8912 Oct 16 08:21 /etc/filebeat/filebeat.yml # original file after installing rpm manually
-rw-------. 1 root root 10864 Oct 27 10:07 /etc/filebeat/filebeat.yml.rpmsave # backup of file managed by Epiphany
```

Furthermore, installing the rpm package does not create dedicated user:
```
# grep -c filebeat /etc/shadow
0
```

If this task is about running filebeat process as a non-root user, then:
1) New user should be added (with privileges to read all log files)
2) Service file (`/usr/lib/systemd/system/filebeat.service`) should be changed to use the regular user from 1)

**Comment by mkyc** [comment]
@toszo can you please decide what is this task about? Is it about running filebeat process as a non-root user?

**Comment by toszo** [comment]
Yes, it is about running Filebeat service as non-root user. Let's discuss risk vs effort here.

**Comment by rafzei** [comment]
The official documentation states that Filebeat process can work as root or user. Of course, running by a user is a more secure approach than do this on root. 
May be useful:
https://www.elastic.co/guide/en/beats/libbeat/7.x/config-file-permissions.html

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
