### ISSUE TITLE
DOC: How to use TLS/SSL certificate with HA Proxy

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#633]
**Is your feature request related to a problem? Please describe.**
Right now we don't have any documentation related to HA Proxy configuration. We had this only for legacy Epiphany and this was removed.

**Describe the solution you'd like**
We need to add missing How-To doc in our [SECURITY.md](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/SECURITY.md#how-to-use-tlsssl-certificate-with-ha-proxy) for upgraded version HAProxy 2.2.

**Describe alternatives you've considered**
None.

**Additional context**
Our configuration for legacy was removed in [commit](https://github.com/epiphany-platform/epiphany/commit/fd5225f56652f5e598580c9d7dc62b49a785aa51#diff-cf1712152eda558da96f06399d8ccae7f3fa2bbf4af1c633a5d38cd6f2beffbd). This can be used as an example.

**Comment by to-bar** [comment]
@erzetpe - please groom this task.

**Comment by rafzei** [comment]
The internal team request for that doc, I move it to the next sprint.

**Comment by seriva** [comment]
This was added recently with pull #2850 so closing.
