### ISSUE TITLE
[SPIKE] Research replacing Fluentd as a replacement for Filebeat

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#64]
**Is your spike related to a problem or idea? Please describe.**
Currently filebeat has some issues we are working around. See discussion below.

**Describe the outcome you'd like**
Check if Fluentd might be a better option over filebeat.

**Additional context**
https://www.fluentd.org/

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by gj25** [comment]
Curious why is this being considered, since Filebeat is part of Elastic stack.

**Comment by erzetpe** [comment]
We are just assessing alternatives for Filebeat, because we have found some things that we don't like about filebeat (e.g. it can consume a lot of CPU and memory under some conditions). We have some workarounds for issues with filebeat, but maybe alternatives can also offer some additional features that may be useful.

**Comment by rafzei** [comment]
@erzetpe is this still valid? If so, please put here some more details about the issue we are currently workaround.

**Comment by rpudlowski93** [comment]
We should still take into consideration changing filebeat to something else. In epiphany 0.8 we are going to release AKS and EKS option, and we need something cloud native, running for example as DaemonSet. We can run filebeat as DaemonSet but right now we use filebeat as sysem service with auditd module installed manually for audit logs what won't work in case of DaemonSets and autoscaling option. 

First of all I would like to get some feeling from people who already used fluentd in AKS/EKS. Did You face with some issues using fluentd? @mkyc  @pyrkamarcin. If we should consider the change, I could create spike for it.

**Comment by mkyc** [comment]
@rpudlowski93 we should change this task into spike instead of feature-request.

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
