### ISSUE TITLE
Repeatable IP addresses in the cluster (to consider)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#739]
**Is your feature request related to a problem? Please describe.**
There was a request for configure repeatable IP addresses in the cluster. It is problematic to remember different addresses each time.

**Describe the solution you'd like**
- Master Node: IP address: **X.X.X.1**
- First Worker Node: IP address: **X.X.X.10**,
- Second Worker Node: IP address: **X.X.X.11**
etc...  

**Describe alternatives you've considered**
AWS: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-associating
Azure: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-static-private-ip-arm-cli

**Additional context**

**Comment by rpudlowski93** [comment]
As Tomasz already said, it is a topic to discuss, I'm not sure if we should allow here setting static IPs in order to access services. In my opinion it should be done by for example using dns.

**Comment by plirglo** [comment]
- Clue of this request is to standardize ip addresses in clusters

- If create two clusters from almost identical yaml config file machines get diffrent ips for the same vm role, for example: 

Cluster1  - kubernetes-master: 10.0.0.1
Cluster2 -  kubernetes-master: 10.0.0.4

Customers need every time check last octet when connecting to cluster

- Downscale - upscale scenario (to confirm):

When downscale cluster (remove kuberetes node), and uspcale again (add node), new node will have different ip then before even if it's got the same hostname.

**Comment by mkyc** [comment]
It's related to cloud computing where you should not care about exact IP address. I also believe this should be solved more dynamic way i.e.: DNS.

**Comment by seriva** [comment]
Closing because lack of usecase
