### ISSUE TITLE
[FEATURE REQUEST] Provide credentials for Azure in data.yaml

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#761]
**Is your feature request related to a problem? Please describe.**
Currently users can only create a cluster un-attended on Azure by adding the sp.yml into the build folder:

https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-a-cloud-provider

**Describe the solution you'd like**
Add the option to provide these fields straight under the cloud segment in the data.yml to simplify the process.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by ks4225** [comment]
Does this mean that there is no way to create an epiphany cluster unattended currently?

**Comment by seriva** [comment]
@ks4225 Cluster can be created unattended by providing a pre-created sp.yml file in the build directory:

https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-a-cloud-provider

We might want to simplify this to allow users to add a pre-created SP straight into the configuration yaml and not in this sp.yml. Changing this request.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
