### ISSUE TITLE
[FEATURE REQUEST] Introduce default resource quotas and limits

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#776]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Introduce default resource quotas and limits

**Describe alternatives you've considered**
None

**Additional context**
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by atsikham** [comment]
In my opinion we can do this configurable but we shouldn't limit user with defaults. Moreover, users can do that themselves and it's supposed that epicli apply/upgrade will not touch that part.
