### ISSUE TITLE
Emoji selector appears twice

### ISSUE THREAD

**Issue by amivaleo** [epiphany-platform/epiphany#799]
Hi!

Open any website in epiphany 3.34.2 (tested on Fedora 31) and then give `ctrl` + `.` so to open the emoji selector. If you give it twice, the selector appears twice.

Look at the screenshot that shows this issue in youtube.
![Schermata da 2019-12-26 15-31-55](https://user-images.githubusercontent.com/24316547/71479854-8bda5080-27f6-11ea-9b63-ad8740562632.png)

As far as I can see, the issue affects every website, but not the url-bar on the headerbar.

**Comment by erzetpe** [comment]
Hi,

Sorry but this is not related to our platform. :) I doubt if we will ever have any emojis. Take care!

Thanks,
Pawel
