### ISSUE TITLE
Docker version is hard-coded in installation tasks

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#802]
`docker_version` property from playbooks\roles\docker\defaults\main.yml is unused

**Comment by mum0l** [comment]
Tested in AWS on Ubuntu, RedHat and deployment works properly.
Docker version for RedHat adjusted as per version available in our repo.

Should I test it on Azure and on Baremetal also in both version Ubuntu/Redhat?

**Comment by przemyslavic** [comment]
All supported configurations were tested. No issues were found after the fix was applied.

**Comment by toszo** [comment]
Please update changelog file with the description of this task.

**Comment by mum0l** [comment]
Changelog has been updated.
