### ISSUE TITLE
[SPIKE] Check whether using yum-plugin-fastestmirror reduces Epiphany installation time

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#806]
**Is your feature request related to a problem? Please describe.**
Right now we are using different repos than fast mirror, which is highly recommended.

**Describe the solution you'd like**
If you are using the default CentOS configuration, and if you are not behind a proxy server, fastestmirror is highly recommended to be used. We want to check if time of downloading packages will decrease after changing default repos on CentOS.

**Describe alternatives you've considered**

**Additional context**
More information accessile here: https://wiki.centos.org/PackageManagement/Yum/FastestMirror,

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
Added grooming again as we switched from Yum -> DNF and CentOS -> Alma Linux.

**Comment by seriva** [comment]
Not going todo anymore spikes for Epiphany.
