### ISSUE TITLE
[FEATURE REQUEST] Review warnings from Ansible output

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#807]
**Is your feature request related to a problem? Please describe.**
We have some warnings in Ansible output log. 

**Describe the solution you'd like**
Get rid of warnings. Check and try to improve our code.

**Additional context**
Examples:
`[DEPRECATION WARNING]: evaluating {'evictionHard': {'memory.available': '200Mi'}, 'kubeReserved': {'cpu': '50m', 'memory': '256Mi'}, 'systemReserved': {'cpu': '50m', 'memory': '768Mi'}} as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

`[DEPRECATION WARNING]: ALLOW_WORLD_READABLE_TMPFILES option, moved to a per plugin approach that is more flexible, use mostly the same config will work, but now controlled from the plugin itself and not using the general constant.`

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by rafzei** [comment]
Is this issue still valid @to-bar ?

**Comment by to-bar** [comment]
Yes, there is at least:

> [DEPRECATION WARNING]: ALLOW_WORLD_READABLE_TMPFILES option, moved to a per plugin approach that is more flexible, use mostly the same config will work, but now controlled from the plugin itself and not using the general constant.

**Comment by seriva** [comment]
This was already done with several Ansible upgrades so closing for now. Can be recreated as they pop up.
