### ISSUE TITLE
[SPIKE] Research speed up/tune Ansible

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#809]
**Is your spike related to a problem or idea? Please describe.**
Test items from: https://dzone.com/articles/speed-up-ansible to see if we can speedup Ansible.

**Describe the outcome you'd like**
Metrics if the described methods in the article might give some beneficial speedups.

**What is the reason or source for the spike**
General improvement in cluster deployment speed,

**Additional context**
None

---

**DoD checklist**

* [ ] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [ ] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by seriva** [comment]
@to-bar I think its still valid, if not feel free to close.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
