### ISSUE TITLE
Review and optimize gathering Ansible facts

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#810]
It seems we overuse “hosts: all + tasks[]” for gathering facts for all hosts and do not use
`gathering = smart` but the default, which is `implicit`
The `smart` value means each new host that has no facts discovered will be scanned, but if the same host is addressed in multiple plays it will not be contacted again in the playbook run. This option can be useful for those wishing to save fact gathering time.
https://docs.ansible.com/ansible/latest/reference_appendices/config.html?highlight=smart#default-gathering
(also take into account fact_caching_timeout)

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
