### ISSUE TITLE
OS Firewall: No route to host even if firewalld is stopped on Ubuntu. After restart works fine.

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#849]

**Comment by to-bar** [comment]
Hotfixed in #859

**Comment by mkyc** [comment]
@przemyslavic can you add any context if that still exists?

**Comment by to-bar** [comment]
Work on this tasks was stopped but for sure have to be continued. I have old feature branch `fix/os-firewall` with not merged changes, however they are not completed.
