### ISSUE TITLE
[FEATURE REQUEST] Test OpenSearch clustering 

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#857]
**Is your feature request related to a problem? Please describe.**
We don't have tests for OpenSearch to check in cluster if the data is replicated from primary to other nodes.

**Describe the solution you'd like**
We want have tests for OpenSearch to check in cluster if the data is replicated correctly from primary to other nodes.

**Describe alternatives you've considered**
No.

**Additional context**
No.

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [ ] Usage compliant with license

**Comment by mkyc** [comment]
@to-bar and @przemyslavic can you please check if that is not already implemented?

**Comment by to-bar** [comment]
> 
> 
> @to-bar and @przemyslavic can you please check if that is not already implemented?

Still valid. Currently we only check if Elasticsearch cluster health is `yellow` or `green` regardless of the number of nodes.

**Comment by seriva** [comment]
Changing this for OpenSearch as we don`t want todo this for Opendistro anymore.

**Comment by seriva** [comment]
Not going todo anymore feature requests for Epiphany.
