### ISSUE TITLE
PostgreSQL replication with more nodes than 1

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#86]
Currently we support only only configuration with one primary node and one secondary node. 
In this task we want to achieve configuration with one primary and several secondary nodes.
In case of fail of primary node we should be able to  promote next secondary node to master (and so on if needed)
Use and extend existing pgbouncer / pgpool configuration.

**Comment by mkyc** [comment]
@plirglo can you please check if that is not done already?

**Comment by plirglo** [comment]
No, it's not done. Currently we support only one secondary node.

**Comment by plirglo** [comment]
It's done in task #2346. I think we can close this one.

**Comment by mkyc** [comment]
Solved in #2346
