### ISSUE TITLE
PostgreSQL replication with automatic recovery and additional copying mechanism to avoid issues with high inserts number on master

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#87]
Adding additional component to automatically recover master and add copying mechanism to replication.

**Comment by mkyc** [comment]
@plirglo can you please check if that isn't already done?

**Comment by plirglo** [comment]
Yes, we already support primary - secondary configuration with automatic failover. We also have configuration with pgpool and pgbouncer to avoid connection issues to database. So i think it's already done.

**Comment by mkyc** [comment]
@przemyslavic can you please confirm and provide some information that it is covered in our test scenarios?

**Comment by plirglo** [comment]
We already have mechanism to promote secondary node to master if needed. I don't think we should support something like auto recover of master (i understand this as auto repair of master). Also i didn't reproduce error: high inserts number. 
I think this issue may be closed. Please confirm @przemyslavic.

**Comment by przemyslavic** [comment]
I've already tested a switchover to promote a standby to primary (triggered manually with `repmgr standby switchover` command).
Also checked automatic failover to automatically promote current standby as the new master.
I think we can close this task.

**Comment by mkyc** [comment]
Solved in some unknown PR :)
