### ISSUE TITLE
[SPIKE] PostgreSQL with multiple servers able to perform insert operations in cluster

### ISSUE THREAD

**Issue by mmakow** [epiphany-platform/epiphany#88]
Basically this request is from DE. This is about active/active cluster of postgresql, we need to investigate possibility for inserts using active/active cluster mode.
The original idea was to use postgresql xl for this purpose, but right now this is not supported project.

If it's possible to implement, another task should be created with detailed description.

**Comment by atsikham** [comment]
Contacted @mmakow in Slack if it's still necessary to do, waiting for response.

**Comment by seriva** [comment]
Closing as this request is not longer relevant.
