### ISSUE TITLE
Backup: PostgreSQL

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#883]
Postgresql backup includes:

Database data and metadata dump using pg_dumpall
Configuration files: *.conf

Backup documentation:

https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/BACKUP.md

PR #1359

**Comment by pyrkamarcin** [comment]
@plirglo tested backup scenario: single node PostgreSQL, 2 nodes PostgreSQL done, works for me

**Comment by pyrkamarcin** [comment]
Tested backup scenario: single node PostgreSQL, clustered nodes PostgreSQL; on Ubuntu and RedHat.
