### ISSUE TITLE
Backup: Prometheus

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#885]
Monitoring backup includes:

Prometheus data snapshot
Prometheus configuration /etc/prometheus/

https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/BACKUP.md

PR #1359

**Comment by pprach** [comment]
Tested on Ubuntu and RHEL.
I backuped grafana dashboard prometheus settings and alerts. Everything backup up (and restore properly).
