### ISSUE TITLE
[Kubernetes upgrade] Update documentation

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#896]
Add upgrade related documentation as mentioned in comments in this taks.

**Comment by mkyc** [comment]
@toszo I believe this task is good start to what Sapna wrote in email. It's visible that epicli is not simple tool for the team over there. 

We could start with documentation for her and after review we could proceed with CICD tooling in separate milestone.

**Comment by rpudlowski93** [comment]
@toszo  Could Your provide description and what exactly need to be updated in documentation?

**Comment by mkyc** [comment]
Helm documentation is also missing. @ar3ndt you can use this task.

**Comment by toszo** [comment]
In Kubernetes 1.17, many of the API was removed. 
Information about Kubernetes deprecated API's (people still use `extensions/v1beta1` in deployments). We need to enclose information that all deployments, configmaps, secrets, policies, etc. have to be updated to use new Kubernetes APIs.

**Comment by to-bar** [comment]
Please keep in mind that we need to add to the documentation information about not supported Epiphany versions (below v0.4.4) since 0.7.0 required K8s in version 1.14.6+. I created issue #1433 to add preflight check for this.

**Comment by mkyc** [comment]
helm documentation already added in #1435.
