### ISSUE TITLE
Kubernetes HA - Test automation (automatic HA cluster deployment + serverspec scripts)

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#934]
**Is your feature request related to a problem? Please describe.**
We don't have Kubernetes HA cluster test automation.

**Describe the solution you'd like**
We want to have Kubernetes HA cluster test automation and serverspecs.

- We want to prepare the pipeline in Azure DevOps for testing the K8s HA installation.

Configuration that should be included in the yaml file:
```
---
kind: configuration/shared-config
title: Shared configuration that will be visible to all roles
name: default
specification:
  use_ha_control_plane: true
provider: aws
```

- We want to have serverspec test scripts for testing HA functionality (in particular to check ETCD, multi-master communication, reverse proxy, node-master communication) should be written to make sure everything works as it should.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by mkyc** [comment]
@przemyslavic can you write if things mentioned by @toszo are tested?

**Comment by mkyc** [comment]
@przemyslavic please review this one.

**Comment by przemyslavic** [comment]
The pipeline for testing Kubernetes HA deployments was created some time ago and is available in Azure DevOps.
Closing this task.
