### ISSUE TITLE
Add usage of use_network_security_groups to disable NSG on AWS

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#959]
**Is your feature request related to a problem? Please describe.**
Currently on Azure we have a flag in use called use_network_security_groups  to completely disable creation of NGS.

**Describe the solution you'd like**
Implement the same solution for AWS to disable the creation of NSG.

**Describe alternatives you've considered**
None

**Additional context**
None

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Tested together with #2853.
