### ISSUE TITLE
Automate switch from software collections PostgreSQL RedHat to PostgreSQL from PostgreSQL repository.

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#970]
Starting from Epicli v0.6 on RedHat we install PostgreSQL packages from the PostgreSQL repository. Earlier versions of Epiphany installed PostgreSQL from Software Collections Repository. The purpose of this task is to automate the switch to the PostgreSQL repository for older installations. See [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-migrate-from-postgresql-installed-from-software-collections-to-installed-from-postgresql-repository) for more instructions.

**Comment by toszo** [comment]
Needs research before estimation.

**Comment by seriva** [comment]
No longer valid as PG has been upgraded already to 13.x since then.
