### ISSUE TITLE
Support data disks (tbd managed or not managed) 

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#983]
Create data disks on cloud providers. 
Configure components that use storage (ELK, PostgreSQL, Kafka, Prometheus, ...) to use external drives (not OS drive). 
The on-premise installation has to have different default values.

**Comment by mkyc** [comment]
That would be actually possible now using combination of [AzBI](https://github.com/epiphany-platform/m-azure-basic-infrastructure) and [Hi](https://github.com/epiphany-platform/m-host-init) modules.

**Comment by seriva** [comment]
Data disk where added properly in 2.0, this should probably be rewritten to only support the components properly.

**Comment by seriva** [comment]
Closing as we have other issues with the proposed work.
