### ISSUE TITLE
Modify default disk size to ~100GB size

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#992]
There are components like image-registry, or repository that requires more disk space that is currently available by default. 

User should still be able to set old-30GB disk size but default should be 90+. 
Looking at pricing tiers in Azure - it could be up to 128GB by default.

**Comment by seriva** [comment]
For AWS at least this will recreate the resource with Terraform:

https://github.com/hashicorp/terraform/issues/14445

**Comment by sk4zuzu** [comment]
I think we should close this on in favor of #1313, #139 and #1355. This one is just reacting in the most basic way and does not capture the subtleness of the problem.. :hand_over_mouth:
