### ISSUE TITLE
Remove meta dependency on docker role for the kubernetes_common role

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#993]
This dependency causes unnecessary provisioning of docker related resources. Nothing gets ever changed and running it multiple times causes unwanted delay for the whole deployment process.

**Comment by mkyc** [comment]
Looks like tuning task similar to #809

**Comment by sk4zuzu** [comment]
I believe this one has been already done as a part of this milestone https://github.com/epiphany-platform/epiphany/milestone/13.  :+1:
