### ISSUE TITLE
Research mitogen and ssh connection pipelining for speeding up ansible provisioning

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#994]
https://mitogen.networkgenomics.com/ansible_detailed.html
https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-pipelining

**Comment by seriva** [comment]
Closing as we will not do this for the current Epiphany anymore.
